:sparkles: (1540): autorité compétente demandes délai
MTES-MCT/potentiel pull request #1009
Opened 2023-03-10 10:59 UTC by HanaeY

Correction de l'autorité compétente pour les demandes de délai. Règles à appliquer : l'autorité est "DGEC" pour l'AO "CRE4 - Eolien", et "DREAL" pour tous les autres AOs.

2023-03-10 13:04 UTC, spontoreau submitted a review, later dismissed

2023-03-13 09:02 UTC, HubM requested changes

2023-03-13 09:02 UTC, HubM commented on src/modules/demandeModification/demandeDélai/demander/demanderDélai.spec.ts
> +        describe(`Autorité DGEC`, () => {
À mon avis ce deuxième describe n'a pas vraiment d'intérêt, il est déjà explicitement décrit dans le `it`

2023-03-13 09:02 UTC, HubM commented on src/modules/demandeModification/demandeDélai/demander/demanderDélai.spec.ts
> +                  cahierDesCharges: '30/07/2021',
pour la clareté du test peut-être qu'on devrait juste vérifier la clé autorité

2023-03-13 10:23 UTC, HubM approved these changes
👍🏼

2023-03-13 10:56 UTC, merged