Refactor GF and DCR handling to use separate database table
MTES-MCT/potentiel pull request #107
Opened 2021-03-11 15:13 UTC by paduc

2021-03-11 18:58 UTC, Zekdar requested changes

2021-03-11 18:58 UTC, Zekdar commented on src/infra/sequelize/projections/projectStep/updates/onProjectStepRemoved.ts
> +    logger.error(e)
On ignorer l'erreur en cas d'exception ?

2021-03-11 18:58 UTC, Zekdar commented on src/infra/sequelize/projections/projectStep/updates/onProjectStepSubmitted.ts
> +  switch (event.type) {
S'il n'y a pas d'autres events à gérer que le `ProjectDCRSubmitted`, on pourrait remplacer le switch par un if

2021-03-11 18:58 UTC, Zekdar commented on src/infra/sequelize/projections/projectStep/updates/onProjectStepSubmitted.ts
> +    logger.error(e)
Idem

2021-03-11 18:58 UTC, Zekdar commented on src/infra/sequelize/queries/getFailedNotificationsForRetry.ts
> +        if (!project || project.get().gf?.submittedOn) {
`project?.get()...`

2021-03-11 18:58 UTC, Zekdar commented on src/modules/notification/eventHandlers/handleProjectGFSubmitted.ts
> +                'Potentiel - Nouveau dépôt de garantie financière dans votre région, département ' +
Utiliser un template literal

2021-03-11 18:58 UTC, Zekdar commented on src/modules/project/useCases/removeStep.ts
> +      },
Mettre le payload dans une constante étant donné qu'il est toujours le même, peu importe l'event

2021-03-11 18:58 UTC, Zekdar commented on src/views/pages/projectDetails/projectDetails.stories.tsx
> +        garantiesFinancieres: { dueOn: new Date(Date.now() + 1000 * 3600 * 24 * 30 * 2) },
Exporter les calculs dans des constantes pour que ça soit plus explicite dès la première lecture

2021-03-11 18:58 UTC, Zekdar commented on src/views/pages/projectDetails/projectDetails.stories.tsx
> +          dueOn: new Date(Date.now() + 1000 * 3600 * 24 * 30 * 2),
idem

2021-03-11 18:58 UTC, Zekdar commented on src/views/pages/projectDetails/sections/ProjectFrise.tsx
> +                    project.dcr.numeroDossier ? '(Dossier ' + project.dcr.numeroDossier + ')' : ''
Utiliser un template literal

2021-03-12 08:15 UTC, paduc commented on src/dataAccess/db/project.ts
> +  // })
Shame on me !

2021-03-12 08:17 UTC, paduc commented on src/infra/sequelize/projections/projectStep/updates/onProjectStepRemoved.ts
> +    logger.error(e)
C'est un handler qui met à jour un projection, en asynchrone donc. Si la requête fail, il n'y a pas grand chose à faire à part remonter l'erreur à Sentry. C'est un fail assez critique si les handlers ne fonctionnent pas (ça signifie sans doute un problème d'infra). Cela dit, c'est un fail qui peut être rattrapé assez facilement puisque l'événement source est dans l'event store et qu'on peut "rejouer" celui-ci sur la projection incriminée.

2021-03-12 08:23 UTC, paduc commented on src/infra/sequelize/projections/projectStep/updates/onProjectStepSubmitted.ts
> +  switch (event.type) {
Oui tu as raison, j'ai fait ça en mode "future-proof" au cas où d'autres types d'événements à venir pouvaient aussi avoir des `details` mais c'est pas utile pour le moment.

2021-03-12 08:26 UTC, paduc commented on src/infra/sequelize/queries/getFailedNotificationsForRetry.ts
> +        if (!project || project.get().gf?.submittedOn) {
Non ici, les conditions sont "Il n'y a pas de project" ou "Il y a un projet qui a une gf avec une date submittedOn". 
En combinant `project?.get()...` ça devient "Il n'y a pas de gf avec une date submittedOn".

2021-03-12 08:31 UTC, paduc commented on src/modules/project/useCases/removeStep.ts
> +      },
ok j'ai refactoré cette partie

2021-03-12 09:04 UTC, Zekdar approved these changes

2021-03-12 09:06 UTC, merged