116 Traitement des demandes de délai
MTES-MCT/potentiel pull request #113
Opened 2021-03-22 08:53 UTC by paduc

2021-03-22 23:17 UTC, Zekdar requested changes

2021-03-22 23:17 UTC, Zekdar commented on src/modules/project/Project.ts
> +      const newCompletionDueOn = +moment(props.completionDueOn).add(delayInMonths, 'months')
`+` > `Number`

2021-03-22 23:17 UTC, Zekdar commented on src/modules/project/Project.ts
> +    if (props.isClasse && (!!forceValue || !props.hasCompletionDueDateMoved)) {
Inverser la condition du `if` et faire un `return` pour économiser un niveau d'indentation.

2021-03-22 23:17 UTC, Zekdar commented on src/modules/project/dtos/ProjectDataForProjectPage.ts
> +  completionDueOn: Date
Pourquoi des fois le type de `completionDueOn` est `Date` et d'autres fois `Number` ? (je commence à être un peu perdu dans la PR :smile: )

2021-03-22 23:17 UTC, Zekdar commented on src/public/scripts.js
> +var dateRegex = new RegExp(/^([0-2][0-9]|(3)[0-1])(\/)(((0)[0-9])|((1)[0-2]))(\/)\d{4}$/)
`const`

2021-03-23 08:06 UTC, paduc commented on src/controllers/modificationRequest/postReplyToModificationRequest.ts
> +      (!delayInMonths || isNaN(delayInMonths) || Number(delayInMonths) <= 0)
Comme `delayInMonths` vient d'un formulaire html, sa valeur par défaut est `''` et `isNaN('') === false` donc la première condition est nécessaire.

2021-03-23 08:37 UTC, paduc commented on src/controllers/modificationRequest/postRequestModification.ts
> +      if (!data.delayInMonths || isNaN(data.delayInMonths) || data.delayInMonths <= 0) {
J'ai déplacé ce genre de vérifications dans un helper situé dans `src/helpers/formValidators.ts`

2021-03-23 08:39 UTC, paduc commented on src/infra/sequelize/queries/getModificationRequestDataForResponseTemplate.ts
> +            .map((previousRequest) => ({ modificationRequest, previousRequest }))
Ici ce n'est pas le `map` de `Array` mais de `ResultAsync`, elle permet d'appliquer une transformation sur la valeur contenue dans le `ResultAsync`.

2021-03-23 08:41 UTC, paduc commented on src/infra/sequelize/queries/getModificationRequestDataForResponseTemplate.ts
> +      const soumisAuxGarantiesFinancieres =
Dans ce cas précis, je considère en effet que le terme métier est `soumis aux garanties financières` en entier.

2021-03-23 09:03 UTC, Zekdar commented on src/controllers/modificationRequest/postReplyToModificationRequest.ts
> +      (!delayInMonths || isNaN(delayInMonths) || Number(delayInMonths) <= 0)
Ok !

2021-03-23 09:34 UTC, paduc commented on src/infra/sequelize/queries/getModificationRequestDataForResponseTemplate.ts
> +}
J'ai retiré ce que je trouvais dans des fonctions privées. Il y a énormément de code lié à la construction du DTO qui est gros, et aux destructurings nécessaires.

2021-03-23 09:36 UTC, paduc commented on src/modules/modificationRequest/dtos/ModificationRequestDataForResponseTemplateDTO.ts
> +  dateLimiteAchevementInitiale: string
C'est à destination du template docx, qui ne prend que des strings en paramètre.

2021-03-23 09:47 UTC, paduc commented on src/modules/project/dtos/ProjectDataForProjectPage.ts
> +  completionDueOn: Date
Pas de soucis, c'est vrai que c'est pas évident à suivre. Au plus bas niveau (base de données), c'est un `Number` tout comme les autres dates `garantiesFinancieresDueOn`, `notifiedOn`, etc.

Par contre, ici, nous sommes dans un DTO qui est consommé par une vue. La conversion `Number` => `Date` se fait à l'interface entre le bas niveau et l'extérieur (vues, API, etc.). C'est le rôle des queries qui produisent des DTO.

2021-03-23 09:59 UTC, Zekdar approved these changes

2021-03-23 10:04 UTC, merged