🚧 Script qui récupère les projets ayant le CDC 30/07/2021 et le change pour le CDC initial de l'appel d'offre
MTES-MCT/potentiel pull request #1226
Opened 2023-07-28 15:00 UTC by HubM

En lien avec cette carte airtable : https://airtable.com/apphLwfLi4vad9EAq/tbl8Xmi9jiTVtLxVp/viwgdXRqhQy6K6lzP/recaqofUkIGQVb3xS?blocks=hide

2023-07-31 06:42 UTC, JulienPavon requested changes

2023-07-31 06:42 UTC, JulienPavon commented on src/sequelize.config.ts
> +dotenv.config({ path: path.resolve(__dirname, '../.env') });
Ne surtout jamais charger les variables d'environnements depuis un fichier

2023-07-31 06:42 UTC, JulienPavon commented on src/scripts/changer-cdc-30072021-vers-initial.ts
> +  await choisirCahierDesCharges({
L'idéal pour ce genre d'opération serait de faire l'opération directement en SQL pour des raisons de performances et pratique

2023-08-03 14:03 UTC, HanaeY commented on src/scripts/changer-cdc-30072021-vers-initial.ts
> +  await choisirCahierDesCharges({
Tu veux dire qu'on ne passe pas par la commande, mais on ouvre un tunnel sur la prod pour émettre des events "CahierDesChargesChoisi" ou on fait un script de migration ?

2023-08-07 07:47 UTC, closed without merging