Validate gf #405
MTES-MCT/potentiel pull request #126
Opened 2021-04-01 14:59 UTC by Zekdar

2021-04-06 09:32 UTC, paduc requested changes

2021-04-06 09:32 UTC, paduc commented on src/controllers/steps/getStatusStep.ts
> +            success: `Le statut de l'étape projet a bien été mis à jour.`,
`Cette étape projet est bien considérée comme ${newStatus}.`

2021-04-06 09:32 UTC, paduc commented on src/controllers/steps/getStatusStep.ts
> +            redirectUrl: routes.ADMIN_DREAL_LIST,
Il me semble qu'on peut utiliser `request.referer` pour avoir l'url d'où l'utilisateur venait.

2021-04-06 09:32 UTC, paduc commented on src/dataAccess/db/project.ts
> +      statusSubmittedAt: {
`statusUpdatedOn`

2021-04-06 09:32 UTC, paduc commented on src/dataAccess/db/project.ts
> +      statusSubmittedBy: {
`statusUpdatedBy`

2021-04-06 09:32 UTC, paduc commented on src/infra/sequelize/migrations/20210321214528-add-columns-validatedBy-validatedAt-to-project-steps.js
> +    queryInterface.addColumn('project_steps', 'statusSubmittedBy', {
`statusUpdatedBy`

2021-04-06 09:32 UTC, paduc commented on src/infra/sequelize/migrations/20210321214528-add-columns-validatedBy-validatedAt-to-project-steps.js
> +    queryInterface.addColumn('project_steps', 'statusSubmittedAt', {
`statusUpdatedOn`

2021-04-06 09:32 UTC, paduc commented on src/entities/project.ts
> +    statusSubmittedAt: Date
`statusUpdatedOn`

2021-04-06 09:32 UTC, paduc commented on src/infra/sequelize/migrations/20210321214528-add-columns-validatedBy-validatedAt-to-project-steps.js
> +    queryInterface.removeColumn('project_steps', 'statusSubmittedAt')
idem

2021-04-06 09:32 UTC, paduc commented on src/infra/sequelize/projections/projectStep/projectStep.model.ts
> +      statusSubmittedAt: {
idem

2021-04-06 09:32 UTC, paduc commented on src/infra/sequelize/projections/projectStep/projectStep.model.ts
> +      statusSubmittedBy: {
idem

2021-04-06 09:32 UTC, paduc commented on src/infra/sequelize/projections/projectStep/updates/onProjectStepStatusUpdated.integration.ts
> +      const { id: projectStepId } = await ProjectStep.create({
`const projectStepId = new UniqueEntityID().toString()`

2021-04-06 09:32 UTC, paduc commented on src/infra/sequelize/projections/projectStep/updates/onProjectStepStatusUpdated.integration.ts
> +      expect(await ProjectStep.findByPk(projectStepId)).toBeDefined()
Attention, cette assertion passera toujours parce que `findByPk` retourne `null` quand l'entrée n'est pas trouvée.

`expect(await ProjectStep.findByPk(projectStepId)).not.toBe(null)`

2021-04-06 09:32 UTC, paduc commented on src/infra/sequelize/projections/projectStep/updates/onProjectStepStatusUpdated.integration.ts
> +      expect(projectStep.status).toStrictEqual('validé')
Vérifier aussi la mise à jour de `statusUpdatedOn` et `statusUpdatedBy`

2021-04-06 09:32 UTC, paduc commented on src/infra/sequelize/projections/projectStep/updates/onProjectStepStatusUpdated.integration.ts
> +      expect(projectStep.status).toStrictEqual('à traiter')
Idem

2021-04-06 09:32 UTC, paduc commented on src/infra/sequelize/projections/projectStep/updates/onProjectStepStatusUpdated.ts
> +  const ProjectStepModel = models.ProjectStep
`const { ProjectStep } = models` (tu trouveras sans doute l'autre forme ailleurs dans le code mais c'est la version que je privilégie maintenant)

2021-04-06 09:32 UTC, paduc commented on src/modules/project/useCases/updateStepStatus.spec.ts
> +describe('ProjectSteps.updateStepStatus()', () => {
Ajouter le test case où l'utilisateur n'a pas les droits pour le faire.

2021-04-06 09:32 UTC, paduc commented on src/views/components/actions/dreal.ts
> +  const gf = project.gf
`const { gf } = project`

2021-04-06 09:32 UTC, paduc commented on src/views/components/projectList.tsx
> +                    Statut : {project.gf.status}
Je mettrais simplement le status, pas besoin d'être explicite avec `Statut : `

2021-04-06 09:32 UTC, paduc commented on src/views/components/projectList.tsx
> +                  <span
Masquer cette section pour éviter la lourdeur. On verra s'ils nous le demandent.

2021-04-06 12:43 UTC, Zekdar commented on src/infra/sequelize/projections/projectStep/updates/onProjectStepStatusUpdated.integration.ts
> +      expect(await ProjectStep.findByPk(projectStepId)).toBeDefined()
J'ai trouvé `not.toBeNull()` directement

2021-04-07 14:19 UTC, paduc commented on src/infra/sequelize/projections/projectStep/updates/onProjectStepStatusUpdated.integration.ts
> +      expect(projectStep.statusUpdatedOn).not.toEqual(createdAt)
`not.toEqual` ?

2021-04-07 14:21 UTC, paduc commented on src/infra/sequelize/projections/projectStep/updates/onProjectStepStatusUpdated.integration.ts
> +      expect(projectStep.statusUpdatedOn).not.toEqual(createdAt)
Il faut s'assurer que la date `statusUpdatedOn` a été mise à jour avec la valeur de `event.occurredAt` que tu peux forcer lors de la création de ton événement dans le test. Regarde par exemple comment j'ai fait dans `onProjectStepSubmitted.integration.ts` à la ligne 34.

2021-04-07 16:10 UTC, paduc approved these changes

2021-04-07 21:27 UTC, merged