Ft/imports projets/enregistrer type gf
MTES-MCT/potentiel pull request #1278
Opened 2023-08-24 13:18 UTC by HubM

2023-08-25 08:36 UTC, HanaeY requested changes

2023-08-25 08:36 UTC, HanaeY commented on src/controllers/notificationCandidats/postImportProjects.ts
> +            type: 'ENREGISTRER_GARANTIES_FINANCIÈRES_USE_CASE',
Je suis pas trop à l'aise avec l'appel du use-case sur chaque projet avant la publication de l'event ProjectImported de chaque projet, mais en même temps ça me semble plus logique d'appeler ce use-case dans un contrôleur que dans la méthode project.import par exemple. Je pense qu'on n'a pas trop le choix pour le moment. On pourra demander à Julien s'il a une autre idée.,

2023-08-25 08:36 UTC, HanaeY commented on src/controllers/notificationCandidats/postImportProjects.ts
> +      for (const projet of projetsPourEnregistrementGFs) {
que penses-tu d'utiliser un Promise.all (au lieu de boucler) pour paralléliser les appels et récupérer toutes les erreurs à la fin ?

2023-08-25 08:36 UTC, HanaeY commented on src/controllers/notificationCandidats/postImportProjects.ts
>        });
On a l'impression que l'objectif de la fonction importProjects est de retourner les projets pour enregistrement GF, ce qui peut induire en erreur. On ne pourrait pas récupérer tous les projets pour faire le filtre dans le contrôleur ? A part si tu as une objection à ça ? Et donc si on va dans ce sens importProject retournerait les "rawProjetsImportés" par exemple.

2023-08-25 08:36 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectImported.ts
> +    await mediator.send<DomainUseCase>;
c'est un oubli ça non ?

2023-08-28 06:16 UTC, JulienPavon requested changes

2023-08-28 06:16 UTC, JulienPavon commented on src/controllers/notificationCandidats/postImportProjects.ts
> +      const rawProjetsImportés = await importProjects({
À cet endroit du code actuellement aucun projet ne sera importé concrètement. En fait cette fonction va seulement émettre un évènement `ProjectRawDataImported`. Ensuite le handler `handleProjectRawDataImported` va lui exécuter l'import et je pense que c'est à cet endroit qu'il faut le faire et non avant.

2023-08-28 06:16 UTC, JulienPavon commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectImported.ts
> +
Ligne vide inutile

2023-08-28 07:58 UTC, HubM commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectImported.ts
> +
C'est à cause du formatOnSave de vscode :/ 
J'avais du passer dans ce fichier pour voir le code et sauvegarder.

J'arrive pas à virer la ligne en trop du couo

2023-08-29 10:21 UTC, JulienPavon approved these changes

2023-08-29 13:56 UTC, HanaeY approved these changes

2023-08-29 14:02 UTC, merged