345 Traitement d'un dépôt de demande d'abandon
MTES-MCT/potentiel pull request #130
Opened 2021-04-15 10:05 UTC by paduc

2021-04-26 22:12 UTC, Zekdar requested changes

2021-04-26 22:12 UTC, Zekdar commented on src/views/pages/modificationRequestDetails/components/DemandeStatus.tsx
> +    modificationRequest.acceptanceParams
Exporter dans une constante

2021-04-27 07:39 UTC, paduc commented on src/infra/sequelize/projections/modificationRequest/updates/onConfirmationRequested.ts
> +  instance.versionDate = event.occurredAt
👍

2021-04-27 07:40 UTC, paduc commented on src/infra/sequelize/projections/modificationRequest/updates/onModificationRequestConfirmed.ts
> +  instance.versionDate = event.occurredAt
👍

2021-04-27 07:41 UTC, paduc commented on src/infra/sequelize/projections/project/updates/onProjectAbandoned.ts
> +  projectInstance.completionDueOn = 0
👍

2021-04-27 07:45 UTC, paduc commented on src/views/pages/modificationRequestDetails/components/DemandeStatus.tsx
> +    modificationRequest.acceptanceParams
Ici je suis un peu coincé par typescript. Sans cette condition explicite sur `modificationRequest.type`, il va me dire que `acceptanceParams` n'existe pas sur le type.

2021-04-27 08:18 UTC, Zekdar commented on src/views/pages/modificationRequestDetails/components/DemandeStatus.tsx
> +    modificationRequest.acceptanceParams
Je voulais dire : exporter les 3 conditions dans une constante :
```js
const isDelaiAccepted = modificationRequest.type === 'delai' &&
    modificationRequest.status === 'acceptée' &&
    modificationRequest.acceptanceParams
```

2021-04-27 08:20 UTC, paduc commented on src/views/pages/modificationRequestDetails/components/DemandeStatus.tsx
> +    modificationRequest.acceptanceParams
Oui c'est ce que j'ai essayé mais à l'intérieur du bloc `if`, typescript ne sait plus que `type === 'delai'`.

2021-04-27 08:47 UTC, Zekdar approved these changes

2021-04-30 08:45 UTC, merged