:sparkles: Liste projets en attente de dépôt de GF > filtrer par statut classé
MTES-MCT/potentiel pull request #1306
Opened 2023-09-12 14:20 UTC by HanaeY

2023-09-13 14:16 UTC, HubM commented
typo : Il faudrait aussi renommer les fichiers `suviDépôts.then.ts` et `suviDépôts.feature` en `suiviDépôts.then.ts` / `suiviDépôts.feature`

2023-09-13 14:16 UTC, HubM requested changes

2023-09-13 14:16 UTC, HubM commented on packages/domain-views/src/garantiesFinancières/dépôtGarantiesFinancières/dépôtGarantiesFinancières.projector.ts
> +              event.payload.aggregate.dépôt.typeGarantiesFinancières || undefined,
dans le type de l'event la clé `typeGarantiesFinancières` peut déjà être `undefined`, alors je pense que tu peux juste faire :
```suggestion
              event.payload.aggregate.dépôt.typeGarantiesFinancières,
```

2023-09-13 14:16 UTC, HubM commented on packages/domain-views/src/garantiesFinancières/dépôtGarantiesFinancières/dépôtGarantiesFinancières.projector.ts
> +            dateÉchéance: event.payload.aggregate.dépôt.dateÉchéance || undefined,
```suggestion
            dateÉchéance: event.payload.aggregate.dépôt.dateÉchéance,
```

2023-09-13 14:16 UTC, HubM commented on packages/domain-views/src/garantiesFinancières/dépôtGarantiesFinancières/dépôtGarantiesFinancières.projector.ts
> +              event.payload.aggregate.dépôt.typeGarantiesFinancières || undefined,
```suggestion
              event.payload.aggregate.dépôt.typeGarantiesFinancières,
```

2023-09-13 14:16 UTC, HubM commented on packages/domain-views/src/garantiesFinancières/dépôtGarantiesFinancières/dépôtGarantiesFinancières.projector.ts
> +            dateÉchéance: event.payload.aggregate.dépôt.dateÉchéance || undefined,
```suggestion
            dateÉchéance: event.payload.aggregate.dépôt.dateÉchéance,
```

2023-09-13 14:16 UTC, HubM commented on packages/domain-views/src/garantiesFinancières/garantiesFinancièresActuelles/garantiesFinancières.projector.ts
> +            typeGarantiesFinancières: typeGarantiesFinancières || undefined,
```suggestion
            typeGarantiesFinancières,
```

2023-09-13 14:16 UTC, HubM commented on packages/domain-views/src/garantiesFinancières/garantiesFinancièresActuelles/garantiesFinancières.projector.ts
> +            dateÉchéance: dateÉchéance || undefined,
```suggestion
            dateÉchéance,
```

2023-09-13 14:16 UTC, HubM commented on packages/domain-views/src/garantiesFinancières/garantiesFinancièresActuelles/garantiesFinancières.projector.ts
> +            typeGarantiesFinancières: typeGarantiesFinancières || undefined,
```suggestion
            typeGarantiesFinancières,
```

2023-09-13 14:16 UTC, HubM commented on packages/domain-views/src/garantiesFinancières/garantiesFinancièresActuelles/garantiesFinancières.projector.ts
> +            dateÉchéance: dateÉchéance || undefined,
```suggestion
            dateÉchéance,

2023-09-13 14:16 UTC, HubM commented on packages/domain-views/src/garantiesFinancières/suiviDesDépôts/suiviDesDépôts.projector.ts
> +              dateLimiteDépôt: event.payload.aggregate.dateLimiteDépôt || undefined,
```suggestion
              dateLimiteDépôt: event.payload.aggregate.dateLimiteDépôt,
```

2023-09-13 14:16 UTC, HubM commented on packages/domain-views/src/garantiesFinancières/suiviDesDépôts/suiviDesDépôts.projector.ts
> +            dateLimiteDépôt: event.payload.aggregate.dateLimiteDépôt || undefined,
```suggestion
            dateLimiteDépôt: event.payload.aggregate.dateLimiteDépôt,
```

2023-09-13 14:16 UTC, HubM commented on packages/specifications/src/garantiesFinancières/suiviDépôts/stepDefinitions/suviDépôts.then.ts
> -              statut,
vu qu'on utilise plus le statut faudrait supprimer la destructuration ligne 32

2023-09-13 14:22 UTC, HanaeY commented on packages/domain-views/src/garantiesFinancières/dépôtGarantiesFinancières/dépôtGarantiesFinancières.projector.ts
> +              event.payload.aggregate.dépôt.typeGarantiesFinancières || undefined,
Les valeurs dans l'event peuvent être NULL, j'ai donc fait ça pour appliquer undefined dans ce cas, mais je peux peut être essayer de mettre undefined dans les données passées aux events dans la query plutôt ....

2023-09-14 11:40 UTC, HubM commented on packages/domain-views/src/garantiesFinancières/dépôtGarantiesFinancières/dépôtGarantiesFinancières.projector.ts
> +            });
On aurait pu extraire l'objet dans une variable et l'utiliser dans le cas du create / update

2023-09-14 11:40 UTC, HubM commented on packages/domain-views/src/garantiesFinancières/garantiesFinancièresActuelles/garantiesFinancières.projector.ts
> +            });
pareil ici

2023-09-14 11:40 UTC, HubM commented on packages/domain-views/src/garantiesFinancières/suiviDépôts/suiviDépôts.projector.ts
> +            });
pareil ici

2023-09-14 13:18 UTC, HubM approved these changes
👍🏼

2023-09-14 13:28 UTC, merged