435 Création et gestion des comptes acheteurs-obligés
MTES-MCT/potentiel pull request #134
Opened 2021-04-16 17:40 UTC by paduc

2021-04-20 22:31 UTC, Zekdar requested changes

2021-04-20 22:31 UTC, Zekdar commented on src/controllers/auth/authentication.ts
> +  if (!Array.isArray(roles)) {
On peut simplifier
```js
const rolesArr = Array.isArray(roles) ? roles : [roles]

if (!roles.includes(user.role)) {
    return res.redirect(routes.REDIRECT_BASED_ON_ROLE)
}
```

2021-04-20 22:31 UTC, Zekdar commented on src/useCases/signup.ts
> +    ['acheteur-obligé', 'ademe'].includes(projectAdmissionKey.forRole)
La première partie de la condition n'est pas utile car `[1,2].includes(undefined)` sera bien `falsy`

2021-04-20 22:31 UTC, Zekdar commented on src/views/components/partnerDashboard.tsx
> +            {typeof currentPage === 'undefined' ? (
Est-ce que ça fait partie des cas où la ternaire est obligatoire car  `&&` ne fonctionne pas ? Sinon remplacer pour simplifier.

2021-04-20 22:31 UTC, Zekdar commented on src/views/pages/adminUsers.tsx
> +        {invitations && invitations.length ? (
`invitations?.length && (`

2021-04-20 22:31 UTC, Zekdar commented on src/views/pages/signup.tsx
> +              !projectAdmissionKey.forRole ? (
Déstructurer

2021-04-26 20:15 UTC, paduc commented on src/useCases/signup.ts
> +    ['acheteur-obligé', 'ademe'].includes(projectAdmissionKey.forRole)
Typescript n'est pas d'accord qu'on appelle `includes` avec un argument potentiellement `undefined`. J'ai du mettre un `!` pour que ça passe.

2021-04-27 08:14 UTC, Zekdar approved these changes

2021-04-27 08:15 UTC, merged