⬆️ Upgrade to React 18
MTES-MCT/potentiel pull request #1354
Opened 2023-10-11 13:02 UTC by spontoreau

2023-10-11 14:03 UTC, HubM approved these changes

2023-10-12 07:43 UTC, HubM submitted a review, later dismissed

2023-10-12 13:15 UTC, HubM approved these changes

2023-10-12 14:00 UTC, HubM submitted a review, later dismissed

2023-10-13 06:39 UTC, JulienPavon requested changes
Je vois des erreurs dans la console javascript au lancement de l'application sur certaines pages. J'investigue pour résoudre le problème

2023-10-13 07:17 UTC, HubM commented
> Je vois des erreurs dans la console javascript au lancement de l'application sur certaines pages. J'investigue pour résoudre le problème

C'est pas à cause des balises `style` @JulienPavon ?

2023-10-13 08:28 UTC, JulienPavon approved these changes

2023-10-13 08:48 UTC, merged