Change project power #115
MTES-MCT/potentiel pull request #136
Opened 2021-04-19 00:52 UTC by Zekdar

2021-04-26 17:44 UTC, paduc requested changes

2021-04-26 17:44 UTC, paduc commented on src/controllers/modificationRequest/postReplyToModificationRequest.ts
> +        ...args,
`args` cache le sens de ce qui est ajouté ici (le fichier de réponse). 
Est-ce qu'on en ferait pas plutôt une variable qui peut être `undefined` ?

```ts
const responseFile = request.file && {
         contents: fs.createReadStream(request.file.path),
         filename: request.file.originalname,
       }
```

2021-04-26 17:44 UTC, paduc commented on src/controllers/modificationRequest/postRequestModification.ts
> +        justification: data.justification,
déstructurer
```ts
const { projectId, puissance, justification } = data
```

2021-04-26 17:44 UTC, paduc commented on src/infra/sequelize/projections/modificationRequest/updates/onModificationReceived.integration.ts
> +    expect(updatedModificationRequest.status).toEqual('information validée')
`updatedModificationRequest` => `newModificationRequest` 

Et aussi, pense à vérifier les autres champs que tu remplis.

2021-04-26 17:44 UTC, paduc commented on src/infra/sequelize/projections/project/updates/onProjectPuissanceSubmitted.integration.ts
> +    expect(updatedProject.puissance).toEqual(newPuissance)
Ajouter test pour vérifier que `puissanceInitiale` n'a pas changé.

2021-04-26 17:44 UTC, paduc commented on src/infra/sequelize/projections/project/updates/onProjectPuissanceSubmitted.ts
> +  const ProjectModel = models.Project
`const { Project }   = models`

2021-04-26 17:44 UTC, paduc commented on src/modules/project/events/ProjectPuissanceSubmitted.ts
> +export class ProjectPuissanceSubmitted
Le nom de la commande est `updatePuissance`, l'événement doit donc s'appeler `ProjectPuissanceUpdated`.

2021-04-26 17:44 UTC, paduc commented on src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
> +
Idéalement à placer entre le `describe` et le `it` puisqu'il s'agit de la condition du scénario ("user is not allowed")

2021-04-26 17:44 UTC, paduc commented on src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
> +      const newPuissance = 89
Idéalement à placer juste sous le `describe` (condition initiale)

2021-04-26 17:44 UTC, paduc commented on src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
> +      expect(event).toBeInstanceOf(ModificationRequested)
Et aussi `event.payload.puissance`

2021-04-26 17:44 UTC, paduc commented on src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
> +      const newPuissance = 111
idem

2021-04-26 17:44 UTC, paduc commented on src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
> +      expect(event).toBeInstanceOf(ModificationRequested)
Idem, `payload` à vérifier

2021-04-26 17:44 UTC, paduc commented on src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
> +      const newPuissance = 105
idem

2021-04-26 17:44 UTC, paduc commented on src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
> +      fakePublish.mockClear()
Je trouve ça plus safe de créer un `fakePublish` par test-case. Ca revient au même de faire `.mockClear` mais si on ne partage rien entre les tests, on ne peut pas se tromper.

2021-04-26 17:44 UTC, paduc commented on src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
> +    it('should emit a ModificationSubmitted', async () => {
`ModificationReceived`

2021-04-26 17:44 UTC, paduc commented on src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
> +      expect(event).toBeInstanceOf(ModificationReceived)
idem `payload` à vérifier

2021-04-26 17:44 UTC, paduc commented on src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
> +    it('should update the puissance', () => {
Il faut également vérifier que le `projectRepo.save()` a été appelé.

2021-04-26 17:44 UTC, paduc commented on src/modules/modificationRequest/useCases/requestPuissanceModification.ts
> +            const MAX_AUTO_ACCEPT_PUISSANCE_RATIO = 1.1
A déplacer à la racine du module.

2021-04-26 17:44 UTC, paduc commented on src/infra/sequelize/projections/modificationRequest/updates/onModificationReceived.integration.ts
> +  it('should update the status to information validée', async () => {
`update` ? Non il s'agit de la création d'une nouvelle demande.

2021-04-26 20:06 UTC, paduc requested changes

2021-04-26 20:06 UTC, paduc commented on src/infra/sequelize/queries/getModificationRequestDataForResponseTemplate.ts
> +          console.log({ commonData })
A retirer

2021-04-26 20:06 UTC, paduc commented on src/modules/file/FileObject.ts
> +  | 'puissance'
Peut-on trouver quelque chose de plus descriptif ?

2021-04-26 22:58 UTC, Zekdar commented on src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
> +      fakePublish.mockClear()
Je suis d'accord dans l'idée que si on ne partage rien, on ne peut pas se tromper. Par contre ça rajoute du boilerplate au setup qui est déjà très verbeux.. Je suis pas convaincu que ça soit souhaitable car ça voudrait dire qu'à chaque test je dois réécrire : 

```js
const fakePublish = jest.fn((event: DomainEvent) => okAsync<null, InfraNotAvailableError>(null))
  const eventBus = {
    publish: fakePublish,
    subscribe: jest.fn(),
  }
```

2021-04-27 07:28 UTC, paduc commented on src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
> +      fakePublish.mockClear()
Oui le boilerplate peut être très verbeux dans les tests je te l'accorde, d'autant plus qu'on doit injecter plein de fakes du fait du découplage. Ma première intuition a été de faire comme toi, réutiliser les mocks mais avec le temps, j'ai réalisé que ça posait plus de problèmes qu'autre chose. Très souvent, je finissais par dupliquer certaines dépendances pour les faire varier en fonction des test-case. Plus rarement, j'oubliais un `mockClear` et ça rendait les tests flaky, et perdre pas mal de temps à trouver la source du problème.

Du coup, maintenant, même si ça rajoute du boilerplate, je préfère que chaque test-case ait ses propres fakes et ne jamais appeler `mockClear`. Si une dépendance injectée n'a aucun effet du tout, on peut éventuellement la partager, vu que le risque est contenu. De cette manière on a plus de boilerplate certes mais aussi des tests plus robustes.

Par ailleurs, ça permet de copier-coller des blocs `describe` sans avoir à vérifier si des mocks partagés (potentiellement tout en haut du fichier) sont compatibles avec ce que je veux tester.

Avoir des tests les plus indépendants possibles est un principe fondateur du testing.

2021-04-27 07:32 UTC, paduc commented on src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
> +      fakePublish.mockClear()
Pour réduire un peu le boilerplate, on peut imaginer créer un utilitaire qui nous crée notre `eventBus`.
```ts
const makeFakeEventBus = () => { publish: jest.fn((event: DomainEvent) => okAsync<null, InfraNotAvailableError>(null)), subscribe: jest.fn() }
```

2021-04-27 22:48 UTC, Zekdar commented on src/modules/file/FileObject.ts
> +  | 'puissance'
J'avais envisagé "decision-justice" mais le PP peut uploader ce qu'il veut en réalité. Tu penses à quoi ?

2021-04-27 22:51 UTC, Zekdar commented on src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
> +    it('should update the puissance', () => {
comme `projectRepo` est un `TransactionalRepo`, comment tu fais pour faire ce check ?

2021-05-05 15:06 UTC, paduc commented on src/modules/file/FileObject.ts
> +  | 'puissance'
Désolé j'avais pas vu ta réponse. Je pense qu'on peut utiliser `modification-request` qui existe déjà et est utilisé pour les PJ des autres types de demandes.

2021-05-05 15:51 UTC, paduc requested changes

2021-05-05 15:51 UTC, paduc commented on src/modules/modificationRequest/useCases/acceptModificationRequest.ts
> +        case 'abandon':
C'est zarb que ça soit dans un de tes commits ça non ?

2021-05-05 15:51 UTC, paduc commented on src/controllers/modificationRequest/postReplyToModificationRequest.ts
> +    }
C'est une règle métier. Sa place est dans `acceptModificationRequest`. Ainsi tu auras accès à la vraie valeur de `puissanceInitiale` (via l'agrégat `Project`) et tu n'auras pas à passer `puissanceInitiale` dans le POST du formulaire.
On ne peut pas se fier à ce qui est passé par le formulaire.

2021-05-05 15:51 UTC, paduc commented on src/infra/sequelize/queries/getModificationRequestDataForResponseTemplate.ts
> +          const puissance = currentPuissance !== puissanceInitiale ? currentPuissance : undefined
J'ai du mal à comprendre pourquoi `puissance` serait `undefined` si elle est identique à `puissanceInitiale`.

2021-05-05 15:51 UTC, paduc commented on src/views/pages/modificationRequestDetails/components/PuissanceForm.tsx
> +      />
Ne devrait pas être nécessaire, cf commentaire plus haut.

2021-05-05 15:52 UTC, paduc commented on src/controllers/modificationRequest/postReplyToModificationRequest.ts
> +    }
Par ailleurs, la règle ne doit s'appliquer que pour le cas `type === puissance`

2021-05-06 14:25 UTC, Zekdar commented on src/modules/modificationRequest/useCases/acceptModificationRequest.ts
> +        case 'abandon':
C'est dû à la transformation de `if/else` en `switch`

2021-05-06 14:35 UTC, Zekdar commented on src/infra/sequelize/queries/getModificationRequestDataForResponseTemplate.ts
> +          const puissance = currentPuissance !== puissanceInitiale ? currentPuissance : undefined
Le but ici est d'afficher un paragraphe conditionnel dans le courrier de réponse. On veut afficher la puissance actuelle seulement si elle est différente de celle lors de la notification. Dans le cas contraire, je set 'puissance = undefined'

2021-05-06 14:39 UTC, paduc commented on src/infra/sequelize/queries/getModificationRequestDataForResponseTemplate.ts
> +          const puissance = currentPuissance !== puissanceInitiale ? currentPuissance : undefined
Je placerais cette logique au plus près du template plutot que dans la query elle-même.

2021-05-07 08:29 UTC, paduc requested changes

2021-05-07 08:29 UTC, paduc commented on src/controllers/modificationRequest/postReplyToModificationRequest.ts
> +    if (!['recours', 'delai', 'puissance'].includes(type)) {
Il manque le type `abandon` qui a du être zappé lors d'un rebase.

2021-05-07 08:29 UTC, paduc commented on src/modules/modificationRequest/useCases/acceptModificationRequest.ts
> +                  new OtherError(
Il faut créer un nouveau type d'erreur plutôt que d'utiliser `OtherError`.

2021-05-07 08:29 UTC, paduc commented on src/modules/modificationRequest/useCases/acceptModificationRequest.ts
> +          (project): ResultAsync<any, OtherError> => {
L'usage de `ResultAsync<any, OtherError>` nous fait perdre le type de `project` pour tout le reste de la chaine et donc le typage. Utiliser `ResultAsync<Project...`.

Il faut aussi corriger le type à la ligne 90 `ResultAsync<{ project; modificationRequest; responseFileId?: string }, any>` qui retire le typage de `project`, `modificationRequest` et aussi le typage de l'erreur.

2021-05-14 11:46 UTC, paduc requested changes

2021-05-14 11:46 UTC, paduc commented on src/modules/modificationRequest/useCases/requestPuissanceModification.ts
> +import { getAutoAcceptRatiosForAppelOffre } from '../helpers'
`getAutoAcceptRatiosForAppelOffre` est une dépendance injectée mais ici, tu utilises l'implémentation directement via cet import au lieu d'utiliser celle qui est injectée via `deps`.

Il faut retirer cet import et injecter cette implémentation dans le fichier `config/usesCases.config.ts` lors de l'appel à `makeRequestPuissanceModification`.

2021-05-17 16:50 UTC, Zekdar commented on src/modules/modificationRequest/useCases/requestPuissanceModification.ts
> +import { getAutoAcceptRatiosForAppelOffre } from '../helpers'
C'est un oubli, merci !

2021-05-18 00:09 UTC, merged