✨ Adapter le rendu de la page projet pour impression
MTES-MCT/potentiel pull request #1371
Opened 2023-10-25 15:44 UTC by HubM

2023-10-26 09:47 UTC, JulienPavon commented on src/views/components/print/PrintHidden.tsx
> +export const PrintHidden = ({
J'ai du mal à voir l'intérêt d'avoir ce genre de component qui vient seulement centraliser l'utilisation d'une classe css tailwind.

2023-10-26 09:58 UTC, HubM commented on src/views/components/print/PrintHidden.tsx
> +export const PrintHidden = ({
C'est pour éviter d'avoir à appliquer les classes à différents endroits dans le code, c'est mon idée. Après si on considère que c'est pas génant je peux appliquer la classe en question aux différents endroits

2023-10-26 10:25 UTC, JulienPavon requested changes
Aller dans tous les éléments de la frise pour modifier tous les endroits avec les liens pour les substituer en texte pour l'impression était vraiment nécessaire ? Parce que point de vue maintenance ça devient très compliqué.
Et si on considère que tous les boutons et liens ne doivent pas apparaître dans une impression pourquoi ne pas directement appliquer une règle css sur les components correspondants ?

2023-10-27 05:20 UTC, JulienPavon submitted a review, later dismissed

2023-10-30 13:58 UTC, HubM commented
PR en draft le temps d'avoir un feu go de la part de l'équipe métier

2023-11-10 17:14 UTC, JulienPavon approved these changes

2023-11-13 08:36 UTC, merged