🧪 ajout des scénarios sans implémentation
MTES-MCT/potentiel pull request #1395
Opened 2023-11-07 10:51 UTC by HubM

2023-11-07 13:17 UTC, spontoreau commented on packages/specifications/src/projet/lauréat/abandon/transmettrePreuveRecandidature.feature
> +      Etant donné une demande d'abandon avec recandidature accordée pour le projet "Du boulodrome de Marseille" avec :
Vu que c'est un given j'aurais pas mis d'exemple

2023-11-07 13:19 UTC, spontoreau commented on packages/specifications/src/projet/lauréat/abandon/transmettrePreuveRecandidature.feature
> +      Quand le porteur transmet comme preuve de recandidature le projet "MIOS" avec :
La le cas nominal tu test qu'avec un projet éliminé. Peut-être qu'u autre scénario sera nécessaire pour un projet lauréat, ou alors on peut aussi faire un scénario outline avec des cas d'exemples. A voir

2023-11-07 13:20 UTC, spontoreau commented on packages/specifications/src/projet/lauréat/abandon/transmettrePreuveRecandidature.feature
> +      Et le porteur devrait être informé que "La preuve de recandidature a bien été prise en compte"
Ce step va assert quoi ? Devrait être informé est un step générique pour renvoyer des erreurs.

Donc pour moi là c'est pas le bon step, il faut plutôt un step pour vérifier que la preuve a bien été transmise

2023-11-07 13:22 UTC, spontoreau commented on packages/specifications/src/projet/lauréat/abandon/transmettrePreuveRecandidature.feature
> +      Alors le porteur devrait être informé que "Il est impossible de transmettre une preuve de recandidature pour un projet non abandonné"
actuellement dans le domaine on parle d'abandon en cours.

Il manque aussi le cas ou de la transmission de preuve pour un abandon rejeté.

2023-11-07 13:22 UTC, spontoreau commented on packages/specifications/src/projet/lauréat/abandon/transmettrePreuveRecandidature.feature
> +      Alors le porteur devrait être informé que "Le projet faisant preuve de recandidature ne doit pas avoir comme doit pas avoir été notifié avant le 15/12/2023"
Il y a un soucis dans la phrase

2023-11-07 13:23 UTC, spontoreau commented on packages/specifications/src/projet/lauréat/abandon/transmettrePreuveRecandidature.feature
> +      Alors le porteur devrait être informé que "Le projet faisant preuve de recandidature ne doit pas avoir comme doit pas avoir été notifié après le 31/03/2024"
Pareil qu'au dessus

2023-11-07 13:24 UTC, spontoreau commented on packages/specifications/src/projet/lauréat/abandon/transmettrePreuveRecandidature.feature
> +Fonctionnalité: Ajouter une preuve de recandidature
Transmettre, pas ajouter

2023-11-13 13:16 UTC, spontoreau requested changes

2023-11-13 13:46 UTC, HubM commented on packages/domain/common/src/valueTypes/dateTime.valueType.ts
> +  estUltérieureÀ(dateTime: Date | ValueType): boolean;
Vu avec Sylvain ça sera fait dans une prochaine PR dédiée

2023-11-13 16:11 UTC, spontoreau approved these changes

2023-11-13 16:21 UTC, merged