:recycle: [ABANDON TO NEXT] Demander abandon
MTES-MCT/potentiel pull request #1442
Opened 2023-11-24 16:58 UTC by HanaeY

2023-11-27 13:43 UTC, JulienPavon requested changes

2023-11-27 13:43 UTC, JulienPavon commented on packages/applications/ssr/src/components/templates/FormTemplate.tsx
> +export const FormTemplate: FC<FormTemplateProps> = ({ children, ...formProps }) => (
Ceci n'est pas un template mais une molécule (utilisant 2 atoms : from et div). Un template est un template de page et donc utilisable seulement par une page.

2023-11-27 13:43 UTC, JulienPavon commented on src/controllers/abandon/getDemanderAbandon.ts
> +    return response.redirect(`/laureat/${encodeURIComponent(projetId)}/abandon/demander`);
Je pense qu'il est temps de créer une query permettant de savoir si un porteur à accès au projet et donc d'éviter de coder dans le legacy. Celle-ci aura en dépendance un adapteur permettant de faire la requête dans l'ancienne projection UserProjects. Cela nous permettra d'ailleur de l'utiliser pour les prochain développement.

2023-11-28 10:33 UTC, HanaeY commented on src/controllers/abandon/getDemanderAbandon.ts
> +    return response.redirect(`/laureat/${encodeURIComponent(projetId)}/abandon/demander`);
Update suite synchro avec Sylvain et hub : la prochaine prio de Sylvain ça va être d'ajouter des middlewares pour vérifier les accès et permissions, sinon ça va être trop galère d'utiliser une query partout. Donc pour cette PR on ne met pas de vérification des accès (comme pour annuler, confirmer ou encore envoyer preuve de recandidature). Et on est d'accord que toute la partie abandon ne sortira pas sans les middlewares pour éviter le risque de fuites de données.

2023-12-01 15:58 UTC, JulienPavon requested changes

2023-12-01 15:58 UTC, JulienPavon commented on src/views/components/actions/porteurProjet.ts
> -      {
J'ai bien peur qu'on ne puisse pas encore modifier ce lien et supprimer le legacy car sinon cela nous empêchera de faire une mise en production avant la fin complète de la migration

2023-12-01 15:58 UTC, JulienPavon commented on packages/domain/lauréat/src/cahierDesCharges/cahierDesCharges.valueType.ts
> +import { InvalidOperationError } from '@potentiel-domain/core';
A-t-on vraiment besoin de toutes cette partie valuetype sachant que nous ne faisons qu'une query pour l'instant ? J'ai bien peur que tout ce qui avait été fait sur ses références et compagnie était beaucoup trop complexe et ne soit pas du tout réimplémenté de cette manière.

2023-12-01 15:58 UTC, JulienPavon commented on packages/domain/lauréat/src/cahierDesCharges/consulter/consulterCahierDesCharges.query.ts
> +export type ConsulterCahierDesChargesReadmodel = CahierDesChargesRéférence.ValueType;
Alors un readmodel doit être un objet et pas seulement un type. On pourrait je pense ici se contenter d'un type string pour le cahier des charges choisi. D'ailleurs je pense que la query devrait plutôt être ConsulterCahierDesChargesChoisi car sinon récupérer un cahier des charges devrait se faire via la période d'un appel d'offre non ?

2023-12-04 10:19 UTC, merged