350 Le PP peut annuler une demande
MTES-MCT/potentiel pull request #151
Opened 2021-05-06 17:42 UTC by paduc

2021-05-10 22:22 UTC, Zekdar requested changes

2021-05-10 22:22 UTC, Zekdar commented on src/infra/sequelize/repos/modificationRequestRepo.ts
> +  // Classic EventStoreRepos take a makeAggregate function that only takes events and an id, to make a project we needs to bind the appelsOffre argument as well
take => takes
needs => need

2021-05-10 22:22 UTC, Zekdar commented on src/modules/notification/eventHandlers/handleModificationRequestCancelled.ts
> +  } = event
Il vaut mieux privilégier la lisibilité. Si tu veux vraiment déstructurer une seule prop, je le ferais que sur un seul niveau
`const { modificationRequestId } = event.payload`

2021-05-10 22:22 UTC, Zekdar commented on src/modules/notification/eventHandlers/handleModificationRequestCancelled.ts
> +  const res = await getModificationRequestInfo(modificationRequestId)
Pourquoi `await` + `andThen` ?

2021-05-10 22:22 UTC, Zekdar commented on src/modules/notification/eventHandlers/handleModificationRequestCancelled.ts
> +              subject: `Potentiel - Annulation d'une demande de ${type} en ${departementProjet}`,
Si `departementProjet = 'Vaucluse'`, il va y avoir un problème de syntaxe, non ?
On pourrait rajouter `... de ${type} dans le département ${departementProjet}`

2021-05-10 22:22 UTC, Zekdar commented on src/views/pages/modificationRequestDetails/components/CancelButton.tsx
> +    null
Si tu enlèves cette condition, ça produit quel résultat ?

2021-05-14 11:50 UTC, paduc commented on src/infra/sequelize/queries/getModificationRequestRecipient.ts
> +  if (!ModificationRequest) return errAsync(new InfraNotAvailableError())
Non tu as raison. Ca planterait plus tot.

2021-05-14 11:52 UTC, paduc commented on src/modules/notification/eventHandlers/handleModificationRequestCancelled.ts
> +  const res = await getModificationRequestInfo(modificationRequestId)
Comme il s'agit d'un handler asynchrone, il doit gérer son cas d'erreur de manière autonome (contrairement aux use-cases qui `return` leur `ResultAsync` qui sera géré au niveau du controleur). Donc ici, il faut bien `await` le `ResultAsync` pour le laisser s'executer.

2021-05-14 11:54 UTC, paduc commented on src/modules/notification/eventHandlers/handleModificationRequestCancelled.ts
> +              subject: `Potentiel - Annulation d'une demande de ${type} en ${departementProjet}`,
Bien vu, je change la formulation.

2021-05-14 11:55 UTC, paduc commented on src/views/pages/modificationRequestDetails/components/CancelButton.tsx
> +    null
Ca plante parce que `boolean` n'est pas un type valide pour `JSX.Element`

2021-05-14 12:10 UTC, merged