458 new gf deposit after producteur actionnaire change
MTES-MCT/potentiel pull request #154
Opened 2021-05-24 00:35 UTC by Zekdar

2021-06-08 09:51 UTC, paduc requested changes

2021-06-08 09:51 UTC, paduc commented on src/modules/project/eventHandlers/handleModificationReceived.spec.ts
> +  Date.now = jest.fn(() => new Date('2020-01-01T00:00:00.000Z'))
Il ne faut pas surcharger des variables globales dans les tests.
D'une manière générale, si le comportement attendu dépend de `Data.now`, il faut en faire une dépendance du constructeur (ex: `getDateNow: () => Date`), comme on le fait pour l'eventBus, et ensuite injecter un fake dans le test (ex: `getDateNow: jest.fn(() => new Date(123))`) et la vraie dans l'implémentation (`getDataNow: () => new Date()`). 

Dans ce cas précis, la spécification dit qu'il faut prendre la date dans un mois, mais en réalité, il s'agit de la date 1 mois après le dépôt de la demande, et cette date est disponible dans l'événement `ModificationReceived`.
Donc pour le test, on peut fixer la valeur `occurredAt` de l'événement `ModificationReceived` ligne 32 et ensuite tester la valeur de `garantiesFinancieresDueOn` par rapport à cette valeur fixée.
Pas besoin d'injecter ou de surcharger `Date.now`.

2021-06-08 09:51 UTC, paduc commented on src/modules/project/eventHandlers/handleModificationReceived.ts
> +        garantiesFinancieresDueOn: moment(Date.now()).add(1, 'months').toDate().getTime(),
Utiliser `event.occurredAt` et non pas `Date.now()`.

2021-06-08 09:51 UTC, paduc commented on src/infra/sequelize/projections/project/updates/onProjectGFInvalidated.integration.ts
> +        order: ['updatedAt'],
Utiliser l'id des project steps pour vérifier leur nouvel état, c'est plus robuste que de compter sur l'ordre de sortie de `findAll`.

```ts
const updatedProjectStep1 = await ProjectStep.findByPk(projectStepId1)
expect(updatedProjectStep1.status).toEqual('invalidé')
//...
```

2021-06-08 09:51 UTC, paduc commented on src/infra/sequelize/projections/project/updates/onProjectGFInvalidated.integration.ts
> +      expect(projectSteps[0].updatedAt).toEqual(projectStep2.updatedAt)
idem

2021-06-08 09:51 UTC, paduc commented on src/infra/sequelize/projections/projectStep/updates/onProjectStepRemoved.integration.ts
> +        const steps = await ProjectStep.findAll({
Idem que l'autre, plus robuste en passant par l'id de l'objet qu'on cherche à observer.

2021-06-14 01:23 UTC, Zekdar commented on src/modules/project/eventHandlers/handleModificationReceived.spec.ts
> +      if (!event) return -1
Non ça ne suffit pas car ça ne fait pas planter le test si tu `return` tout seul

2021-06-14 17:30 UTC, paduc commented on src/modules/project/eventHandlers/handleModificationReceived.spec.ts
> +  const now = new Date()
Figer la date pour être sur que le test ne dépends pas de la date du moment:  `new Date(123)`

2021-06-14 17:30 UTC, paduc commented on src/modules/project/eventHandlers/handleModificationReceived.spec.ts
> +      if (!event) return -1
C'est le `expect(event).toBeDefined()` qui doit faire planter le test, non ?
Je pensais que `if(!event) return` n'était là que pour typescript.

2021-06-14 17:31 UTC, paduc requested changes

2021-06-14 17:31 UTC, paduc commented on src/__tests__/fixtures/projectStep.ts
> +    stepDate: new Date(),
Figer les dates pour les tests

2021-06-14 17:51 UTC, paduc approved these changes

2021-06-15 09:06 UTC, merged