346 demande changement fournisseurs
MTES-MCT/potentiel pull request #161
Opened 2021-06-14 00:41 UTC by Zekdar

2021-06-14 17:24 UTC, paduc requested changes

2021-06-14 17:24 UTC, paduc commented on src/entities/fournisseur.ts
> +export type Fournisseur = { kind: FournisseurKind; name: string }
Le dossier `src/entities` comprend du code legacy, il ne faut pas en rajouter. Les nouveaux types doivent être créés dans un sous dossier de `src/modules`. Ici je pense que le type irait dans `src/modules/project`.

2021-06-14 17:24 UTC, paduc commented on src/infra/sequelize/projections/modificationRequest/updates/onModificationRequested.ts
> +    fournisseurs,
`ModificationRequested` n'est jamais concerné par un changement de fournisseur, si ?

2021-06-14 17:24 UTC, paduc commented on src/infra/sequelize/projections/project/updates/onProjectFournisseursUpdated.integration.ts
> +  const ProjectModel = models.Project
```const { Project }  = models```

2021-06-14 17:24 UTC, paduc commented on src/infra/sequelize/projections/project/updates/onProjectFournisseursUpdated.integration.ts
> +  const projectId = uuid()
Utiliser plutot `new UniqueEntityID().toString()` pour éviter un couplage avec `uuid`.

2021-06-14 17:24 UTC, paduc commented on src/infra/sequelize/projections/project/updates/onProjectFournisseursUpdated.ts
> +    projectInstance.details[fournisseur.kind] = fournisseur.name
```
new Fourisseurs.forEach(({ kind, name }) => {
  projectInstance.details[kind] = name
})
```

2021-06-14 17:24 UTC, paduc commented on src/infra/sequelize/projections/project/updates/onProjectFournisseursUpdated.ts
> +  projectInstance.changed('details', true)
Bien joué !

2021-06-14 17:24 UTC, paduc commented on src/modules/modificationRequest/events/ModificationRequested.ts
> +  fournisseurs?: FournisseurKind[]
Idem, inutile ?

2021-06-14 17:24 UTC, paduc commented on src/modules/modificationRequest/useCases/requestFournisseursModification.spec.ts
> +    fournisseur: 'initial fournisseur',
Est-ce utile de préciser des valeurs pour `fournisseur` et `evaluationCarbone` ?

2021-06-14 17:24 UTC, paduc commented on src/useCases/requestModification.ts
> +  Fournisseurs: Fournisseur[]
Idem, jamais appelé pour `fournisseur` d'après `postRequestModification.ts`

2021-06-14 17:24 UTC, paduc commented on src/modules/notification/eventHandlers/handleModificationReceived.ts
> +        Math.round(Number(evaluationCarbone) / 50) !== Math.round(project.evaluationCarbone)
T'es sur de ta comparaison ? Il ne manque pas un `/ 50` coté droite ?

2021-06-15 12:48 UTC, Zekdar commented on src/modules/notification/eventHandlers/handleModificationReceived.ts
> +        Math.round(Number(evaluationCarbone) / 50) !== Math.round(project.evaluationCarbone)
Si :D

2021-06-15 12:49 UTC, paduc commented on src/modules/notification/eventHandlers/handleModificationReceived.ts
> +        Math.round(Number(evaluationCarbone) / 50) !== Math.round(project.evaluationCarbone)
C'est le signe qu'il manque un test ! ;)

2021-06-15 13:44 UTC, Zekdar commented on src/modules/modificationRequest/events/ModificationRequested.ts
> +  fournisseurs?: FournisseurKind[]
On le garde car quelques events ont déjà été enregistrés avec ces props

2021-06-15 13:47 UTC, Zekdar commented on src/modules/modificationRequest/useCases/requestFournisseursModification.spec.ts
> +    fournisseur: 'initial fournisseur',
Non, on peut laisser les valeurs par défaut. J'enlève.

2021-06-16 12:31 UTC, paduc commented on src/modules/modificationRequest/events/ModificationRequested.ts
> +  fournisseurs?: FournisseurKind[]
On garde `fournisseur` et on ne remplace pas par `fournisseurs`.

2021-06-16 12:33 UTC, paduc commented on src/useCases/requestModification.ts
> +  Fournisseurs: Fournisseur[]
Tu ne le retires pas ?

2021-06-16 12:59 UTC, paduc approved these changes

2021-06-17 07:56 UTC, paduc approved these changes

2021-06-17 08:33 UTC, merged