517 changement actionnaire retirer obligation depot gf
MTES-MCT/potentiel pull request #163
Opened 2021-06-20 22:34 UTC by Zekdar

2021-06-22 14:31 UTC, paduc approved these changes

2021-06-24 08:38 UTC, paduc requested changes

2021-06-24 08:38 UTC, paduc commented on src/modules/project/eventHandlers/handleModificationReceived.spec.ts
> +      producteur: 'producteur1',
En fait ce paramètre est inutile puisqu'il s'agit d'un type `puissance`. Il m'a même embrouillé parce que le titre c'est "when type is not producteur" :D

2021-06-24 19:57 UTC, Zekdar commented on src/modules/project/eventHandlers/handleModificationReceived.spec.ts
> +      producteur: 'producteur1',
Ah oui !

2021-06-25 11:33 UTC, paduc approved these changes

2021-06-27 23:05 UTC, merged