Make dev and test postgres containers independant
MTES-MCT/potentiel pull request #166
Opened 2021-06-25 09:37 UTC by paduc

Use `npm run dev-db` to start/restart the container with a local postgres database for use with the applcation.

Use `npm run test-db` to start/restart the container with a postgres database ready for integration testing (replaces `npm run test-int-init-db` which is long to type...).

2021-06-25 11:01 UTC, Zekdar requested changes

2021-06-25 11:01 UTC, Zekdar commented on package.json
> +    "test-int-init-db": "export NODE_ENV=test && export COMPOSE_PROJECT_NAME=potentiel_tests && docker compose down --remove-orphans && docker compose -f ./docker-compose-integration.yml up -d && unt
:+1:  l'astuce du`COMPOSE_PROJECT_NAME`

2021-06-25 11:29 UTC, paduc commented on package.json
> +    "test-db": "npm run test-int-init-db",
C'était pour ne pas "casser" ton workflow éventuel.

2021-06-27 23:03 UTC, Zekdar approved these changes

2021-06-28 05:52 UTC, merged