244 import legacy projects
MTES-MCT/potentiel pull request #168
Opened 2021-06-29 16:26 UTC by paduc

2021-06-29 23:48 UTC, Zekdar requested changes
Je pense qu'il ne faut pas avoir peur de split une grosse fonction en sous fonctions. Le fait de devoir mettre des commentaires qui explique le `how` au lieu du `why` est généralement code smell.

2021-06-29 23:48 UTC, Zekdar commented on src/useCases/importProjects.ts
> +  for (const index of [1, 2, 3]) {
Astucieux. C'est pour éviter un `for` traditionnel ?

2021-06-29 23:48 UTC, Zekdar commented on src/useCases/importProjects.ts
> +      if (!appelOffreId || !appelOffre) {
Simplifier : pas besoin de vérifier `appelOffreId` puisqu'il est utilisé pour recherché l'appel d'offre. Ca retournera `undefined` s'il est lui même `undefined`.

2021-06-29 23:48 UTC, Zekdar commented on src/useCases/importProjects.ts
> +      if (!periodeId || !periode) {
idem

2021-06-29 23:48 UTC, Zekdar commented on src/useCases/importProjects.ts
> +        console.log('famille manquante', appelOffre)
`logger.error`

2021-06-29 23:48 UTC, Zekdar commented on src/useCases/importProjects.ts
> +        ...appelOffre.dataFields.reduce((properties, dataField) => {
Extraire le `reduce` dans une `const` car c'est confusant de trouver ce traitement dans la construction de l'objet.

2021-06-29 23:48 UTC, Zekdar commented on src/useCases/importProjects.ts
> +              ? line[column] && line[column].split('/')[0].trim().toLowerCase()
```js
const field = line[column]
field?.split('/')[0].trim().toLowerCase()
```

2021-06-29 23:48 UTC, Zekdar commented on src/useCases/importProjects.ts
> +              ? line[column] && line[column].trim()
`field?.`

2021-06-29 23:48 UTC, Zekdar commented on src/useCases/importProjects.ts
> +              ? (line[column] && moment(line[column], 'DD/MM/YYYY').toDate().getTime()) || undefined
`field`

2021-06-29 23:48 UTC, Zekdar commented on src/useCases/importProjects.ts
> +          const fieldValue =
On a choisi de n'uiliser les ternaires que sur un seul niveau pour garder une lisibilité dans le code. Peux-tu le refacto en ce sens stp ?

De plus, je pense que ce `reduce` pourrait être exporté dans une fonction séparée, toujours pour gagner en lisibilité (et séparer les responsabilités).

2021-06-29 23:48 UTC, Zekdar commented on src/useCases/importProjects.ts
> +        )
Exporter dans une fonction séparée

2021-06-29 23:48 UTC, Zekdar commented on src/useCases/importProjects.ts
> +            !pickedColumns.includes(columnTitle)
- Condition difficile à lire. Peux-tu la split en sous variables stp ?
- Pourquoi faut-il un double cast en `unknown` et en  `string[]` ?

2021-06-29 23:48 UTC, Zekdar commented on src/useCases/importProjects.ts
> +          (map, [columnTitle, value]) => ({
`map` => `columnsAcc`

2021-06-30 08:18 UTC, paduc commented on src/useCases/importProjects.ts
> +  for (const index of [1, 2, 3]) {
Oui c'est ça.

2021-06-30 08:52 UTC, paduc commented on src/useCases/importProjects.ts
> +          `Colonne concernée ${index} doit être soit Classé ? soit Motif d'élimination pour un Recours gracieux`
Non c'est comme ça dans le fichier csv. J'ai mis des guillemets pour que ça soit plus clair.

2021-06-30 09:05 UTC, paduc commented on src/useCases/importProjects.ts
> +            !pickedColumns.includes(columnTitle)
Le cast était parce qu'il n'arrivait pas à accepter que `LegacyModificationColumns`soit un `string[]` (comme je l'avais déclaré comme `as const` pour pouvoir l'utiliser comme type, chaque possibilité était un literal). J'ai retiré le `as const`. Ce n'est pas très utile dans ce cas précis.

2021-06-30 10:27 UTC, Zekdar approved these changes

2021-06-30 12:16 UTC, merged