:recycle: [MIGRATION GARANTIES FINANCIÈRES] Branchements avec le legacy
MTES-MCT/potentiel pull request #1683
Opened 2024-03-27 10:53 UTC by HanaeY

- import types avec candidature
- recours accordé
- changement de producteur
- changement d'actionnaire

2024-04-05 13:36 UTC, HubM requested changes

2024-04-05 13:36 UTC, HubM commented on packages/applications/legacy/src/controllers/modificationRequest/postRequestModification.ts
> +          : détailAppelOffre.soumisAuxGarantiesFinancieres;
Pourquoi ne pas réutiliser la méthode `isSoumisAuxGF` définie dans `packages/applications/legacy/src/controllers/modificationRequest/postReplyToModificationRequest.ts` ici ?

2024-04-05 13:36 UTC, HubM commented on packages/specifications/src/projet/lauréat/garantiesFinancières/stepDefinitions/garantiesFinancières.then.ts
> +);
Je pense qu'ici tu devrais juste faire quelque chose du genre, je comprends pas pq on a besoin d'avoir une variale résultat à any. Normalement la query est censé throw une erreur si pas de résultat, donc tu devrais pouvoir simplifier en quelque chose comme ça  : 

```
Alors(
  `il ne devrait pas y avoir d'historique de garanties financières pour le projet {string}`,
  async function (this: PotentielWorld, nomProjet: string) {
    const { identifiantProjet } = this.lauréatWorld.rechercherLauréatFixture(nomProjet);

    await waitForExpect(async () => {
     const résultat =  await mediator.send<GarantiesFinancières.ConsulterGarantiesFinancièresQuery>({
          type: 'Lauréat.GarantiesFinancières.Query.ConsulterGarantiesFinancières',
          data: {
            identifiantProjetValue: identifiantProjet.formatter(),
          },
        });
     
      résultat.should.be.equal(`Il n'y a aucunes garanties financières sur le projet`);
    });
  },
);
```

2024-04-05 13:36 UTC, HubM commented on packages/domain/lauréat/src/garantiesFinancières/garantiesFinancières.entity.ts
> +        par?: string;
Je pense que ça devrait être tout le temps une string, et si t'as pas de valeur tu mets une chaine vide

2024-04-05 13:36 UTC, HubM commented on packages/domain/lauréat/src/garantiesFinancières/garantiesFinancières.aggregate.ts
> +  dépôts?: Array<{
ptet qu'on devrait revoir cette partie aussi mettant aucune valeur optionnelle, avoir un array vide si pas de dépots, et un objet vide pour les actuelles si pas de gf actuellement on pourra en rediscuter lundi si tu veux

2024-04-05 13:36 UTC, HubM commented on packages/domain/lauréat/src/garantiesFinancières/dépôt/validerDépôtEnCours/validerDépôtGarantiesFinancièresEnCours.behavior.ts
> +  this.dépôts = this.dépôts!.filter((dépôt) => !dépôt.statut.estEnCours());
Devoir faire des `?` ou `!` c'est assez dérangeant au final. Je pense qu'on pourra reprendre cette partie ensemble

2024-04-05 13:36 UTC, HubM commented on packages/applications/legacy/src/modules/project/eventHandlers/handleProjectRawDataImported.ts
> +const convertGarantiesFinancièresType = (typeImporté: string) => {
J'aurais plutôt nommé la fonction avec le terme "convertir" pour garder une cohérence avec le reste 

```suggestion
const convertirGarantiesFinancièresType = (typeImporté: string) => {
```

2024-04-08 09:04 UTC, HanaeY commented on packages/applications/legacy/src/controllers/modificationRequest/postRequestModification.ts
> +          : détailAppelOffre.soumisAuxGarantiesFinancieres;
parce que le retour n'est pas le même, dans l'autre on récupère un bouléen et ici on veut savoir si c'est avant ou après candidature. En revanche pour ne pas répérer la méthode isSoumisAuxGF j'ai créé un helper

2024-04-08 09:19 UTC, HanaeY commented on packages/specifications/src/projet/lauréat/garantiesFinancières/stepDefinitions/garantiesFinancières.then.ts
> +);
Tu as testé la solution que tu proposes ? pour moi elle ne fonctionne pas :s. Le résultat est une erreur puisque pour le moment on retourne encore des erreurs si la requête ne trouve rien, donc pour récupérer le message j'ai pas trouvé d'autre solution que le try/catch. On aurait pu utiliser le step "alors l'utilisateur devrait être informé que ..." mais c'est pas vraiment le résultat métier attendu.

2024-04-08 12:20 UTC, HanaeY commented on packages/domain/lauréat/src/garantiesFinancières/garantiesFinancières.aggregate.ts
> +  dépôts?: Array<{
ok on peut revoir ça, par contre je te propose de faire ça dans une autre PR de refacto pour ne pas alourdir celle-ci qui traite déjà plusieurs sujets

2024-04-08 12:45 UTC, HanaeY commented on packages/domain/lauréat/src/garantiesFinancières/dépôt/validerDépôtEnCours/validerDépôtGarantiesFinancièresEnCours.behavior.ts
> +  this.dépôts = this.dépôts!.filter((dépôt) => !dépôt.statut.estEnCours());
ok, j'ai fait une modif en attendant de faire un refacto complet de l'agrégat

2024-04-09 09:24 UTC, HubM approved these changes

2024-04-09 09:31 UTC, merged