530 Allow demande approval without the need of a mail attachment
MTES-MCT/potentiel pull request #169
Opened 2021-06-30 00:39 UTC by Zekdar

2021-06-30 07:21 UTC, paduc requested changes

2021-06-30 07:21 UTC, paduc commented on src/controllers/modificationRequest/postReplyToModificationRequest.ts
> +      !courrierReponseExists && (!acceptedReply || (!isDecisionJustice && !answerWithoutAttachment))
J'ai du mal à comprendre cette condition. Comme il n'y pas de test correspondant, ce serait bien de la rendre plus claire.

2021-06-30 07:21 UTC, paduc commented on src/views/pages/modificationRequestDetails/components/AdminResponseForm.tsx
> +          Répondre sans pièce jointe
`Répondre sans courrier` ?

2021-06-30 10:30 UTC, Zekdar commented on src/views/pages/modificationRequestDetails/components/AdminResponseForm.tsx
> +          Répondre sans pièce jointe
J'ai utilisé la phrase qui a été proposée par Julie dans la carte.

2021-07-01 08:38 UTC, paduc commented on src/controllers/modificationRequest/postReplyToModificationRequest.ts
> +      !courrierReponseExists && (!acceptedReply || (!isDecisionJustice && !replyWithoutAttachment))
J'ai l'impression que c'est l'ensemble des négatifs qui rend la lecture compliquée.
Si on inverse la logique, ça me parait plus clair:

Que penses-tu de ça ?
`const courrierReponseOk = courrierReponseExists || (acceptedReply && (isDecisionJustice || replyWithoutAttachment))`

2021-07-01 08:44 UTC, paduc approved these changes

2021-07-01 08:48 UTC, merged