Correct project data
MTES-MCT/potentiel pull request #17
Opened 2020-11-17 16:10 UTC by paduc

2020-11-20 18:44 UTC, Zekdar requested changes
N'hésite pas à split tes blocs aussi bien avec des retours à la ligne (aérer) qu'avec des sous fonctions pour gagner en lisibilité. A plusieurs occasions tu as choisi la concision > lisibilité et je trouve que ça rend la lecture plus complexe.

Sinon la PR est propre, je n'ai pas eu beaucoup de commentaires à faire hormis quelques fois sur le style.

Il faut vraiment qu'à partir de maintenant on ne fasse plus d'aussi grosse PR car c'est trop long à review et on bâcle forcément à un moment donné. Je propose qu'une PR ne dépasse pas 500l en essayant de viser 300max si possible, sauf exceptions.

2020-11-20 18:44 UTC, Zekdar commented on src/modules/notification/eventHandlers/handleProjectCertificateUploadedOrRegenerated.ts
> +        porteursProjet.map((porteurProjet) =>
Ce serait plus lisible si tu exportais la fonction anonyme vers `function sendNotification()`

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/errors/IllegalProjectDataError.ts
> +      'Champs erronés: ' +
On peut remplacer par une string interpolation 

```js
`Champs erronés: ${
  Object
    .entries(errorsInFields)
    .map(([key, value]) => `${key} (${value})`)
    .join(", ")
}`;

```

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/eventHandlers/handlePeriodeNotified.ts
> +          () => {},
pas très explicite

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/events/ProjectCertificateGenerated.ts
> +    this.payload.projectVersionDate =
`const { projectversionDate } = this.payload`

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/events/ProjectCertificateRegenerated.ts
> +    this.payload.projectVersionDate = new Date(this.payload.projectVersionDate)
const { projectversionDate } = this.payload

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/events/ProjectCertificateRegenerated.ts
> +  currentVersion = 1
Si cette variable vient bien de la classe mère, ce serait plus explicite de préfixer par `this.`

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/events/ProjectDCRSubmitted.ts
> +    this.payload.dcrDate = new Date(this.payload.dcrDate)
`const { dcrDate } = this.payload`

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/events/ProjectGFSubmitted.ts
> +    this.payload.gfDate = new Date(this.payload.gfDate)
`const { gfDate } = this.payload`

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/mappers/toProjectDataForCertificate.ts
> +      'toProjectDataForCertificate failed to create DTO because project has no data prop'
Est-ce que ça remonte la stack trace dans une erreur de type `Result` ? Si oui, pas besoin d'expliciter `toProjectDataForCertificate `

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/Project.ts
> +  if (!history || !history.length) {
`!history?.length`

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/Project.ts
> +      if (!data || !data.email) {
`!data?.email`

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/Project.ts
> +              props.data[correctionKey] !== correctionValue)
Extraire dans une constante

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/Project.ts
> +        )
Ici tu peux mettre un `return ok(null)` comme ça tu enlève le `else` (meilleure lisibilité)

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/Project.ts
> +        (!props.lastCertificateUpdate || props.lastCertificateUpdate < props.lastUpdatedOn)
Tu peux enlever `!props.lastCertificateUpdate ||`

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/Project.ts
> +      const { periode } = props.appelOffre
`const { isNotifiedOnPotentiel, certificateTemplate, notifiedOn } = props.appelOffre.periode`

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/Project.ts
> +        // When a certificate has been generated, use the version date that was current at the time of generation (projectVersionDate). Use event date when absent.
Pas utile car le code le dit déjà. En règle général : commenter le pourquoi et pas le comment.

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/Project.ts
> +      appelOffreId: props.appelOffre.id,
Tu peux extraitre `props.appelOffre` pour éviter de te répéter

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/Project.ts
> +    else props.isClasse = false
`props.isClasse = classe === 'Classé`

2020-11-20 18:44 UTC, Zekdar commented on src/modules/project/Project.ts
> +    return classe === 'Classé' ? true : classe === 'Eliminé' ? false : null
Je trouve que le chaînage des ternaires n'est pas très lisible. Je préfèrerais qu'on ne l'utilise que sur un niveau si ça te va ?

2020-11-21 11:24 UTC, paduc commented on src/core/utils/validators.ts
> +const validateOrThrow = <T>(validationFn: (obj: any) => boolean, errorMsg: string) => (
Oui c'est un façade simple pour le moment mais on peut utiliser les implémentations de Joi ou autre par la suite.

2020-11-23 08:56 UTC, paduc commented on src/modules/eventStore/makeEventStoreRepo.ts
> +export const makeEventStoreRepo = <T extends EventStoreAggregate>(deps: {
Ok je comprends ton point de vue.
J'ai fait une légère repasse dessus pour simplifier mais en essayant de faire plus, je me suis rendu compte que c'était très difficile à extraire proprement parce que les signatures typées sont très complexes. Je me retrouve à rajouter 3x le nombre de lignes pour avoir des types corrects sur la fonction extraite...

2020-11-23 09:04 UTC, paduc commented on src/modules/project/Project.ts
> +      const { periode } = props.appelOffre
Ne fonctionne pas parce que `certificateTemplate` n'est pas présent sur toutes les périodes. On a une erreur de compilation `certificateTemplate does not exist on type Periode`.

2020-11-23 09:09 UTC, paduc commented on src/modules/project/Project.ts
> +      appelOffreId: props.appelOffre.id,
Ok j'en ai profité pour rendre cette partie plus explicite.

2020-11-23 09:11 UTC, paduc commented on src/modules/project/Project.ts
> +    return classe === 'Classé' ? true : classe === 'Eliminé' ? false : null
ok je remplace par des `if/else if`

2020-11-24 09:33 UTC, Zekdar approved these changes

2020-11-24 13:07 UTC, merged