🚧 (attestation conformité): Transmission par le porteur
MTES-MCT/potentiel pull request #1768
Opened 2024-04-26 15:24 UTC by HanaeY

# Description

Les porteurs de projets lauréats non abandonnés doivent pouvoir transmettre dans Potentiel leur attestation de conformité, une preuve de la transmission de cette attestation au cocontractant et la date de cette transmission au cocontractant. Cela doit se faire depuis un formulaire accessible depuis la page d'un projet, depuis le menu "Actions" qui remplace le menu "faire une demande".
Contraintes à tester : les fichiers sont obligatoires et la date ne peut pas être future. 

## Type de changement

Veuillez supprimer les options qui ne sont pas pertinentes.

- [ ] Nouvelle fonctionnalité

# Comment cela a-t-il été testé?

Veuillez décrire les tests que vous avez effectués pour vérifier vos changements. Fournissez des instructions afin que nous puissions les reproduire. Veuillez également lister tous les détails pertinents pour la configuration de votre test.

## Pré-requis 

- [ ] Pré-requis A   
- [ ] Pré-requis B   
 
## Scénarios 

- [ ] Scénario A
- [ ] Scénario B

# Check-up :

- [ ] Mon code [suit les directives de style](../docs/contributing//DEVELOPMENT_FLOW.md) de ce projet
- [ ] J'ai effectué une auto-revue de mon code
- [ ] J'ai commenté mon code, en particulier dans les zones difficiles à comprendre
- [ ] J'ai apporté des modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun warning
- [ ] J'ai ajouté des tests qui prouvent l'efficacité de ma correction ou que ma fonctionnalité fonctionne
- [ ] Les nouveaux tests unitaires et les tests existants passent en local / dans la CI avec mes modifications

2024-05-07 14:00 UTC, VioMrqs reviewed
Quelques commentaires pas fonctionnels 
=> très difficile de review une PR aussi longue, y'avait pas moyen de faire en plusieurs petits bouts ? 
=> en plus j'ai l'impression que c'est un WIP
=> je teste le front

2024-05-08 09:50 UTC, HubM commented
> Quelques commentaires pas fonctionnels => très difficile de review une PR aussi longue, y'avait pas moyen de faire en plusieurs petits bouts ? => en plus j'ai l'impression que c'est un WIP => je teste le front

Ouais je suis bien d'accord pour la longeur de la PR. Le soucis c'est qu'on doit avancer sur le sujet, et que pour dégager des PRs plus courte faudrait qu'on ait un flow de review plus rapide. On a essayé de découper au mieux, par feature...

2024-05-08 12:41 UTC, VioMrqs commented
Front comment
- Ok pour le cas projet éliminé ou abandonné
- Ok pour la transmission
=> dans la projet, l'utilisateur de la dernière maj est admin@test.test alors que je l'ai fait via porteur@test.test
=> les inputs de fichier pourraient être plus courts (l'erreur s'affiche au milieu de l'écran dans le vide) => sinon faire en sorte que l'erreur s'affiche à gauche de l'input, c'est plus lisible
<img width="923" alt="Capture d’écran 2024-05-08 à 14 35 25" src="https://github.com/MTES-MCT/potentiel/assets/27735540/cb60870d-44c5-4d68-80cc-9ace3b9db090">

=> pas de MAJ du feed (j'imagine que c'est normal?)
<img width="425" alt="Capture d’écran 2024-05-08 à 14 36 08" src="https://github.com/MTES-MCT/potentiel/assets/27735540/7fca9a4a-acf7-49a1-b235-caa767a2f7d9">

2024-05-17 08:37 UTC, JulienPavon requested changes

2024-05-17 08:37 UTC, JulienPavon commented on packages/domain/utilisateur/src/role.valueType.ts
> +    attestationConformité: {
il faut parler d'`achevement` ici

2024-05-17 08:37 UTC, JulienPavon commented on packages/domain/lauréat/src/achèvement/attestationConformité/attestationConformité.aggregate.ts
> +export type AttestationConformitéAggregate = Aggregate<AttestationConformitéEvent> & {
Alors ici il faut renommer l'agrégat `AchèvementAggregate` car il ne s'agit pas que de l'attestation de conformité mais d'un ensemble lié à l'achèvement du projet, la preuve de transmission au cocontractant par exemple est une autre info.

2024-05-17 08:37 UTC, JulienPavon commented on packages/domain/lauréat/src/achèvement/attestationConformité/attestationConformité.entity.ts
> +export type AttestationConformitéEntity = Entity<
Ici nous avons l'ensemble des informations sur l'achèvement d'un projet et pas que l'attestation de conformité (la preuve de transmission au cocontractant par exemple est une autre info).

2024-05-17 08:37 UTC, JulienPavon commented on packages/domain/lauréat/src/achèvement/attestationConformité/attestationConformité.aggregate.ts
> +  attestation: { format: '' },
Il faudrait renommer cette propriété `attestationConformité` et avoir  la date correspondante au même niveau que le format

2024-05-17 08:37 UTC, JulienPavon commented on packages/domain/lauréat/src/achèvement/attestationConformité/attestationConformité.aggregate.ts
> +  preuveTransmissionAuCocontractant: { format: '' },
Il faudrait avoir la date correspondante au même niveau que le format

2024-05-17 08:37 UTC, JulienPavon commented on packages/domain/lauréat/src/achèvement/attestationConformité/attestationConformité.entity.ts
> +    attestation: { format: string };
Il faudrait renommer cette propriété `attestationConformité` et avoir  la date correspondante au même niveau que le format

2024-05-17 08:37 UTC, JulienPavon commented on packages/domain/lauréat/src/achèvement/attestationConformité/attestationConformité.aggregate.ts
> +      aggregateId: `attestation-conformite|${identifiantProjet.formatter()}`,
La catégorie du stream doit être `achevement`

2024-05-17 08:37 UTC, JulienPavon commented on packages/domain/lauréat/src/achèvement/attestationConformité/typeDocumentAttestationConformité.valueType.ts
> +import { InvalidOperationError } from '@potentiel-domain/core';
Le nom du fichier doit être `typeDocumentAchèvement.ts`

2024-05-17 08:38 UTC, JulienPavon requested changes
En général il faut revoir l'organisation du code du domain avec la catégorie `Achèvement` plutôt que `AttestationConformité`

2024-05-17 09:46 UTC, VioMrqs commented on packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
> +                {...(modificationsNonPermisesParLeCDCActuel && { disabled: true })}
disabled: modificationsNonPermisesParLeCDCActuel

2024-05-17 09:53 UTC, VioMrqs reviewed
Première petite partie uniquement sur le front, je regarde le back après !

2024-05-17 09:53 UTC, VioMrqs commented on packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
> +        {...{
[optionnel] Je trouve des écritures comme
        project={project}
        abandonEnCours={abandonEnCours}
        modificationsNonPermisesParLeCDCActuel={modificationsNonPermisesParLeCDCActuel}
        hasAttestationConformité={hasAttestationConformité}
bien plus lisibles

2024-05-17 09:53 UTC, VioMrqs commented on packages/applications/legacy/src/controllers/project/getProjectPage.ts
>            ...(abandon && { abandon }),
```suggestion
          abandon,
```

2024-05-17 09:53 UTC, VioMrqs commented on packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
> +              <DropdownMenuSecondaryButton.DropdownItem
[optionnel] Dans ce cas ce que j'aime bien faire c'est de sortir ce composant et de l'appeler DropDownMenuIfNoAbandon (par exemple) et de l'importer directement ici. Code mieux séparer et moins long :) 
C'est valable pour la condition en dessous

2024-05-17 14:08 UTC, HanaeY commented on packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
> +              <DropdownMenuSecondaryButton.DropdownItem
Je suis pas contre ces changement mais si ça te va je te propose de les faire dans une autre PR car là on sort du scope de cette PR qui est déjà bien grosse.

2024-05-17 14:08 UTC, HanaeY commented on packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
> +                {...(modificationsNonPermisesParLeCDCActuel && { disabled: true })}
Pareil hors scope de la PR

2024-05-17 14:10 UTC, VioMrqs reviewed
Et quelques commentaires dans le back ! 
J'ai testé en local sinon, on a l'air bon pour le comportement front + event + projection

2024-05-17 14:10 UTC, VioMrqs commented on packages/specifications/src/projet/lauréat/achèvement/attestationConformité/stepDefinitions/attestationConformité.then.ts
> +      // ASSERT ON READ MODEL
On peut virer ces commentaires, je sais pas torp à quoi ça sert ?

2024-05-17 14:10 UTC, VioMrqs commented on packages/specifications/src/projet/lauréat/achèvement/attestationConformité/stepDefinitions/attestationConformité.then.ts
> +        //attestation
Pareil

2024-05-17 14:10 UTC, VioMrqs commented on packages/specifications/src/projet/lauréat/achèvement/attestationConformité/stepDefinitions/attestationConformité.then.ts
> +        // preuve transmission
Pareil, c'est assez découpé pour qu'on comprenne

2024-05-17 14:11 UTC, VioMrqs commented on packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
> +              <DropdownMenuSecondaryButton.DropdownItem
Pas de soucis, c'est une mini refacto à faire après

2024-05-17 14:27 UTC, HanaeY commented on packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
> +                {...(modificationsNonPermisesParLeCDCActuel && { disabled: true })}
Pareil hors scope de la PR

2024-05-17 14:32 UTC, HanaeY commented on packages/applications/projectors/src/subscribers/lauréat/achèvement.projector.ts
> +      switch (type) {
yes c'est dans une PR suivante

2024-05-17 15:08 UTC, HanaeY commented on packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
> +                {...(modificationsNonPermisesParLeCDCActuel && { disabled: true })}
pas de modif faite dans cette PR

2024-05-17 15:09 UTC, HanaeY commented on packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
> +        {...{
done

2024-05-17 15:09 UTC, HanaeY commented on packages/applications/legacy/src/controllers/project/getProjectPage.ts
>            ...(abandon && { abandon }),
done

2024-05-17 15:09 UTC, HanaeY commented on packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
> +              <DropdownMenuSecondaryButton.DropdownItem
pas de modif faite dans cette PR

2024-05-17 15:09 UTC, HanaeY commented on packages/applications/legacy/src/controllers/project/getProjectPage.ts
> +            ...(garantiesFinancières && { garantiesFinancières }),
pas de modif faite dans cette PR

2024-05-17 15:09 UTC, HanaeY commented on packages/applications/projectors/src/subscribers/lauréat/achèvement.projector.ts
> +          nomProjet: Option.isSome(projet) ? projet.nom : 'Projet inconnu',
done

2024-05-17 15:10 UTC, HanaeY commented on packages/applications/projectors/src/subscribers/lauréat/achèvement.projector.ts
> +            identifiantProjet: payload.identifiantProjet,
done mais j'ai gardé l'identifiant du projet qui n'est pas dans "projet"

2024-05-17 15:10 UTC, HanaeY commented on packages/specifications/src/projet/lauréat/achèvement/attestationConformité/stepDefinitions/attestationConformité.then.ts
> +      // ASSERT ON READ MODEL
done

2024-05-17 15:10 UTC, HanaeY commented on packages/specifications/src/projet/lauréat/achèvement/attestationConformité/stepDefinitions/attestationConformité.then.ts
> +        //attestation
done

2024-05-17 15:10 UTC, HanaeY commented on packages/specifications/src/projet/lauréat/achèvement/attestationConformité/stepDefinitions/attestationConformité.then.ts
> +        // preuve transmission
done

2024-05-17 15:35 UTC, JulienPavon requested changes

2024-05-17 15:35 UTC, JulienPavon commented on packages/domain/lauréat/src/achèvement/achèvement.entity.ts
> +    attestationConformité: { format: string };
Il serait intéressant d'avoir également ici la date correspondante au même niveau que le `format`

2024-05-17 15:35 UTC, JulienPavon commented on packages/domain/lauréat/src/achèvement/achèvement.entity.ts
> +    preuveTransmissionAuCocontractant: { format: string };
Il serait intéressant d'avoir également ici la date correspondante au même niveau que le format

2024-05-17 16:03 UTC, VioMrqs approved these changes
Bon pour moi ! 
Carte crée pour les petites améliorations, je pourrais le faire une fois que tu auras merge : https://linear.app/startup-potentiel/issue/POT-282/%5Bcleancode%5D-achevement-petites-ameliorations

2024-05-21 06:45 UTC, JulienPavon approved these changes

2024-05-21 07:10 UTC, merged