✨ (Attestation de conformité transmise): notification dreal
MTES-MCT/potentiel pull request #1783
Opened 2024-05-07 13:44 UTC by HanaeY

# Description

Les utilisateurs "dreal" rattachés à la région d'un projet pour lequel une attestation de conformité a été déposée sont notifiées par mail. 

## Type de changement

Veuillez supprimer les options qui ne sont pas pertinentes.

- [ ] Correction de bug
- [ ] Nouvelle fonctionnalité
- [ ] Refacto de code
- [ ] Breaking changes (correction ou fonctionnalité qui ferait en sorte que la fonctionnalité existante ne fonctionne pas comme prévu)
- [ ] Ce changement nécessite une mise à jour de la documentation

# Comment cela a-t-il été testé?

Pas possible à tester en local

## Pré-requis 

- [ ] Pré-requis A   
- [ ] Pré-requis B   
 
## Scénarios 

- [ ] Scénario A
- [ ] Scénario B

# Check-up :

- [ ] Mon code [suit les directives de style](../docs/contributing//DEVELOPMENT_FLOW.md) de ce projet
- [ ] J'ai effectué une auto-revue de mon code
- [ ] J'ai commenté mon code, en particulier dans les zones difficiles à comprendre
- [ ] J'ai apporté des modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun warning
- [ ] J'ai ajouté des tests qui prouvent l'efficacité de ma correction ou que ma fonctionnalité fonctionne
- [ ] Les nouveaux tests unitaires et les tests existants passent en local / dans la CI avec mes modifications

2024-05-08 08:52 UTC, HubM submitted a review, later dismissed

2024-05-21 12:12 UTC, JulienPavon requested changes

2024-05-21 12:12 UTC, JulienPavon commented on packages/applications/bootstrap/src/setupLauréat.ts
> +  AttestationConformitéNotification.register();
Il faudrait renommer ceci en AchèvementNotification

2024-05-21 12:12 UTC, JulienPavon commented on packages/applications/bootstrap/src/setupLauréat.ts
> +  const unsubscribeAttestationConformitéNotification =
Renommer en `unsubscribeAchèvementNotification`

2024-05-21 12:12 UTC, JulienPavon commented on packages/applications/notifications/src/subscribers/lauréat/attestationConformité.notification.ts
> +const sendEmailAttestationConformité = async ({
Renommer le fichier en `achèvementNotification.ts` et peut être aussi cette fonction

2024-05-21 14:02 UTC, JulienPavon approved these changes

2024-05-21 14:06 UTC, merged