Poc/ore
MTES-MCT/potentiel pull request #1784
Opened 2024-05-07 16:10 UTC by VioMrqs

# Description

Veuillez inclure un résumé des changements apportés dans la PR. Veuillez également inclure la motivation et le contexte pertinents. Listez toutes les dépendances nécessaires pour ce changement.

## Type de changement

Veuillez supprimer les options qui ne sont pas pertinentes.

- [ ] Correction de bug
- [ ] Nouvelle fonctionnalité
- [ ] Refacto de code
- [ ] Breaking changes (correction ou fonctionnalité qui ferait en sorte que la fonctionnalité existante ne fonctionne pas comme prévu)
- [ ] Ce changement nécessite une mise à jour de la documentation

# Comment cela a-t-il été testé?

Veuillez décrire les tests que vous avez effectués pour vérifier vos changements. Fournissez des instructions afin que nous puissions les reproduire. Veuillez également lister tous les détails pertinents pour la configuration de votre test.

## Pré-requis 

- [ ] Pré-requis A   
- [ ] Pré-requis B   
 
## Scénarios 

- [ ] Scénario A
- [ ] Scénario B

# Check-up :

- [ ] Mon code [suit les directives de style](../docs/contributing//DEVELOPMENT_FLOW.md) de ce projet
- [ ] J'ai effectué une auto-revue de mon code
- [ ] J'ai commenté mon code, en particulier dans les zones difficiles à comprendre
- [ ] J'ai apporté des modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun warning
- [ ] J'ai ajouté des tests qui prouvent l'efficacité de ma correction ou que ma fonctionnalité fonctionne
- [ ] Les nouveaux tests unitaires et les tests existants passent en local / dans la CI avec mes modifications

2024-05-15 07:30 UTC, spontoreau requested changes

2024-05-15 07:30 UTC, spontoreau commented on packages/applications/bootstrap/package.json
> +    "@potentiel-infrastructure/ore-client": "^0.0.0",
Cette dépendance n'est plus utilisée dans le bootstrap à priori

2024-05-15 07:30 UTC, spontoreau commented on packages/applications/bootstrap/tsconfig.json
> +    {
Cette dépendance n'est plus utilisée dans le bootstrap à priori

2024-05-15 07:30 UTC, spontoreau commented on packages/applications/legacy/src/controllers/notificationCandidats/postSendCandidateNotifications.ts
> +            redirectTitle: 'Liste des projets de cette période',
Pour ce  changement dans cette PR ?

2024-05-15 07:30 UTC, spontoreau commented on packages/applications/scheduled-tasks/mettre-à-jour-gestionnaires-réseau.sh
> +if [ "$APPLICATION_STAGE" != "production" ] && [ "$APPLICATION_STAGE" != "development" ]
Il faut choisir ici, soit on lance la tâche uniquement en prod, soit sur tout les envs pour qu'il est tous le référenciel

2024-05-15 07:30 UTC, spontoreau commented on packages/applications/scheduled-tasks/mettre-à-jour-gestionnaires-réseau.sh
> +if [ -z $EVENT_STORE_CONNECTION_STRING ]
Il faut vérifier que la variable ORE_ENDPOINT soit définit sinon la tâche ne peut pas marcher

2024-05-15 07:30 UTC, spontoreau commented on packages/applications/scheduled-tasks/src/mettre-à-jour-gestionnaires-réseau.ts
> +    `[updateGestionnaireDeRéseau] Il y a ${gestionnairesRéseauToUpdate.length} gestionnaires réseau à mettre à jour`,
Comme on va switch sur un tool de monitoring plus avancé par la suite, il faut essayer de ne pas concaténer de variable dans le log. La valeur peut-être mise dans les meta (deuxiéme params)

2024-05-15 07:30 UTC, spontoreau commented on packages/applications/scheduled-tasks/src/mettre-à-jour-gestionnaires-réseau.ts
> +    const siblingOreGestionnaireRéseau = gestionnairesFromORE.find(
sibling ne me semble pas super clair comme nom de variable, en français ça serait mieux

2024-05-15 07:30 UTC, spontoreau commented on packages/applications/scheduled-tasks/src/mettre-à-jour-gestionnaires-réseau.ts
> +    `[updateGestionnaireDeRéseau] Il y a ${newGestionnairesRéseaux.length} nouveaux gestionnaires réseau à ajouter`,
Même commentaire qu'au dessus

2024-05-15 07:30 UTC, spontoreau commented on packages/applications/scheduled-tasks/src/mettre-à-jour-gestionnaires-réseau.ts
> +async function updateExistingGestionnairesDeRéseauContactEmail({
Dans la convention c'est pas spécialement précise, mais sauf besoin spécifique (genre bind ou autre) on déclare les fonctions en arrow function pour éviter les problématiques de scope

2024-05-15 07:30 UTC, spontoreau commented on packages/applications/scheduled-tasks/src/mettre-à-jour-gestionnaires-réseau.ts
> +async function addNewGestionnairesDeRéseau({ gestionnairesFromORE, gestionnairesRéseau }: Params) {
Idem : Dans la convention c'est pas spécialement précise, mais sauf besoin spécifique (genre bind ou autre) on déclare les fonctions en arrow function pour éviter les problématiques de scope

2024-05-15 07:30 UTC, spontoreau commented on packages/applications/scheduled-tasks/src/mettre-à-jour-gestionnaires-réseau.ts
> +async function updateGestionnaireDeRéseau() {
Idem : Dans la convention c'est pas spécialement précise, mais sauf besoin spécifique (genre bind ou autre) on déclare les fonctions en arrow function pour éviter les problématiques de scope

2024-05-15 07:30 UTC, spontoreau commented on packages/domain/réseau/src/gestionnaire/ajouter/ajouterGestionnaireRéseau.behavior.ts
> +    contactEmail?: string;
Pas de propriété optionnelle dans les events. On met une valeur vide pour éviter les problématiques lié à undefined quand on transforme les données.

2024-05-15 07:30 UTC, spontoreau commented on packages/domain/réseau/src/gestionnaire/ajouter/ajouterGestionnaireRéseau.behavior.ts
> +  contactEmail?: string;
On peut utiliser Option ici pour traiter le cas d'un contact email manquant

2024-05-15 07:30 UTC, spontoreau commented on packages/domain/réseau/src/gestionnaire/ajouter/ajouterGestionnaireRéseau.command.ts
> +    contactEmail?: string;
L'email doit être un value type en entrée de la command correspondant à un email. Et vu que c'est optionnel il faut utilise Option ici.

2024-05-15 07:30 UTC, spontoreau commented on packages/domain/réseau/src/gestionnaire/consulter/consulterGestionnaireRéseau.query.ts
> +  contactEmail?: string;
Idem que pour l'ajout : Pas de propriété optionnelle dans les events. On met une valeur vide pour éviter les problématiques lié à undefined quand on transforme les données.

2024-05-15 07:30 UTC, spontoreau commented on packages/domain/réseau/src/gestionnaire/consulter/consulterGestionnaireRéseau.query.ts
> +    contactEmail,
Il faut map cette valuer en value type

2024-05-15 07:30 UTC, spontoreau commented on packages/domain/réseau/src/gestionnaire/gestionnaireRéseau.entity.ts
> +    contactEmail?: string;
Comme pour les events, ici ça peut être une chaine vide si pas définit

2024-05-15 07:30 UTC, spontoreau commented on packages/domain/réseau/src/gestionnaire/lister/listerGestionnaireRéseau.query.ts
> +    contactEmail,
Idem qu'au dessus il faut map l'email emn value type

2024-05-15 07:30 UTC, spontoreau commented on packages/domain/réseau/src/gestionnaire/modifier/modifierGestionnaireRéseau.behavior.ts
> +    contactEmail?: string;
Idem qu'au dessus, pas de prop optionnelle dans les events

2024-05-15 07:30 UTC, spontoreau commented on packages/domain/réseau/src/gestionnaire/modifier/modifierGestionnaireRéseau.behavior.ts
> +    contactEmail,
Idem que pour ajouter, on peut utiliser Option ici et avoir un ValueType en entrée

2024-05-15 07:30 UTC, spontoreau commented on packages/domain/réseau/src/gestionnaire/modifier/modifierGestionnaireRéseau.command.ts
> +    contactEmail?: string;
Idem ici: ValueType + Option

2024-05-15 07:30 UTC, spontoreau commented on packages/specifications/src/gestionnaireRéseau/ajouterGestionnaireRéseau.feature
> +            | Email                | arc@gmail.com          |
Contact Email pour rester cohérent avec le reste

2024-05-15 07:30 UTC, spontoreau commented on packages/specifications/src/gestionnaireRéseau/modifierGestionnaireRéseau.feature
> +            | Email                | arc@gmail.com    |
Contact Email pour rester cohérent avec le reste

2024-05-15 07:31 UTC, spontoreau commented
Le titre de la PR est à revoir avec un emoji et une description clair (genre : mise à jour du référenciel GRD automatiquement)

2024-05-15 08:06 UTC, VioMrqs commented on packages/applications/legacy/src/controllers/notificationCandidats/postSendCandidateNotifications.ts
> +            redirectTitle: 'Liste des projets de cette période',
Quick fix en passant dessus, mais je peux virer

2024-05-15 08:06 UTC, VioMrqs commented on packages/applications/scheduled-tasks/mettre-à-jour-gestionnaires-réseau.sh
> +if [ "$APPLICATION_STAGE" != "production" ] && [ "$APPLICATION_STAGE" != "development" ]
Tous les envs sauf local :)

2024-05-16 12:58 UTC, spontoreau commented
@VioMrqs tu as un test en régression à priori.

2024-05-17 13:29 UTC, spontoreau approved these changes

2024-05-17 13:33 UTC, merged