:children_crossing: Formatage id potentiel courriers réponse
MTES-MCT/potentiel pull request #1801
Opened 2024-05-16 13:27 UTC by HanaeY

# Description

Sur les modèles de réponse aux demandes d'abandon, demandes d'abandon avec recandidature et de mise en demeure (GF), le "code Potentiel" affiché est formaté avec des "#" en séparateur. Il faut les remplacer par des "-", et placer un "P" devant la période, et un "F" devant la famille afin de faciliter la compréhension des informations. 

ex : 

- PPE2 - Eolien#1##24 devient PPE2 - Eolien-P1-24
- CRE4 - Sol#1#2#25 devient CRE4 - Sol-P1-F2-25

## Type de changement

Veuillez supprimer les options qui ne sont pas pertinentes.

- [ ] Correction de bug
- [ ] Nouvelle fonctionnalité
- [ ] Refacto de code
- [ ] Breaking changes (correction ou fonctionnalité qui ferait en sorte que la fonctionnalité existante ne fonctionne pas comme prévu)
- [ ] Ce changement nécessite une mise à jour de la documentation

# Comment cela a-t-il été testé?

- en tant que PP, demander un abandon avec recandidature > en tant que dgec-validateur choisir l'option "accorder" > vérifier le courrier de réponse généré : le "code potentiel" de l'en-tête devrait être correctement formaté
- en tant que PP, demander un abandon (classique) > en tant que dgec-validateur  ou admin choisir l'option "accorder" ou "rejeter" ou "demander conformation" > vérifier le courrier de réponse généré : le "code potentiel" de l'en-tête devrait être correctement formaté
- en tant que dreal, depuis la liste des projets en attente de GF, télécharger le modèle de mise en demeure pour des GF en retard  > vérifier le courrier de réponse généré : le "code potentiel" de l'en-tête devrait être correctement formaté

# Check-up :

- [ ] Mon code [suit les directives de style](../docs/contributing//DEVELOPMENT_FLOW.md) de ce projet
- [ ] J'ai effectué une auto-revue de mon code
- [ ] J'ai commenté mon code, en particulier dans les zones difficiles à comprendre
- [ ] J'ai apporté des modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun warning
- [ ] J'ai ajouté des tests qui prouvent l'efficacité de ma correction ou que ma fonctionnalité fonctionne
- [ ] Les nouveaux tests unitaires et les tests existants passent en local / dans la CI avec mes modifications

2024-05-16 14:01 UTC, VioMrqs submitted a review, later dismissed
ça m'a l'air bien !

2024-05-17 07:45 UTC, spontoreau requested changes

2024-05-17 07:45 UTC, spontoreau commented on packages/domain/common/src/valueTypes/identifiantProjet.valueType.ts
> +    arrange() {
Formattage à faire dans l'infra (dans l'adapter)

2024-05-21 14:12 UTC, VioMrqs approved these changes

2024-05-22 09:14 UTC, spontoreau approved these changes

2024-05-22 09:17 UTC, merged