✨ Script for moving files between two buckets
MTES-MCT/potentiel pull request #1833
Opened 2024-05-31 15:42 UTC by HubM

# Description

Veuillez inclure un résumé des changements apportés dans la PR. Veuillez également inclure la motivation et le contexte pertinents. Listez toutes les dépendances nécessaires pour ce changement.

## Type de changement

Veuillez supprimer les options qui ne sont pas pertinentes.

- [ ] Correction de bug
- [ ] Nouvelle fonctionnalité
- [ ] Refacto de code
- [ ] Breaking changes (correction ou fonctionnalité qui ferait en sorte que la fonctionnalité existante ne fonctionne pas comme prévu)
- [ ] Ce changement nécessite une mise à jour de la documentation

# Comment cela a-t-il été testé?

Veuillez décrire les tests que vous avez effectués pour vérifier vos changements. Fournissez des instructions afin que nous puissions les reproduire. Veuillez également lister tous les détails pertinents pour la configuration de votre test.

## Pré-requis 

- [ ] Pré-requis A   
- [ ] Pré-requis B   
 
## Scénarios 

- [ ] Scénario A
- [ ] Scénario B

# Check-up :

- [ ] Mon code [suit les directives de style](../docs/contributing//DEVELOPMENT_FLOW.md) de ce projet
- [ ] J'ai effectué une auto-revue de mon code
- [ ] J'ai commenté mon code, en particulier dans les zones difficiles à comprendre
- [ ] J'ai apporté des modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun warning
- [ ] J'ai ajouté des tests qui prouvent l'efficacité de ma correction ou que ma fonctionnalité fonctionne
- [ ] Les nouveaux tests unitaires et les tests existants passent en local / dans la CI avec mes modifications

2024-06-03 14:42 UTC, VioMrqs requested changes
Quelques commentaires, je pense notamment que tu peux simplifier ta partie log qui contient beaucoup de logique et de code pour donner de l'information

2024-06-03 14:42 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +const sourceBucketName = process.env.S3_BUCKET || 'potentiel';
Pourquoi mettre des défaults ici ?

2024-06-03 14:42 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +  let keys = fileKeys ? fileKeys.map((f) => f.Key).filter((f): f is string => f !== undefined) : [];
Pour éviter les let, tu peux remplacer par 

  const keys = fileKeys.map((f) => f.Key).filter((f): f is string => f !== undefined);

  if (IsTruncated) {
    logger.info(`ℹ List objects is truncated : ${IsTruncated}`);
    const nextKeys = await getAllFileKeys(source, NextMarker);
    return keys.concat(nextKeys);
  }

return keys

2024-06-03 14:42 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +const getAllFileKeys = async (source: S3, nextMarker?: string) => {
Certains noms de fonction sont en anglais, d'autres en français

2024-06-03 14:42 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +  new Upload({
il manque un await ?

2024-06-03 14:42 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +    endpoint: process.env.S3_ENDPOINT || 'http://localhost:9000',
Pourquoi mettre des options ici ?

2024-06-03 14:42 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +    process.exit();
process.exit(1) => failure code pour info
https://nodejs.org/api/process.html#processexitcode

2024-06-03 14:42 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +      const { Body: sourceFileBody } = await récupérerContenuFichier({
Pourquoi est ce qu'on ne fait pas ça avant de téléverser vers le bucket cible ?

2024-06-03 14:42 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +      const { Body: sourceFileBody } = await récupérerContenuFichier({
Je crois que c'est un duplicata

2024-06-03 14:42 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +      if (fichierSourceBodyString.length !== fichierDestinationBodyString.length) {
C'est un cas qui peut arriver ? Si il n'y a pas eu d'erreur lors du téléversage

2024-06-03 14:42 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +  if (fichiersDuBucketSourceSansContenu.length) {
ça fait beaucoup de logs et de logique pour cette partie je trouve, possibilité de simplifier peut être ? ça prendre 70 lignes de ta fonction principale
Au lieu de push les logs, directement tu les mets en warning comme ça tu as l'info, et pas besoin de dire quand il n'y a pas d'erreurs ou d'incohérence

2024-06-04 08:30 UTC, HubM commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +const getAllFileKeys = async (source: S3, nextMarker?: string) => {
On met les noms des fonctions / variables en français quand elles mentionnent un terme métier, ici par exemple c'est relatif aux clés des fichiers dans le bucket S3. Donc on peut se permettre d'utiliser un terme en anglais.

Je le rajouterais dans la documentation

2024-06-04 08:31 UTC, HubM commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +  new Upload({
Pas besoin de await si tu retournes directement une fonction asynchrone. C'est même moins performant de faire un `return await` plutôt qu'un `return` direct.
Au niveau du comportement y a pas de soucis ça fonctionne exactement pareil :)

2024-06-04 08:33 UTC, HubM commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +      const { Body: sourceFileBody } = await récupérerContenuFichier({
Non c'est normal avec S3 !
En gros quand tu prends le contenu d'un fichier A et que tu le copies dans un nouveau fichier B, si tu veux récupérer à nouveau le contenu du fichier A t'es obligé de refaire l'action d'aller le chercher dans son bucket source. On s'en est rendu compte à force de faire des scripts qui manipulent S3

2024-06-04 08:37 UTC, HubM commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +      if (fichierSourceBodyString.length !== fichierDestinationBodyString.length) {
Techniquement je sais pas si ce cas peut arriver, mais je préfère avoir une trace pour cibler les fichiers au cas où ça arrive, c'est tellement critique les fichiers qu'il vaut mieux être parano

2024-06-04 08:38 UTC, HubM commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +  if (fichiersDuBucketSourceSansContenu.length) {
Oui tu as raison j'ai mis énormément de logs, mais c'est volontaire, je voulais pouvoir isoler les problèmes pour avoir une trace claire et faciliter la maintenance post-opération.
Je pense que pour les fichiers spécifiquement vaut mieux en mettre trop pour faciliter la maintenance

2024-06-04 08:44 UTC, HubM commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +  let keys = fileKeys ? fileKeys.map((f) => f.Key).filter((f): f is string => f !== undefined) : [];
fileKeys pouvant être undefined, je vais avoir une erreur si je mets le code tel quel.
Après je pourrais modifier avec une const et laisser ma condition.

Je me demande simplement l'intérêt qu'on a de passer de `let` à `const` ici ?

2024-06-04 08:45 UTC, HubM commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +    process.exit();
Ah yes bien vu merci

2024-06-04 08:46 UTC, HubM commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +    endpoint: process.env.S3_ENDPOINT || 'http://localhost:9000',
J'avoue j'ai repris le comportement trouvés sur les autres scripts

2024-06-04 08:55 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +      const { Body: sourceFileBody } = await récupérerContenuFichier({
Ah ouaiii ok - tu m'étonnes que le script prenne un peu de temps

2024-06-04 08:55 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +      if (fichierSourceBodyString.length !== fichierDestinationBodyString.length) {
ça marche, tu vérifieras avec Sylvain

2024-06-04 08:56 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +    endpoint: process.env.S3_ENDPOINT || 'http://localhost:9000',
Je pense qu'on peut enlever du coup :) Pas hyper bonne pratique

2024-06-04 08:57 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +  let keys = fileKeys ? fileKeys.map((f) => f.Key).filter((f): f is string => f !== undefined) : [];
Il me semble que c'est pas mal d'éviter les ré-assignation au max en js, après en vrai ici ça ne change pas grand chose

2024-06-04 09:19 UTC, VioMrqs commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +const vérifierLesVariablesDEnvironnement = () => {
Un peu moins répétitif

const vérifierLesVariablesDEnvironnement = () => {
  const variables = [
    'S3_ENDPOINT',
    'AWS_ACCESS_KEY_ID',
    'AWS_SECRET_ACCESS_KEY',
    'S3_SECNUM_ENDPOINT',
    'S3_SECNUM_AWS_ACCESS_KEY_ID',
    'S3_SECNUM_AWS_SECRET_ACCESS_KEY'
  ];

  for (const variable of variables) {
    if (!process.env[variable]) {
      getLogger().error(new Error(`❌ ${variable} is not defined`));
      process.exit(1);
    }
  }
};

2024-06-04 09:39 UTC, HubM commented on packages/applications/scheduled-tasks/src/déplacer-fichiers-vers-bucket-secnum.ts
> +const vérifierLesVariablesDEnvironnement = () => {
J'avoue j'ai laissé copilot faire x)

2024-06-05 14:38 UTC, spontoreau approved these changes

2024-06-05 17:10 UTC, VioMrqs approved these changes

2024-06-06 07:32 UTC, merged