✨Ajouter le nombre de raccordements à la liste des gestionnaires
MTES-MCT/potentiel pull request #1835
Opened 2024-06-03 10:26 UTC by VioMrqs

# Description

Veuillez inclure un résumé des changements apportés dans la PR. Veuillez également inclure la motivation et le contexte pertinents. Listez toutes les dépendances nécessaires pour ce changement.

## Type de changement

Veuillez supprimer les options qui ne sont pas pertinentes.

- [ ] Correction de bug
- [ ] Nouvelle fonctionnalité
- [ ] Refacto de code
- [ ] Breaking changes (correction ou fonctionnalité qui ferait en sorte que la fonctionnalité existante ne fonctionne pas comme prévu)
- [ ] Ce changement nécessite une mise à jour de la documentation

# Comment cela a-t-il été testé?

Test visuel avec un dump de prod
Vérification avec une query

<img width="669" alt="Capture d’écran 2024-06-03 à 12 24 07" src="https://github.com/MTES-MCT/potentiel/assets/27735540/eb61f640-e5d1-4de1-a7f9-c90502e8cdcf">

## Pré-requis 

- [ ] Pré-requis A   
- [ ] Pré-requis B   
 
## Scénarios 

- [ ] Scénario A
- [ ] Scénario B

# Check-up :

- [ ] Mon code [suit les directives de style](../docs/contributing//DEVELOPMENT_FLOW.md) de ce projet
- [ ] J'ai effectué une auto-revue de mon code
- [ ] J'ai commenté mon code, en particulier dans les zones difficiles à comprendre
- [ ] J'ai apporté des modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun warning
- [ ] J'ai ajouté des tests qui prouvent l'efficacité de ma correction ou que ma fonctionnalité fonctionne
- [ ] Les nouveaux tests unitaires et les tests existants passent en local / dans la CI avec mes modifications

2024-06-03 14:22 UTC, HubM requested changes

2024-06-03 14:22 UTC, HubM commented on packages/applications/ssr/src/app/reseaux/gestionnaires/page.tsx
> +  GestionnaireWithRaccordementNumber,
Faudrait repasser ça en fr

2024-06-03 14:22 UTC, HubM commented on packages/applications/ssr/src/components/pages/réseau/gestionnaire/lister/GestionnaireRéseauList.page.tsx
> +export type GestionnaireWithRaccordementNumber = GestionnaireRéseauListItemReadModel &
À repasser en fr

2024-06-03 14:22 UTC, HubM commented on packages/applications/ssr/tsconfig.json
Pourquoi ce fichier est modifié ?

2024-06-03 14:22 UTC, HubM commented on packages/domain/réseau/src/raccordement/index.ts
T'avais une erreur spéficique pour que tu sois obligée de préciser `export type` ici ?

2024-06-03 14:23 UTC, VioMrqs commented on packages/domain/réseau/src/raccordement/index.ts
Une erreur avec isolatedModule sur tous les exports lors d'un build force, tu avais eu la même chose non ?

2024-06-03 14:24 UTC, VioMrqs commented on packages/applications/ssr/tsconfig.json
cf erreur isolatedModules, mon linter a du faire des siennes

2024-06-04 08:25 UTC, HubM approved these changes

2024-06-04 09:01 UTC, JulienPavon requested changes

2024-06-04 09:01 UTC, JulienPavon commented on packages/applications/ssr/src/app/reseaux/gestionnaires/page.tsx
> +    for (const gestionnaire of gestionnairesRéseau.items) {
Afin de gagner en performance il faudrait éxecuter ceci dans un `Promise.all`. Ou même on pourrait plutôt revoir la query afin d'y passer la liste des identifiant des gestionnaires, éxecuter la query avec l'opérateur `include` et récupérer le nombre de raccordement par gestioonnaire en une seule requête. Ensuite ici on reduirait `gestionnairesRéseau` pour y ajouter le `nombreRaccordements` issue du résultat de la query.

2024-06-04 09:45 UTC, JulienPavon commented on packages/applications/ssr/src/app/reseaux/gestionnaires/page.tsx
> +    for (const gestionnaire of gestionnairesRéseau.items) {
Ah ok ça marche pour le promise.all ;)

2024-06-04 09:59 UTC, merged