:sparkles: Instruire les demandes de main-levée de GF
MTES-MCT/potentiel pull request #1850
Opened 2024-06-06 14:19 UTC by HanaeY

# Description

La Dreal devrait avoir accès à une page d'instruction d'une demande de main-levée avec les options suivante : 
- démarrer l'instruction (passe le statut en "en-instruction'")
- télécharger un modèle de réponse
- accorder
- rejeter

La page d'instruction est accessible depuis le détail des GF du projet. 
Détail ici : https://linear.app/startup-potentiel/issue/POT-215/creation-nouvelle-page-instruction-dune-demande-de-mainlevee-des 

Le statut de la demande de main-levée doit être mis à jour sur le détail de la GF du projet.

## Type de changement

Veuillez supprimer les options qui ne sont pas pertinentes.

- [ ] Correction de bug
- [ ] Nouvelle fonctionnalité
- [ ] Refacto de code
- [ ] Breaking changes (correction ou fonctionnalité qui ferait en sorte que la fonctionnalité existante ne fonctionne pas comme prévu)
- [ ] Ce changement nécessite une mise à jour de la documentation

# Comment cela a-t-il été testé?

Veuillez décrire les tests que vous avez effectués pour vérifier vos changements. Fournissez des instructions afin que nous puissions les reproduire. Veuillez également lister tous les détails pertinents pour la configuration de votre test.

## Pré-requis 

- [ ] Pré-requis A   
- [ ] Pré-requis B   
 
## Scénarios 

- [ ] Scénario A
- [ ] Scénario B

# Check-up :

- [ ] Mon code [suit les directives de style](../docs/contributing//DEVELOPMENT_FLOW.md) de ce projet
- [ ] J'ai effectué une auto-revue de mon code
- [ ] J'ai commenté mon code, en particulier dans les zones difficiles à comprendre
- [ ] J'ai apporté des modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun warning
- [ ] J'ai ajouté des tests qui prouvent l'efficacité de ma correction ou que ma fonctionnalité fonctionne
- [ ] Les nouveaux tests unitaires et les tests existants passent en local / dans la CI avec mes modifications

2024-06-10 08:13 UTC, VioMrqs commented on packages/applications/routes/src/garanties-financières/garantiesFinancières.routes.ts
> +export const instructionMainLevée = (identifiantProjet: string) =>
Est ce qu'on ferait pas plutôt une route de ce type ?

```
export const mainLevée = {
instruire: (identifiantProjet: string) =>
  `/laureats/${encodeParameter(identifiantProjet)}/garanties-financieres/main-levee:instruire`;
lister: /garanties-financieres/main-levees-en-cours
}
```

2024-06-13 12:30 UTC, HanaeY commented on packages/applications/routes/src/garanties-financières/garantiesFinancières.routes.ts
> +};
a priori cette route pourra être supprimée puisque le détail des mainlevées est dans le détail des GF d'un projet

2024-06-13 12:32 UTC, VioMrqs commented on packages/applications/routes/src/garanties-financières/garantiesFinancières.routes.ts
> +};
Exact, je fait sauter

2024-06-13 12:34 UTC, HanaeY commented on packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/rejeter/RejeterDemandeMainleveGarantiesFinancières.tsx
> +              <p className="mt-3">Rejeter la demande de mainlevée ?</p>
pour harmonisation avec les autres : 
```suggestion
              <p className="mt-3">Êtes-vous sûr de vouloir rejeter la demande de mainlevée ?</p>
```

2024-06-13 13:02 UTC, HanaeY commented on packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/lister/ListeDemandeMainlevée.page.tsx
> +      items={mainslevées.map((mainlevée) => ({
dans le composant ListeItemDemandeMainLevée, il faudra changer la la route pour le bouton "instruire" : `Routes.GarantiesFinancières.détail(identifiantProjet`

2024-06-13 13:04 UTC, VioMrqs commented on packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/lister/ListeDemandeMainlevée.page.tsx
> +      items={mainslevées.map((mainlevée) => ({
Donc la page des garanties financières actuelles c'est ça ?

2024-06-14 08:45 UTC, JulienPavon requested changes

2024-06-14 08:45 UTC, JulienPavon commented on packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/instruire/DémarrerInstructionDemandeMainlevéeGarantiesFinancières.tsx
> +                Cela passera son statut en $
`$` À supprimer

2024-06-14 08:45 UTC, JulienPavon commented on packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/annuler/AnnulerDemandeMainlevéeGarantiesFinancières.tsx
> +        Annuler la demande de mainlevée des garanties financières
`Annuler` ce ne serait pas suffisant plutôt qu'un libellé aussi long ?

2024-06-14 08:45 UTC, JulienPavon commented on packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/accorder/AccorderDemandeMainleveGarantiesFinancières.tsx
> +        Accorder la demande
Est ce qu'on ne pourrait pas réduire l'intitulé par `Accorder` ?

2024-06-14 08:45 UTC, JulienPavon commented on packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/rejeter/RejeterDemandeMainleveGarantiesFinancières.tsx
> +        Rejeter la demande
Est ce qu'on ne pourrait pas réduire l'intitulé par `Rejeter` ?

2024-06-14 08:51 UTC, VioMrqs commented on packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/annuler/AnnulerDemandeMainlevéeGarantiesFinancières.tsx
> +        Annuler la demande de mainlevée des garanties financières
J'ai mis "Annuler la demande de mainlevée"

2024-06-14 09:48 UTC, JulienPavon approved these changes

2024-06-14 10:20 UTC, merged