✨ Notifier les porteurs quand la demande de mainlevée change de statut
MTES-MCT/potentiel pull request #1865
Opened 2024-06-13 09:33 UTC by JulienPavon

# Description

Lors de la modification du statut de sa demande de GF (en instruction, validé, ou refusé),

Le PP est notifié par email 

Objet : Le statut de la demande de main-levée des garanties financière a été modifié [Nom du projet]

Contenu : Le statut de votre demande de main-levée des garanties financières pour le projet X a été modifié + Vous pouvez consulter cette demande sur Potentiel :  lien vers la page de la garantie financière

## Type de changement

- Nouvelle fonctionnalité

2024-06-13 09:55 UTC, HubM approved these changes

2024-06-13 10:03 UTC, VioMrqs commented
Où trouver le template du mail ?

2024-06-13 10:07 UTC, HubM commented
> Où trouver le template du mail ?

Sur mailejt

2024-06-13 10:41 UTC, VioMrqs requested changes
Des petites typos à corriger
Aussi => est ce qu'on enverrait pas le statut directement dans le mail ?

2024-06-13 10:41 UTC, VioMrqs commented on packages/applications/notifications/src/subscribers/lauréat/garantiesFinancières.notification.ts
> +          subject: `Potentiel - Le statut de la demande de main-levée des garanties financière a été modifié ${nomProjet}`,
C'est mainlevée
Et financière prend un s

2024-06-13 12:11 UTC, VioMrqs approved these changes

2024-06-14 12:39 UTC, VioMrqs approved these changes

2024-06-14 12:40 UTC, merged