🎨 Add historique ID to be able to identity the rejet
MTES-MCT/potentiel pull request #1882
Opened 2024-06-19 16:08 UTC by VioMrqs

# Description

Nous devons être capable d'identifier une mainlevée rejetée dans l'historique des mainlevée rejetée pour pouvoir faire une modification de réponse signée pour un rejet spécifique => https://linear.app/startup-potentiel/issue/POT-356/[dreal]-etq-dreal-je-peux-modifier-le-courrier-de-reponse-dune
J'ai donc :
- ajouté un id pour chaque mainlevée rejetée dans la project historique
- ajouté l'array des id dans l'aggrégat GF
- modifié les tests en fonction

## Type de changement

Veuillez supprimer les options qui ne sont pas pertinentes.

- [ ] Correction de bug
- [ ] Nouvelle fonctionnalité
- [ ] Refacto de code
- [ ] Breaking changes (correction ou fonctionnalité qui ferait en sorte que la fonctionnalité existante ne fonctionne pas comme prévu)
- [ ] Ce changement nécessite une mise à jour de la documentation

# Comment cela a-t-il été testé?

Veuillez décrire les tests que vous avez effectués pour vérifier vos changements. Fournissez des instructions afin que nous puissions les reproduire. Veuillez également lister tous les détails pertinents pour la configuration de votre test.

## Pré-requis 

- [ ] Pré-requis A   
- [ ] Pré-requis B   
 
## Scénarios 

- [ ] Scénario A
- [ ] Scénario B

# Check-up :

- [ ] Mon code [suit les directives de style](../docs/contributing//DEVELOPMENT_FLOW.md) de ce projet
- [ ] J'ai effectué une auto-revue de mon code
- [ ] J'ai commenté mon code, en particulier dans les zones difficiles à comprendre
- [ ] J'ai apporté des modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun warning
- [ ] J'ai ajouté des tests qui prouvent l'efficacité de ma correction ou que ma fonctionnalité fonctionne
- [ ] Les nouveaux tests unitaires et les tests existants passent en local / dans la CI avec mes modifications

2024-06-19 16:46 UTC, benjlevesque reviewed
j'ai juste spotté deux détails, je peux pas challenger le fond du changement...

2024-06-19 16:46 UTC, benjlevesque commented on packages/specifications/src/projet/lauréat/mainLevéeGarantiesFinancières/rejeterDemandeMainlevéeGarantiesFinancières.feature
> +@select
```suggestion
```

2024-06-19 16:46 UTC, benjlevesque commented on packages/domain/lauréat/src/garantiesFinancières/garantiesFinancières.aggregate.ts
> +  historiqueMainlevéeRejetée?: Array<string>;
au pluriel, non?
```suggestion
  historiqueMainlevéeRejetées?: Array<string>;
```

2024-06-20 07:29 UTC, spontoreau requested changes

2024-06-20 07:29 UTC, spontoreau commented on packages/domain/lauréat/src/garantiesFinancières/mainlevée/rejeter/rejeterDemandeMainlevéeGarantiesFinancières.usecase.ts
> +import { v4 as uuid } from 'uuid';
Alors je connais pas le besoin exact, mais on ne doit jamais utiliser d'identifiant technique dans le domain, uniquement des identifiants naturels.

C'est quelque chose qui n'a pas été fait dans le legacy et qui a posé des soucis par la suite lors de la maintenance

2024-06-20 07:31 UTC, spontoreau commented
Je ne connais pas le besoin exacte, mais je refuse d'approve cette PR (cf mon commentaire sur l'identifiant technique).

On peut en parler aprés le daily si besoin

2024-06-20 07:54 UTC, VioMrqs commented
=> vu en daily, ça part aux oubliettes, on utilisera la date !

2024-06-20 07:54 UTC, closed without merging