✨ Renommer un fichier s3
MTES-MCT/potentiel pull request #1888
Opened 2024-06-21 13:46 UTC by benjlevesque

2024-06-21 13:46 UTC, benjlevesque commented on docker-compose.yml
> +    command: server /data --console-address ":9090"
La console minio ne fonctionnait pas car le port devrait etre 9090, il est exposé en tant que 9091 plus bas (L91)

2024-06-24 15:34 UTC, JulienPavon requested changes

2024-06-24 15:34 UTC, JulienPavon commented on packages/libraries/file-storage/src/test-utils.ts
> +export const setTestBucket = (bucketName: string) => {
Ici je serai plus explicite sur le nom de la fonction avec `setTestBucketEnvVariable` ou un truc du genre

2024-06-24 15:47 UTC, JulienPavon approved these changes

2024-06-24 15:52 UTC, merged