Switch from sqlite to postgres
MTES-MCT/potentiel pull request #19
Opened 2020-11-19 14:42 UTC by Zekdar

2020-11-21 11:08 UTC, paduc requested changes

2020-11-21 11:08 UTC, paduc commented on src/dataAccess/db/projectAdmissionKey.ts
> +      allowNull: true,
Je ne suis pas sur de l'intérêt d'accepter une valeur `null` plutôt qu'une valeur 0 par défaut.
Il y a deux risques: 
1. que dans le code métier, je check si la valeur est 0
2. que dans les données en base, il y ait un mélange de 0 et de null

2020-11-21 11:08 UTC, paduc commented on src/infra/sequelize/migrations/20201103233948-add-fulltext-search-to-project.js
> +          console.log(query)
`console.log` à retirer ?

2020-11-21 11:08 UTC, paduc commented on src/infra/sequelize/projections/project/project.model.ts
> +        allowNull: true,
Idem, risque pour les règles métier et les données en base.

2020-11-21 11:08 UTC, paduc commented on src/sequelize.config.js
> +  port: 5432,
Le port devrait aussi être issu d'une variable d'environnement.

2020-11-23 09:39 UTC, Zekdar commented on src/infra/sequelize/migrations/20201103233948-add-fulltext-search-to-project.js
> +          console.log(query)
bien vu

2020-11-23 13:14 UTC, Zekdar commented on src/sequelize.config.js
> +  port: 5432,
yep

2020-11-23 14:06 UTC, paduc approved these changes

2020-11-23 20:18 UTC, merged