✨ Exécuter tâche planifiée
MTES-MCT/potentiel pull request #1991
Opened 2024-07-19 14:59 UTC by benjlevesque

2024-07-19 15:01 UTC, benjlevesque commented on packages/specifications/src/tâche-planifiée/executerTâchePlanifiée.feature
> +    #  Et les garanties financières du projet "Du boulodrome de Marseilles" sont échues
TODO décommenter

2024-07-19 16:21 UTC, benjlevesque commented on packages/specifications/src/tâche-planifiée/stepDefinitions/tâchePlanifiée.when.ts
> +      // TODO  l'aggregate n'a pas pris en compte les events publiés ?
```suggestion
```

2024-07-19 16:23 UTC, benjlevesque commented on packages/specifications/src/tâche-planifiée/exécuterTâchePlanifiée.feature
> +    # TODO Et les garanties financières du projet "Du boulodrome de Marseilles" sont échues
TODO décommenter

2024-07-19 16:23 UTC, benjlevesque commented on packages/specifications/src/tâche-planifiée/exécuterTâchePlanifiée.feature
> +    # TODO Et les garanties financières du projet "Du boulodrome de Marseilles" sont échues
TODO décommenter

2024-07-19 16:23 UTC, benjlevesque commented on packages/specifications/src/tâche-planifiée/exécuterTâchePlanifiée.feature
> +        # TODO retirer GF ? on teste juste le use case Tacheplanifiée
TODO

2024-07-19 16:23 UTC, benjlevesque commented on packages/specifications/src/tâche-planifiée/exécuterTâchePlanifiée.feature
> +    # TODO Et les garanties financières du projet "Du boulodrome de Marseilles" sont échues
TODO

2024-07-22 09:09 UTC, HubM requested changes

2024-07-22 09:09 UTC, HubM commented on packages/domain/tâche-planifiée/src/ajouter/ajouterTâchePlanifiée.behavior.ts
> +import * as TâchePlanifiéeType from '../typeTâchePlanifiée.valueType';
Dnas les events métiers on utilise le terme `typeTâchePlanifiée`, du coup pourquoi renommer ici?

2024-07-22 09:09 UTC, HubM commented on packages/specifications/src/tâche-planifiée/stepDefinitions/tâchePlanifiée.when.ts
> +        },
on veut pas trigger l'erreur ici ?

2024-07-22 09:35 UTC, benjlevesque commented on packages/domain/tâche-planifiée/src/ajouter/ajouterTâchePlanifiée.behavior.ts
> +import * as TâchePlanifiéeType from '../typeTâchePlanifiée.valueType';
non c'est une erreur, j'ai voulu corriger la typo (inversion planifiée et tâche) mais tu as raison ca devrait etre `TypeTâchePlanifiée`

2024-07-22 09:38 UTC, benjlevesque commented on packages/specifications/src/tâche-planifiée/stepDefinitions/tâchePlanifiée.when.ts
> +        },
il faut le mettre à chaque fois le try/catch? même quand ce n'est pas attendu?

2024-07-22 09:44 UTC, benjlevesque commented on packages/specifications/src/tâche-planifiée/stepDefinitions/tâchePlanifiée.when.ts
> +        },
(je l'ai mis, ca a l'air d'être presque toujours le cas en effet)

2024-07-22 09:49 UTC, HubM approved these changes

2024-07-22 09:50 UTC, merged