feat/candidature/domain
MTES-MCT/potentiel pull request #2058
Opened 2024-08-07 10:40 UTC by benjlevesque

- **✨ Schema de validation du fichier CSV d'import des candidatures**
- **♻️ Refactor output shape schema**
- **✨ Instruire candidature - domaine et specs**

2024-08-08 14:42 UTC, benjlevesque commented on packages/domain/candidature/src/candidature.entity.ts
> +    identifiantProjet: IdentifiantProjet.RawType;
à retirer après avoir renommé ConsulterCandidature en ConsulterProjet

2024-08-09 07:08 UTC, HubM requested changes

2024-08-09 07:08 UTC, HubM commented on packages/applications/projectors/src/subscribers/candidature/candidature.projector.ts
> +          });
Pourquoi pas directement faire : 
```suggestion
          await upsertProjection<CandidatureEntity>(`candidature|${identifiantProjet}`, candidatureDefaultValue);
```

2024-08-09 07:08 UTC, HubM commented on packages/domain/candidature/src/importer/importerCandidature.usecase.ts
> +    const { statutValue, dateÉchéanceGfValue, technologieValue } = payload;
tu peux merger ces deux extractions du payload non ?

2024-08-09 07:08 UTC, HubM commented on packages/specifications/src/candidature/importerCandidature.feature
> +Fonctionnalité: Importée une candidature
```suggestion
Fonctionnalité: Importer une candidature
```

2024-08-09 07:08 UTC, HubM commented on packages/specifications/src/candidature/stepDefinitions/candidature.then.ts
> +      assert(Option.isSome(candidature), 'Candidature non trouvée');
Tu devrais pas rajouter un expect juste avant histoire d'avoir un trigger dans le step au niveau de la CI ? 

Il me semble que le assert n'est pas détecté quand on run les tests

2024-08-09 07:47 UTC, benjlevesque commented on packages/specifications/src/candidature/stepDefinitions/candidature.then.ts
> +      assert(Option.isSome(candidature), 'Candidature non trouvée');
ah si si, assert envoie une erreur dans les tests. D'ailleurs le texte en deuxième paramètre est le message d'erreur si le premier est falsy

2024-08-09 07:47 UTC, benjlevesque commented on packages/domain/candidature/src/importer/importerCandidature.usecase.ts
> +    const { statutValue, dateÉchéanceGfValue, technologieValue } = payload;
hum oui certes, mais ca fait plein de lignes 😅

2024-08-09 08:38 UTC, HubM approved these changes

2024-08-09 08:38 UTC, merged