🎨 Ne pas afficher les pages raccordements si le projet est abandonné ou éliminé
MTES-MCT/potentiel pull request #2156
Opened 2024-09-04 13:58 UTC by HubM

# Description

Ajout d'utilitaire au niveau des routes next (page.tsx) pour :
- vérifier qu'un projet existe
- vérifier que celui-ci n'est pas abandonné

J'ai appliqué cette vérification aux pages raccordements suivantes : 
- détail du raccordement
- transmettre DCR
- Modifier le gestionnaire du raccordement

## Type de changement

- [x] Correction de bug
- [x] Nouvelle fonctionnalité

2024-09-04 14:52 UTC, VioMrqs requested changes
Effectivement dommage de ne pas pouvoir bloquer l'affichage avant ! 
Du coup je t'ai fait une remarque pour ta fonction, moi j'aurais peut être balancé le notFound ici directement plutôt => ```packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/page.tsx```

2024-09-04 14:52 UTC, VioMrqs commented on packages/applications/ssr/src/app/_helpers/récupérerProjetSiNonAbandonné.ts
> +export const récupérerProjetSiNonAbandonné = async (identifiantProjet: string) => {
Mais du coup on s'en fiche de récupérer le projet vu ton usage, tu veux juste vérifier que le projet n'est pas abandonné non ? 
Effectivement passer par un middleware serait mieux, pourquoi ça ne fonctionne pas ?

Sinon tu n'as pas besoin de retourner le projet, tu peux juste faire quelque chose de ce type : 

```
export const vérifieQueLeProjetNestPasAbandonné = async (identifiantProjet: string) => {
  const projet = await récupérerProjet(identifiantProjet);

  if (StatutProjet.convertirEnValueType(projet.statut).estAbandonné()) {
    return notFound();
  }
};
```

2024-09-04 14:52 UTC, VioMrqs commented on packages/applications/ssr/src/components/pages/réseau/raccordement/détails/AucunDossierDeRaccordement.page.tsx
> +        Aucun dossier de raccordement trouvé pour ce projet,{' '}
Pourquoi tu supprimes ```vous devez transmettre un```?

2024-09-04 15:22 UTC, HubM commented on packages/applications/ssr/src/app/_helpers/récupérerProjetSiNonAbandonné.ts
> +export const récupérerProjetSiNonAbandonné = async (identifiantProjet: string) => {
On peut pas passer un middleware à la volée à une route, à moins d'utiliser du pattern-matching. Je comprends l'idée qu'ils ont eu de faire ça, mais c'est relou à maintenir.

2024-09-04 15:23 UTC, HubM commented on packages/applications/ssr/src/components/pages/réseau/raccordement/détails/AucunDossierDeRaccordement.page.tsx
> +        Aucun dossier de raccordement trouvé pour ce projet,{' '}
fausse manip

2024-09-04 15:27 UTC, HubM commented
> Effectivement dommage de ne pas pouvoir bloquer l'affichage avant ! Du coup je t'ai fait une remarque pour ta fonction, moi j'aurais peut être balancé le notFound ici directement plutôt => `packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/page.tsx`

Je suis pas d'accord avec l'endroit où retourner le `notFound()`, pour moi il doit rester dans la fonction helper, c'est bien tout l'intérêt. Vu que ce helper est utilisé à trois endroits ça fait sens de mon pdv

2024-09-04 15:37 UTC, VioMrqs commented on packages/applications/ssr/src/app/_helpers/récupérerProjetSiNonAbandonné.ts
> +export const récupérerProjetSiNonAbandonné = async (identifiantProjet: string) => {
ça me choque pas trop les path matcher, mais comme tu veux ;)

2024-09-04 15:37 UTC, VioMrqs approved these changes

2024-09-04 16:09 UTC, benjlevesque commented on packages/applications/ssr/src/app/_helpers/récupérerProjetSiNonAbandonné.ts
> +export const récupérerProjetSiNonAbandonné = async (identifiantProjet: string) => {
je pense pas que ca ait ca place dans un middleware, parce que Next ne supporte qu'un seul middleware, du coup ce serait le bordel. S'il en supportait plusieurs ce serait une autre histoire... 

En revanche, on pourrait imaginer d'utiliser un [layout ](https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates) pour ca... (mais peut etre dans une autre PR, c'est une expérience qu'il faut qu'on fasse)

2024-09-05 07:01 UTC, HubM commented on packages/applications/ssr/src/app/_helpers/récupérerProjetSiNonAbandonné.ts
> +export const récupérerProjetSiNonAbandonné = async (identifiantProjet: string) => {
Ouais le layout ça pourrait effectivement répondre au besoin mais à priori pas tout seul, sauf si on modifie l'arborescence des routes du dossier app.

Par contre je pense que combiné à [route groups](https://nextjs.org/docs/app/building-your-application/routing/route-groups) ça pourrait marcher. 

Après selon moi la finalité est qu'on doit pouvoir facilement faire ces vérifications, et que ça soit suffisamment  explicite pour garantir une maintenance facile et fluide.

2024-09-05 07:48 UTC, benjlevesque commented on packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/page.tsx
> +        vérifierQueLeProjetNestPasÉliminé(projet.statut, projet.statut),
c'est pas les bons paramètres il me semble !

2024-09-05 07:48 UTC, benjlevesque commented on packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/demande-complete-raccordement:transmettre/page.tsx
> +      vérifierQueLeProjetNestPasÉliminé(projet.statut, projet.statut),
c'est pas les bons paramètres il me semble !

2024-09-05 08:16 UTC, VioMrqs reviewed
Quelques commentaires (encore 👼 )

2024-09-05 08:16 UTC, VioMrqs commented on packages/applications/ssr/src/app/_helpers/vérifierQueLeProjetNestPasÉliminé.ts
> +  projetStatut?: Candidature.ConsulterProjetReadModel['statut'],
Pourquoi est il optionnel ?

2024-09-05 08:16 UTC, VioMrqs commented on packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/demande-complete-raccordement:transmettre/page.tsx
> +    await vérifierQueLeProjetNestPasAbandonné(identifiantProjet.formatter(), projet.statut);
[optionnel] Tant qu'à faire vu l'usage tu pouvais vérifier les 2 d'un coup avec une fonction vérifierQueLeProjetNestPasAbandonnéOuEliminé(identifiantProjet.formatter(), projet.statut) et fusionner tes 2 fonctions du haut

2024-09-05 08:17 UTC, HubM commented on packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/demande-complete-raccordement:transmettre/page.tsx
> +    await vérifierQueLeProjetNestPasAbandonné(identifiantProjet.formatter(), projet.statut);
J'ai fais deux méthodes car si on généralise cette approche on aura besoin à un moment d'avoir ptet que le contexte éliminé ou abandonné !

2024-09-05 08:25 UTC, VioMrqs commented on packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/demande-complete-raccordement:transmettre/page.tsx
> +    await vérifierQueLeProjetNestPasAbandonné(identifiantProjet.formatter(), projet.statut);
On pourra découper si on en a besoin, autant faire à l'usage :)

2024-09-05 08:27 UTC, VioMrqs approved these changes
Merci

2024-09-05 08:35 UTC, VioMrqs approved these changes

2024-09-05 08:37 UTC, VioMrqs reviewed
last but not least

2024-09-05 08:37 UTC, VioMrqs commented on packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/gestionnaire:modifier/page.tsx
> +    const projet = await récupérerProjet(identifiantProjet);
Juste un détail, dans l'autre page (transmettre) tu fais ça => 
```
    const decodedIdentifiant = decodeParameter(identifiant);

    const identifiantProjet = IdentifiantProjet.convertirEnValueType(decodedIdentifiant);

    const projet = await récupérerProjet(identifiantProjet.formatter());
```

Du coup si en une ligne c'est bon tu peux simplifier non ?

2024-09-05 08:43 UTC, VioMrqs approved these changes

2024-09-05 08:45 UTC, merged