✅ Impossible de transmettre une demande complète de raccordement si le projet est abandonné
MTES-MCT/potentiel pull request #2177
Opened 2024-09-10 14:09 UTC by HubM

# Comment cela a-t-il été testé?

TDD

2024-09-10 14:18 UTC, spontoreau requested changes

2024-09-10 14:18 UTC, spontoreau commented on packages/domain/réseau/src/raccordement/transmettre/transmettreDemandeComplèteRaccordement.behavior.ts
> +    throw new Abandon.ProjetAbandonnéError(
Cette exception devrait être dans le domain Raccordement et spécifique pour ce cas avec un nom explicte :ImpossibleTransmetttreDCRProjetAbandonnéError

2024-09-10 15:04 UTC, benjlevesque commented on packages/domain/réseau/src/raccordement/transmettre/transmettreDemandeComplèteRaccordement.command.ts
> +      aUnAbandonAccordé: !!abandon.accord?.accordéLe,
peut-on avoir une fonction `estAccordé` sur l'aggrégat abandon afin d'éviter de répartir ce genre de logique hors du domaine abandon ?

2024-09-11 07:24 UTC, benjlevesque approved these changes

2024-09-11 07:24 UTC, spontoreau commented on packages/domain/réseau/src/raccordement/transmettre/transmettreDemandeComplèteRaccordement.command.ts
> +      aUnAbandonAccordé: !!abandon.accord?.accordéLe,
Yes bonne remarque !

2024-09-11 11:03 UTC, spontoreau approved these changes

2024-09-11 11:05 UTC, merged