✨ Ajouter la preview et le téléchargement de l'attestation sur la page candidature
MTES-MCT/potentiel pull request #2182
Opened 2024-09-12 09:42 UTC by VioMrqs

# Description

- Ajouter la preview et le téléchargement de l'attestation sur la page candidature
- Mini fix => ID formulaire, ajout d'un StatusCandidature pour éviter des confusions

## Type de changement

Veuillez supprimer les options qui ne sont pas pertinentes.

- [x] Nouvelle fonctionnalité

# Comment cela a-t-il été testé?

Visuel

# Check-up :

- [ ] Mon code [suit les directives de style](../docs/contributing//DEVELOPMENT_FLOW.md) de ce projet
- [ ] J'ai effectué une auto-revue de mon code
- [ ] J'ai commenté mon code, en particulier dans les zones difficiles à comprendre
- [ ] J'ai apporté des modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun warning
- [ ] J'ai ajouté des tests qui prouvent l'efficacité de ma correction ou que ma fonctionnalité fonctionne
- [ ] Les nouveaux tests unitaires et les tests existants passent en local / dans la CI avec mes modifications

2024-09-12 10:21 UTC, benjlevesque commented on packages/applications/ssr/src/app/candidatures/page.tsx
> +    for (const identifiantPériode of identifiantsPériode) {
faut voir mais je me demande si ca vaut pas le coup de faire `listerPériode` ? sauf si périodeParams est set peut-être...

2024-09-12 10:22 UTC, benjlevesque commented on packages/applications/ssr/src/app/candidatures/page.tsx
> +    for (const identifiantPériode of identifiantsPériode) {
en fait on a ces cas:
- pas de filtre: vaut mieux faire listerPériode
- filtre sur AO: listerPériode avec filtre sur AO
- filtre sur période: consulter période
- filter sur statut candidature: listerPériode ?

2024-09-12 14:22 UTC, VioMrqs commented on packages/applications/ssr/src/app/candidatures/page.tsx
> +    for (const identifiantPériode of identifiantsPériode) {
Ok je change, bonne idée

2024-09-12 16:26 UTC, benjlevesque commented on packages/domain/candidature/src/consulter/consulterProjet.query.ts
> +import * as Technologie from '../valueType/typeTechnologie.valueType';
on le fait que dans "common"  d'avoir un dossier à part. Je suis pas contre, mais dans ce cas on peut introduire un `index.ts` et ainsi définir `* as Technologie` dans cet index, ce qui faciliterait l'autocompletion

on en parle au daily voir si le changement fait consensus

2024-09-12 16:27 UTC, benjlevesque commented on packages/domain/candidature/src/consulter/consulterProjet.query.ts
> +import * as Technologie from '../valueType/typeTechnologie.valueType';
NB: risque de conflit avec #2185, si on peut faire ca dans un second temps ca m'arrange

2024-09-12 16:36 UTC, benjlevesque requested changes

2024-09-12 16:36 UTC, benjlevesque commented on packages/applications/ssr/src/app/candidatures/page.tsx
> +  identifiantProjet,
c'est pas bon ca, tu peux avoir `périodeParams` qui est set, mais pas `identifiantProjet`. Pour moi cette fonction doit prendre `identifiantPériode` en input.

2024-09-12 16:36 UTC, benjlevesque commented on packages/applications/ssr/src/app/candidatures/page.tsx
> +    : await récupérerPériodes({ appelOffreParams });
```suggestion
  const périodes = périodeParams || identifiantProjet
    ? await récupérerPériode({ identifiantPériode: périodeParams??identifiantProjet.formatter().slice(0, ...) })
    : await récupérerPériodes({ appelOffreParams });
```

2024-09-13 07:39 UTC, VioMrqs commented on packages/domain/candidature/src/consulter/consulterProjet.query.ts
> +import * as Technologie from '../valueType/typeTechnologie.valueType';
Ok noté, je peux revert pour le moment

2024-09-13 10:38 UTC, benjlevesque commented on packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
> +      {!project.isLegacy && (
attention tu as changé la condtion, on ne veut pas afficher ce bouton si le projet est notifé

2024-09-13 10:38 UTC, benjlevesque commented on packages/applications/ssr/src/components/pages/candidature/lister/CandidatureListItemActions.tsx
> +      {estNotifiée && (
dans les refactos récents on a plutot un array d'actions qui viennent de la page
ici ce serait `télecharger-attestation`  ou `prévisualiser-attestation`

ca évite de se trimbaler plein de variables dans les composants et d'avoir la logique dans le composant

ex: https://github.com/MTES-MCT/potentiel/pull/2181/files#diff-c33eafa0c451eafc8949430994dc004f5ffd2e583d06eb73b5d9b6a23804e382R67

2024-09-13 11:30 UTC, VioMrqs commented on packages/applications/ssr/src/components/pages/candidature/lister/CandidatureListItemActions.tsx
> +      {estNotifiée && (
Hub m'avait dit une fois que c'était une "ancienne façon de faire dans le projet", j'ai fait un peu différemment du coup

2024-09-13 14:18 UTC, benjlevesque commented on packages/applications/ssr/src/components/pages/candidature/lister/CandidatureListItemActions.tsx
> +      {estNotifiée && (
ah bon dac, je trouvais pas ca si mal. Perso j'aimerais bien un record (genre `actions={{preview:true, download: false}}`), avec typage

2024-09-13 14:21 UTC, benjlevesque approved these changes

2024-09-16 07:30 UTC, VioMrqs commented on packages/applications/ssr/src/components/pages/candidature/lister/CandidatureListItemActions.tsx
> +      {estNotifiée && (
Pas mal, ça pourrait se refacto rapidement au niveau du projet (encore un truc non prio)

2024-09-16 07:30 UTC, merged