🔥 ETQ PP je ne reçois qu'une notification lorsqu'un ou plusieurs de mes projets est notifié
MTES-MCT/potentiel pull request #2250
Opened 2024-09-24 12:19 UTC by VioMrqs

# Description

Veuillez inclure un résumé des changements apportés dans la PR. Veuillez également inclure la motivation et le contexte pertinents. Listez toutes les dépendances nécessaires pour ce changement.

## Type de changement

Veuillez supprimer les options qui ne sont pas pertinentes.

- [ ] Correction de bug
- [ ] Nouvelle fonctionnalité
- [ ] Refacto de code
- [ ] Breaking changes (correction ou fonctionnalité qui ferait en sorte que la fonctionnalité existante ne fonctionne pas comme prévu)
- [ ] Ce changement nécessite une mise à jour de la documentation

# Comment cela a-t-il été testé?

Veuillez décrire les tests que vous avez effectués pour vérifier vos changements. Fournissez des instructions afin que nous puissions les reproduire. Veuillez également lister tous les détails pertinents pour la configuration de votre test.

## Pré-requis 

- [ ] Pré-requis A   
- [ ] Pré-requis B   
 
## Scénarios 

- [ ] Scénario A
- [ ] Scénario B

# Check-up :

- [ ] Mon code [suit les directives de style](../docs/contributing//DEVELOPMENT_FLOW.md) de ce projet
- [ ] J'ai effectué une auto-revue de mon code
- [ ] J'ai commenté mon code, en particulier dans les zones difficiles à comprendre
- [ ] J'ai apporté des modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun warning
- [ ] J'ai ajouté des tests qui prouvent l'efficacité de ma correction ou que ma fonctionnalité fonctionne
- [ ] Les nouveaux tests unitaires et les tests existants passent en local / dans la CI avec mes modifications

2024-09-24 13:26 UTC, benjlevesque requested changes
il faut notifier uniquement les PP qui ont des projets concernés par la période notifiée

2024-09-25 07:00 UTC, benjlevesque requested changes

2024-09-25 07:00 UTC, benjlevesque commented on packages/applications/notifications/src/subscribers/période/période.notification.ts
> +          période: période.id,
attention là tu charges potentiellement les périodes de plusieurs AO, il faut aussi un filtre pour l'AO concerné

2024-09-25 07:16 UTC, benjlevesque commented on packages/applications/notifications/src/subscribers/période/période.notification.ts
> +            modification_request_url: `${BASE_URL}/projets.html`,
attention, je crois pas que ce sont les bonns variables

2024-09-25 07:16 UTC, benjlevesque commented on packages/applications/notifications/src/subscribers/période/période.notification.ts
> +          messageSubject: `Potentiel - Notification de la période ${période.id} de l'appel d'offres ${appelOffre.id}`,
attention, pas le bon subject

2024-09-25 09:00 UTC, VioMrqs commented on packages/applications/notifications/src/subscribers/période/période.notification.ts
> +            modification_request_url: `${BASE_URL}/projets.html`,
C'était ça pour les utilisateurs hors PP et DGEC (pour les variables et le sujet) : 

```
        messageSubject: `Potentiel - Notification de la période ${période.id} de l'appel d'offres ${appelOffre.id}`,
        variables: {
          appel_offre: appelOffre.id,
          periode: période.id,
          date_notification: new Date(event.payload.notifiéeLe).toLocaleDateString(),
```

Et j'ai ajouté ```modification_request_url``` car, en regardant le template du mail, j'ai vu que cette var était demandée (mais pas envoyée, c'est donc un petit fix)

2024-09-25 09:01 UTC, VioMrqs commented on packages/applications/notifications/src/subscribers/période/période.notification.ts
> +          messageSubject: `Potentiel - Notification de la période ${période.id} de l'appel d'offres ${appelOffre.id}`,
Ah bon ? C'est un copié collé

2024-09-25 15:18 UTC, benjlevesque approved these changes
lgtm :)

2024-09-26 06:11 UTC, JulienPavon approved these changes

2024-09-26 07:32 UTC, merged