✨ Ajout d'une commande cli pour vérifier l'existance de fichiers S3
MTES-MCT/potentiel pull request #2292
Opened 2024-10-09 10:43 UTC by benjlevesque

2024-10-14 12:01 UTC, JulienPavon commented on packages/applications/cli/src/commands/files/check.ts
> +export default class FilesRename extends Command {
Il faudrait renommer la class

2024-10-14 12:03 UTC, JulienPavon commented on packages/libraries/file-storage/src/fileExists.ts
> +export const fileExists = async (filePath: string) => {
Quelle est l'utilité d'avoir 2 fonctions `assertFileExists` et `fileExists` qui ont le même rôle ? (j'ai bien vu que les signatures ne sont pas les mêmes mais le besoin est identique)

2024-10-14 12:53 UTC, benjlevesque commented on packages/applications/cli/src/commands/files/check.ts
> +export default class FilesRename extends Command {
bien vu ;)

2024-10-16 07:27 UTC, JulienPavon requested changes

2024-10-16 07:27 UTC, JulienPavon commented on packages/applications/cli/src/helpers/renameFile.ts
> +    throw new FichierInexistant(fromName);
Est ce que on aurait pas plutôt une erreur `RenameFailedError` avec une info qui dirait `from file inexistant`. (et faire de même pour l'erreur suivante) ?

2024-10-16 07:27 UTC, JulienPavon commented on packages/libraries/file-storage/src/copyFile.ts
> +      throw new FichierInexistant(targetKey);
Est ce que on aurait pas plutôt une erreur `CopyFailedError` avec une info qui dirait `from file inexistant` ?

2024-10-16 08:56 UTC, benjlevesque commented on packages/applications/cli/src/helpers/renameFile.ts
> +    throw new FichierInexistant(fromName);
done

2024-10-16 08:56 UTC, benjlevesque commented on packages/libraries/file-storage/src/copyFile.ts
> +      throw new FichierInexistant(targetKey);
done

2024-10-17 08:42 UTC, JulienPavon approved these changes

2024-10-17 08:44 UTC, merged