497 reset front side check on power modification requests
MTES-MCT/potentiel pull request #231
Opened 2021-11-02 15:23 UTC by HanaeY

2021-11-03 08:47 UTC, JulienPavon requested changes

2021-11-03 08:47 UTC, JulienPavon commented on src/controllers/modificationRequest/getDemandePage.ts
> +import { NewModificationRequestPage } from '../../views/index'
Retirer index du chemin d'import car implicite

2021-11-03 08:47 UTC, JulienPavon commented on src/modules/modificationRequest/helpers/getAutoAcceptRatiosForAppelOffre.ts
> +    case 'CRE4 - Bâtiment':
Couvrir avec des tests

2021-11-03 08:47 UTC, JulienPavon commented on src/views/components/requestList.tsx
> +import { titlePerAction } from '../pages/newModificationRequestPage/index'
Retirer index du chemin d'import car implicite

2021-11-03 08:47 UTC, JulienPavon commented on src/views/pages/newModificationRequestPage/index.tsx
> +import { Puissance } from './newModificationRequest.stories';
Import à enlever

2021-11-03 08:47 UTC, JulienPavon commented on src/views/pages/newModificationRequestPage/index.tsx
> +  const infoOnPowerModificationValidation = (e) => {
Renomer la fonction par handlePuissanceOnChange

2021-11-03 08:47 UTC, JulienPavon commented on src/views/pages/newModificationRequestPage/index.tsx
> +    handleDisplayAlertOnPower(puissanceModificationRatio < minAutoAcceptPuissanceRatio || puissanceModificationRatio > maxAutoAcceptPuissanceRatio)
Extraire dans une constante la vérification de la modification de la puissance

2021-11-03 11:53 UTC, paduc commented on src/views/pages/newModificationRequestPage/index.tsx
> +    handleDisplayAlertOnPower(puissanceModificationRatio < minAutoAcceptPuissanceRatio || puissanceModificationRatio > maxAutoAcceptPuissanceRatio)
Renommer en `setDisplayAlertOnPower` (le préfixe `handle` est à reserver aux handlers d'événements).

2021-11-03 12:06 UTC, HanaeY commented on src/controllers/modificationRequest/getDemandePage.ts
> +import { NewModificationRequestPage } from '../../views/index'
ok

2021-11-03 12:07 UTC, HanaeY commented on src/views/components/requestList.tsx
> +import { titlePerAction } from '../pages/newModificationRequestPage/index'
ok

2021-11-03 12:09 UTC, HanaeY commented on src/views/pages/newModificationRequestPage/index.tsx
> +import { Puissance } from './newModificationRequest.stories';
ok

2021-11-03 12:15 UTC, HanaeY commented on src/views/pages/newModificationRequestPage/index.tsx
> +  const infoOnPowerModificationValidation = (e) => {
ok

2021-11-03 12:28 UTC, HanaeY commented on src/views/pages/newModificationRequestPage/index.tsx
> +    handleDisplayAlertOnPower(puissanceModificationRatio < minAutoAcceptPuissanceRatio || puissanceModificationRatio > maxAutoAcceptPuissanceRatio)
ok pour les deux

2021-11-03 14:59 UTC, HanaeY commented on src/modules/modificationRequest/helpers/getAutoAcceptRatiosForAppelOffre.ts
> +    case 'CRE4 - Bâtiment':
ok

2021-11-04 08:35 UTC, JulienPavon approved these changes

2021-11-04 08:35 UTC, JulienPavon commented on src/views/helpers/titlePerAction.ts
> +export const titlePerAction = {
Renommer avec un nom plus précis comme par exemple `ModificationRequestActionTitles`

2021-11-04 08:55 UTC, JulienPavon reviewed
Concernant le "titlePerAction" dans l'idéal il faudrait créer un composant qui retourne l'intitulé par rapport au type de demande modification passé en props.
Et ensuite on réutilise ce composant.

2021-11-04 16:48 UTC, merged