630 as pp i can opt in new cdc rules from project page
MTES-MCT/potentiel pull request #237
Opened 2021-11-08 13:30 UTC by HanaeY

to be confirmed: under which conditions must the form be displayed

2021-11-08 13:31 UTC, paduc commented
> to be confirmed: under which conditions must the form be displayed

Tu veux dire quoi par là ?

2021-11-08 13:48 UTC, paduc requested changes

2021-11-08 13:48 UTC, paduc commented on src/controllers/project/postUpdateNewRulesOptIn.ts
> +        if (!optedInBy) {
Cette condition est impossible avec `ensureRole`.

2021-11-08 13:48 UTC, paduc commented on src/views/pages/projectDetailsPage/index.tsx
> +            <Section title="Cahier des charges" icon="clipboard-check">
Aligner cette section à gauche comme les autres.

2021-11-08 13:48 UTC, paduc commented on src/views/components/CDCChoiceForm.tsx
> +    const handleCDCChange = (event :any) => {
Dans ce cas, c'est le composant `CDCChoiceFrom` qui pilote son parent avec `setSubmitBtnState`.
La composition doit se faire dans l'autre sens, c'est à dire que le parent doit écouter le composant et choisir son comportement.

Ici, le composant `CDCChoiceForm` doit exposer l'événement utilisateur de sélection de choix. Il peut exposer un prop `onChoiceChange ?: (isNewRules: boolean) => void` par exemple, qui serait un handler passé par le parent (ou pas s'il n'est pas intéressé par cet événement).

Coté composant, on aurait
```ts
const handleCDCChange = (event: any) => {
  if(props.onChoiceChange){
    props.onChoiceChange(event.target.value === "Nouvelles règles")
  }
}
```

Coté parent, on peut rajouter un handler pour effectuer un comportement:
```ts
<CDCChoiceForm onChoiceChange={ (isNewRule) => setDisplaySubmitButton(isNewRule) } />
```

2021-11-08 13:48 UTC, paduc commented on src/views/components/CDCChoiceForm.tsx
> +            <div style={{border: "1px solid #adb9c9", padding: 20, borderRadius: 3, marginBottom: 15}}>
N'hésite pas à utiliser les utilities `tailwindcss` maintenant qu'ils sont disponibles.

2021-11-08 13:48 UTC, paduc commented on src/views/pages/newModificationRequestPage/index.tsx
> +              <CDCChoiceForm project={project} cahiersChargesURLs={cahiersChargesURLs} setSubmitBtnState={null}/>
Il me semble que le comportement de cette page est que si on choisit les anciennes règles, le formulaire de demande de modification disparait. Non ?

2021-11-08 16:43 UTC, HanaeY commented on src/views/pages/newModificationRequestPage/index.tsx
> +              <CDCChoiceForm project={project} cahiersChargesURLs={cahiersChargesURLs} setSubmitBtnState={null}/>
Dans le composant j'ai changé le comportement du formulaire de choix du CDC : le cahier des charges actuel est coché par défaut. L'impact sur la vue newModificationRequestPage est que les champs suivants (ex : puissance) sont affichés si le PP sélectionne les nouvelles règles. Tu aimerais avoir l'ancien comportements, à savoir ne pas cocher par défaut la cahier des charges actuel et afficher tout le formulaire lorsque le PP arrive sur la page ? ou alors garder ce nouveau comportement mais utiliser react (et non plus les scripts) pour gérer l'affichage du formulaire ?

2021-11-08 16:45 UTC, paduc commented on src/views/pages/newModificationRequestPage/index.tsx
> +              <CDCChoiceForm project={project} cahiersChargesURLs={cahiersChargesURLs} setSubmitBtnState={null}/>
Je pense que le nouveau comportement est bien. J'étais surpris de voir que ça fonctionnait même sans handler react. Ce serait bien d'utiliser react pour l'intégralité des comportements de ce composant au moins.

2021-11-08 16:46 UTC, HanaeY commented on src/views/pages/projectDetailsPage/index.tsx
> +            <Section title="Cahier des charges" icon="clipboard-check">
Je ne suis pas sûre d'avoir compris. La section a un décalage à droite comme les deux sections précédence car est englobées dans une condition.

2021-11-08 18:41 UTC, paduc commented on src/views/pages/projectDetailsPage/index.tsx
> +            <Section title="Cahier des charges" icon="clipboard-check">
Pardon, je voulais parler du css / centrage visuel sur la page. Je ne sais pas si c'est une règle spécifique à la section ou bien le composant.

2021-11-10 08:19 UTC, HanaeY commented on src/views/components/CDCChoiceForm.tsx
> +            <div style={{border: "1px solid #adb9c9", padding: 20, borderRadius: 3, marginBottom: 15}}>
J'ai testé un composant Tailwind Radio Group sur ce formulaire CDC mais le rendu ne s'intégrait pas bien avec les autres inputs dans lequel le formulaire est inséré, à mon avis il faudrait changer le style de tous les formulaires dans la même user story pour ne pas perturber l'utilisateur avec différents styles. Qu'en penses-tu ? En attendant j'ai commencé par utiliser les classes tailwinds plutôt sur du css inline.

2021-11-15 13:16 UTC, paduc commented on src/views/pages/projectDetailsPage/index.tsx
> +                  onChoiceChange={(isNewRule:boolean) => setDisplaySubmitButton(isNewRule)}
Ici, ce n'est pas nécessaire (et potentiellement risqué) de mettre le type de `isNewRule`. Celui-ci est déjà fixé par l'interface `CDCFormProps`.

2021-11-15 13:17 UTC, paduc approved these changes

2021-11-15 13:41 UTC, merged