641 refactor user creation
MTES-MCT/potentiel pull request #238
Opened 2021-11-09 09:54 UTC by paduc

2021-11-10 08:55 UTC, JulienPavon commented on src/modules/authZ/eventHandlers/handleUserCreated.spec.ts
> +    const userProjectLinkedEvents = eventBus.publish.mock.calls
On pourrait peut être simplifier cette partie de cette manière :
`
const expectedEvent = new UserProjectsLinkedByContactEmail({
      payload: { userId: 'userId', projectIds: [projectWithSameEmailId] },
    })
    expect(eventBus.publish).toHaveBeenNthCalledWith(1, expectedEvent)
`

2021-11-10 10:00 UTC, JulienPavon requested changes

2021-11-10 12:04 UTC, paduc commented on src/modules/authZ/eventHandlers/handleUserCreated.spec.ts
> +    const userProjectLinkedEvents = eventBus.publish.mock.calls
Bien vu, c'est un problème récurrent partout.

Malheureusement, on ne peut pas utiliser `new UserProjectsLinkedByContactEmail` en l'état parce que la date `occurredAt` à l'intérieur de l'instance d'événement change à chaque `new`. Les instances ne seront pas égales.

J'ai deux pistes:
- Overrider la méthode `valueOf` de `BaseDomainEvent` pour ne faire de comparaison que du payload (si le payload est identique, l'objet est identique).
- Une extension de jest qui rajoute un opérateur du type `expect(eventBus).toHavePublishedEvent(...)`

J'ai un résultat très aléatoire avec `valueOf`, c'est super bizarre.

2021-11-12 09:24 UTC, paduc commented on src/modules/authN/queries/CreateUserCredentials.ts
> +    null,
Il n'est pas possible d'utiliser `void` pour le typage du paramètre de valeur d'un `ResultAsync`. C'est pourquoi j'utilise `null` dans les commandes qui ne renvoient rien.

2021-11-12 09:44 UTC, paduc commented on src/modules/users/User.ts
> +    role: OldUser['role']
Tout à fait, je l'ai mis dans `modules/user/UserRoles.ts` comme `entities/user` est voué à disparaitre.
J'en ai profité pour mettre à jour tous les usages dans la code base.

2021-11-12 10:33 UTC, JulienPavon commented on src/modules/authN/queries/CreateUserCredentials.ts
> +    null,
Ah dommage

2021-11-12 10:33 UTC, JulienPavon approved these changes

2021-11-12 10:50 UTC, merged