🚧 WIP Historique mainlevée rejetée
MTES-MCT/potentiel pull request #2397
Opened 2024-10-31 11:02 UTC by VioMrqs

# Description

Veuillez inclure un résumé des changements apportés dans la PR. Veuillez également inclure la motivation et le contexte pertinents. Listez toutes les dépendances nécessaires pour ce changement.

## Type de changement

Veuillez supprimer les options qui ne sont pas pertinentes.

- [ ] Correction de bug
- [ ] Nouvelle fonctionnalité
- [ ] Refacto de code
- [ ] Breaking changes (correction ou fonctionnalité qui ferait en sorte que la fonctionnalité existante ne fonctionne pas comme prévu)
- [ ] Ce changement nécessite une mise à jour de la documentation

# Comment cela a-t-il été testé?

Veuillez décrire les tests que vous avez effectués pour vérifier vos changements. Fournissez des instructions afin que nous puissions les reproduire. Veuillez également lister tous les détails pertinents pour la configuration de votre test.

## Pré-requis 

- [ ] Pré-requis A   
- [ ] Pré-requis B   
 
## Scénarios 

- [ ] Scénario A
- [ ] Scénario B

# Check-up :

- [ ] Mon code [suit les directives de style](../docs/contributing//DEVELOPMENT_FLOW.md) de ce projet
- [ ] J'ai effectué une auto-revue de mon code
- [ ] J'ai commenté mon code, en particulier dans les zones difficiles à comprendre
- [ ] J'ai apporté des modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun warning
- [ ] J'ai ajouté des tests qui prouvent l'efficacité de ma correction ou que ma fonctionnalité fonctionne
- [ ] Les nouveaux tests unitaires et les tests existants passent en local / dans la CI avec mes modifications

2024-11-07 14:23 UTC, HubM commented on packages/applications/projectors/src/subscribers/lauréat/garantiesFinancières.projector.ts
> +  }
```suggestion
  if (Option.isSome(mainlevée)) {
    for (const détailsMainlevée of mainlevée.détailsMainlevées) {
      await removeProjection<GarantiesFinancières.DétailsMainlevéeGarantiesFinancièresEntity>(
        `details-mainlevee-garanties-financieres|${identifiantProjet}#${détailsMainlevée.demande.demandéeLe}`,
      );
    }
    await removeProjection<GarantiesFinancières.MainlevéeGarantiesFinancièresEntity>(
      `mainlevee-garanties-financieres|${identifiantProjet}`,
    );
  }
```

2024-11-07 15:45 UTC, HubM commented on packages/domain/lauréat/src/garantiesFinancières/mainlevée/mainlevéeGarantiesFinancières.entity.ts
> +  identifiantProjet: string;
Pourquoi remettre l'identifiantProjet ici ?

2024-11-07 15:45 UTC, HubM commented on packages/domain/lauréat/src/garantiesFinancières/mainlevée/mainlevéeGarantiesFinancières.entity.ts
> +  nomProjet: string;
Pareil ici on a déjà ces infos au niveau supérieur non ?

2024-11-07 15:49 UTC, HubM commented on packages/domain/lauréat/src/garantiesFinancières/mainlevée/consulter/consulterHistoriqueDemandeMainlevéeRejetéeGarantiesFinancières.query.ts
> +      result.détailsMainlevées.filter((mainlevée) => mainlevée.statut === 'rejeté').length < 1;
C'est toujours mieux d'utiliser le valueType

```suggestion
      result.détailsMainlevées.filter((mainlevée) => StatutMainlevéeGarantiesFinancières.convertirEnValueType(mainlevée.statut).estRejeté()).length < 1;
```

2024-11-07 15:54 UTC, HubM requested changes
Quelques questions / suggestions

2024-11-07 16:20 UTC, HubM commented
Je viens de faire un test en faisant un rebuild de la category `garanties-financieres` et quand j'accède à la liste des demande de mainlevée  j'ai une seule demande, alors que dans mes projections j'en ai 112. Je pense qu'il y a un problème.

<img width="1906" alt="Capture d’écran 2024-11-07 à 17 18 17" src="https://github.com/user-attachments/assets/f8b3e589-96df-4417-8bb4-b6b78ef295c9">

<img width="147" alt="Capture d’écran 2024-11-07 à 17 20 06" src="https://github.com/user-attachments/assets/b913227d-e7fd-43c4-b684-7867b5837024">

2024-11-07 17:11 UTC, VioMrqs commented on packages/domain/lauréat/src/garantiesFinancières/mainlevée/mainlevéeGarantiesFinancières.entity.ts
> +  nomProjet: string;
Oui mais j'en ai besoin pour la query List ! Comme dans Raccordement / DossierRaccordement, même si je suis pas contente de dupliquer effectivement

2024-11-07 17:11 UTC, VioMrqs commented on packages/domain/lauréat/src/garantiesFinancières/mainlevée/consulter/consulterHistoriqueDemandeMainlevéeRejetéeGarantiesFinancières.query.ts
> +      result.détailsMainlevées.filter((mainlevée) => mainlevée.statut === 'rejeté').length < 1;
Yes merci

2024-11-07 17:12 UTC, VioMrqs commented
Pourquoi y'a l'erreur "112 rows fetched" ? Je vais refaire des tests :)

2024-11-07 17:15 UTC, VioMrqs commented on packages/domain/lauréat/src/garantiesFinancières/mainlevée/mainlevéeGarantiesFinancières.entity.ts
> +  identifiantProjet: string;
Idem que le commentaire du bas, j'en ai besoin dans le front ensuite...

2024-11-12 09:10 UTC, benjlevesque commented on packages/domain/lauréat/src/garantiesFinancières/mainlevée/consulter/consulterDemandeEnCoursMainlevéeGarantiesFinancières.query.ts
> +    return ConsulterDemandeEnCoursMainlevéeGarantiesFinancièresMapToReadModel(result);
```suggestion
    return mapToReadModel(result);
```

2024-11-13 08:52 UTC, VioMrqs commented on packages/applications/projectors/src/subscribers/lauréat/garantiesFinancières.projector.ts
> +  // TODO: delete this after migration
Hum le problème c'est que ces projections ne vont pas être supprimées dans ce cas

2024-11-13 08:53 UTC, VioMrqs commented on packages/applications/projectors/src/subscribers/lauréat/garantiesFinancières.projector.ts
> +  // TODO: delete this after migration
Vu que maintenant c'est identifiantprojet#datededemande

2024-11-13 09:12 UTC, benjlevesque commented on packages/applications/projectors/src/subscribers/lauréat/garantiesFinancières.projector.ts
> +  // TODO: delete this after migration
oui mais ca devrait faire partie de ta procédure de migration

2024-11-13 14:14 UTC, benjlevesque approved these changes

2024-11-13 14:28 UTC, HubM approved these changes

2024-11-13 14:29 UTC, merged