:star: 509 ETQ porteur de projet, je peux créer un compte sur Potentiel
MTES-MCT/potentiel pull request #241
Opened 2021-11-12 13:41 UTC by JulienPavon

Afin de tester cette fonctionnalité la création d'utilisateur a été activée sur l'environnement staging et il a fallu également ajouter le rôle 'Porteur de projet' aux rôles par défaut.

Avant le merge il faudra donc faire ses 2 changements sur l'instance de production.

2021-11-12 15:36 UTC, paduc requested changes

2021-11-12 15:36 UTC, paduc commented on src/infra/keycloak/attachUserToRequestMiddleware.spec.ts
> +          getUserByEmail.mockImplementation((email) =>
Je ne suis pas à l'aise avec la réutilisation de spy entre les tests (sauf s'ils sont ignorés). Préférer une redéfinition dans le scope du test: `const getUserByEmail = jest.fn((email) => ...)`.

2021-11-12 15:36 UTC, paduc commented on src/modules/users/User.spec.ts
> -describe('User.registerFirstLogin()', () => {
Retirer l'import de `UserRegistered`

2021-11-12 15:36 UTC, paduc commented on src/modules/users/User.ts
> -        props.isRegistered = true
Du coup, `isRegistered` ne sert plus dans les props. A retirer.

2021-11-12 15:36 UTC, paduc commented on src/infra/keycloak/attachUserToRequestMiddleware.ts
> +              isRegistered: true,
`isRegistered` ne sert plus. A retirer (partout dans la codebase).

2021-11-12 15:43 UTC, JulienPavon commented on src/infra/keycloak/attachUserToRequestMiddleware.spec.ts
> +        hasRealmRole.mockReturnValue(false)
Je ne crois pas qu'il y ait d'avantage en effet. Je vais faire le changement pour être homogène dans le code

2021-11-12 15:45 UTC, JulienPavon commented on src/modules/users/User.ts
> -        props.isRegistered = true
En effet et je crois que celui-ci est réapparu apreès mon rebase

2021-11-15 08:42 UTC, paduc commented on src/infra/keycloak/attachUserToRequestMiddleware.ts
> +    const userResult = await getUserByEmail(userEmail).andThen((user: User | null) => {
Ici le typage des arguments est donné par `getUserByEmail`, pas nécessaire de l'expliciter. D'ailleurs je me demande si ça ne présente pas un risque (ex: si le type de `getUserByEmail` change, le code de ce scope ne verra pas le changement).

2021-11-15 08:45 UTC, paduc commented on src/infra/keycloak/attachUserToRequestMiddleware.ts
> +    }
Une autre manière d'écrire ça pour info:

```ts
await getUserByEmail(...).match((user) => { request.user = user }, (err) => { logger.error(err) })
```

2021-11-15 08:48 UTC, JulienPavon commented on src/infra/keycloak/attachUserToRequestMiddleware.ts
> +    const userResult = await getUserByEmail(userEmail).andThen((user: User | null) => {
Bien vu d'ailleurs je ne me rappelle plus pourquoi je l'avais rajouté :sweat_smile:

2021-11-15 08:48 UTC, paduc approved these changes

2021-11-15 14:45 UTC, paduc commented on src/modules/users/useCases/createUser.ts
> +          return ok({ id, role })
Ici `andThen` n'est pas utile puisqu'on ne fait qu'une transformation du résultat (`andThen` est pour les traitements qui peuvent retourner soit `Ok` soit `Err`). On peut donc utiliser `map` dont c'est le role.

```ts
user.getUserId().map((id) => ({ id, role }))
```

2021-11-16 09:27 UTC, paduc commented on src/__tests__/fakes/makeCreateUser.ts
> +  jest.fn((createUserArgs) => {
On se retrouve dans le cas de figure que j'ai évoqué hier: ici, tu crées un fake avec `jest.fn` mais tu le types avec `CreateUser`.
Donc quand on fait `const createUser = makeFakeCreateUser()`, le type de `createUser` est `CreateUser`, ce qui va très bien pour l'injecter dans un use-case mais qui ne permet pas de faire `expect(createUser).toHaveBeenCalled()`.
Si on n'en a pas besoin, on peut laisser le typage comme ça, mais alors c'est inutile de passer par `jest.fn()`, on peut écrire directement `makeFakeCreateUser =  (fakeArgs) => (createUserArgs) => okAsync({ ... })`.

Si on veut pouvoir profiter du `jest.fn()` de notre fake, il faut retirer le typage `CreateUser` et accepter que le type de retour de `makeFakeCreateUser` est `(fake) => jest.Mock<...>(...)`.
Peut-être que les use-case vont faire des erreurs de compilation lors de l'injection, et dans ce cas, on peut faire un cast du type lors de l'injection:
```
const fakeCreateUser = makeFakeCreateUser()
const myUseCase = makeUserCase({ createUser: fakeCreateUser as CreateUser })

expect(fakeCreateUser).toHaveBeenCalledWith({ role: 'porteur-projet'})
```

Est-ce que je suis clair ? On peut en parler sur Gather si tu veux.

2021-11-16 09:29 UTC, paduc commented on keycloak/themes/potentiel/email/html/email-verification.ftl
> +      <a href="${link}" style="display:inline-block;background:#1c38b0;color:#ffffff;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;tex
`Créer mon compte` => `Valider mon courriel`

2021-11-16 09:31 UTC, paduc commented on keycloak/themes/potentiel/email/messages/messages_en.properties
> +emailVerificationBody=Afin de finaliser la création de votre compte, merci de cliquer sur le bouton ci-dessous.
Dans le version texte, il n'y a pas de bouton. Il faut l'ajouter dans le corps du message.

```
Afin de finaliser la création de votre compte, merci de cliquer sur le lien ci-dessous.\n\n{0}\n\nSi vous n'êtes pas à l'origine de cette création vous pouvez ignorer cet email.
```

2021-11-17 15:48 UTC, JulienPavon commented
Alors pour notre problème d'"access denied" en fait cela vient de la function ensureRole qui vérifie le role depuis le token prèsent. Cependant comme nous n'avons pas encore ajouté le role dans keycloak le role ne figure pas dans le token tant que celui-ci est valide.
Donc j'ai rajouté la suppression du cookie de session express lorsque l'utilisateur créé est un succès et qu'il n'y avait pas de role dans le token avant la création

2021-11-17 16:07 UTC, paduc commented on src/infra/keycloak/keycloakClient.ts
> +    console.log(`KEYCLOAK ENV VARS : ${KEYCLOAK_SERVER} and ${KEYCLOAK_REALM}`)
`console.log` à retirer

2021-11-17 16:07 UTC, paduc commented on src/infra/keycloak/attachUserToRequestMiddleware.ts
> +          logger.info(JSON.stringify(user))
`logger.info` à retirer ?

2021-11-18 09:09 UTC, paduc requested changes

2021-11-18 15:01 UTC, paduc approved these changes

2021-11-18 15:49 UTC, merged