✨ Ajout de tache planifiée pour "accorder / rejeter" les demandes de changement de représentant légal en fonction de la période de l'AO du projet
MTES-MCT/potentiel pull request #2542
Opened 2024-12-17 16:12 UTC by HubM

# Description

Veuillez inclure un résumé des changements apportés dans la PR. Veuillez également inclure la motivation et le contexte pertinents. Listez toutes les dépendances nécessaires pour ce changement.

## Type de changement

Veuillez supprimer les options qui ne sont pas pertinentes.

- [ ] Correction de bug
- [ ] Nouvelle fonctionnalité
- [ ] Refacto de code
- [ ] Breaking changes (correction ou fonctionnalité qui ferait en sorte que la fonctionnalité existante ne fonctionne pas comme prévu)
- [ ] Ce changement nécessite une mise à jour de la documentation

# Comment cela a-t-il été testé?

Veuillez décrire les tests que vous avez effectués pour vérifier vos changements. Fournissez des instructions afin que nous puissions les reproduire. Veuillez également lister tous les détails pertinents pour la configuration de votre test.

## Pré-requis 

- [ ] Pré-requis A   
- [ ] Pré-requis B   
 
## Scénarios 

- [ ] Scénario A
- [ ] Scénario B

# Check-up :

- [ ] Mon code [suit les directives de style](../docs/contributing//DEVELOPMENT_FLOW.md) de ce projet
- [ ] J'ai effectué une auto-revue de mon code
- [ ] J'ai commenté mon code, en particulier dans les zones difficiles à comprendre
- [ ] J'ai apporté des modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun warning
- [ ] J'ai ajouté des tests qui prouvent l'efficacité de ma correction ou que ma fonctionnalité fonctionne
- [ ] Les nouveaux tests unitaires et les tests existants passent en local / dans la CI avec mes modifications

2024-12-19 13:07 UTC, VioMrqs commented on packages/domain/lauréat/src/garantiesFinancières/typeTâchePlanifiéeGarantiesFinancières.valueType.ts
> +  // estInconnu: () => boolean;
comment oublié ?

2024-12-19 13:08 UTC, VioMrqs commented on packages/domain/lauréat/src/représentantLégal/changement/typeTâchePlanifiéeChangementReprésentantLégal.valueType.ts
> +  estChangementRéputéAccordé: () => boolean;
Pourquoi Réputé ? Plutôt Supposé non ?

2024-12-19 13:10 UTC, VioMrqs commented on packages/specifications/src/tâche-planifiée/tâchePlanifiée.world.ts
> +  | 'instruction tacite de la demande de changement de représentant légal';
Suggestion : 'gestion automatique de la demande de changement de représentant légal'

2025-01-02 16:36 UTC, VioMrqs commented on packages/specifications/src/tâche-planifiée/tâchePlanifiée.world.ts
> +      .with('executée', () => StatutTâchePlanifiée.exécutée)
Mini typo (exécutée), mais y'aurait pas mal de change à faire

2025-01-03 14:25 UTC, benjlevesque reviewed
je ne suis pas sur de comprendre pourquoi `changement.représentantLégal.typeTâchePlanifiée` est sur la période et non l'Appel d'offre ? pour moi il vaut mieux limiter le nombre d'options sur la période quand on peut...

2025-01-03 14:25 UTC, benjlevesque commented on packages/specifications/src/projet/lauréat/représentant-légal/changement/demanderChangementReprésentantLégal.feature
> +# @NotImplemented
volontaire ?

2025-01-03 14:25 UTC, benjlevesque commented on packages/domain/lauréat/src/représentantLégal/saga/index.ts
> +      .with({ type: 'TâchePlanifiéeExecutée-V1' }, handleTâchePlanifiéeExécutée)
tu aurais pas oublié le register pour cet event ? je le trouve pas :)

2025-01-03 14:25 UTC, benjlevesque commented on packages/specifications/src/tâche-planifiée/stepDefinitions/tâchePlanifiée.then.ts
> +      const dateDemande = match(typeTâche)
je suis pas hyper fan de ce cas speçifique à Représentant Légal dans un step générique :thinking: 
ca ne fonctionnait pas de mettre la date en paramètre comme on fait d'habitude ? => `une tâche {string} est planifiée à la date du {string} pour le projet lauréat`

2025-01-03 14:36 UTC, JulienPavon commented
> je ne suis pas sur de comprendre pourquoi `changement.représentantLégal.typeTâchePlanifiée` est sur la période et non l'Appel d'offre ? pour moi il vaut mieux limiter le nombre d'options sur la période quand on peut...

C'est à dire que selon les règles métiers les appels d'offres PPE2 eolien et neutre vont voir le type de tâche devenir `accord-automatique` à leur prochaine période

2025-01-03 14:38 UTC, JulienPavon commented on packages/specifications/src/projet/lauréat/représentant-légal/changement/demanderChangementReprésentantLégal.feature
> +# @NotImplemented
Je ne pense pas

2025-01-03 14:44 UTC, JulienPavon commented on packages/specifications/src/tâche-planifiée/stepDefinitions/tâchePlanifiée.then.ts
> +      const dateDemande = match(typeTâche)
c'est un peu plus complexe que seulement mettre une date car la règle ici est 3 mois plus tard mais je peux regarder pour variabliliser ça

2025-01-03 14:45 UTC, benjlevesque commented
> > je ne suis pas sur de comprendre pourquoi `changement.représentantLégal.typeTâchePlanifiée` est sur la période et non l'Appel d'offre ? pour moi il vaut mieux limiter le nombre d'options sur la période quand on peut...
> 
> C'est à dire que selon les règles métiers les appels d'offres PPE2 eolien et neutre vont voir le type de tâche devenir `accord-automatique` à leur prochaine période

Ah ok c'est ca qui me manquait :)

2025-01-03 14:46 UTC, benjlevesque commented on packages/specifications/src/tâche-planifiée/stepDefinitions/tâchePlanifiée.then.ts
> +      const dateDemande = match(typeTâche)
ok, c'est pas hyper bloquant non plus t'embête pas trop :)

2025-01-06 07:39 UTC, benjlevesque requested changes
je pense qu'il manque un test couvrant l'execution même de la saga, car en l'état actuel elle ne semble jamais executée

2025-01-06 07:39 UTC, benjlevesque commented on packages/applications/bootstrap/src/setupLauréat.ts
> +    eventType: ['LauréatNotifié-V1', 'TâchePlanifiéeExecutée-V1'],
ca fonctionne ca ? ca devrait pas être sur le stream-category `tâche-planifiée` ? :thinking:

2025-01-06 07:39 UTC, benjlevesque commented on packages/domain/lauréat/src/représentantLégal/saga/handleTâchePlanifiéeExecutée.ts
> +export const handleTâchePlanifiéeExécutée = async (event: TâchePlanifiéeExecutéeEvent) => {
ici tu traites toutes les éxecutions de tâches planifiées, même celles non liées à Représentant Légal. Si tu regardes l'implem dans GF, il faut vérifier que le type de tâche planifiée est "gestion automatique...", et ne rien faire si tu ne connais pas le type.

2025-01-07 10:45 UTC, benjlevesque commented on packages/specifications/src/projet/lauréat/représentant-légal/changement/accorderChangementReprésentantLégal.feature
> +@select
```suggestion
```

2025-01-07 10:47 UTC, benjlevesque commented on packages/domain/lauréat/src/représentantLégal/saga/handleTâchePlanifiéeGestionAutomatiqueDemandeChangementExecutée.ts
> +  match(typeTâchePlanifiée)
il manque un await ici non ?

2025-01-07 10:48 UTC, benjlevesque commented on packages/domain/lauréat/src/représentantLégal/saga/handleTâchePlanifiéeGestionAutomatiqueDemandeChangementExecutée.ts
> +  match(typeTâchePlanifiée)
(sinon l'erreur ne sera pas gérée)

2025-01-07 10:48 UTC, VioMrqs commented on packages/specifications/src/tâche-planifiée/exécuterTâchePlanifiée.feature
>          Quand on execute les tâches planifiées à la date du "2024-07-02"
replace tout les execute par exécute 👼

2025-01-07 10:58 UTC, HubM commented on packages/domain/lauréat/src/représentantLégal/saga/handleTâchePlanifiéeGestionAutomatiqueDemandeChangementExecutée.ts
> +  match(typeTâchePlanifiée)
Il manque surtout un return

2025-01-07 11:09 UTC, benjlevesque commented on packages/domain/lauréat/src/représentantLégal/saga/handleTâchePlanifiéeGestionAutomatiqueDemandeChangementExecutée.ts
> +  match(typeTâchePlanifiée)
un return résoud aussi le problème, mais ce genre de fonction n'a pas de retour attendu il me semble

2025-01-07 14:24 UTC, benjlevesque approved these changes

2025-01-08 08:56 UTC, merged