:sparkles: 723 Publier tous les évennements également dans un stream Redis
MTES-MCT/potentiel pull request #255
Opened 2021-11-30 10:44 UTC by JulienPavon

2021-11-30 14:43 UTC, paduc commented on src/config/eventBus.config.ts
> +  const redis = new Redis({ port, host: REDIS_HOST, password: REDIS_PASSWORD })
Est-ce qu'on peut avoir une erreur de connexion à ce moment-là ? Si par exemple, le `REDIS_HOST` et/ou `REDIS_PASSWORD` sont erronés.

2021-11-30 14:43 UTC, paduc commented on src/infra/dualEventBus/dualEventBus.ts
> +export const makeDualEventBus = ({
On est d'accord que lors du passage en fonctionnel (séparation `publish` et `subscribe`), on n'aura pas dual `subscribe`, seulement une version dual du `publish`?

2021-11-30 14:43 UTC, paduc commented on src/infra/redis/helpers/toRedisMessage.spec.ts
> +      payload,
On ne `stringify` pas le payload ?

2021-11-30 14:57 UTC, JulienPavon commented on src/infra/redis/helpers/toRedisMessage.spec.ts
> +      payload,
Non car désormais c'est la responsabilité du publish de `stringify` l'event entier dans le stream

2021-11-30 14:59 UTC, paduc commented on src/infra/redis/helpers/toRedisMessage.spec.ts
> +      payload,
Ok

2021-11-30 15:03 UTC, JulienPavon commented on src/infra/dualEventBus/dualEventBus.ts
> +export const makeDualEventBus = ({
Oui c'est exactement ça sauf que je me rend compte que nous n'avons plus de subscribe du tout avec cette implémentation. Je rajoute donc le subscribe du in memory ici

2021-12-02 10:38 UTC, HanaeY commented on src/config/eventBus.config.ts
> +    password: 'REDIS_PASSWORD',
REDIS_PASSWORD sans les guillemets ?

2021-12-03 09:58 UTC, paduc requested changes

2021-12-03 09:58 UTC, paduc commented on src/infra/dualEventBus/dualPublish.ts
> +export const makePublishToEventBus = (deps: MakePublishEventDeps) => (event: DomainEvent) => {
`makeDualPublish`

2021-12-03 09:58 UTC, paduc commented on src/infra/dualEventBus/dualPublish.ts
> +  publishInMemory: EventBus['publish']
`redisPublish`
`inMemoryPublish`

2021-12-03 09:58 UTC, paduc commented on src/infra/redis/redisPublish.ts
> +export const makePublishInRedisEventBus = (deps: MakePublishInRedisEventBusDeps) => (
Le module s'appelle `redisPublish`, ce que je trouve bien, puisque ça mets le discriminant en premier, ce qui le rend tout de suite clair. 

En revanche, je l'appellerais `redisPublish` partout et notamment dans le nom du constructeur `makeRedisPublish`. 

D'une manière générale, la convention qu'on a adopté est que le nom du module est le nom de la chose exportée (`module.ts` exporte `module()`), ou bien, si c'est une constructeur, le nom de ce qui est construit (`module.ts` exporte `makeModule()`).

2021-12-03 09:58 UTC, paduc commented on src/infra/redis/redisPublish.integration.ts
> +describe('redisPublish', () => {
Même convention dans le `describe`, on mets le nom de la méthode testée.

Ici, c'est bien `describe('redisPublish', ...)` et l'objet construit doit prendre ce nom `const redisPublish = makeRedisPublish({ redis, streamName })`.

2021-12-03 09:58 UTC, paduc commented on src/infra/inMemoryEventBus/inMemoryEventBus.ts
> +export const makeSubscribeToMemory = ({
`makeInMemorySubscribe`

2021-12-03 09:58 UTC, paduc commented on src/infra/inMemoryEventBus/inMemoryEventBus.ts
> +export const makePublishInMemory = ({
`makeInMemoryPublish`

2021-12-03 16:26 UTC, paduc approved these changes

2021-12-03 17:28 UTC, merged