:sparkles: 724 Subscribe events from a Redis stream
MTES-MCT/potentiel pull request #259
Opened 2021-12-06 13:48 UTC by JulienPavon

2021-12-07 17:01 UTC, paduc requested changes

2021-12-07 19:05 UTC, JulienPavon commented on src/infra/redis/redisSubscribe.ts
> +          redisClient.xack(streamName, groupName, messageId)
J'ai déplacé la duplication seulement lorsque l'on attend un nouveau message. Donc pour toutes les autres opérations nous utilisons maintenant la même connection

2021-12-08 14:27 UTC, JulienPavon commented on src/infra/redis/redisSubscribe.ts
> +    const redisClient = redis.duplicate()
Ici il vaut mieux dupliquer la connexion dans le cas où elle serait blquée (attente de nouveau message)

2021-12-10 08:37 UTC, paduc commented on src/infra/sequelize/helpers/makeSequelizeProjector.ts
> +        await Promise.all(handlersByType[type]?.map((handler) => handler(event)))
Ici je vois un cas problématique: plusieurs handlers pour un événement et un d'eux échoue (et les autres réussissent). Ca fait que le `Promise.all` échoue et donc pas de `ack` coté Redis, donc potentiellement un retry plus tard, mais les handlers qui ont réussi ont eu un impact sur la base de données. On est dans un état partiellement appliqué pour la projection...

Une solution que je vois est d'ouvrir une transaction sequelize pour chaque événement. On passe cette transaction aux handlers et on ne commit la transaction que si tout passe. 
Qu'en penses-tu ?

2021-12-10 13:30 UTC, JulienPavon commented on src/infra/sequelize/helpers/makeSequelizeProjector.ts
> +        await Promise.all(handlersByType[type]?.map((handler) => handler(event)))
Ça peut être une solution par contre je me pose une question. Est ce possible d'avoir plusieurs handlers pour un type d'évennement ? Si je ne me trompe pas chaque projection va avoir un sequelizeProjector dédié non ?

2021-12-10 15:37 UTC, paduc commented on src/infra/sequelize/helpers/makeSequelizeProjector.ts
> +        await Promise.all(handlersByType[type]?.map((handler) => handler(event)))
Oui on peut partir du principe que pour une projection donnée, on n'a qu'un seul handler par type d'événement. Si un deuxième handler est ajouté pour le même type d'événement, ça crashe.

2021-12-13 17:13 UTC, paduc requested changes

2021-12-13 17:13 UTC, paduc commented on src/infra/redis/redisSubscribe.integration.ts
> +    it('should add the failed event to the consumer dead letter queue', async () => {
Les deux blocs `it` peuvent utiliser le même contexte de test.

```ts

beforeAll(() => {
  // .. setup du consumer, redisSubscribe et envoi des deux messages dans le stream
})

it('should not call the consumer with the message that failed before', async () => {
  // .. juste la partie waitForExpect qui vérifie que consumer a été appelé 2 fois
})

it('should add the failed event to the consumer dead letter queue', async () => {
  // .. juste la partie waitForExpect qui vérifie la DLQ
})
```

2021-12-13 17:13 UTC, paduc commented on src/infra/redis/redisSubscribe.integration.ts
> +    it('should not call the consumer with the message that failed before', async () => {
`should send the failed message to the consumer only once`

2021-12-13 17:13 UTC, paduc commented on src/infra/redis/helpers/fromRedisMessage.ts
> +    return null
Pourquoi catcher l'erreur à ce niveau et retourner `null` ?
L'appel à `fromRedisMessage` par `redisSubscribe` est fait dans un `try/catch`.

J'ai l'impression qu'on peut laisser `fromRedisMessage` throw.

2021-12-13 17:13 UTC, paduc commented on src/infra/redis/redisSubscribe.ts
> +          )
`logger.error(error)`

2021-12-14 09:53 UTC, JulienPavon commented on src/infra/redis/redisSubscribe.integration.ts
> +    it('should add the failed event to the consumer dead letter queue', async () => {
Pour cette partie il est nécessaire de laisser l'ajout des massages au stream et la fabrication su redisSubscribe sinon certains tests fails

2021-12-14 13:31 UTC, paduc approved these changes

2021-12-14 13:40 UTC, merged