✨ 752 validate ids in controllers and forward to error page if necessary
MTES-MCT/potentiel pull request #268
Opened 2021-12-15 11:58 UTC by paduc

2021-12-15 14:58 UTC, HanaeY commented on src/views/pages/Error.tsx
> +      <section className="section section-grey" style={{ paddingTop: 40 }}>
Sinon on peut appliquer le style avec la classe tailwind pt-[valeur]

2021-12-17 10:42 UTC, paduc commented on src/controllers/helpers/unauthorizedResponse.ts
> +    customStatus: 404,
403 !

2021-12-17 14:13 UTC, JulienPavon requested changes
J'ai également vu qq import à supprimer dans certains controllers

2021-12-17 14:13 UTC, JulienPavon commented on src/controllers/project/postCorrectProjectData.ts
> +    if (!validateUniqueId(projectId)) {
Ici la valeur venant du body de la request est ce bien un notFoundResponse qu'il faut retourner ? Ne faut-il pas faire comme dans postClaimProjects ?

2021-12-17 14:13 UTC, JulienPavon commented on src/controllers/project/postUpdateNewRulesOptIn.ts
> +    if (!validateUniqueId(projectId)) {
Ici la valeur venant du body de la request est ce bien un `notFoundResponse` qu'il faut retourner ? Ne faut-il pas faire comme dans `postClaimProjects` ?

2021-12-17 14:13 UTC, JulienPavon commented on src/controllers/steps/postSubmitStep.ts
> +    if (!validateUniqueId(projectId)) {
Ici la valeur venant du body de la request est ce bien un `notFoundResponse` qu'il faut retourner ? Ne faut-il pas faire comme dans `postClaimProjects` ?

2021-12-17 14:56 UTC, JulienPavon approved these changes

2021-12-17 15:41 UTC, merged