757 certificate uploaded by a user is visible in new timeline
MTES-MCT/potentiel pull request #275
Opened 2021-12-20 17:25 UTC by HanaeY

Branche créée à partir de la branche 755

2021-12-22 16:25 UTC, JulienPavon requested changes
- Dans le composant DesignationItem il faudrait retirer les types d'event qui sont déjà dans le type ProjectCertificateDTO
- La fonction makeCertificateLink n'est pas testée et je pense qu'il faudrait forcé le paramètre latestCertificateEvent à ne pas être undefined ce qui forcerait de ne l'utiliser que lorsque l'on a cet event 
- Et je pense qu'il serait intéressant d'extraire un composant dédié à la partie attestation (qui aurait donc la responsabilité de fabriquer le lien de celle-ci)
- On peut aussi destructurer props afin de récuper projectId et events ;)

2021-12-22 16:25 UTC, JulienPavon commented on src/views/pages/projectDetailsPage/components/timeline/helpers/getLatestCertificateEvent.spec.ts
> +      potentielIdentifier: 'pot-id',
Pas sûr qu'il y ait un grand intérêt à rajouter toutes les propriétés. Sont-elles déterminantes pour ces tests ?

2021-12-22 16:25 UTC, JulienPavon commented on src/views/pages/projectDetailsPage/components/timeline/helpers/getLatestCertificateEvent.spec.ts
> +      expect(result1?.type).toEqual('ProjectClaimed')
Est ce que nous ne râtons pas des cas ici ? Par exemple si le dernier évènnement est de type ProjectCertificateRegenerated par exemple

2021-12-22 16:25 UTC, JulienPavon commented on src/views/pages/projectDetailsPage/components/timeline/helpers/mapTimelineItemList.spec.ts
> +            type: 'ProjectClaimed',
Rajouter ProjectClaimed dans la description du test

2021-12-22 17:12 UTC, HanaeY commented on src/views/pages/projectDetailsPage/components/timeline/helpers/getLatestCertificateEvent.spec.ts
> +      expect(result1?.type).toEqual('ProjectClaimed')
Je ne sais pas si c'était l'idée, mais je peux mettre comme résultat attendu un événement qui n'est pas à la dernière place dans la liste mais qui a la date la plus proche.

2021-12-23 10:58 UTC, JulienPavon approved these changes

2021-12-23 11:01 UTC, merged