684 display alert to pp is gf due date has been reached
MTES-MCT/potentiel pull request #284
Opened 2021-12-28 17:25 UTC by HanaeY

Branch created from branch 678 that is not merged yet.
The review concerns only last commit.

2022-01-03 15:45 UTC, paduc requested changes

2022-01-03 15:45 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.integration.ts
> +  const submissionDate = new Date(27 / 12 / 2021)
`new Date('2021-12-27')`

2022-01-03 15:45 UTC, paduc commented on src/infra/sequelize/queries/frise/getProjectEvents.integration.ts
> +  it('should return events orderedby date', async () => {
`ordered by date in ascending order`

2022-01-03 15:45 UTC, paduc commented on src/infra/sequelize/queries/frise/getProjectEvents.integration.ts
> +        const submissionDate = new Date(27 / 12 / 2021)
idem pour la date, `new Date('2021-12-27')`

2022-01-03 15:45 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.integration.ts
> +        valueDate: Number(submissionDate),
`submissionDate.getTime()` (plus explicite)

2022-01-03 15:45 UTC, paduc commented on src/infra/sequelize/queries/frise/getProjectEvents.integration.ts
> +          valueDate: Number(submissionDate),
idem, utiliser `getTime()`

2022-01-03 15:45 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFDueDateSet.ts
> +        valueDate: occurredAt.getTime(),
Pour cet événement, la `valueDate` est `garantiesFinancieresDueOn`.

2022-01-03 15:45 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFDueDateSet.ts
> +        payload: { garantiesFinancieresDueOn },
Du coup, pas besoin de payload, vu que c'est la `valueDate` qui contient la date.

2022-01-03 15:45 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.ts
> +        payload: { fileId, submittedBy, gfDate: gfDate.getTime() },
Idem, ici `valueDate` est `gfDate` vue que c'est la date qu'on affiche dans le frise.

2022-01-03 15:45 UTC, paduc commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +                      gfDate: payload.gfDate,
à retirer (`valueDate` contient l'info)

2022-01-03 15:45 UTC, paduc commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +                      garantiesFinancieresDueOn: payload.garantiesFinancieresDueOn,
à retirer au profit de `valueDate`

2022-01-03 15:45 UTC, paduc commented on src/modules/frise/dtos/ProjectEventListDTO.ts
> +  garantiesFinancieresDueOn: number
`garantiesFinancieresDueon` à retirer

2022-01-03 15:45 UTC, paduc commented on src/modules/frise/dtos/ProjectEventListDTO.ts
> +  gfDate: number
`gfDate` à retirer

2022-01-03 15:45 UTC, paduc commented on src/views/components/dateInput.tsx
> +    'La date saisie doit être de la forme JJ/MM/AAAA, soit par exemple 25/04/2021 pour le 25 mai 2021.'
`25 avril 2021`

2022-01-03 15:45 UTC, paduc commented on src/views/components/dateInput.tsx
> +const DateInput = ({ setErrorMessage, setDisableSubmit, maxDate }) => {
Mettre une majuscule au nom du fichier aussi

2022-01-03 15:45 UTC, paduc commented on src/views/components/dateInput.tsx
> +        setDisableSubmit(false)
D'une manière générale, ce n'est pas au composant de piloter le comportement de son parent. Un composant reçoit des données et peut éventuellement émettre des événements à son parent, que celui-ci récupère via des props du type `onClick`.

Dans ce cas-ci, tu veux afficher une erreur et désactiver le bouton submit dans le parent. 

On peut considérer que l'erreur est un comportement local au composant (on lui passe "maxDate", c'est le composant qui compare la date, etc.). Dans ce cas, le comportement ne doit pas sortir du composant. On peut inclure le message d'erreur et activer/désactiver son affichage dans le composant.

Pour la désactivation du bouton submit, il s'agit d'un comportement qui appartient au parent. Le rôle du composant se limite à prévenir son parent qu'il y a une erreur. C'est au parent ensuite de réagir à ce signalement. Pour cela, le parent peut nous passer une prop `onError`, qui est appelée par ce composant avec `true` quand il y a une erreur et `false` quand l'erreur est résolue. 
Le parent peut ensuite attacher un callback qui va activer/désactiver son bouton submit. C'est à lui de gérer ce comportement.

2022-01-03 15:45 UTC, paduc commented on src/views/components/dateInput.tsx
> +  const errorMaxDate = "La date saisie doit être antérieure à la date d'aujourd'hui."
Ici, il y a un excès de généricité (sans doute parce que la fonction que tu remplaces était trop générique aussi).
Ton composant a une capacité générique avec `maxDate` alors que tu ne t'en sers que pour comparer avec la date actuelle. A remplacer avec une prop `isPast` pour avoir une capacité qui colle mieux avec le besoin.

2022-01-03 15:45 UTC, paduc commented on src/views/pages/projectDetailsPage/components/timeline/GarantiesFinancieresItem.tsx
>    const projectGFSubmittedEvent = events.find(isProjectGFSubmitted)
`setIsHiddenForm` => `toggleForm`

2022-01-03 15:45 UTC, paduc commented on src/views/pages/projectDetailsPage/components/timeline/components/StateIcons.tsx
> +export const CurrentIcon = () => (
Faire un fichier par icone.

2022-01-03 15:45 UTC, paduc commented on src/views/pages/projectDetailsPage/components/timeline/helpers/mapTimelineItemList.spec.ts
> +    it('should create a groupe with the latest event of type ProjectGFDueDateSet or ProjectGFSubmitted', () => {
`group`

2022-01-03 15:45 UTC, paduc commented on src/views/pages/projectDetailsPage/components/timeline/helpers/mapTimelineItemList.ts
> +  events: (ProjectGFSubmittedDTO | ProjectGFDueDateSetDTO)[]
On ne garde que le dernier des événements dans ce groupe. Le type de `events` pourrait donc être plus étroit: `events: ProjectGFSubmittedDTO | ProjectGFDueDateSetDTO`. Ca simplifierait aussi le type du composant `GarantiesFinancieresItem`, qui m'a laissé songeur quand je l'ai lu. Je me suis demandé ce qui s'afficherait s'il y avait les deux événements dans `events`. Je n'avais pas compris que c'était filtré en amont. Le type m'aurait aidé à comprendre.

2022-01-03 16:29 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFDueDateSet.ts
> +        valueDate: occurredAt.getTime(),
Dans la frise on va afficher l'événement qui a la date la plus grande ('grande' car on compare des nombres), donc si on utilise la date de constitution de la GF pour l'événement ProjectGFSubmitted et la date dueOn pour l'événement ProjectGFDueDateSet, on risque de toujours afficher la date dueOn qui sera toujours la plus grande. Mon idée était donc d'utiliser la date des événements pour ne garder que celui qui est arrivé en dernier, puis une fois l'événement 'choisi' d'afficher soit la date dueOn soit la date de constitution de la GF...

2022-01-03 17:47 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFDueDateSet.integration.ts
> +      type: 'ProjectGFDueDateSet',
ok

2022-01-03 17:50 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.integration.ts
> +  const submissionDate = new Date(27 / 12 / 2021)
ok

2022-01-03 17:50 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.integration.ts
> +        valueDate: Number(submissionDate),
ok

2022-01-03 17:52 UTC, HanaeY commented on src/infra/sequelize/queries/frise/getProjectEvents.integration.ts
> +  it('should return events orderedby date', async () => {
ok

2022-01-03 17:53 UTC, HanaeY commented on src/infra/sequelize/queries/frise/getProjectEvents.integration.ts
> +        const submissionDate = new Date(27 / 12 / 2021)
ok

2022-01-03 17:53 UTC, HanaeY commented on src/infra/sequelize/queries/frise/getProjectEvents.integration.ts
> +          valueDate: Number(submissionDate),
ok

2022-01-03 18:02 UTC, HanaeY commented on src/views/components/dateInput.tsx
> +const DateInput = ({ setErrorMessage, setDisableSubmit, maxDate }) => {
ok

2022-01-04 10:48 UTC, paduc commented on src/views/pages/projectDetailsPage/components/timeline/helpers/mapTimelineItemList.ts
> +  events: (ProjectGFSubmittedDTO | ProjectGFDueDateSetDTO)[]
Renommer `events` en `event` puisqu'il n'y en a qu'un dans le type `GarantieFinanciereItem`

2022-01-04 14:09 UTC, HanaeY commented on src/views/components/dateInput.tsx
> +  const errorMaxDate = "La date saisie doit être antérieure à la date d'aujourd'hui."
comme tous les composants parents qui utilisent le sous-composant DateInput ont les mêmes contraintes de date max et de format, j'ai réintégré ces validations au composant enfant, la seule props est donc au final onError pour remonter les éventuelles erreurs au parent qui décide de désactiver/activer le bouton submit

2022-01-04 16:13 UTC, HanaeY commented on src/views/pages/projectDetailsPage/components/timeline/helpers/mapTimelineItemList.ts
> +  events: (ProjectGFSubmittedDTO | ProjectGFDueDateSetDTO)[]
Yes c'est modifié, on a bien un seul événement envoyé à  GFItem et le type est corrigé. 

Plus généralement et concernant les autres timeline items, jusqu'à maintenant on a créé des paquets d'événements qu'on a placé dans des timeline items et c'était la responsabilité des composants de choisir l'événement à afficher. Mais je me rends compte que dans tous cas qu'on a traités le composant n'a besoin que du dernier événement du paquet qu'on lui envoie. Donc je me demande si on ferait pas mieux de filtrer au niveau de mapTimelineItemList pour ne conserver que le dernier événement pour chaque timeline item. Ou alors on se dit qu'à l'avenir on aimerait bien avoir un historique des événements passés et on envoie tout aux composants, mais alors on va déjà plus loin que l'objectif frise iso ... qu'en pensez-vous ? Si on se dit qu'on envoie un seul événement à chaque composant, on pourrait intégrer les modifs à DesignationItem et ImportItem à la carte 775 comme les mêmes fichiers vont être corrigés pour modifier la logique des dates, ou sinon on peut créer une carte à part...

2022-01-06 09:18 UTC, paduc commented on src/views/pages/projectDetailsPage/components/timeline/GarantiesFinancieresItem.tsx
> +  const displayWarning = deadlineHaspassed && event.variant === 'porteur-projet' ? true : false
Les `? true : false` ne sont pas nécessaires sur ces deux lignes.

2022-01-06 09:35 UTC, HanaeY commented on src/views/pages/projectDetailsPage/components/timeline/GarantiesFinancieresItem.tsx
> +  const displayWarning = deadlineHaspassed && event.variant === 'porteur-projet' ? true : false
ah oui ! ça me semblait bizarre je me demandais comment les remplacer, il suffit donc de les supprimer :)

2022-01-06 09:47 UTC, paduc requested changes

2022-01-06 09:47 UTC, paduc commented on src/views/components/DateInput.tsx
> +const DateInput = ({ onError }: DateInputProps) => {
Notre convention est de faire des exports nommés: `export const DateInput = ...` au lieu de `export default DateInput`.

Ceci permet de faire des imports plus simples: `import { DateInput } from '../components'`, pratique quand on fait plusieurs imports: `import { DateInput, OtherComponent } from '../components'`

2022-01-06 09:47 UTC, paduc commented on src/views/pages/projectDetailsPage/components/DCRForm.tsx
> +  const [disableSubmit, setDisableSubmit] = useState(true)
`const [isSubmitDisabled, disableSubmit] = useState(true)`

2022-01-06 09:47 UTC, paduc commented on src/views/pages/projectDetailsPage/components/GarantiesFinancieresForm.tsx
> +  const [disableSubmit, setDisableSubmit] = useState(true)
idem `const [isSubmitDisabled, disableSubmit] = useState(true)`

2022-01-06 09:47 UTC, paduc commented on src/views/pages/projectDetailsPage/components/PTFForm.tsx
> +  const [disableSubmit, setDisableSubmit] = useState(true)
idem `const [isSubmitDisabled, disableSubmit] = useState(true)`

2022-01-06 09:47 UTC, paduc commented on src/views/pages/projectDetailsPage/components/DCRForm.tsx
> +        <DateInput onError={(isError: boolean) => setDisableSubmit(isError)} />
Ne pas typer `isError`, le composant `DateInput` nous donne déjà son type.

2022-01-06 09:47 UTC, paduc commented on src/views/pages/projectDetailsPage/components/DCRForm.tsx
> +          type="numero-dossier"
`type="text"`

2022-01-06 09:47 UTC, paduc commented on src/views/pages/projectDetailsPage/components/timeline/GFForm.tsx
> +export const GFForm = (props: { projectId: string; toggleForm: boolean; setToggleForm: any }) => {
Sortir le type des props dans une interface `GFFormProps`

2022-01-06 09:47 UTC, paduc commented on src/views/pages/projectDetailsPage/components/timeline/GFForm.tsx
> +  const [disableSubmit, setDisableSubmit] = useState(true)
`const [isSubmitDisabled, disableSubmit] = useState(true)`

2022-01-06 09:47 UTC, paduc commented on src/views/pages/projectDetailsPage/components/timeline/GarantiesFinancieresItem.tsx
> +  const [toggleForm, setToggleForm] = useState(false)
`const [isFormVisible, showForm] = useState(false)`

2022-01-06 09:47 UTC, paduc commented on src/views/pages/projectDetailsPage/components/timeline/GFForm.tsx
> +      <a onClick={() => setIsHiddenForm(!isHiddenForm)}>Annuler</a>
Le composant ne doit pas contrôler son parent. 
Au lieu de passer `isHiddenForm` + `setIsHiddenForm`, passer juste une prop `onCancel` et traiter le comportement de masquage dans le parent.

2022-01-06 16:42 UTC, paduc approved these changes

2022-01-06 16:52 UTC, merged