775 Add eventPublishedAt column and fill with event occuredAt date in project_events projection
MTES-MCT/potentiel pull request #288
Opened 2022-01-05 09:19 UTC by JulienPavon

2022-01-05 14:52 UTC, HanaeY requested changes

2022-01-06 08:32 UTC, HanaeY approved these changes

2022-01-06 08:44 UTC, paduc commented on src/infra/sequelize/migrations/20220104135530-add-eventPublishedAt-column-to-project-events-table.js
> +    const tableDefinition = await queryInterface.describeTable('project_events')
Excellent, je découvre `describeTable` !

2022-01-06 08:59 UTC, paduc requested changes

2022-01-06 08:59 UTC, paduc commented on src/infra/sequelize/migrations/20220104135530-add-eventPublishedAt-column-to-project-events-table.js
> +    if (!tableDefinition.eventPublishedAt) {
Est-ce que cette vérification est nécessaire puisque les scripts de migrations s'executent dans l'ordre ?

2022-01-06 08:59 UTC, paduc commented on src/infra/sequelize/migrations/20220104135530-add-eventPublishedAt-column-to-project-events-table.js
> +        type: queryInterface.sequelize.QueryTypes.DELETE,
Pour info, `TRUNCATE project_events` a le même effet et est plus rapide. https://www.postgresql.org/docs/8.2/sql-truncate.html

2022-01-06 08:59 UTC, paduc commented on src/infra/sequelize/migrations/20220104135530-add-eventPublishedAt-column-to-project-events-table.js
> +                        'ProjectGFSubmitted')
On est d'accord que c'est de l'optimisation de filtrer par `type` ? Tu pourrais retirer la classe `WHERE` et ça aurait le même effet (en plus lent, mais sans le risque d'oublier un type d'événement concerné par cette projection).

Je me demande à terme, si on souhaite garder cette optimisation, sans le risque d'oublier un type (et sans devoir les taper à la main), si on ne pourrait pas exposer les types écoutés par `ProjectEvent.projector`. Qu'est-ce que tu en penses ?

2022-01-06 08:59 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.integration.ts
> +      valueDate: occurredAt.getTime(),
La `valueDate` est la `gfDate` du payload.

2022-01-06 08:59 UTC, paduc commented on src/infra/sequelize/queries/frise/getProjectEvents.integration.ts
> +              date: eventTimestamp,
`gfDate`

2022-01-06 09:30 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.integration.ts
> +      valueDate: occurredAt.getTime(),
Comme l'event ProjectGFSubmitted a été découpé en plusieurs US, cette date est prise en compte dans la grosse PR GF qui vient après

2022-01-06 10:39 UTC, JulienPavon commented on src/infra/sequelize/migrations/20220104135530-add-eventPublishedAt-column-to-project-events-table.js
> +    if (!tableDefinition.eventPublishedAt) {
En production le script de création de la table project_events à déjà été éxecuté. Donc en production il faudra créer cette colonne. Comme précisé dans la description de la PR j'ai rajouté la colonne dans le script original de création de la table sinon lors d'une reconstruction depuis zéro il y aura une erreur avec le script `20211220152638-add-project-claimed-notified-imported-certificate-to-project-events-table` car celui-ci exécute les event hanlders qui ont besoin de la colonne eventPublishedAt maintenant

2022-01-06 10:41 UTC, paduc commented on src/infra/sequelize/migrations/20220104135530-add-eventPublishedAt-column-to-project-events-table.js
> +    if (!tableDefinition.eventPublishedAt) {
Je m'excuse, je n'avais pas vu/lu la description de la PR ! C'est tout bon !

2022-01-06 10:44 UTC, JulienPavon commented on src/infra/sequelize/migrations/20220104135530-add-eventPublishedAt-column-to-project-events-table.js
> +                        'ProjectGFSubmitted')
Effectivement le filtre sur les types n'est qu'une question d'optimisation afin que la migration soit le plus rapide possible. Et l'idée d'avoir les types d'evènnement pris en charge serait vraiment idéal

2022-01-06 12:34 UTC, JulienPavon commented on src/infra/sequelize/migrations/20220104135530-add-eventPublishedAt-column-to-project-events-table.js
> +                        'ProjectGFSubmitted')
J'ai fait la modif dans le script de migration pour récupérer tous les type d'évènnement à rejouer pour la projection. On pourrait même maintenant imaginer une fonction `rebuild` dans le projecteur et ne plus exposer `handleEvent` et `getListenedEvents`. Comme ça le projecteur lui même sait comment gérer son rebuild et un seul appel suffira depuis un script ! Mais à faire dans une PR dédiée

2022-01-06 13:30 UTC, paduc approved these changes

2022-01-06 13:44 UTC, merged