Refactor file service
MTES-MCT/potentiel pull request #29
Opened 2020-11-25 18:26 UTC by paduc

2020-11-27 18:29 UTC, Zekdar requested changes

2020-11-27 18:29 UTC, Zekdar commented on src/infra/sequelize/repos/fileRepo.ts
> +            console.log('fileRepo.save error', e)
`console.error`

2020-11-27 18:29 UTC, Zekdar commented on src/modules/file/FileObject.ts
> +/* global NodeJS */
Met le au plus proche de l'utilisation de la variable l.14 stp

2020-11-27 18:29 UTC, Zekdar commented on src/useCases/addDCR.ts
> +    }).asyncAndThen((file) => fileRepo.save(file).map(() => file.id.toString()))
Pourquoi chaîner et ne pas découper en plusieurs `await` ? Je pense que ce serait plus lisible du premier coup d'oeil.

2020-11-27 18:29 UTC, Zekdar commented on src/useCases/requestModification.ts
> +      }).asyncAndThen((file) => fileRepo.save(file).map(() => file.id.toString()))
J'ai l'impression que cette ligne revient souvent dans les useCase. Ce serait bien de la factoriser dans une petite fonction :)

2020-11-30 08:10 UTC, paduc commented on src/helpers/makeProjectFilePath.ts
>    // add timestamp to avoid duplicate file names
Bien vu !

2020-11-30 08:10 UTC, paduc commented on src/infra/file/localFileStorageService.ts
> +    upload({ contents, path: filePath }) {
Le retour est typé par l'interface `FileStorageService`.

2020-11-30 08:16 UTC, paduc commented on src/infra/file/localFileStorageService.ts
> +          }
Ca marche !

2020-11-30 08:18 UTC, paduc commented on src/infra/sequelize/repos/fileRepo.integration.ts
> +    upload: jest.fn((args: { contents; path }) => okAsync('storageLocation')),
Aucune idée, c'est prettier qui le rajoute.

2020-11-30 08:21 UTC, paduc commented on src/infra/sequelize/repos/fileRepo.ts
> +            console.log('fileRepo.save error', e)
yep

2020-11-30 08:22 UTC, paduc commented on src/modules/file/FileObject.ts
> +/* global NodeJS */
ok

2020-11-30 08:26 UTC, paduc commented on src/useCases/addDCR.ts
> +    }).asyncAndThen((file) => fileRepo.save(file).map(() => file.id.toString()))
L'idée est de construire une instance de `File` (ce qui peut renvoyer une erreur) puis ensuite de faire une sauvegarde via le `fileRepo`. Le dernier `map` est là pour récupérer l'id du fichier créé (parce que `save` renvoi `null` en cas de succès).

Si je fais plusieurs await, je vais devoir vérifier si le résultat est une erreur à chaque étape, ce qui est plus lourd. Tout l'intérêt de la syntaxe en `andThen` est de retarder le traitement de l'erreur à la fin de chaine (comme le `then` des promesses ou le `catch` dans `try/catch`).

2020-11-30 08:30 UTC, paduc commented on src/useCases/requestModification.ts
> +      }).asyncAndThen((file) => fileRepo.save(file).map(() => file.id.toString()))
Yep je fais ça

2020-11-30 08:54 UTC, Zekdar commented on src/useCases/addDCR.ts
> +    }).asyncAndThen((file) => fileRepo.save(file).map(() => file.id.toString()))
Ok je comprends l'idée, par contre je pense qu'on est en train de privilégier la concision/perf sur la lisibilité. Ok pour le moment car j'ai pas assez de recule sur la lib (je me répète ... 😅)

2020-11-30 08:58 UTC, Zekdar commented on src/modules/file/helpers/makeAndSaveFile.ts
> + * @param args.fileRepo: the file repository
Tu peux ajouter un `@returns` si tu veux

2020-11-30 09:00 UTC, Zekdar approved these changes

2020-11-30 15:31 UTC, Zekdar approved these changes

2020-11-30 15:32 UTC, merged