659 La frise doit contenir les évènnements de la DCR
MTES-MCT/potentiel pull request #296
Opened 2022-01-13 15:07 UTC by JulienPavon

2022-01-13 15:47 UTC, paduc requested changes

2022-01-13 15:47 UTC, paduc commented on src/views/components/timeline/helpers/extractGFItemProps.ts
> +function makeGFDocumentUrl(fileId: string, filename: string): string {
A retirer ?

2022-01-13 15:47 UTC, paduc commented on src/views/components/timeline/helpers/extractImportItemProps.ts
> +import { isProjectNotified } from './extractDesignationItemProps'
Peut-être que la place de `isProjectNotified` est dans un dossier `helpers` s'il est partagé.

2022-01-13 15:47 UTC, paduc commented on src/views/components/timeline/components/DCRItem.tsx
> +                Annuler le dépôt
Uniquement pour le porteur de projet

2022-01-13 15:47 UTC, paduc commented on src/views/components/timeline/helpers/extractDCRItemProps.spec.ts
> +    })
Il manque le cas `ProjectDCRSubmitted` => `ProjectDCRRemoved` => `ProjectDCRSubmitted`. Je l'ai testé en ce n'est pas le dernier document déposé qui est retourné dans `url`

2022-01-13 15:56 UTC, JulienPavon commented on src/views/components/timeline/helpers/extractImportItemProps.ts
> +import { isProjectNotified } from './extractDesignationItemProps'
D'ailleurs ne faudrait-il pas avoir tous les isProjectxxxed relatif aux ProjectEventsDTO dans les fichier projectEventListDTO.ts du module/frise ?

2022-01-13 16:15 UTC, JulienPavon commented on src/views/components/timeline/helpers/extractDCRItemProps.spec.ts
> +    })
J'ai rajouté le test mais l'implementation rempli bien son rôle. Ai-je râté quelque chose ?

2022-01-13 16:34 UTC, paduc commented on src/views/components/timeline/helpers/extractDCRItemProps.spec.ts
> +        } as ProjectDCRDueDateSetDTO,
Il y a plus d'événements que nécessaires dans cette liste, ça embrouille. Ne garder que le minimum pour tester ce cas.

2022-01-13 16:35 UTC, paduc commented on src/views/components/timeline/helpers/extractDCRItemProps.spec.ts
> +    })
J'ai testé manuellement et ça ne marchait pas... ?

2022-01-13 17:23 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectDCRSubmitted.ts
> +        payload: { fileId, submittedBy },
je me demande s'il faut garder le submittedBy, on ne s'en sert pas et je crois que c'est un id

2022-01-13 17:23 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectDCRRemoved.ts
> +        payload: { removedBy },
même chose ici, on n'aura pas besoin du removedBy il me semble

2022-01-13 17:23 UTC, HanaeY commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +                      removedBy: payload.removedBy,
A voir si on garde le submittedBy

2022-01-13 17:23 UTC, HanaeY commented on src/views/components/timeline/helpers/extractDCRItemProps.ts
> +const isProjectDCR = or(or(isProjectDCRDueDateSet, isProjectDCRSubmitted), isProjectDCRRemoved)
de mon côté ici pour les GF j'avais modifié la methode "or" pour qu'elle puisse accepter trois arguments, je ne sais pas ce qui est le mieux, visuellement c'est plus propre d'avoir un seul "or" mais il y a peut être d'autres arguements qui m'échappent ;)

2022-01-13 17:23 UTC, HanaeY commented on src/views/components/timeline/components/DCRItem.tsx
> +              <div className="flex">
pour les GF j'ai mis l'action "annuler le dépôt" à côté de "télécharger", faudra qu'on s'accorde là dessus du coup :), et est-ce qu'on ne mettrait pas cette action dans un composant ?

2022-01-13 17:29 UTC, paduc commented on src/views/components/timeline/helpers/extractDCRItemProps.spec.ts
> +    })
Ok j'ai réussi à reproduire le problème.
Si le porteur redépose sa DCR avec une date antérieure à la précédente, ça ne marche plus.

2022-01-13 17:34 UTC, paduc commented on src/views/components/timeline/helpers/extractDCRItemProps.spec.ts
> +          date: new Date('2022-01-09').getTime(),
Si tu changes ça en `2022-01-06` ça ne passe plus alors que ça devrait. Cette date est la date que l'utilisateur a déclaré comme DCR, pas la date à laquelle l'utilisateur a déposé sa DCR sur Potentiel.
Il faut se fier à l'ordre des événements dans le tableau (trié par `eventOccurredAt`).

2022-01-13 17:37 UTC, paduc commented on src/views/components/timeline/helpers/extractDCRItemProps.spec.ts
> +    })
J'ai réussi à reproduire avec des données de prod.

2022-01-13 17:44 UTC, paduc approved these changes

2022-01-13 17:44 UTC, paduc commented on src/views/components/timeline/helpers/extractDCRItemProps.spec.ts
> +    })
Et puis plus... 😭 
J'ai du avoir un glitch quelque part...

2022-01-14 08:33 UTC, JulienPavon commented on src/views/components/timeline/helpers/extractDCRItemProps.ts
> +const isProjectDCR = or(or(isProjectDCRDueDateSet, isProjectDCRSubmitted), isProjectDCRRemoved)
Le problème c'est que lorsqu'on aura besoin d'un 4e arguments il va falloir continuellement changer la fonction or. Je serai d'avis de laisser á 2 arguments et de les enchaîner comme pour les autres utilitaire de type comme Omit par exemple

2022-01-14 08:34 UTC, JulienPavon commented on src/views/components/timeline/components/DCRItem.tsx
> +              <div className="flex">
Oui j'avais vu et je trouvais que l'action n'était pas super visible. Je l'ai mise en dessous pour avoir votre avis

2022-01-14 08:35 UTC, JulienPavon commented on src/views/components/timeline/components/DCRItem.tsx
> +              <div className="flex">
J'ai même essayé avec une couleur différente pour le lien et rajouter une icone mais ce nétait pas terrible

2022-01-14 08:35 UTC, JulienPavon commented on src/views/components/timeline/components/DCRItem.tsx
> +              <div className="flex">
Pour le composant à la rigueur j'attendrai d'avoir plusieurs fois ce même code avant

2022-01-14 09:37 UTC, paduc commented on src/views/components/timeline/components/DCRItem.tsx
> +          event.preventDefault()
Si tu faisais juste `return confirm(...)` ça ne marche pas ?

2022-01-14 09:43 UTC, JulienPavon commented on src/views/components/timeline/components/DCRItem.tsx
> +          event.preventDefault()
On doit traiter le retour dans le cas ou l'utilisateur annule. Par contre on peut le faire en une seule ligne

2022-01-14 09:49 UTC, paduc commented on src/views/components/timeline/components/DCRItem.tsx
> +          event.preventDefault()
Si l'utilisateur annule, `confirm` retourne `false` et l'effet d'un `false` sur un listener typique c'est d'annuler l'événement.

2022-01-14 09:55 UTC, paduc commented on src/views/components/timeline/components/DCRItem.tsx
> +          event.preventDefault()
Je retire ce que j'ai dit. Ca ne marche pas avec React, seulement en natif.

2022-01-14 09:58 UTC, paduc commented on src/views/components/timeline/components/DCRItem.tsx
> +        event.preventDefault()
```ts
      onClick={(event) =>
         confirm(`Êtes-vous sur de vouloir annuler le dépôt et supprimer l'attestion jointe ?`) ||
         event.preventDefault()
 ```
Plus clair ?

2022-01-14 10:04 UTC, JulienPavon commented on src/views/components/timeline/components/DCRItem.tsx
> +          event.preventDefault()
Oui mais la navigation vers le href renseigné se fait tout de même sauf si en exécutant la fonction preventDefault on empèche l'action par défaut du lien de s'exécuter (j'ai essayer en retournant false et ça ne fonctionnait pas)

2022-01-14 10:05 UTC, JulienPavon commented on src/views/components/timeline/components/DCRItem.tsx
> +          event.preventDefault()
D'ailleurs c'est la logique déjà présente dans le script.js legacy ici https://github.com/MTES-MCT/potentiel/blob/master/src/public/scripts.js#L755

2022-01-14 13:15 UTC, merged