773 as pp i can remove gf if not validated
MTES-MCT/potentiel pull request #297
Opened 2022-01-13 15:48 UTC by HanaeY

2022-01-17 14:44 UTC, paduc requested changes

2022-01-17 14:44 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectDCRSubmitted.ts
> +    const filename = rawFilename.filename
Attention, `rawFilename` peut être `null`, ce qui ferait une exception.

2022-01-17 14:44 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectDCRSubmitted.ts
> +    const { File } = models
Déplacer à la ligne 5.

2022-01-17 14:44 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectDCRSubmitted.integration.ts
> +  const { File } = models
déplacer à la ligne 7

2022-01-17 14:44 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.ts
> +    const { File } = models
déplacer en ligne 5

2022-01-17 14:44 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.ts
> +    const filename = rawFilename.filename
traiter le cas `rawFilename = null`

2022-01-17 14:44 UTC, paduc commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +                      user.role === 'dreal') &&
`['porteur-projet', 'admin', 'dgec', 'dreal'].includes(user.role)`

2022-01-17 15:41 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.ts
> +    const { File } = models
Si je déplace const { File } = models en dehors j'ai une erreur "TypeError: Cannot destructure property 'File' of 'models_1.models' as it is undefined." :thinking:

2022-01-17 16:21 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.ts
> +    const { File } = models
Ok il doit y avoir un problème de dépendance circulaire.

2022-01-17 16:25 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.ts
> +    const { File } = models
En fait le fichier `models.ts` importe tout ce qui est dans `projectionsNext`, c'est à dire `onProjectGFSubmitted.ts`, et donc si tu essayes d'importer `models.ts` dans ce fichier, ça fait une dépendance circulaire, ce qui empêche node de faire un chargement.

2022-01-17 16:26 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.ts
> +    const { File } = models
Très bizarre, pour GF le test passe une fois sur deux en local lorsque je sors la constante File. Et pour le cas de la DCR ça passe en local mais le test échoue sur github ...

2022-01-17 16:27 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.ts
> +    const { File } = models
Je cherche une solution

2022-01-17 16:28 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.ts
> +    const { File } = models
Oui, les dépendanes circulaires peuvent faire des choses bizarres, parce que ça dépend de l'ordre de chargement des fichiers, qui n'est pas déterministe.

2022-01-17 16:32 UTC, HanaeY commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +                      user.role === 'dreal') &&
de cette manière j'ai une alerte sur le variant qui s'attend à avoir tous les rôles (ademe inclus), le filtre sur les rôles ne fonctionne pas bien

2022-01-17 17:05 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.ts
> +    const { File } = models
Bon, c'est un vrai sac de noeuds, on peut dire que dans le contexte de ta PR, tu peux garder `const { File } = models` à l'intérieur de ton callback.

2022-01-18 09:05 UTC, JulienPavon commented on src/infra/sequelize/queries/frise/getProjectEvents.integration.ts
> -      it('should return ProjectGFSubmitted events', async () => {
Il faudrait sortir les tests concernant les GF dans un fichier getProjectEventsGF.integration.ts (comme pour la DCR) afin de simplifier la maintenance des tests

2022-01-18 13:41 UTC, JulienPavon approved these changes

2022-01-18 14:44 UTC, paduc approved these changes

2022-01-18 15:05 UTC, merged