658 La frise doit contenir les événnements de la PTF
MTES-MCT/potentiel pull request #306
Opened 2022-01-14 15:42 UTC by JulienPavon

2022-01-17 10:34 UTC, paduc requested changes

2022-01-17 10:34 UTC, paduc commented on src/views/components/timeline/helpers/extractPTFItemProps.ts
> +  if (!latestProjectPTF || latestProjectPTF.type === 'ProjectPTFRemoved') {
Que penses-tu de :
```ts
if(!latestProjectPTF || is('ProjectPTFRemoved')(latestProjectPTF)){ ... }
```

2022-01-17 10:34 UTC, paduc commented on src/views/components/timeline/helpers/extractPTFItemProps.ts
> +      url: undefined
Je suis un peu perplexe de l'usage de `date: undefined` pour ce type. J'aurais omis `date` et `url` du type quand le status est `not-submitted`.

Ca aurait comme conséquence qu'on ne puisse pas faire la destructuration des props dans `PTFItem` mais on peut les déstructurer juste après.
```ts
// Avant (impossible si PTFItemProps n'a pas toujours les propriétés date et url)
export const PTFItem = ({
  role,
  projectId,
  date,
  status,
  url,
}: PTFItemProps & { projectId: string }) => {
  // ...
}

// Après
export const PTFItem = (props: PTFItemProps & { projectId: string }) => {
  const { role, projectId, status } = props
  // ...
}
```

Les deux alternatives sont possibles et je pense qu'on peut choisir l'une ou l'autre comme convention et s'y tenir.

T'as une préférence ?

2022-01-17 10:34 UTC, paduc commented on src/views/components/timeline/Timeline.tsx
> +    .sort((a, b) => (!a.date ? 1 : !b.date ? -1 : a.date - b.date))
Utiliser des conditions plus verbeuses pour les rendre plus lisibles.

2022-01-17 13:16 UTC, JulienPavon commented on src/views/components/timeline/helpers/extractPTFItemProps.ts
> +      url: undefined
Au début je n'avais pas inclus date et url mais ensuite j'ai eu des soucis pour le sort dans Timeline. Et je souhaitais avoir un avis avant de pousser plus.
En tout cas je suis d'accord il vaut mieux ne pas inclure date et url pour le cas not-submitted

2022-01-17 14:33 UTC, paduc commented on src/views/components/timeline/helpers/extractPTFItemProps.ts
> +      url: undefined
J'avoue que le sort n'est pas trivial sur le plan typescript si certains cas n'ont pas de `date`. Tu voudrais qu'on le fasse en pair/mob ?

2022-01-17 15:10 UTC, HanaeY requested changes

2022-01-17 15:35 UTC, paduc approved these changes

2022-01-17 15:36 UTC, paduc requested changes

2022-01-17 15:36 UTC, paduc commented on src/views/components/timeline/Timeline.tsx
> +  const hasDateProperty = (props: unknown): props is { date: any } =>
Sortir `hasDateProperty` de `sortItemProps`

2022-01-17 16:16 UTC, JulienPavon commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +                case 'ProjectPTFSubmitted':
Par contre quel doit être le comportement si le fichier n'existe pas ? Est ce qu'on crée tout de même la projection de l'événnement ?

2022-01-17 16:35 UTC, HanaeY commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +                case 'ProjectPTFSubmitted':
j'étais partie sur l'idée de ne pas enregistrer l'événement dans la table ProjectEvents si on n'a pas de fichier... est-ce qu'il y a une meilleure solution ?

2022-01-18 09:03 UTC, JulienPavon commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +                case 'ProjectPTFSubmitted':
Il faut créer l'évévennement sans filename

2022-01-18 09:53 UTC, paduc approved these changes

2022-01-18 11:25 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectPTFSubmitted.ts
> +    const filename = rawFilename?.filename
Remonter une erreur si nous n'avons pas de rawFilename

2022-01-18 11:25 UTC, HanaeY commented on src/views/components/timeline/components/PTFItem.tsx
> +      <div className="flex">
Il me semble que pour tous les éléments du content area nous n'avons pas besoin d'utiliser flex comme les éléments sont disposés en colonne.

2022-01-18 13:19 UTC, HanaeY approved these changes

2022-01-18 13:31 UTC, merged