792 as pp i can specify my gestionnaire reseau id when uploading my dcr
MTES-MCT/potentiel pull request #309
Opened 2022-01-18 14:37 UTC by HanaeY

2022-01-19 13:30 UTC, JulienPavon requested changes

2022-01-19 13:30 UTC, JulienPavon commented on src/views/components/timeline/helpers/extractDCRItemProps.ts
> +      numeroDossier: undefined
Comme pour le status `not-submitted` de la PTF, il faudrait n'avoir ni `url`, ni `numeroDossier` plutôt que de les avoir avec comme type `undefined`

2022-01-19 13:30 UTC, JulienPavon commented on src/views/components/timeline/components/DCRItem.tsx
>          {status !== 'submitted' ? (
Ne serait-il pas plus simple d'avoir plusieurs composants suivant le status comme dans le cas de la PTF ?

2022-01-19 13:40 UTC, HanaeY commented on src/views/components/timeline/components/DCRItem.tsx
>          {status !== 'submitted' ? (
oui je me suis posée la question d'harmoniser l'organisation des composants GF, PTF et DCR, je vais donc commencer par caler DCR sur PTF !

2022-01-19 15:43 UTC, JulienPavon requested changes

2022-01-19 15:43 UTC, JulienPavon commented on src/views/components/timeline/components/DCRItem.tsx
>      <>
Retirer ce fragment inutile

2022-01-19 15:43 UTC, JulienPavon commented on src/views/components/timeline/components/DCRItem.tsx
> +      {status === 'due' && <CurrentIcon />}
Une seule instruction ternaire serait suffisante non ? 
`{ status === 'due' ? <CurrentIcon /> : <WarningIcon />}`

2022-01-20 14:56 UTC, JulienPavon approved these changes

2022-01-20 15:09 UTC, merged