795 handle drc submitted and filename not found for timeline
MTES-MCT/potentiel pull request #312
Opened 2022-01-19 13:11 UTC by HanaeY

- Ajout d'un événement à ProjectEvent même si nous n'avons pas de filename
- Dans ce cas, afficher un message 
- GF, PTF, DCR : masquer le bouton "annuler le dépôt" si le fichier n'est pas téléchargeable

2022-01-19 13:45 UTC, JulienPavon requested changes

2022-01-19 13:45 UTC, JulienPavon commented on src/views/components/timeline/components/DCRItem.tsx
> +            {isPorteurProjet && url && <CancelDeposit {...{ projectId }} />}
Pas sûr qu'il faille cacher la possibilité d'annuler le dépôt. Je n'ai pas l'impression que ce soit bloquant de le laisser et ça pourrait permettre de re-uploader l'attestation dans ce cas particulier

2022-01-19 13:45 UTC, JulienPavon commented on src/views/components/timeline/helpers/extractDCRItemProps.ts
> +      url: string | undefined
Ici on peut aussi rendre le membre url comme optionnel comme fait pour la PTF. Mais peut être que déclarer le membre comme obligatoire mais qui peut être `undefined` serait une meilleure pratique. Qu'en penses-tu @paduc ?

2022-01-19 15:06 UTC, HanaeY commented on src/views/components/timeline/components/DCRItem.tsx
> +            {isPorteurProjet && url && <CancelDeposit {...{ projectId }} />}
oui tu as raison, je supprime cette condition que j'avais ajouté aux trois composants ...

2022-01-21 12:44 UTC, paduc commented on src/views/components/timeline/helpers/extractDCRItemProps.ts
> +      url: string | undefined
Dans notre cas immédiat, ça n'aurait aucun impact d'utiliser l'une ou l'autre solution.

Cela dit, si on se fie à la réalité de notre situation, j'opterais pour `string | undefined` parce que dans ce status, une url est logiquement attendue. Ce n'est pas facultatif, le `undefined` représente une exception anormale.

2022-01-21 12:52 UTC, paduc requested changes

2022-01-21 12:52 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectDCRSubmitted.ts
> +        payload: { fileId, filename, numeroDossier },
Ne pas transmettre le `fileId` si `filename` est manquant.

Je changerais le `payload` de la forme:
```ts
{
  // ...
  file: {
    id: string,
    name: string
  } | undefined
}
```

2022-01-21 12:52 UTC, paduc commented on src/views/components/timeline/components/DCRItem.tsx
> +            <span>Attestation indisponible actuellement</span>
Confusion possible avec le message concernant l'attestation de désignation. J'afficherais plutôt un message du genre `Pièce-jointe introuvable`, vu qu'il s'agit d'un cas d'erreur.

2022-01-21 13:08 UTC, JulienPavon approved these changes

2022-01-21 17:21 UTC, paduc approved these changes

2022-01-21 17:52 UTC, merged