798 refactor gf item
MTES-MCT/potentiel pull request #313
Opened 2022-01-19 16:46 UTC by HanaeY

2022-01-20 16:28 UTC, JulienPavon requested changes

2022-01-20 16:28 UTC, JulienPavon commented on src/views/components/timeline/helpers/extractGFItemProps.ts
> +      isValidated: boolean
Je ne pense pas qu'il faille introduire un booléen ici. En rajoutant dans le status `validated` cela devrait suffire

2022-01-20 17:32 UTC, HanaeY commented on src/views/components/timeline/helpers/extractGFItemProps.ts
> +      isValidated: boolean
à la place du statut "submitted" on pourrait avoir soit "validé" soit "à traiter", qu'en penses-tu ?

2022-01-21 07:36 UTC, JulienPavon commented on src/views/components/timeline/helpers/extractGFItemProps.ts
> +      isValidated: boolean
Oui eventuellement. Le but ici est d'éviter d'avoir un statut et un booléen

2022-01-21 08:18 UTC, paduc commented on src/views/components/timeline/helpers/extractGFItemProps.ts
> +      isValidated: boolean
Oui c'est pas mal `due => past-due => à-traiter => validé`
Je réalise que c'est un mélange de français et d'anglais. Qu'est-ce qu'on choisi ?

2022-01-21 08:57 UTC, JulienPavon commented on src/views/components/timeline/helpers/extractGFItemProps.ts
> +      isValidated: boolean
en anglais ce serait raccord avec tous les statut qu'on à déjà. `validated` c'est facile mais `a-traiter`...

2022-01-21 09:21 UTC, HanaeY commented on src/views/components/timeline/helpers/extractGFItemProps.ts
> +      isValidated: boolean
Je serais aussi partante pour garder les status en anglais. Pour le "à traiter" je verrais bien "pending" mais il faudrait dans ce cas remplacer le pending de l'attestation comme les deux cas n'ont pas le même sens. Sinon "to-be-handled", "to-be-validated" ?

2022-01-21 10:24 UTC, paduc commented on src/views/components/timeline/helpers/extractGFItemProps.ts
> +      isValidated: boolean
Dans ce cas, je propose `pending-validation`

2022-01-21 13:09 UTC, paduc commented on src/views/components/timeline/components/GFItem.tsx
> +    case 'pending-for-validation':
`pending-validation` ça veut dire "en attente de validation".
`pending-for-validation` ça n'a pas de sens.

2022-01-21 13:14 UTC, paduc approved these changes

2022-01-21 13:17 UTC, JulienPavon approved these changes

2022-01-21 14:37 UTC, merged