:star2:  Remove certificate message for DREAL in timeline
MTES-MCT/potentiel pull request #322
Opened 2022-01-24 13:09 UTC by HanaeY

2022-01-25 08:49 UTC, paduc requested changes

2022-01-25 08:49 UTC, paduc commented on src/views/components/timeline/components/DesignationItem.tsx
> +      {role !== 'dreal' && <Certificate {...{ certificate, role }} />}
La règle métier "La DREAL ne voit pas l'attestation" doit être dans `extractDesignationItemProps` et non dans le composant visuel.

Ici, on devrait voir plutot `{certificate && <Certificate {...{ certificate, role }} />}`, ce qui veut dire qu'on doit aussi adapter la forme de `DesignationItemProps` pour que `certificate` puisse être `undefined`.

```
export type DesignationItemProps = {
  type: 'designation'
  date: number
  role: UserRole
  certificate:
    | {
        date: number
        url: string
        status: 'uploaded' | 'generated'
      }
    | { status: 'pending' }
    | { status: 'not-applicable' }
    | undefined
}
```

et rajouter la condition sur le role et `dreal` dans `extractDesignationItemProps`.

Je vois que le role est passé à `Certificate` (pour ajuster le message, ok) mais pour moi, c'est un anti-pattern.

2022-01-25 14:09 UTC, paduc approved these changes

2022-01-25 14:20 UTC, HanaeY commented on src/views/components/timeline/components/DesignationItem.tsx
> +      {role !== 'dreal' && <Certificate {...{ certificate, role }} />}
pour cette question de rôle passé à certificate pour afficher un message différent pour les admin vous avez une autre idée ?  @paduc @JulienPavon

2022-01-25 15:46 UTC, JulienPavon commented on src/views/components/timeline/components/DesignationItem.tsx
> +      {role !== 'dreal' && <Certificate {...{ certificate, role }} />}
En fait il faut revoir l'extraction des props pour la Designation. Le statut `pending` n'existe probablement pas. Donc si nous n'avons pas d'attestation et que le projet n'est pas un projet historique `certificate` sera `null`.
Dans le composant quand tu n'as pas de certificate nous allons afficher un des 2 messages suivant le rôle (les messages actuellement dans le composant Pending) 
```javascript
{certificate ? <Certificate {...{ certificate }} /> : <Pending {...{ role }} />}
```

2022-01-26 08:30 UTC, HanaeY commented on src/views/components/timeline/components/DesignationItem.tsx
> +      {role !== 'dreal' && <Certificate {...{ certificate, role }} />}
ok je créé une nouvelle PR de refacto pour ça alors !

2022-01-26 08:31 UTC, merged