797 As admin i can notify PPE2 projects
MTES-MCT/potentiel pull request #334
Opened 2022-01-28 10:30 UTC by HanaeY

2022-02-01 16:33 UTC, JulienPavon commented on src/dataAccess/inMemory/appelOffre.ts
> +  if (
Ici il ne faut plus se baser sur l'id de l'appel d'offre mais bien le champ `soumisAuxGarantiesFinancieres` nouvellement introduit.
Et pour l'appel d'offre Eolien CRE4 il faut rajouter cette propriété
Un petit test sur cette fonction serait le bienvenu également

2022-02-02 13:15 UTC, JulienPavon requested changes

2022-02-02 13:15 UTC, JulienPavon commented on src/dataAccess/inMemory/appelOffre.ts
> +  soumisAuxGarantiesFinancieres?: boolean
Ici il ne faut pas rajouter d'arguments à la fonction. On peut grâce à l'id `appelOffreId` récupérer l'appel d'offre correspondant depuis `appelOffreStatic` et utiliser le champ `soumisAuxGarantiesFinancieres`

2022-02-02 13:15 UTC, JulienPavon commented on src/dataAccess/inMemory/isSoumisAuxGarantiesFinancieres.spec.ts
> +    for (const appelOffre of [
Pour les jeux de tests il faut ici se constituer un appel d'offre selon les cas de tests. Soumis ou non, ayant la famille soumise ou non aux GFs. Pour faire ceci il faudrait avoir une dépendance à injecter pour fabriquer la fonction `isSoumisAuxGarantiesFinancieres`

2022-02-02 13:15 UTC, JulienPavon commented on src/dataAccess/inMemory/appelsOffres/CRE4/autoconsommationMetropole.ts
> +  soumisAuxGarantiesFinancieres: false,
je serai d'avis de ne pas rajouter la valeur false ici. Ou bien il faudrait changer le champ `soumisAuxGarantiesFinancieres` du type `AppelOffre` pour qu'il soit obligatoire et non optionel comme il est actuellement

2022-02-02 15:56 UTC, HanaeY commented on src/dataAccess/inMemory/appelOffre.ts
> +  soumisAuxGarantiesFinancieres?: boolean
Je ne peux pas rendre la propriété obligatoire car dans certains cas cela dépend de la famille, mais je peux retirer le cas soumisAuxGarantiesFinancieres = false pour les AO jamais soumis aux GF.

2022-02-02 15:59 UTC, HanaeY commented on src/dataAccess/inMemory/appelsOffres/CRE4/autoconsommationMetropole.ts
> +  soumisAuxGarantiesFinancieres: false,
Je ne peux pas rendre la propriété obligatoire car dans certains cas cela dépend de la famille, mais je peux retirer le cas soumisAuxGarantiesFinancieres = false pour les AO jamais soumis aux GF.

2022-02-03 08:12 UTC, JulienPavon commented on src/dataAccess/inMemory/isSoumisAuxGarantiesFinancieres.spec.ts
> +    for (const appelOffre of [
Sinon de dans la branche sur les attestations j'avais aussi cette fonction que j'ai testé. Peut être serait-il intéressant de prendre les tests que j'ai écrit et les adapter à ce cas. (https://github.com/MTES-MCT/potentiel/blob/824-ppe2-certificates-templates/src/views/certificates/ppe2/helpers/estSoumisAuxGFs.spec.ts)
Ensuite il faudrait que j'utilise la même fonction dans les attestations

2022-02-04 15:50 UTC, HanaeY commented on src/dataAccess/inMemory/isSoumisAuxGarantiesFinancieres.spec.ts
> +    for (const appelOffre of [
j'ai créé une carte pour le refacto tu test et traiter ce doublon de fonctions qu'on a (isSoumisAuxGF et estSoumisAuxGFs)

2022-02-04 17:02 UTC, JulienPavon approved these changes

2022-02-04 17:07 UTC, merged