820 timeline gf item for ppe2 pp
MTES-MCT/potentiel pull request #339
Opened 2022-02-07 17:36 UTC by HanaeY

2022-02-24 15:18 UTC, JulienPavon requested changes

2022-02-24 16:40 UTC, HanaeY commented on src/views/components/timeline/helpers/extractGFItemProps.ts
> +      status: 'pending-validation' | 'validated' | 'submitted-with-application-and-uploaded'
tout à fait !

2022-02-24 17:52 UTC, HanaeY commented on src/views/components/timeline/helpers/extractGFItemProps.ts
> +      date: undefined
Bon en fait ça me casse des trucs dans la Timeline, je vais voir si je peux trouver une solution ...

2022-03-01 17:35 UTC, paduc commented on src/modules/project/useCases/submitGF.spec.ts
> +      const submitStep = makeSubmitGF({
`submitGF`

2022-03-03 14:12 UTC, JulienPavon requested changes

2022-03-03 14:12 UTC, JulienPavon commented on src/controllers/garantiesFinancieres/getRemoveGF.ts
> +  ensureRole(['admin', 'dgec', 'porteur-projet']),
Est ce que cette fonctionnalité n'est pas uniquement pour les porteurs de projet ?

2022-03-03 14:12 UTC, JulienPavon commented on src/controllers/garantiesFinancieres/getWithdrawGF.ts
> +  ensureRole(['admin', 'dgec', 'porteur-projet']),
Est ce que cette fonctionnalité n'est pas uniquement pour les porteurs de projet ?

2022-03-04 17:28 UTC, paduc approved these changes

2022-03-07 08:22 UTC, merged