:wrench:  CD requirements
MTES-MCT/potentiel pull request #36
Opened 2021-01-03 23:44 UTC by Zekdar

2021-01-04 10:55 UTC, paduc requested changes

2021-01-04 10:55 UTC, paduc commented on .env.template
> +PORT=
Est-ce qu'on est d'accord que pour le déploiement sur Clever-cloud, on n'aura plus à passer par un fichier `.env` ? Ces valeurs d'environment devront être saisies dans l'admin Clever-cloud.

2021-01-04 10:55 UTC, paduc commented on .github/workflows/nodejs.cd.dev.yml
> +          appID: app_eeb6121a-65e3-4085-b85a-a56c986c680c
Est-ce qu'on ne pourrait pas aussi placer l'appID dans les secrets ? Par exemple `CLEVER_DEV_APPID`.

2021-01-04 10:55 UTC, paduc commented on .github/workflows/nodejs.cd.master.yml
> +          appID: app_01c01a7d-783f-42a6-8d10-db9167ae056b
idem

2021-01-04 10:55 UTC, paduc commented on .github/workflows/nodejs.cd.staging.yml
> +          appID: app_14ec2d47-8d37-4388-9833-ea413f2841da
idem

2021-01-04 10:55 UTC, paduc commented on package.json
> +    "install": "npm run build",
C'est un script requis par Clever ?

2021-01-04 10:56 UTC, paduc commented on .github/workflows/nodejs.cd.dev.yml
> +          appID: app_eeb6121a-65e3-4085-b85a-a56c986c680c
Ca nous permettrait de changer l'appID sans passer par une PR.

2021-01-04 11:02 UTC, Zekdar commented on .github/workflows/nodejs.cd.dev.yml
> +          appID: app_eeb6121a-65e3-4085-b85a-a56c986c680c
Si on met l'AppID dans les secrets, ça implique qu'on ne peut plus voir sa valeur.
Ca nous permettrait effectivement de ne plus passer par une PR, mais du coup on perd aussi la traçabilité des changements.
Je pense que la balance bénéfice/risque est < 1 pour le moment.

2021-01-04 11:02 UTC, Zekdar commented on .env.template
> +PORT=
Oui c'est le cas, tout est injecté par CC. Le `.env` sert pour lancer l'appli en local.

2021-01-04 11:02 UTC, Zekdar commented on package.json
> +    "install": "npm run build",
Oui CC exécute automatiquement le script `install`

2021-01-04 11:04 UTC, paduc commented on .github/workflows/nodejs.cd.dev.yml
> +          appID: app_eeb6121a-65e3-4085-b85a-a56c986c680c
Quand tu dis qu'on ne peut plus voir sa valeur, tu penses à quoi ? En tant qu'admin, on peut voir la valeur dans github. 
Quel risque vois-tu dans la perte de traçabilité de ce changement ?

2021-01-04 11:05 UTC, paduc commented on package.json
> +    "install": "npm run build",
Je trouve ça un peu dommage de leur part de l'avoir appelé `install` parce que ça crée une confusion entre `npm install` et `npm run install`.

2021-01-04 11:59 UTC, paduc submitted a review, later dismissed

2021-01-05 09:00 UTC, paduc approved these changes

2021-01-05 09:01 UTC, merged