:recycle: Use direct import on @entities/periode to use isNotifiedPeriode
MTES-MCT/potentiel pull request #364
Opened 2022-03-02 13:42 UTC by JulienPavon

Pour les parties utilisée côté front il faut faire des imports direct sur `@entities/periode` pour utiliser `isNotifiedPeriode`. Sinon tous le module `@entities` sera chargé inutilement par webpack

2022-03-02 14:55 UTC, paduc requested changes

2022-03-02 14:55 UTC, paduc commented on .github/workflows/ci.build.yml
> +      - run: npm install --ignore-scripts
Ce n’est pas idéal d’utiliser ignore scripts, certains packages npm plantent à cause de ça (comme esloader). Pourquoi as-tu eu besoin de changer ?

2022-03-02 15:06 UTC, JulienPavon commented on .github/workflows/ci.build.yml
> +      - run: npm install --ignore-scripts
Ah... En éxecutant `npm ci` on ne peut pas avoir le NODE_ENV au niveau du job sinon le script `migrate` est éxecuté et échoue. Et en mettant le NODE_ENV en production seulement quand on éxecute `build` et bien la variable n'est pas prise en compte et le build n'est pas celui fait pour la production. Par contre normalement ça devrait fonctionner d'après la doc donc je ré essaie

2022-03-02 16:18 UTC, JulienPavon commented on .github/workflows/ci.build.yml
> +      - run: npm install --ignore-scripts
Après une multitude d'essai, peu importe l'éxecution des scripts si on veut avoir une erreur lié au build webpack en mode production il faut mettre la variable d'environnement NODE_ENV au niveu du job et faire le build via `npm ci`. Du coup j'ai introduit une variable DO_NOT_EXECUTE_MIGRATE pour ne pas éxecuter le script `migrate` pendant le ci.build.

2022-03-03 08:55 UTC, paduc approved these changes

2022-03-03 09:19 UTC, merged