322 L'admin peut valider une demande de recours
MTES-MCT/potentiel pull request #37
Opened 2021-01-06 11:09 UTC by paduc

2021-01-08 18:40 UTC, Zekdar requested changes

2021-01-08 18:40 UTC, Zekdar commented on src/infra/sequelize/queries/getModificationRequestDetails.ts
> +      requestedBy: requestedBy.get().fullName,
If `requestedBy` can be `undefined`, please use `?`

2021-01-08 18:40 UTC, Zekdar commented on src/infra/sequelize/queries/getModificationRequestDetails.ts
> +  const UserModel = models.User
You can simplify : 

```js
const { ModificationRequest: ModificationRequestModel, Project: ProjectModel, File: FileModel, User: UserModel }  = models


```

2021-01-08 18:40 UTC, Zekdar commented on src/infra/sequelize/queries/getModificationRequestDetails.ts
> +    const unitePuissance = getAppelOffre({ appelOffreId, periodeId })?.unitePuissance || '??'
`const unitePuissance: string`

2021-01-08 18:40 UTC, Zekdar commented on src/infra/sequelize/queries/getModificationRequestInfoForStatusNotification.integration.ts
> +    await sequelize.sync({ force: true })
Idem. Please don't use.

2021-01-08 18:40 UTC, Zekdar commented on src/infra/sequelize/queries/getModificationRequestInfoForStatusNotification.ts
> +  const UserModel = models.User
You could simplify by destructuring

2021-01-08 18:40 UTC, Zekdar commented on src/infra/sequelize/queries/getModificationRequestInfoForStatusNotification.ts
> +    const { email, fullName, id } = requestedBy
You can do it in one line : 
```js
const { type, requestedBy: { email, fullName, id }, project : { nomProjet } } = modificationRequestRaw.get()
```

2021-01-08 18:40 UTC, Zekdar commented on src/infra/sequelize/queries/getModificationRequestStatus.integration.ts
> +    await sequelize.sync({ force: true })
Idem. Please don't use.

2021-01-08 18:40 UTC, Zekdar commented on src/infra/sequelize/queries/getModificationRequestStatus.ts
> +  ).map((modificationRequest: any) => modificationRequest.status)
```js
).map(({ status }) => status)
```

2021-01-08 18:40 UTC, Zekdar commented on src/modules/modificationRequest/ModificationRequest.ts
> +  if (!history || !history.length) {
You can use `?`

2021-01-08 18:40 UTC, Zekdar commented on src/modules/modificationRequest/eventHandlers/handleResponseTemplateDownloaded.ts
> +        console.error('handleResponseTemplateDownloaded failed to make the transaction', e)
Expliciting `handleResponseTemplateDownloaded` is not needed since it will be in the stacktrace.

2021-01-08 18:40 UTC, Zekdar commented on src/views/helpers/ModificationRequestTitleByType.ts
> +  // fournisseur: 'changement de fournisseur',
Remove dead code

2021-01-08 18:40 UTC, Zekdar commented on src/modules/modificationRequest/useCases/acceptModificationRequest.ts
> +    .map(() => null)
What does that do ?

2021-01-08 18:40 UTC, Zekdar commented on src/modules/modificationRequest/useCases/acceptModificationRequest.ts
> +    })
I find all these `.andThen` are really complexifying the intent and the readability compared to what they make us benefit.

To me, they look like a js Hadoken ![Hadoken](https://media.tenor.com/images/86374c728b43c3203f9ff1a49f3ed1fb/tenor.png)

I get that they provide extra security, but they make it a hard time to read.

2021-01-08 18:40 UTC, Zekdar commented on src/modules/notification/eventHandlers/handleModificationRequestStatusChanged.ts
> +        'handleModificationRequestStatusChanged caught an event but could not send the notifications',
The stacktrace already explicits the function name

2021-01-11 08:23 UTC, paduc commented on src/controllers/postReplyToModificationRequest.ts
> +  const courrierReponseExists: boolean = !!request.file && (await pathExists(request.file.path))
How ? The second part is a call to `pathExists`.

2021-01-11 08:32 UTC, paduc commented on src/infra/sequelize/projections/modificationRequest/updates/onModificationRequestAccepted.integration.ts
> +    // Create the tables and remove all data
The line below is not explicit. The comment answers the `why` of the `await sequelize.sync({ force: true })`

2021-01-11 08:35 UTC, paduc commented on src/infra/sequelize/projections/modificationRequest/updates/onModificationRequestAccepted.integration.ts
> +    await sequelize.sync({ force: true })
Unfortunately, using `resetDatabase` from `src/dataAccess/db/index.ts` will not work because it is not the same `sequelize` instance. 

This is something we can address after merging with `dev` branch but not in this PR.

2021-01-11 08:38 UTC, paduc commented on src/infra/sequelize/projections/modificationRequest/updates/onModificationRequestAccepted.ts
> +  instance.versionDate = event.occurredAt
Point taken. I used `Object.assign` instead, to keep the `instance` (which is a class instance, not a pojo).

2021-01-11 08:44 UTC, paduc commented on src/infra/sequelize/queries/getModificationRequestDetails.ts
> +      requestedBy: requestedBy.get().fullName,
No it cannot be `undefined` (see `modificationRequest.model.ts`)

2021-01-11 08:50 UTC, paduc commented on src/infra/sequelize/queries/getModificationRequestDetails.ts
> +    const unitePuissance = getAppelOffre({ appelOffreId, periodeId })?.unitePuissance || '??'
Why ? The right-hand part determines the type and also the `ModificationRequestPageDTO`.

2021-01-11 09:00 UTC, paduc commented on src/modules/modificationRequest/useCases/acceptModificationRequest.ts
> +    .map(() => null)
This one does nothing, it is a remnant of past code. What it used to do is change the return type from whatever the previous `ResultAsync<T>` was to `ResultAsync<null>` which is the expected return type.

2021-01-11 09:04 UTC, paduc commented on src/modules/modificationRequest/useCases/acceptModificationRequest.ts
> +    })
Yes I get what you're saying but there are only 2 levels here. There could have been two levels of `try/catch` without using `ResultAsync`.

2021-01-11 09:18 UTC, Zekdar commented on src/controllers/postReplyToModificationRequest.ts
> +  const courrierReponseExists: boolean = !!request.file && (await pathExists(request.file.path))
Yep, my bad :D

2021-01-11 16:31 UTC, Zekdar approved these changes

2021-01-11 16:38 UTC, merged