:sparkles: 592 Accès au profil utilisateur pour les administrateurs
MTES-MCT/potentiel pull request #377
Opened 2022-03-09 09:28 UTC by JulienPavon

Pour activer l'authentification à double facteur pour les admins il faut modifier la config keycloak comme décrit dans la doc KEYCLOAK.MD. (la partie configuration d'un nouveau flow copié sur l'existant est déjà faite en production. Il ne restera plus qu'à faire le binding)
Afin de permettre aux admins de supprimer/modifier la validation en 2 étapes il a fallu autoriser l'accès à l'édition du compte pour les utlisateurs.

Toute la partie "account" de keycloak a été revue avec le Design System de l'état. La package `@gouvfr/dsfr` a été ajouté et toutes les ressources copiées dans la partie ressource de la page "account".

Également certains ajustements ont été fait afin d'utiliser une instance Keycloak localement.

Enfin l'accès au compte est autorisé pour tous les utilisateurs afin de leur permettre de modifier leur nom, mot de passe et validation en 2 étapes.

<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/377"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-03-11 17:47 UTC, paduc commented
Je n'ai toujours pas su tester de mon coté.

Sur Gitpod, j'arrive à lancer keycloak + potentiel et me connecter sur Keycloak (y compris 2FA) mais dès que j'essaye d'accéder à une page protégée sur Potentiel, j'ai une erreur "access denied". Ca vient vraisemblablement du https et du reverse proxy.

En local, j'arrive à lancer keycloak mais je n'arrive pas à importer le fichier `realm-export.json`. Je me demande si ça ne vient pas de la version de keycloak que j'ai en local. Tu as quelle version de ton coté ?

Reste à tester l'instance keycloak sur gitpod et configurer potentiel en local pour s'authentifier dessus. Peut-être que mon problème "access denied" n'existera pas dans cette config. Je n'ai pas encore eu le temps d'essayer.

2022-03-14 07:59 UTC, JulienPavon commented
> Je n'ai toujours pas su tester de mon coté.
> 
> Sur Gitpod, j'arrive à lancer keycloak + potentiel et me connecter sur Keycloak (y compris 2FA) mais dès que j'essaye d'accéder à une page protégée sur Potentiel, j'ai une erreur "access denied". Ca vient vraisemblablement du https et du reverse proxy.
> 
> En local, j'arrive à lancer keycloak mais je n'arrive pas à importer le fichier `realm-export.json`. Je me demande si ça ne vient pas de la version de keycloak que j'ai en local. Tu as quelle version de ton coté ?
> 
> Reste à tester l'instance keycloak sur gitpod et configurer potentiel en local pour s'authentifier dessus. Peut-être que mon problème "access denied" n'existera pas dans cette config. Je n'ai pas encore eu le temps d'essayer.

J'ai quelques fois eu cette erreur "acces denied" et en relançant l'instance potentiel après avoir supprimer les cookies c'était ok. Peut être que c'est le même comportement sur gitpod.
Sinon en local j'utilise la dernière version de l'image `jboss/keycloak`

2022-03-14 12:05 UTC, paduc commented
> J'ai quelques fois eu cette erreur "acces denied" et en relançant l'instance potentiel après avoir supprimer les cookies c'était ok. Peut être que c'est le même comportement sur gitpod. Sinon en local j'utilise la dernière version de l'image `jboss/keycloak`

En local, `jboss/keycloak` ne fonctionne pas chez moi, à cause de mon cpu M1 et mon image alternative est périmée (keycloak 12). J'ai trouvé une autre manière de procéder que je vais essayer.

Sinon, j'ai vu que les identifiants uuid dans le fichier `realm-export.json` avaient tous changé. Est-ce que tu es bien parti de la version qui est dans le repo comme configuration ? Ou bien as-tu créé de nouveaux clients ?

2022-03-14 13:12 UTC, JulienPavon commented
> > J'ai quelques fois eu cette erreur "acces denied" et en relançant l'instance potentiel après avoir supprimer les cookies c'était ok. Peut être que c'est le même comportement sur gitpod. Sinon en local j'utilise la dernière version de l'image `jboss/keycloak`
> 
> En local, `jboss/keycloak` ne fonctionne pas chez moi, à cause de mon cpu M1 et mon image alternative est périmée (keycloak 12). J'ai trouvé une autre manière de procéder que je vais essayer.
> 
> Sinon, j'ai vu que les identifiants uuid dans le fichier `realm-export.json` avaient tous changé. Est-ce que tu es bien parti de la version qui est dans le repo comme configuration ? Ou bien as-tu créé de nouveaux clients ?

Ah oui pour l'export je n'était pas parti de celui en local. Je corrige ça :+1:

2022-03-14 14:13 UTC, paduc requested changes

2022-03-14 14:13 UTC, paduc commented on keycloak/themes/potentiel/account/account.ftl
> +          <label for="email" class="fr-label">${msg("email")} (ce champ n'est pas modifiable)</label>
Utiliser le style DSFR pour [les champs désactivés](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/217088099/Champs+de+saisie+-+Input#État-désactivé)

2022-03-14 14:13 UTC, paduc commented on keycloak/themes/potentiel/account/messages/messages_en.properties
>  authenticatorTitle=Authentification
Appeler ça "Deuxième facteur" plutôt qu'authentification ?

2022-03-14 14:13 UTC, paduc commented on keycloak/themes/potentiel/account/messages/messages_en.properties
>  authenticatorCode=Mot de passe unique
"Code affiché sur votre application (6 chiffres)"

2022-03-14 15:40 UTC, JulienPavon commented on keycloak/themes/potentiel/account/messages/messages_en.properties
>  authenticatorTitle=Authentification
Plusieurs expressions différentes dans la page wikipedia https://fr.wikipedia.org/wiki/Double_authentification

2022-03-15 09:23 UTC, paduc commented on keycloak/themes/potentiel/account/messages/messages_en.properties
>  authenticatorTitle=Authentification
Va pour "Double authentification"

2022-03-22 07:28 UTC, paduc approved these changes

2022-03-22 07:52 UTC, merged