:star: Add DSFR header to Potentiel App
MTES-MCT/potentiel pull request #379
Opened 2022-03-10 15:58 UTC by HanaeY

2022-03-15 13:07 UTC, HanaeY commented on src/views/components/Footer.tsx
> +                  licence etalab-2.0
Espace manquant entre "sous" et "licence"

2022-03-15 13:25 UTC, JulienPavon requested changes

2022-03-15 13:25 UTC, JulienPavon commented on src/views/index.html.ts
> +        <meta name="theme-color" content="#000091" />
Je n'ai plus l'la favicon lorsque je suis dans l'appli. Sinon aucun problème sur les pages de connexion ou d'accueil

2022-03-15 13:25 UTC, JulienPavon commented on src/views/components/Header.tsx
> +                      {user ? (
Ici l'affichage est très condensé je trouve. Est ce qu'on ne pourrait pas profiter de la hauteur disponible et avoir par exemple la partie "Mon compte" au dessus du lien du guide d'utilisation ?

2022-03-15 13:29 UTC, JulienPavon commented
L'hamburger menu en mode mobile ne s'ouvre pas :(

2022-03-15 13:32 UTC, JulienPavon commented on src/views/components/Header.tsx
> +                    Facilite le parcours des producteurs d'énergies renouvelables électriques
La phrase d'acroche étant un peu longue peut être qu'on pourrait passer une ligne après "producteurs"

2022-03-15 13:43 UTC, JulienPavon commented on src/views/components/Header.tsx
> +                          <span>{user.fullName}</span>
On peut appliquer les class css `fr-link fr-fi-user-line` afin d'avoir le même style que les autres éléments "tools" avec une icône "user"

2022-03-15 13:44 UTC, JulienPavon commented on src/views/components/Header.tsx
> +                      {user ? (
J'ai essayé en local et c'est pas géniel :'(

2022-03-15 13:52 UTC, HanaeY commented on src/views/components/Header.tsx
> +                        Guide d'utilisation
Actuellement dans l'application on a "aide", je crois qu'on a dû récupérer ce "guide d'utilisation" de la première maquette de landing page de Julie, ou du header type dsfr. Mais à mon avis la page ciblée est plus une aide qu'un guide d'utilisation :) !

2022-03-15 14:23 UTC, paduc commented on src/views/components/Footer.tsx
> +                  licence etalab-2.0
Ca vient d'un copier-coller. 
Que penses-tu d'enlever cette partie ?

2022-03-15 14:25 UTC, paduc commented on src/views/components/Header.tsx
> +                        Guide d'utilisation
Bien vu !

2022-03-15 16:30 UTC, HanaeY commented on src/views/components/Footer.tsx
> +                  licence etalab-2.0
Cette mention fait partie des éléments obligatoire du footer (ils sont listés ici : https://gouvfr.atlassian.net/wiki/spaces/DB/pages/222331413/Pied+de+page+-+Footer)

2022-03-15 17:38 UTC, paduc commented on src/views/components/Header.tsx
> +                          <span>{user.fullName}</span>
J'ai rajouté un style pour que ça soit gris, afin de le distinguer des liens qui sont bleus.

2022-03-17 10:52 UTC, paduc approved these changes

2022-03-18 10:13 UTC, merged