968 Admin can upload/attach files for legacy modifications
MTES-MCT/potentiel pull request #424
Opened 2022-04-05 13:18 UTC by paduc

We don't have an identifier for legacy modifications so we only use `filename` and `projectId` to link a file to the corresponding legacy modification. 

- Look for a modification with a file with that name
- Trigger `LegacyModificationFileAttached` with that file name and project id
- Merge `LegacyModificationImported` and `LegacyModificationFileAttached` at the very end, in `extractLegacyModificationProps`

<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/424"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-04-06 08:06 UTC, JulienPavon requested changes

2022-04-06 08:06 UTC, JulienPavon commented on src/views/pages/UploadLegacyModificationFilesPage.tsx
> +export const UploadLegacyModificationFiles = PageLayout(
Est ce qu'on ne commencerait pas, pour cette nouvelle page, à appliquer les styles du dsfr (à l'aide de tailwind) pour les boutons, champs ?

2022-04-06 08:56 UTC, paduc commented on src/views/components/timeline/components/LegacyModificationsItem.tsx
> +const LegacyModificationContainer = (
Oui les deux alternatives sont possibles. 

J'ai choisi la voie de la composition pour garder la main sur le contenu de chaque composant variant. Ainsi si un variant a un contenu qui ne correspond pas au cas commun (représenté par `LegacyModificationContainer`), on a la liberté de l'implémenter sans utiliser `LegacyModificationContainer`. On n'aurait pas cette liberté en remontant tout le code commun dans `LegacyModificationsItem`.

Qu'en penses-tu ?

2022-04-06 08:59 UTC, paduc commented on src/views/components/timeline/helpers/extractLegacyModificationsItemProps.ts
> +          courrier: getCourrier(event.filename),
Bien vu !

2022-04-06 09:01 UTC, paduc commented on src/views/pages/UploadLegacyModificationFilesPage.tsx
> +export const UploadLegacyModificationFiles = PageLayout(
Tu veux dire ajouter un composant `Button` ?
C'est une bonne idée mais je commencerais par faire une PR dédiée à la création du composant, qu'on peut ensuite réutiliser dans les PRs qui suivent.

2022-04-07 13:51 UTC, paduc commented on src/modules/modificationRequest/useCases/attachLegacyModificationFile.ts
> +interface AttachLegacyModificationFileDeps {
On utilise des interfaces pour toutes les déclarations de dépendances de use-case.

2022-04-07 13:51 UTC, paduc commented on src/modules/modificationRequest/useCases/attachLegacyModificationFile.ts
> +interface AttachLegacyModificationFileArgs {
On utilise des interfaces pour toutes les déclarations d'arguments de use-case.

2022-04-07 13:52 UTC, paduc commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +                      filename: payload.filename,
Je ne vois pas trop ce qu'apporterait un test ici. C'est un simple mapper.

2022-04-07 13:53 UTC, paduc commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +                case 'LegacyModificationFileAttached':
Idem, simple mapper.

2022-04-08 11:35 UTC, JulienPavon approved these changes

2022-04-08 12:25 UTC, merged