:sparkles: 1051 Signaler une demande de delai
MTES-MCT/potentiel pull request #439
Opened 2022-04-13 08:19 UTC by JulienPavon

2022-04-14 13:13 UTC, HanaeY commented on src/controllers/project/postSignalerDemandeDelai.ts
> +    console.log(JSON.stringify(request.body))
console.log à retirer

2022-04-14 14:00 UTC, HanaeY commented on src/views/components/timeline/Timeline.stories.tsx
> +          status: 'acceptée',
isAccepted à la place du status

2022-04-14 14:01 UTC, HanaeY commented on src/views/components/timeline/components/DemandeDelaiSignaledItem.tsx
> +}
est-ce qu'on ajouterait pas la note visible pour les admin (dreal et dgec) uniquement ?

2022-04-15 07:02 UTC, JulienPavon commented on src/views/components/timeline/components/DemandeDelaiSignaledItem.tsx
> +}
Oui on peut ;)

2022-04-15 11:55 UTC, paduc requested changes

2022-04-15 11:55 UTC, paduc commented on src/modules/project/Project.signalerDemandeDelai.spec.ts
> +      it('should emit a DemandeDelaiSignaled event', () => {
Pour que ça soit clair la différence avec l'autre cas: `should emit a DemandeDelaiSignaled event with isNewDateApplicable=false`

2022-04-15 11:55 UTC, paduc commented on src/modules/project/Project.signalerDemandeDelai.spec.ts
> +      it('should emit a DemandeDelaiSignaled event', () => {
idem `with isNewDateApplicated=true`

2022-04-15 11:55 UTC, paduc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onDemandeDelaiSignaled.ts
> +        id: new UniqueEntityID().toString(),
Ici, plutot que de créer un nouvel uuid, je propose qu'on utilise l'id de l'événement. Ca permet aussi d'être idempotent.

2022-04-15 11:55 UTC, paduc commented on src/infra/sequelize/projections/project/updates/onDemandeDelaiSignaled.ts
> +      const ProjectModel = models.Project
`const { Project } = models`

2022-04-25 10:44 UTC, HanaeY commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +                      ...(userIs(['admin', 'dgec'])(user) && { notes }),
Ajouter la dreal dans les utilisateurs qui voient les notes

2022-04-25 10:44 UTC, HanaeY commented on src/views/components/timeline/components/DemandeDelaiSignaledItem.tsx
> +          Date d'attestation de conformité demandée {formatDate(newCompletionDueOn)}
Ajouter ":" à "... de conformité demandé : "

2022-04-25 10:47 UTC, HanaeY requested changes

2022-04-25 10:47 UTC, HanaeY commented on src/views/pages/signalerDemandeDelaiPage/SignalerDemandeDelai.tsx
> +                {...(validationErrors && { error: validationErrors['decidedOn']?.toString() })}
J'aurais juste une réserve avec cet affichage des erreurs, c'est que lorsque l'utilisateur modifie la date, l'erreur reste affichée sous le champ, ce qui peut laisser penser que la saisie actuelle est mauvaise... enfin c'est à discuter !
![datesaisirinvalide](https://user-images.githubusercontent.com/72154904/165074526-1b4e9f2d-7503-4c28-8c32-e541d4837fcf.png)

2022-04-26 12:12 UTC, JulienPavon commented on src/views/pages/signalerDemandeDelaiPage/SignalerDemandeDelai.tsx
> +                {...(validationErrors && { error: validationErrors['decidedOn']?.toString() })}
Oui tu as raison je regarde ce qui est possible de faire

2022-04-26 13:26 UTC, HanaeY approved these changes

2022-04-26 13:57 UTC, paduc requested changes

2022-04-26 13:57 UTC, paduc commented on src/views/components/buttons/Button.tsx
> +type ButtonProps = {
Je réitère ma remarque : il est nécessaire de passer toutes les props possibles (ex: `onClick`) au composant `<button>`. On ne sera jamais exhaustif en les énumérant explicitement un par un donc on passe par la définition de base qu'on étends.

```ts
// On étends les attributs natifs
type ButtonProps = React.HTMLAttributes<HTMLButtonElement> & {
  type?: 'button' | 'submit' | 'reset'
  primary?: true
}

export const Button = ({ className = '', children, primary, ...props }: ButtonProps) => (
   <button
     className={`inline-flex items-center px-6 py-2 border border-solid text-base font-medium shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 ${
       primary
         ? 'border-transparent text-white bg-blue-france-sun-base hover:bg-blue-france-sun-hover focus:bg-blue-france-sun-active'
         : 'border-blue-france-sun-base text-blue-france-sun-base bg-white hover:bg-blue-france-975-base focus:bg-blue-france-975-base'
     } ${className}`}
     style={{ color: primary ? 'white' : '#000091', textDecoration: 'none' }}
     {...props}
   >
     {children}
   </button>
 )
```

2022-04-28 09:52 UTC, HanaeY commented on src/views/components/timeline/helpers/extractACItemProps.ts
> +import { DemandeDelaiSignaledDTO, is, ProjectEventDTO, ProjectStatus } from '@modules/frise'
retirer l'import non utilisé

2022-04-28 13:49 UTC, paduc approved these changes

2022-04-28 13:59 UTC, merged