1048 add expiration date to gf form
MTES-MCT/potentiel pull request #445
Opened 2022-04-27 12:52 UTC by HanaeY

2022-04-29 13:21 UTC, JulienPavon requested changes

2022-05-04 09:54 UTC, HanaeY commented on src/controllers/garantiesFinancieres/postUploadGF.ts
> +    if (!isDate(parsedStepDate)) {
ok, je vérifie si on retrouve bien un nombre alors (dans le cas où un utilisateur arriverait outrepasser la vérif côté front et à envoyer des lettres par exemple)

2022-05-05 09:14 UTC, paduc commented on src/controllers/garantiesFinancieres/postSubmitGF.ts
> +      new Date().toLocaleDateString('en-ca'),
Pourquoi `en-ca` ?

2022-05-05 10:27 UTC, HanaeY commented on src/controllers/garantiesFinancieres/postSubmitGF.ts
> +      new Date().toLocaleDateString('en-ca'),
pour obtenir ce format là "2022-04-05", sinon j'ai une erreur Typescript

2022-05-05 10:29 UTC, paduc commented on src/controllers/garantiesFinancieres/postSubmitGF.ts
> +      new Date().toLocaleDateString('en-ca'),
c'est quoi l'erreur typescript ?

`max` ne devrait pas accepter une `Date` ?

2022-05-05 12:09 UTC, JulienPavon commented on src/controllers/garantiesFinancieres/postSubmitGF.ts
> +      new Date().toLocaleDateString('en-ca'),
`max` peut accepter un type `Date` ou `string`. Je pense que le problème vient de la tranformation `parseStringDate`. C'est la aprtie ou il faut tester le premier argument pour check si value est un type `Date` ou pas. Par contre je ne vois pas exactement dans la doc `yup` pourquoi on a ce comportement. C'est ce qui est expliqué dans cet article https://www.codedaily.io/tutorials/Yup-Date-Validation-with-Custom-Transform.
On l'avait retiré car pour le moment on utilisait pas encore `max` et `min` dans les validations

2022-05-05 12:10 UTC, HanaeY commented on src/controllers/garantiesFinancieres/postSubmitGF.ts
> +      new Date().toLocaleDateString('en-ca'),
L'erreur venait de la règle de date max de l'input (j'avais utilisé le même format), j'ai trouvé une alternative avec "new Date().toISOString().split('T')[0]"

2022-05-05 12:24 UTC, JulienPavon commented on src/controllers/garantiesFinancieres/postSubmitGF.ts
> +      new Date().toLocaleDateString('en-ca'),
Par contre il n'y a pas d'erreur Typescript pour mettre `new Date()` dans la fonction `max`

2022-05-05 12:25 UTC, JulienPavon commented on src/controllers/garantiesFinancieres/postSubmitGF.ts
> +      new Date().toLocaleDateString('en-ca'),
Tu veux dire une erreur à l'exécution ?

2022-05-05 12:37 UTC, JulienPavon commented on src/views/components/timeline/components/GFItem.tsx
> +              max={new Date().toISOString().split('T')[0]}
Ici on peut utiliser un `format` simplement. D'après la doc (https://developer.mozilla.org/fr/docs/Web/HTML/Element/input/date) pour un `input` `date` `max` doit être au format `yyyy-mm-dd`.
Donc on peut avoir `max={format(new Date(), 'yyyy-MM-dd`)}`

2022-05-05 12:41 UTC, paduc commented on src/controllers/garantiesFinancieres/postSubmitGF.ts
> +      new Date().toLocaleDateString('en-ca'),
Pourquoi est-ce qu'on utilise un `<input type="date">` alors qu'on a un composant `DateInput`.
L'utilisateur devra faire avec deux méthodes de saisie de date et on se retrouve en back avec deux méthodes de traitement/validation des dates.
Est-ce qu'une transition est prévue ?

2022-05-05 12:44 UTC, paduc commented on src/controllers/garantiesFinancieres/postSubmitGF.ts
> +      new Date().toLocaleDateString('en-ca'),
> C'est ce qui est expliqué dans cet article https://www.codedaily.io/tutorials/Yup-Date-Validation-with-Custom-Transform.

Il me semble que le validateur de l'article souhaite accepter soit une date soit une string dans un certain format. Dans notre cas, nous n'acceptons qu'une string dans un certain format. 
Cela dit, suite à la transformation, on a forcément une `Date` et donc `max` peut être une `Date`.

2022-05-05 12:54 UTC, HanaeY commented on src/views/components/timeline/components/GFItem.tsx
> +              max={new Date().toISOString().split('T')[0]}
de mon côté max={format(new Date(), 'yyyy-MM-dd')} ne fonctionne pas mais max={new Date().toISOString().split('T')[0]} oui

2022-05-05 13:08 UTC, HanaeY commented on src/controllers/garantiesFinancieres/postSubmitGF.ts
> +      new Date().toLocaleDateString('en-ca'),
A mon avis ça serait bien de faire la transition vers l'utilisation du type date de l'input, ça permet une saisie plus facile pour l'utilisateur et ça évite d'avoir à utiliser une règle compliquée. On a commencé à passer sur le type date avec la déclaration de demandes de délai par les admin. Pour ce qui est de la frise, soit on fait une PR pour mettre à jour les champs de dates des formulaires, soit on attend de passer les formulaires sur des pages ? qu'en pensez-vous ?

2022-05-05 13:26 UTC, merged