Update user invitation forms
MTES-MCT/potentiel pull request #455
Opened 2022-05-11 10:03 UTC by HanaeY

2022-05-12 07:55 UTC, JulienPavon requested changes

2022-05-12 07:55 UTC, JulienPavon commented on src/controllers/admin/drealUsers/getDrealPage.ts
> +    const drealUsers = await userRepo.findAll({ role: 'dreal' })
Ne pas utiliser de repository dans un controller. Créer une query pour récupérer les données nécessaire à cette page

2022-05-12 07:55 UTC, JulienPavon commented on src/controllers/admin/drealUsers/postInviteDrealUser.ts
> +          return eventStore
Ici publier directement un évennement dans l'event store sans passer par un agrégat n'est pas génial. D'ailleurs dans `DrealUserInvited` l'`aggregateId` est `undefined`. On pourrait commencer à implémenter la fonctionnalité pour inviter un utilisateur dans l'agrégat `User`. Et avoir comme `aggregateId` la propriété `userId`

2022-05-12 07:55 UTC, JulienPavon commented on src/controllers/admin/partnerUsers/getPartnersListPage.ts
> +    const users = await userRepo.findAll({ role: ['acheteur-obligé', 'ademe'] })
Même remarque que pour la liste des utilisateurs DREAL. Avoir une query dédiée à la page.

2022-05-12 07:55 UTC, JulienPavon commented on src/controllers/admin/partnerUsers/postInvitePartnerUser.ts
> +          return eventStore
Même remarque, il ne faudrait pas publier directement dans l'event store mais utiliser une fonction de l'agrégat user. Peut être d'ailleurs qu'il faudrait un user case spécifique.

2022-05-12 07:55 UTC, JulienPavon commented on src/controllers/admin/partnerUsers/postInvitePartnerUser.ts
> +              success: `Une invitation a bien été envoyée à ${email}.`,
Je ne vois aucun effet de bord pour l'évennement `PartnerUserInvited`. Du coup est-on sûr qu'une invitation est envoyée ?

2022-05-12 07:55 UTC, JulienPavon commented on src/views/components/inputs/Select.tsx
> +  options: string[]
Avons nous réélement besoin de passer les `options` dans ce select ? Le but d'avoir des composants react pour des éléments HTML est de centraliser les styles CSS uniquement.

2022-05-12 07:55 UTC, JulienPavon commented on src/views/components/inputs/Select.tsx
> +      {isOnError && (
Est-ce qu'on ne pourrait pas imaginer un décorateur pour ajouter l'affichage des erreurs sur nos composants ?

2022-05-12 07:55 UTC, JulienPavon commented on src/views/pages/partnersListPage/PartnersList.tsx
> +  request: Request
Utiliser un type pour les props

2022-05-12 07:55 UTC, JulienPavon commented on src/views/pages/drealListPage/DrealList.tsx
> +interface DrealListProps {
Utiliser un type pour les props

2022-05-12 07:55 UTC, JulienPavon commented on src/views/pages/AdemeStatistiquesPage.tsx
>  interface Props {
Utiliser un type pour les props et le renomer pour correspondre au composant cible

2022-05-12 07:55 UTC, JulienPavon commented on src/views/pages/AdminStatistiquesPage.tsx
>  interface Props {
Utiliser un type pour les props et le renomer pour correspondre au composant cible

2022-05-12 07:55 UTC, JulienPavon commented on src/views/pages/StatistiquesPage.tsx
>  interface Props {
Utiliser un type pour les props et le renomer pour correspondre au composant cible

2022-05-19 12:25 UTC, HanaeY commented on src/controllers/admin/partnerUsers/postInvitePartnerUser.ts
> +              success: `Une invitation a bien été envoyée à ${email}.`,
Dans le cadre de cette PR je n'ai pas touché à cette partie du code, j'ai juste séparé le controlleur en deux controlleurs distincts Dreal / autres partenaires. On peut en reparler avec PA dans le cadre de la refonte des parcours d'invitation/inscription.

2022-05-19 12:50 UTC, HanaeY commented on src/views/components/inputs/Select.tsx
> +      {isOnError && (
Je ne suis pas sûre d'avoir compris. Tu veux dire un nouveau composant pour l'erreur ?

2022-05-20 07:48 UTC, JulienPavon commented on src/controllers/admin/partnerUsers/postInvitePartnerUser.ts
> +              success: `Une invitation a bien été envoyée à ${email}.`,
Ça marche :+1:

2022-05-20 08:15 UTC, JulienPavon approved these changes

2022-05-20 08:26 UTC, merged