:star2:  importProjects should check familleId
MTES-MCT/potentiel pull request #49
Opened 2021-01-13 17:22 UTC by paduc

I noticed that importProjects accepted csv files with familleId that did not exist for the appel d'offre. 
This adds a check that throws an error if such a line is in the file.

2021-01-14 14:06 UTC, Zekdar requested changes

2021-01-14 14:06 UTC, Zekdar commented on src/useCases/importProjects.ts
> +            new Error('Famille manquante (cette appel d‘offre requiert une famille)'),
cette > cet

2021-01-14 14:06 UTC, Zekdar commented on src/useCases/importProjects.ts
> +            index + 2,
This line should be commented to explain the `+2`

2021-01-14 14:08 UTC, Zekdar commented
The function `makeImportProjects` is ~300 lines long. We should be careful about making function only do one thing. Plus, there are a lot of comments inside of it, this is a sign of a need to split in my opinion. What do you think ?

2021-01-14 14:15 UTC, paduc commented
> The function `makeImportProjects` is ~300 lines long. We should be careful about making functions only do one thing.
> Plus, there are a lot of comments, this is a sign of a need for splitting in my opinion. What do you think ?

Ce n'est pas une nouvelle méthode, c'est du code ancien. J'ajoute de la fonctionnalité. Un refactoring me parait hors-scope de cette PR.

2021-01-14 14:46 UTC, Zekdar commented
Oui c'est pour ça que je l'ai mis en commentaire de PR et non en required change. 
C'était plus une réflexion en général, pour avoir ton avis.

2021-01-15 16:20 UTC, Zekdar approved these changes

2021-01-15 16:20 UTC, merged