💬 changement de wording
MTES-MCT/potentiel pull request #507
Opened 2022-07-04 10:00 UTC by HubM

* Date d'achèvement demandée -> Nouvelle date limite d'achèvement accordée
* mise en service -> achèvement

2022-07-04 10:02 UTC, HubM commented
L'[issue (](https://airtable.com/apphLwfLi4vad9EAq/tbl8Xmi9jiTVtLxVp/viwZ5cGuW9v5FJb7B/rec9w0JYnVjoxRRX9?blocks=hide) avait comme point : 
*- wording formulaire DREAL et Porteur: remplacer "mise en service" par "achèvement"*

J'ai modifié ce terme dans la frise projet (étape "MISE EN SERVICE"). Est-ce que c'était le bon endroit ?

2022-07-04 11:47 UTC, JulienPavon commented
> L'[issue](https://airtable.com/apphLwfLi4vad9EAq/tbl8Xmi9jiTVtLxVp/viwZ5cGuW9v5FJb7B/rec9w0JYnVjoxRRX9?blocks=hide) avait comme point : _- wording formulaire DREAL et Porteur: remplacer "mise en service" par "achèvement"_
> 
> J'ai modifié ce terme dans la frise projet (étape "MISE EN SERVICE"). Est-ce que c'était le bon endroit ?

Il faudrait voir avec Julie si cet intitulé doit être modifié

2022-07-04 11:49 UTC, JulienPavon commented on src/views/pages/modificationRequestPage/components/DelaiForm.tsx
>              name="dateAchèvementDemandée"
Ici on devrait renommer e name de l'input en `dateAchèvementAccordée` et modifier le controller en conséquence

2022-07-04 11:51 UTC, JulienPavon requested changes

2022-07-04 11:51 UTC, JulienPavon commented on src/views/pages/modificationRequestPage/components/DelaiForm.tsx
> +          <label htmlFor="dateAchèvementDemandée">Nouvelle date limite d'achèvement accordée</label>
Ici est ce que c'est nécessaire de mettre "Nouvelle" ? Je trouve qu'avec le terme "accordée" c'est assez explicite

2022-07-04 13:32 UTC, HubM commented on src/views/pages/modificationRequestPage/components/DelaiForm.tsx
> +          <label htmlFor="dateAchèvementDemandée">Nouvelle date limite d'achèvement accordée</label>
Oui tu as raison je vais retravailler ça

2022-07-04 14:16 UTC, HubM commented on src/views/pages/modificationRequestPage/components/DelaiForm.tsx
>              name="dateAchèvementDemandée"
Hum après avoir regardé je ne pense pas qu'il faille changer ni le wording, ni le nom de l'input. On est ici dans le cas du formulaire de demande de délai, donc par conséquent la date n'a pas encore été accordée ou refusée

2022-07-04 14:45 UTC, HubM commented
> Il faudrait voir avec Julie si cet intitulé doit être modifié

J'ai vu avec Julie et fait les modifications nécessaire pour la partie "mise en service" -> "achèvement"

2022-07-04 16:27 UTC, JulienPavon commented on src/views/pages/modificationRequestPage/components/DelaiForm.tsx
>              name="dateAchèvementDemandée"
Ça donnerai ça :
![image](https://user-images.githubusercontent.com/17512486/177192245-0666c835-0006-4a74-9fbd-1fb8aa0bd573.png)

2022-07-05 13:17 UTC, JulienPavon commented on src/views/components/timeline/components/MeSItem.tsx
> -        <ItemTitle title="Mise en service" />
Est ce vraiment cet intitulé que l'on souhaite modifier ? Ici il ne s'agit pas des demandes de délai

2022-07-05 13:48 UTC, HubM commented on src/views/components/timeline/components/MeSItem.tsx
> -        <ItemTitle title="Mise en service" />
J'ai demandé à Julie et en effet on veut aussi modifier à cet endroit

2022-07-05 13:57 UTC, JulienPavon commented
:+1:

2022-07-05 15:27 UTC, merged