Create centralized logger
MTES-MCT/potentiel pull request #55
Opened 2021-01-20 01:10 UTC by Zekdar

2021-01-20 10:18 UTC, paduc requested changes

2021-01-20 10:18 UTC, paduc commented on src/controllers/getModeleReponseRecours.ts
> +  logger.info('Call to getModeleReponseRecours received', request.query)
à retirer

2021-01-20 10:18 UTC, paduc commented on src/controllers/getProjectFile.ts
> +    logger.error(error)
C'est seulement une erreur à reporter en cas de problème infra. Les autres possibilités `FileNotFoundError` et `FileAccessDeniedError` sont des erreurs utilisateur. 
```
if(error instanceof InfraNotAvailableError){
  logger.error(error)
}
else{
  logger.warn(error.message)
}
```

2021-01-20 10:18 UTC, paduc commented on src/controllers/getSignupPage.ts
> +    logger.error(
`logger.warn`

2021-01-20 10:18 UTC, paduc commented on src/controllers/postCorrectProjectData.ts
> +      logger.error(e)
Déplacer après le bloc `if(e instance of ...)`

2021-01-20 10:18 UTC, paduc commented on src/controllers/postGarantiesFinancieres.ts
> +  logger.info('Call to postGarantiesFinancieres received', request.body, request.file)
retirer

2021-01-20 10:18 UTC, paduc commented on src/controllers/postGarantiesFinancieres.ts
> +  logger.info('postGarantiesFinancieres addGarantiesFinancieres returned')
retirer ainsi que le suivant

2021-01-20 10:18 UTC, paduc commented on src/controllers/postRequestModification.ts
> +    logger.error(new Error('Could not convert puissance to Number'))
Les erreurs de validation doivent être en `logger.info`. Idem pour les deux suivants de ce module.

2021-01-20 10:18 UTC, paduc commented on src/controllers/postRequestModification.ts
> +      logger.info(`redirecting to ${redirectRoute}`)
retirer

2021-01-20 10:18 UTC, paduc commented on src/dataAccess/db/user.ts
> +      logger.info('hasProject found all projects', allProjects)
retirer

2021-01-20 10:18 UTC, paduc commented on src/index.ts
> +    logger.error(new Error(`Missing ${variable} environment variable`))
idem que mon commentaire tout en haut: utiliser `console.error` ici parce qu'à mon avis, ça sera silencieux (`index.ts` se charge en tout premier)

2021-01-20 19:14 UTC, Zekdar commented on src/config/emails.config.ts
> +    )
Non je n'ai pas testé ce log. Par précaution j'ai remis un `console.error`

2021-01-22 16:07 UTC, paduc requested changes

2021-01-22 16:07 UTC, paduc commented on src/config/logger.config.ts
> +  Sentry.init({
Désactiver les `breadcrumbs`:

```ts
Sentry.init({
  // ...

  integrations: function(integrations) {
    // integrations will be all default integrations
    return integrations.filter(function(integration) {
      return integration.name !== "Breadcrumbs";
    });
  },
});
```

2021-01-22 16:22 UTC, paduc requested changes

2021-01-22 16:22 UTC, paduc commented on src/config/logger.config.ts
> +  logger.on('errorLog', (exception: Error) => {
`exception: Error | string`

Je pensais à un truc, en acceptant la version `string`, on perds l'information de la stack (ie. où ça a été appelé).
On peut laisser comme ça pour l'existant mais pour la suite, il faudrait seulement accepter des `Error` pour avoir la stack.

2021-01-25 08:58 UTC, paduc approved these changes

2021-01-25 09:08 UTC, merged