961 notification candidats restreinte au rôle validateur
MTES-MCT/potentiel pull request #564
Opened 2022-08-12 16:22 UTC by HanaeY

2022-08-17 14:51 UTC, flodlc commented on src/views/certificates/index.ts
> +      }
Pas sûr du tout mais est-ce que validateur et signataire ne devraientt pas s'appeler pareil ?
Et au niveau de la syntax il y a une raison de ne pas avoir ça:

```javascript
const signataire: Signataire = prévisualisation
    ? prévisualisationSignataire
    : validateur ?? {
        fullName: 'Ghislain Ferran',
        fonction: `L’adjoint au sous-directeur du système électrique et des énergies renouvelables`,
      }
```

2022-08-17 14:51 UTC, flodlc commented on src/views/certificates/index.ts
> +export type Signataire = { fullName: string; fonction: string | undefined }
ici est-ce qu'on peut avoir
``` typescript
fonction?: string
```
et du coup ne pas avoir à renseigner fonction: undefined quand on s'en sert ou c'est volontaire ?

2022-08-17 15:52 UTC, HanaeY commented on src/views/certificates/index.ts
> +      }
Ah je ne connais pas cette syntaxe, mais effectivement ça simplifie ! Pour le validateur et signataire, les deux n'ont pas exactement le même type.

2022-08-18 12:42 UTC, JulienPavon commented
Je trouve qu'il y a beaucoup de modifications pour l'ajout d'un nouveau rôle. 
Est ce que en ajoutant seulement le rôle à l'utilisateur (il aurait 2 rôles donc) ća n'aurait pas été suffisant et éviter d'ajouter le nouveau rôle partout où l'on avait 'admin' ?

2022-08-18 12:45 UTC, flodlc approved these changes

2022-08-18 12:45 UTC, flodlc commented on src/views/certificates/ppe2.v1/Certificate.tsx
> +  const { type, project, content, validateur: validateur } = props
shortcut possible sur le validateur

2022-08-18 12:45 UTC, flodlc commented on src/views/certificates/index.ts
> +  const { template, data, prévisualisation } = args
C'était déjà comme ça mais je me demande pourquoi ne pas déstructurer directement dans les params de fonctions pour plus de lisibilité. Clairement pas un truc à modifier maintenant par contre :)

2022-08-18 12:46 UTC, flodlc commented
Deux petites remarques mais rien de bloquant. Approved !

2022-08-18 14:02 UTC, JulienPavon requested changes

2022-08-18 14:02 UTC, JulienPavon commented on src/views/certificates/index.ts
> +  validateur?: Validateur
Rendre cette argument obligatoire et faire le choix du validateur dans les appelants ;)

2022-08-18 14:54 UTC, JulienPavon approved these changes

2022-08-18 14:54 UTC, JulienPavon commented on src/modules/project/useCases/generateCertificate.ts
> +            validateur: validateur
Raccourci ```validateur: validateur ?? validateurParDéfaut,```

2022-08-18 16:17 UTC, merged