1029 dgec peut annuler recours refusé
MTES-MCT/potentiel pull request #575
Opened 2022-08-22 15:23 UTC by HubM

2022-08-23 07:25 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onRejetRecoursAnnulé.integration.ts
> +import models from '../../../models'
import à supprimer

2022-08-24 07:47 UTC, HanaeY commented on src/modules/demandeModification/demandeRecours/annulerRejet/annulerRejetRecours.ts
> +          shouldUserAccessProject({ projectId: projectId.toString(), user })
A supprimer

2022-08-25 09:16 UTC, JulienPavon requested changes
Concernant l'agrégat DemandeDélai pourquoi traitons nous les anciens événements ? Le but du refactoring est de ne traiter que les nouveaux événements et non les anciens. Sinon il faut les migrer vers de nouveaux. À prévoir dans une carte car là nous n'allons pas dans la bonne direction et rajoutons une dépendance vers des événements que nous souhaitons supprimer à terme

2022-08-25 09:16 UTC, JulienPavon commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onRejetRecoursAnnulé.integration.ts
> +  describe(`Etant donné un événement RejetRecoursAnnulé émis`, () => {
Alors j'aurai plus vu le scénario écrit comme ceci :

Étant donné des événements de type "ModificationRequestRejected" et "ModificationRequestInstructionStarted" pour une demande de recours
Lorsqu'on émet un événement RejetRecoursAnnulé avec la même demande
Alors on ne devrait plus avoir les événements de type "ModificationRequestRejected" et "ModificationRequestInstructionStarted" dans les événements du projet concerné

2022-08-25 09:38 UTC, HubM commented on src/controllers/modificationRequest/postAnnulerRejetRecours.ts
> +    if (!validateUniqueId(modificationRequestId)) {
On peut mais la méthode `validateUniqueId` se base déjà sur yup pour effectuer la validation de l'id : 

```
import * as yup from 'yup'

const isUuid = yup.string().required().uuid()

export const validateUniqueId = (uniqueId: string): boolean => {
  return isUuid.isValidSync(uniqueId)
}
```

2022-08-25 15:35 UTC, HubM commented on src/controllers/modificationRequest/postAnnulerRejetRecours.ts
> +    if (!validateUniqueId(modificationRequestId)) {
vu avec Julien, on utilise yup pour valider le body de la request

2022-08-29 09:39 UTC, HanaeY approved these changes

2022-08-29 12:07 UTC, JulienPavon approved these changes

2022-08-29 12:11 UTC, merged