♻️ 1055: Passage en atomic design des boutons
MTES-MCT/potentiel pull request #582
Opened 2022-08-24 13:53 UTC by JulienPavon

2022-08-25 08:01 UTC, flodlc requested changes

2022-08-25 08:01 UTC, flodlc commented on src/views/components/UI/atoms/LinkButton.tsx
> +    style={{ color: '#ffffff' }}
Est-ce qu'on devrait pas omit `style` des props ou l'ajouter avec le style de la balise `a` comme dans `SecondaryLinkButton` ?

2022-08-25 08:09 UTC, HubM commented on src/views/components/UI/atoms/SecondaryLinkButton.tsx
> +  style,
Oui je vais le virer des props

2022-08-25 08:13 UTC, HanaeY commented on src/views/components/UI/atoms/Button.stories.tsx
>      type: { control: { type: 'radio' }, options: ['button', 'submit', 'reset'] },
Est-ce qu'on a besoin de garder le type ici comme il n'y a pas de changement visuel ?

2022-08-25 08:15 UTC, flodlc commented on src/views/components/UI/atoms/LinkButton.tsx
> +    style={{ color: '#ffffff' }}
En fait c'est bon, vu avec Hub

2022-08-25 08:27 UTC, HanaeY commented on src/views/components/UI/molecules/DownloadLink.tsx
> +    <FileDownloadIcon className="text-lg ml-1" />
Est-ce qu'il serait possible de centrer l'icone sur le texte (comme pour le DownloadLinkButton) ou de l'aligner sur la bas ?

2022-08-25 08:32 UTC, HanaeY commented on src/views/pages/signalerDemandeDelaiPage/SignalerDemandeDelai.tsx
>                <LinkButton href={routes.PROJECT_DETAILS(project.id)}>Annuler</LinkButton>
Pour le bouton "Annuler" je mettrais bien un bouton SecondartLinkButton plutôt (comme c'est le cas actuellement en prod)

2022-08-25 08:35 UTC, HanaeY commented on src/views/components/dropdowns/Dropdown.tsx
>            <ChevronDownIcon className="w-5 h-5 ml-1" />
Ici aussi les chevrons sont un peu hauts par rapport au lien

2022-08-25 08:38 UTC, JulienPavon commented on src/views/components/dropdowns/Dropdown.tsx
>            <ChevronDownIcon className="w-5 h-5 ml-1" />
Est ce qu'on ne ferai pas cette correction dans une autre PR car c'est déjà le cas en production ?

2022-08-25 08:45 UTC, HanaeY commented on src/views/components/dropdowns/Dropdown.tsx
>            <ChevronDownIcon className="w-5 h-5 ml-1" />
En production je vois les icones plus bas

2022-08-25 08:46 UTC, HanaeY commented on src/views/components/dropdowns/Dropdown.tsx
>            <ChevronDownIcon className="w-5 h-5 ml-1" />
Et je me demandais aussi pourquoi les DropDowns ne sont pas dans les molécules ?

2022-08-25 08:54 UTC, HanaeY commented on src/views/components/UI/atoms/Link.tsx
> +  </a>
Comme on a appliqué un bleu différent que le bleu de base d'un lien <a>, il faudrait essayer d'utiliser ce composant partout où on a un <a> pour harmoniser les couleurs. Par exemple dans la frise : DemandeDélaiItem (bouton voir le demande) et ModificationRequestItem (boutons voir la demande et voir le courrier de réponse)

2022-08-25 08:58 UTC, JulienPavon commented on src/views/components/dropdowns/Dropdown.tsx
>            <ChevronDownIcon className="w-5 h-5 ml-1" />
Tout simplement parceque ce composant a été fait avant le découpage atoms/molecules. D'ailleurs ce n'est pas une dropdown mais plutot un collapse/expand button

2022-08-25 08:59 UTC, JulienPavon commented on src/views/components/dropdowns/Dropdown.tsx
>            <ChevronDownIcon className="w-5 h-5 ml-1" />
> En production je vois les icones plus bas

Ah oui c'est vrai j'ai modifié cette partie car en production en mobile ça ne s'affichait pas correctement, on va regarder

2022-08-25 09:02 UTC, JulienPavon commented on src/views/components/UI/atoms/Link.tsx
> +  </a>
ok on regarde ça par contre on ne va pas remplacer tous les liens de l'application de suite. Peut être juste dans la frise dans un premier temps

2022-08-25 09:57 UTC, JulienPavon commented on src/views/components/UI/atoms/Link.tsx
> +    className={`inline-flex justify-start items-center text-blue-france-sun-base underline hover:text-blue-france-sun-base hover:underline focus:text-blue-france-sun-base focus:underline
Problème d'affichage en mobile
![image](https://user-images.githubusercontent.com/17512486/186635299-1ad1f8fa-4a1c-4cb2-997a-9057c8bb4799.png)

2022-08-25 10:02 UTC, JulienPavon commented on src/views/components/UI/atoms/Link.tsx
> +    className={`inline-flex justify-start items-center text-blue-france-sun-base underline hover:text-blue-france-sun-base hover:underline focus:text-blue-france-sun-base focus:underline
Peut être que je n'ai ciblée la bonne ligne de code :sweat_smile:

2022-08-25 14:16 UTC, HanaeY commented on src/views/components/dropdowns/Dropdown.tsx
>            <ChevronDownIcon className="w-5 h-5 ml-1" />
> Tout simplement parceque ce composant a été fait avant le découpage atoms/molecules. D'ailleurs ce n'est pas une dropdown mais plutot un collapse/expand button

OK, ok je pensais qu'il y aurait pu y avoir une autre raison, désolée. Mais du coup comme ce composant utilise des atomes on peut peut être juste le déplacer, juste une suggestion.

2022-08-25 15:56 UTC, HanaeY approved these changes

2022-08-29 07:51 UTC, flodlc approved these changes

2022-08-29 07:53 UTC, merged