✅ (1031): empecher aux autres role que admin/dgec-validateur/dreal de…
MTES-MCT/potentiel pull request #585
Opened 2022-08-30 12:54 UTC by HubM

… pouvoir accèder à la commande annulerRejetChangementDePuissance

2022-08-31 07:28 UTC, flodlc commented on src/views/pages/modificationRequestPage/components/DemandeStatus.tsx
> +        modificationRequestId: id,
On pourrait passer en français ici et du coup dans le Controller

2022-08-31 07:28 UTC, flodlc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onRejetChangementDePuissanceAnnulé.ts
> +        `Error: onRejetRecoursAnnulé n'a pas pu enregistrer la mise à jour de la demande ref ${demandeChangementDePuissanceId}.`
Ici on a deux logs pour une erreur. Avec Julien on a utilisé `ProjectionEnEchec` pour l'erreur pour être homogène le plus possible

2022-08-31 07:28 UTC, flodlc commented on src/infra/sequelize/projections/modificationRequest/updates/onRejetChangementDePuissanceAnnulé.ts
> +      logger.error(e)
Pareil ici, `ProjectionEnEchec` peut être utilisé pour logger l'erreur

2022-08-31 10:05 UTC, flodlc commented on src/modules/demandeModification/demandeChangementDePuissance/annulerRejet/annulerRejetChangementDePuissance.spec.ts
> +describe(`Commande annulerRejetChangementDePuissanceRecours`, () => {
Je crois que Recours est en trop

2022-08-31 10:05 UTC, flodlc commented on src/modules/notification/eventHandlers/demandeChangementDePuissance/onRejetChangementDePuissanceAnnulé.ts
> +            document_absent: hasDocument ? undefined : '', // injecting an empty string will prevent the default "with document" message to be injected in the email body
En fait ici on peut directement mettre document_absent à `false`

2022-08-31 12:22 UTC, JulienPavon requested changes

2022-08-31 12:22 UTC, JulienPavon commented on src/infra/sequelize/projectionsNext/projectEvents/updates/onRejetChangementDePuissanceAnnulé.integration.ts
> +        const preModificationRequestRejected = await ProjectEvent.findOne({
Est ce vraiment nécessaire de tester que les create ont bien fonctionné ? Avec tous ces `expect` on a du mal à voir ce que l'on teste vraiment

2022-08-31 12:22 UTC, JulienPavon commented on src/modules/notification/eventHandlers/demandeChangementDePuissance/onRejetChangementDePuissanceAnnulé.ts
> +              _sendUpdateNotification({
Il serait intéressant d'utiliser l'utilitaire `NotifierPorteurChangementStatutDemande` qui à été introduit pour les demandes d'abandon

2022-08-31 12:22 UTC, JulienPavon commented on src/views/pages/modificationRequestPage/components/DemandeStatus.tsx
> +    case 'puissance':
Peut être pas à faire dans cette PR mais il va à un moment falloir s'occupper d'avoir des pages dédiées à chaque type de demande et arrêter de faire grossir ce `switch` et la condition plus bas

2022-08-31 13:17 UTC, HubM commented on src/modules/notification/eventHandlers/demandeChangementDePuissance/onRejetChangementDePuissanceAnnulé.ts
> +              _sendUpdateNotification({
Yes bonne idée je vais attendre que Florian ait fini d'en faire un usecase

2022-08-31 13:17 UTC, HubM commented on src/views/pages/modificationRequestPage/components/DemandeStatus.tsx
> +    case 'puissance':
Carrément

2022-08-31 14:55 UTC, JulienPavon approved these changes
Comme je ne suis pas là pour le reste de la semaine j'approuve la PR afin de ne pas vous bloquer

2022-09-01 10:08 UTC, flodlc approved these changes

2022-09-01 10:10 UTC, merged