✨ (1027): ajout du usecase d'annulation d'un refus d'abandon
MTES-MCT/potentiel pull request #586
Opened 2022-08-30 13:19 UTC by flodlc

2022-08-31 12:30 UTC, JulienPavon reviewed
Il faudrait déplacer `makeNotifierPorteurChangementStatutDemande` qui est actuellement dans le repertoire `demandeAbandon` des eventsHandler de notification. Je pense que ceci serait un `usecase`

2022-08-31 13:07 UTC, flodlc commented
> 

Je le fais dans cette PR 👍

2022-08-31 13:48 UTC, HubM requested changes

2022-08-31 13:48 UTC, HubM commented on src/modules/demandeModification/demandeAbandon/annulerRejet/annulerRejetAbandon.spec.ts
> +        const shouldUserAccessProject = jest.fn(async () => true)
Si jamais l'annulation du rejet de demande d'abandon est une action réservée aux admin/dgec-validateur, alors tu peux enlever le `shouldUserAccessProject` car il se focus vraiment sur le rôle `dreal`

2022-08-31 13:48 UTC, HubM commented on src/modules/demandeModification/demandeAbandon/annulerRejet/annulerRejetAbandon.spec.ts
> +          shouldUserAccessProject,
à enlever

2022-08-31 13:48 UTC, HubM commented on src/modules/demandeModification/demandeAbandon/annulerRejet/annulerRejetAbandon.spec.ts
> +  })
Ce test est à enlever

2022-08-31 13:48 UTC, HubM commented on src/modules/demandeModification/demandeAbandon/annulerRejet/annulerRejetAbandon.spec.ts
> +      const shouldUserAccessProject = jest.fn(async () => true)
à virer

2022-08-31 13:48 UTC, HubM commented on src/modules/demandeModification/demandeAbandon/annulerRejet/annulerRejetAbandon.spec.ts
> +        shouldUserAccessProject,
à virer

2022-08-31 13:48 UTC, HubM commented on src/modules/demandeModification/demandeAbandon/annulerRejet/annulerRejetAbandon.spec.ts
> +      const shouldUserAccessProject = jest.fn(async () => true)
à virer

2022-08-31 13:48 UTC, HubM commented on src/modules/demandeModification/demandeAbandon/annulerRejet/annulerRejetAbandon.spec.ts
> +        shouldUserAccessProject,
à virer

2022-08-31 13:48 UTC, HubM commented on src/modules/demandeModification/demandeAbandon/annulerRejet/annulerRejetAbandon.ts
> +  ({ shouldUserAccessProject, demandeAbandonRepo, publishToEventStore }) =>
`shouldUserAccessProject` à enlever du use-case

2022-08-31 13:48 UTC, HubM commented on src/modules/demandeModification/demandeDélai/annulerRejet/annulerRejetDélai.spec.ts
> +import { StatutRéponseIncompatibleAvecAnnulationError } from '../../errors'
Pourquoi enlever l'appel à l'alias  `@modules` ?

2022-08-31 13:48 UTC, HubM commented on src/modules/demandeModification/demandeDélai/annulerRejet/annulerRejetDélai.ts
> +import { StatutRéponseIncompatibleAvecAnnulationError } from '../../errors'
same

2022-08-31 13:48 UTC, HubM commented on src/modules/demandeModification/demandeRecours/annulerRejet/annulerRejetRecours.spec.ts
> +import { StatutRéponseIncompatibleAvecAnnulationError } from '../../errors'
same

2022-08-31 13:48 UTC, HubM commented on src/modules/demandeModification/demandeRecours/annulerRejet/annulerRejetRecours.ts
> +import { StatutRéponseIncompatibleAvecAnnulationError } from '../../errors'
same

2022-08-31 14:11 UTC, HanaeY commented on src/modules/notification/eventHandlers/demandeAbandon/onRejetAbandonAnnulé.spec.ts
> +  describe(`Notifier les porteurs ayant accès au projet`, () => {
En réalité la requête getModificationRequestInfoForStatusNotification ne retourne que les info de la personne qui a demandé l'abandon. Donc dans le test le tableau de porteur qu'elle retourne ne devrait contenir qu'un seul porteur.

2022-08-31 14:24 UTC, flodlc commented on src/modules/notification/eventHandlers/demandeAbandon/onRejetAbandonAnnulé.spec.ts
> +  describe(`Notifier les porteurs ayant accès au projet`, () => {
Est-ce qu'on devrait pas modifier cette requête pour qu'elle retourne tous les porteurs du projet dans ce cas ?

2022-08-31 15:54 UTC, HanaeY approved these changes

2022-09-01 07:55 UTC, HubM approved these changes

2022-09-01 07:56 UTC, merged