290 invitation automatique nouveau producteur
MTES-MCT/potentiel pull request #590
Opened 2022-08-31 11:12 UTC by HanaeY

Rafacto :
-  extraction vue et contrôleur pour les changements de producteur
-  choix du CDC dans une commande à part

2022-08-31 13:57 UTC, flodlc commented on src/controllers/modificationRequest/changementProducteur/postChangerProducteur.ts
> +        return okAsync({ fichier: undefined, producteur, email, justification, user, projetId })
C'est normal de mettre fichier à undefined dans ce cas ?

2022-08-31 13:57 UTC, flodlc commented on src/controllers/modificationRequest/changementProducteur/postChangerProducteur.ts
> +          ...(fichier && fichier),
Ici je crois qu'il manque des accolades autour de fichier `...(fichier && { fichier }),`

2022-08-31 14:24 UTC, HanaeY commented on src/controllers/modificationRequest/changementProducteur/postChangerProducteur.ts
> +        return okAsync({ fichier: undefined, producteur, email, justification, user, projetId })
Non c'est une erreur je l'ai corrigée !

2022-09-01 08:02 UTC, HubM commented on src/controllers/modificationRequest/changementProducteur/postChangerProducteur.ts
> +          }).map(() => ({ fichier, producteur, email, justification, user, projetId }))
tu devrais pas faire un `try / catch` ici ?

2022-09-01 08:02 UTC, HubM commented on src/controllers/modificationRequest/changementProducteur/postChangerProducteur.ts
> +          }).map(() => projetId)
tu devrais pas faire un `try / catch` ici ?

2022-09-01 08:09 UTC, HubM requested changes

2022-09-01 08:09 UTC, HubM commented on src/modules/project/errors/PasDeChangementDeCDCPourCetAOError.ts
> +    super(`Vous ne pouvez pas changer de cahier des charges pour cet appel d'offres.`)
typo : pour cet appel d'offre

2022-09-01 08:09 UTC, HubM commented on src/modules/project/useCases/choisirNouveauCahierDesCharges.spec.ts
> +      it(`Lorsqu'il souscrit une seconde dois au nouveau CDC,
typo : une seconde fois

2022-09-01 08:35 UTC, HanaeY commented on src/controllers/modificationRequest/changementProducteur/postChangerProducteur.ts
> +          }).map(() => ({ fichier, producteur, email, justification, user, projetId }))
Pourquoi ? J'ai testé et les erreurs sont bien récupérées dans le .match plus bas

2022-09-01 08:42 UTC, HanaeY commented on src/modules/project/errors/PasDeChangementDeCDCPourCetAOError.ts
> +    super(`Vous ne pouvez pas changer de cahier des charges pour cet appel d'offres.`)
Il y a bien un "s" à appel d'offres il me semble

2022-09-01 08:55 UTC, HubM commented on src/modules/project/errors/PasDeChangementDeCDCPourCetAOError.ts
> +    super(`Vous ne pouvez pas changer de cahier des charges pour cet appel d'offres.`)
Ah oui tu as raison

2022-09-01 08:56 UTC, HubM approved these changes
👍🏼

2022-09-01 12:58 UTC, closed without merging