1006 Message durée couverture GF selon AO
MTES-MCT/potentiel pull request #599
Opened 2022-09-02 14:26 UTC by HanaeY

Dans la frise, dans les formulaires d'ajout des GF et d'ajout de la date d'échéance, appliquer la bonne durée de couverture de GF en fonction de l'AO.

2022-09-05 08:52 UTC, HubM approved these changes
:+1:

2022-09-05 09:21 UTC, JulienPavon requested changes

2022-09-05 09:21 UTC, JulienPavon commented on src/entities/appelOffre.ts
> +  garantieFinanciereEnMois?: number
Peut être qu'ici on pourrait avoir un type conditionné à la valeur de `soumisAuxGarantiesFinancieres`. Et voir le type de cette propriété. Avoir un booléen optionnel  nous force à gérer 3 cas. On peut avoir un booléen obligatoire (gérer les 2 cas métier soumis ou non), ou bien le laisser optionnel mais avec comme type `true`

2022-09-06 09:22 UTC, JulienPavon approved these changes

2022-09-06 09:25 UTC, merged