♻️ (1095): Migration des événements ProjectNewRulesOptedIn
MTES-MCT/potentiel pull request #606
Opened 2022-09-06 15:23 UTC by JulienPavon

2022-09-12 14:55 UTC, HubM approved these changes
:+1:

2022-09-12 16:51 UTC, HanaeY requested changes

2022-09-12 16:51 UTC, HanaeY commented on src/modules/project/useCases/choisirNouveauCahierDesCharges.ts
> +              projetId: projetId,
On peut simplifier avec juste 'projetId"

2022-09-12 16:51 UTC, HanaeY commented on src/infra/sequelize/projections/project/updates/onProjectNewRulesOptedIn.ts
> +export const onProjectNewRulesOptedIn =
"onNouveauCahierDesChargesChoisi"

2022-09-12 16:51 UTC, HanaeY commented on src/modules/notification/eventHandlers/handleNewRulesOptedIn.ts
>  export const handleNewRulesOptedIn =
"onNouveauCahierDesChargesChoisi"

2022-09-12 16:51 UTC, HanaeY commented on src/infra/sequelize/projections/project/updates/onProjectNewRulesOptedIn.ts
> +    projectInstance.newRulesOptIn = true
Est-ce qu'on renommerait pas la colonne dans la projection ?

2022-09-13 09:15 UTC, JulienPavon commented on src/infra/sequelize/projections/project/updates/onProjectNewRulesOptedIn.ts
> +    projectInstance.newRulesOptIn = true
Si on fait le changement maintenant est ce que cette colonne s'appellerai `nouvellesRèglesDInstructionChoisie` ?

2022-09-13 10:10 UTC, HanaeY approved these changes
nom fichier postUpdateNewRulesOptIn à passer en français, sinon tout est ok !

2022-09-13 12:28 UTC, merged