1054 fix changement fournisseur erreur
MTES-MCT/potentiel pull request #615
Opened 2022-09-09 15:25 UTC by HanaeY

2022-09-12 11:40 UTC, flodlc approved these changes

2022-09-12 12:52 UTC, JulienPavon commented on src/controllers/modificationRequest/fournisseur/postChangerFournisseur.ts
> +          return errAsync(new ChampFournisseurManquantError())
Est ce qu'on ne pourrait pas utiliser la fonction `test` de yup afin de faire le check directement dans le schema de validation ?

2022-09-12 12:53 UTC, JulienPavon commented on src/controllers/modificationRequest/fournisseur/postChangerFournisseur.ts
> +})
Ici on pourrait utiliser une fonction `test` pour tester globalement le body après une première validation

2022-09-13 10:07 UTC, flodlc requested changes

2022-09-13 10:07 UTC, flodlc commented on src/controllers/modificationRequest/fournisseur/postChangerFournisseur.ts
> +      }
Je crois qu'ici il va manquer un match avec une response

2022-09-13 13:16 UTC, JulienPavon requested changes

2022-09-13 13:16 UTC, JulienPavon commented on src/modules/project/types/fournisseur.ts
> +    'Fournisseur modules ou films',
C'est dommage d'avoir de la duplication. On pourrait avoir ce genre de chose :
```
const CHAMPS_FOURNISSEURS: ReadonlyArray<string> = [
  'Fournisseur modules ou films',
  'Fournisseur cellules',
  'Fournisseur plaquettes de silicium (wafers)',
  'Fournisseur polysilicium',
  'Fournisseur postes de conversion',
  'Fournisseur structure',
  'Fournisseur dispositifs de stockage de l’énergie',
  'Fournisseur dispositifs de suivi de la course du soleil',
  'Fournisseur autres technologies',
]

export type FournisseurKind = typeof CHAMPS_FOURNISSEURS[number]

export const isFournisseurKind = (value: string): value is FournisseurKind => {
  return CHAMPS_FOURNISSEURS.includes(value)
}
```

2022-09-13 13:16 UTC, JulienPavon commented on src/controllers/modificationRequest/fournisseur/postChangerFournisseur.ts
> +      'Fournisseur modules ou films': yup.string().optional(),
Je me demande si on ne pourrait pas générer dynamiquement les règles sur les fournisseurs depuis le tableau déclaré dans `fournisseurs.ts`

2022-09-13 13:16 UTC, JulienPavon commented on src/controllers/modificationRequest/fournisseur/postChangerFournisseur.ts
> +          !!fields['Fournisseur modules ou films'] ||
Idem peut être qu'on pourrait faire le check en s'appuyany sur le tableau des fournisseurs

2022-09-13 13:16 UTC, JulienPavon commented on src/views/pages/changerFournisseurPage/ChangerFournisseur.tsx
> +                      defaultValue={project.details?.['Nom du fabricant \n(Modules ou films)']}
Est ce qu'on n'aurai pas intérêt d'utiliser les tableaux des fournisseurs pour générer tous ces inputs et ainsi éviter d'avoir à dupliquer systématiquement les libellés, name et id ?

2022-09-13 13:16 UTC, JulienPavon commented on src/modules/notification/eventHandlers/modificationRequests/handleModificationReceived.spec.ts
> +                { kind: 'Fournisseur cellules' as FournisseurKind, name: 'fournisseur' },
`as FournisseurKind` inutile ici

2022-09-13 13:16 UTC, JulienPavon commented on src/modules/modificationRequest/useCases/requestFournisseursModification.spec.ts
> +        kind: 'Fournisseur modules ou films' as FournisseurKind,
Il vaudrait mieux typer la constante `newFournisseurs` plutôt que d'utiliser `as FournisseurKind`

2022-09-14 09:15 UTC, JulienPavon commented on src/modules/project/types/fournisseur.ts
> +export const CHAMPS_FOURNISSEURS: ReadonlyArray<string> = [
On devrait pouvoir récupérer cette liste depuis le dictionnaire de correspondance 
```
export const CHAMPS_FOURNISSEURS: ReadonlyArray<string> = Object.keys(
  CORRESPONDANCE_CHAMPS_FOURNISSEURS_COLONNE_IMPORT
)

export type FournisseurKind = keyof typeof CORRESPONDANCE_CHAMPS_FOURNISSEURS_COLONNE_IMPORT
```

2022-09-14 09:35 UTC, JulienPavon approved these changes

2022-09-14 09:36 UTC, JulienPavon commented
:+1:

2022-09-14 09:55 UTC, flodlc approved these changes

2022-09-14 10:07 UTC, merged