🎨 (1111): afficher tt les cdc, et les rendre disable si on ne peut pas les changer
MTES-MCT/potentiel pull request #617
Opened 2022-09-12 13:41 UTC by HubM

2022-09-12 15:27 UTC, flodlc requested changes

2022-09-12 15:34 UTC, HubM commented on src/views/pages/choisirCahierDesChargesPage/ChoisirCahierDesCharges.tsx
>                        disabled={newRulesOptIn}
Actuellement c'était comme ça, mais sur le dsfr c'est présenté que les radios peuvent etre affiché disabled

2022-09-13 08:01 UTC, HanaeY requested changes

2022-09-13 13:10 UTC, HanaeY approved these changes
:+1:

2022-09-13 13:11 UTC, flodlc approved these changes

2022-09-13 13:18 UTC, merged