342 Send email to PP when modification is requested
MTES-MCT/potentiel pull request #62
Opened 2021-01-21 17:25 UTC by paduc

2021-01-24 21:25 UTC, Zekdar requested changes

2021-01-24 21:25 UTC, Zekdar commented on src/modules/notification/eventHandlers/handleModificationRequested.spec.ts
> +        (notification) =>
Déstructurer `{ type, message, variables }`

2021-01-24 21:25 UTC, Zekdar commented on src/modules/notification/eventHandlers/handleModificationRequested.ts
> +    (e: any) => {
Typer en `Error`

2021-01-27 09:32 UTC, paduc commented on src/modules/notification/eventHandlers/handleModificationRequested.spec.ts
> +        (notification) =>
Il y a un inconvénient à déstructurer, c'est que tu perds les informations de type sur `notification`. Comme il y a plusieurs variantes de `notification` qui ont des formes de `variables` qui sont différentes, le compilateur ne peut plus utiliser l'assertion `type === 'modification-request-status-update'` pour déterminer quelle variante de `notification` et ainsi le forme de `variables`.

Si je déstructure, je suis obligé de faire ça:
```ts
type === 'modification-request-status-update' &&
message.email === 'email@test.test' &&
message.name === 'john doe' &&
(variables as any).status === 'envoyée' &&
(variables as any).nom_projet === 'nomProjet' &&
(variables as any).type_demande === 'recours' &&
(variables as any).document_absent === ''
```

Si je ne mets pas  `variables as any` il me fait une erreur du genre `Property status does not exist on type...`.

Tu préfères quoi ? Destructurer + `as any` ou bien comme c'est ci-dessus ?

2021-01-27 15:39 UTC, Zekdar commented on src/modules/notification/eventHandlers/handleModificationRequested.spec.ts
> +        (notification) =>
Si on peut pas typer la notif, autant mettre l'ancienne forme car ça me plaît moyennement le `as any`

2021-01-28 15:53 UTC, Zekdar approved these changes

2021-01-28 16:06 UTC, merged