✨ (1091): Choisir le cahier des charges 2022
MTES-MCT/potentiel pull request #632
Opened 2022-09-19 14:13 UTC by JulienPavon

2022-09-21 14:38 UTC, flodlc commented on src/controllers/project/postChoisirNouveauCahierDesCharges.ts
> +      }
Est-ce que c'est possible de se retrouver sans `choixCahierDesCharges` avec la validation yup ?

2022-09-21 14:38 UTC, flodlc commented on src/modules/project/useCases/choisirNouveauCahierDesCharges.ts
> +          )
Pour être plus safe peut-être ?
```
!appelOffre || !appelOffre.cahiersDesChargesModifiésDisponibles.find(
            (c) => c.paruLe === paruLe && c.alternatif === alternatif
          )
```

2022-09-21 15:04 UTC, HanaeY requested changes
- Dans le mail de notification envoyé au porteur, ça pourrait être intéressant d'ajouter le cdc choisi via les variables. 
- Rebaser sur master pour tester tout le parcours jusqu'à l'affichage dans la frise, et il faudra ajouter le cas "alternatif" dans le handler de project_events et getProjectEvents...

2022-09-21 15:48 UTC, JulienPavon commented on src/controllers/project/postChoisirNouveauCahierDesCharges.ts
> +      }
Au niveau des types on essayé plusieurs choses mais rien à faire yup nous retourne `ChoixCahierDesCharges | undefined` alors que nous avons bien spécifié `required()`

2022-09-21 15:49 UTC, JulienPavon commented
> * Dans le mail de notification envoyé au porteur, ça pourrait être intéressant d'ajouter le cdc choisi via les variables.

Est ce que nous ne pourrions pas voir ceci dans une PR séparée ?

2022-09-21 16:01 UTC, JulienPavon commented on src/modules/project/events/NouveauCahierDesChargesChoisi.ts
>  export class NouveauCahierDesChargesChoisi
Je pense que nous pouvons rester en v1 car ici nous ne cassons pas la compatibilité avec la version précédente. De plus je ne crois que nous trations les versions des évènements dans potentiel

2022-09-21 16:12 UTC, JulienPavon commented on src/modules/project/useCases/choisirNouveauCahierDesCharges.ts
> +          )
Oui effectivement je n'avais pas vu. Bien joué. Tant que les types nous disent que l'AO peut être undefined je pense qu'il prévoir le cas. Je rajoute un cas dans les tests

2022-09-21 16:20 UTC, HanaeY commented on src/views/components/ChoisirCahierDesChargesFormulaire.tsx
![image](https://user-images.githubusercontent.com/72154904/191558107-9caaab24-29e5-4016-8be2-fb6b2f2a0a3d.png)

2022-09-21 16:26 UTC, JulienPavon commented on src/modules/project/useCases/choisirNouveauCahierDesCharges.ts
> +          )
J'ai fait en sorte de retourner une erreur `EntityNotFoundError` si l'AO n'existe pas

2022-09-21 16:27 UTC, JulienPavon commented on src/views/components/ChoisirCahierDesChargesFormulaire.tsx
Oui entièrement d'accord. Je vais poser la question

2022-09-22 07:34 UTC, JulienPavon commented on src/controllers/project/postChoisirNouveauCahierDesCharges.ts
> +      }
Finalement c'est bon !

2022-09-22 09:13 UTC, HanaeY approved these changes
:+1:

2022-09-22 09:14 UTC, flodlc approved these changes

2022-09-22 09:16 UTC, merged