✨ (1109):  afficher un cahier des charges dans les pages
MTES-MCT/potentiel pull request #639
Opened 2022-09-22 15:31 UTC by flodlc

de demande

2022-09-29 13:29 UTC, JulienPavon commented on src/modules/demandeModification/demandeAbandon/demander/demanderAbandon.ts
> +              cahierDesCharges: formatCahierDesChargesRéférence(project.cahierDesCharges),
Il faudrait rajouter ou modifier un scénario de test qui couvre cette modification

2022-09-29 13:29 UTC, JulienPavon commented on src/modules/demandeModification/demandeDélai/demander/demanderDelai.ts
> +              cahierDesCharges: formatCahierDesChargesRéférence(project.cahierDesCharges),
Il faudrait rajouter ou modifier un scénario de test qui couvre cette modification

2022-09-29 13:30 UTC, JulienPavon commented on src/modules/modificationRequest/useCases/requestActionnaireModification.ts
> +                  cahierDesCharges: formatCahierDesChargesRéférence(project.cahierDesCharges),
Il faudrait rajouter ou modifier un scénario de test qui couvre cette modification

2022-09-29 13:30 UTC, JulienPavon commented on src/modules/modificationRequest/useCases/requestActionnaireModification.ts
> +                cahierDesCharges: formatCahierDesChargesRéférence(project.cahierDesCharges),
Il faudrait rajouter ou modifier un scénario de test qui couvre cette modification

2022-09-29 13:32 UTC, JulienPavon commented on src/views/pages/modificationRequestPage/components/DemandeDetails.tsx
> +      {cahierDesCharges && (
Est ce qu'on aurait pas un composant pour l'affichage d'un cahier des charges ? (peut être sont ils différents)

2022-09-29 13:36 UTC, flodlc commented on src/views/pages/modificationRequestPage/components/DemandeDetails.tsx
> +      {cahierDesCharges && (
Je me suis posé la question. Et puis je me suis dit que le wording pourrait être différent selon les pages.

2022-09-29 14:21 UTC, flodlc commented
Pour les tests des usecases, j'ai ajouté la vérification de la valeur du cahierDesCharges dans l'event lorsqu'il est émis.

2022-09-29 14:23 UTC, HanaeY requested changes

2022-09-29 14:23 UTC, HanaeY commented on src/infra/sequelize/queries/modificationRequest/getModificationRequestDetails.ts
> +  }
Ici il va manquer la propriété 'alternatif'

2022-09-29 14:23 UTC, HanaeY commented on src/infra/sequelize/queries/modificationRequest/getModificationRequestDetails.ts
> +          : undefined,
Dans quel cas on pourrait ne pas avoir de cahier des charges ?

2022-09-29 14:23 UTC, HanaeY commented on src/views/pages/modificationRequestPage/components/DemandeDetails.tsx
> +            : `modifié rétroactivement et publié le ${cahierDesCharges.paruLe}`}{' '}
il manque le cas 'alernatif' ici

2022-09-29 14:37 UTC, flodlc commented on src/views/pages/modificationRequestPage/components/DemandeDetails.tsx
> +            : `modifié rétroactivement et publié le ${cahierDesCharges.paruLe}`}{' '}
Ce serait quel wording dans le cas du cdc alternatif ?
J'avoue que j'ai repris le type et wordding de `src/views/pages/projectDetailsPage/ProjectDetails.tsx` mais il manque peut-être quelque chose aussi dans cette page

2022-09-29 15:17 UTC, HanaeY approved these changes

2022-09-30 06:51 UTC, JulienPavon approved these changes
👍

2022-09-30 08:02 UTC, merged