♻️ (UI): Ajout de l'atom RichRadio conforme au DSFR
MTES-MCT/potentiel pull request #645
Opened 2022-09-27 14:52 UTC by JulienPavon

2022-09-27 15:06 UTC, flodlc commented on src/views/components/UI/atoms/RichRadio.tsx
> +type RichRadioProps = Exclude<ComponentProps<'input'>, 'type'> & { id: string }
Petit doute sur le Exclude, pas testé mais il me semble que le Exclude est pour les Unions et le Omit pour enlever des props d'un type Objet

2022-09-27 15:08 UTC, flodlc commented on src/views/components/UI/atoms/RichRadio.tsx
> +type RichRadioProps = Exclude<ComponentProps<'input'>, 'type'> & { id: string }
Je viens d'essayer et en effet Typescript garde `type` dans `RichRadioProps`. A remplacer par Exclude du coup

2022-09-27 15:58 UTC, HubM requested changes

2022-09-27 15:58 UTC, HubM commented on src/views/components/UI/atoms/RichRadio.tsx
> +      {...{
L'icone du radio est pas complètement centré, j'ai investigué avec tailwind en utilisant la classe `-translate-y-1/2` mais je comprends pas pq ça ne fonctionne pas...

Du coup si tu veux quick-win tu peux rajouter un style inline `style={{ transform: 'translateY(-50%)' }}`

2022-09-28 07:20 UTC, JulienPavon commented on src/views/components/UI/atoms/RichRadio.tsx
> +type RichRadioProps = Exclude<ComponentProps<'input'>, 'type'> & { id: string }
Ah oui je m'était dit qu'il fallait que je revois cette parti merci

2022-09-29 07:23 UTC, flodlc approved these changes

2022-09-29 08:23 UTC, HanaeY approved these changes

2022-09-29 12:10 UTC, HubM approved these changes
👍🏼

2022-09-29 12:11 UTC, merged