✨ 1148 accepter le choix du cdc initial si l'AO le permet
MTES-MCT/potentiel pull request #647
Opened 2022-09-28 12:34 UTC by HubM

2022-09-28 13:09 UTC, HanaeY requested changes
Pour ce qui est de la notification du porteur qui change de CDC, il faut soit adapter le template mailjet actuel, soit créer un nouveau template. 
En l'état on aura cette phrase : "Vous avez choisi les modalités d'instruction selon le cahier de charges modifié rétroactivement et publié le initial."
Le template actuel est ici : https://app.mailjet.com/template/10354099/version-history
Je serais plutôt d'avis de créer un nouveau template dédié comme presque tout le texte est à changer.

2022-09-28 13:10 UTC, HanaeY commented on src/entities/cahierDesCharges.ts
> +  paruLe: DateParutionCahierDesCharges
Et il faut aussi changer l'affichage dans la frise car le composant s'attendait à recevoir une date. Actuellement on a "CHOIX DU CAHIER DES CHARGES MODIFIÉ PARU LE INITIAL"

2022-09-30 12:34 UTC, HanaeY commented on src/modules/project/events/NouveauCahierDesChargesChoisi.ts
> -  paruLe: '30/07/2021' | '30/08/2022'
On peut supprimer cet événement ?

2022-09-30 12:37 UTC, HanaeY commented on src/infra/sequelize/projections/project/updates/onCahierDesChargesChoisi.ts
>              nomProjection: 'onNouveauCahierDesChargesChoisi',
onCahierDesChargesChoisi

2022-09-30 12:38 UTC, HanaeY commented on src/modules/project/events/index.ts
> +export * from './NouveauCahierDesChargesChoisi'
A supprimer ?

2022-09-30 12:55 UTC, HubM commented on src/infra/sequelize/projections/project/updates/onCahierDesChargesChoisi.ts
>              nomProjection: 'onNouveauCahierDesChargesChoisi',
Je comprends pas ?

2022-09-30 13:47 UTC, JulienPavon requested changes

2022-09-30 13:47 UTC, JulienPavon commented on src/views/components/UI/organisms/choisirCahierDesCharges/ChoisirCahierDesChargesFormulaire.tsx
> +            type: 'modifié',
Est ce qu'on ne devrait pas avoir cette info directement dans `cahiersDesChargesModifiésDisponibles` ?

2022-09-30 13:47 UTC, JulienPavon commented on src/modules/project/useCases/choisirCahierDesCharges.spec.ts
> +      expect(res._unsafeUnwrapErr()).toBeInstanceOf(CahierDesChargesNonDisponibleError)
Est ce qu'on aurait pas une autre erreur ici ? "Impossible de revenir au cahier de charges en vigueur à la candidature"

2022-09-30 13:49 UTC, HubM commented on src/views/components/UI/organisms/choisirCahierDesCharges/ChoisirCahierDesChargesFormulaire.tsx
> +            type: 'modifié',
On s'était posé la question, on voulait pas forcément le faire directement dans cette PRs car ça nécessite de repasser sur tt les AOs, mais ptet que c'est plus propre

2022-09-30 14:35 UTC, JulienPavon approved these changes
👍

2022-09-30 14:41 UTC, HanaeY approved these changes

2022-09-30 14:42 UTC, merged