💄 (UI): Passage du menu dans l'entête
MTES-MCT/potentiel pull request #656
Opened 2022-10-03 11:51 UTC by JulienPavon

2022-10-05 13:43 UTC, HubM commented on src/views/pages/AdemeStatistiquesPage.tsx
> +    // <PartnerDashboard currentPage="ademe-statistiques" role="ademe">
Commentaire à enlever

2022-10-05 13:43 UTC, HubM commented on src/views/pages/AdemeStatistiquesPage.tsx
>  /* Pure component */
commentaire inutile?

2022-10-05 13:43 UTC, HubM commented on src/views/pages/ImporterListingEDFPage.tsx
> +    // <PartnerDashboard role={role} currentPage={'upload-edf'}>
ici aussi

2022-10-05 13:44 UTC, HubM commented on src/views/pages/changerFournisseurPage/ChangerFournisseur.tsx
> +              {CHAMPS_FOURNISSEURS.map((champ) => {
je suis plutot d'accord avec Github pour le coup, tu pourrais faire une variable avant le return. genre `const name = champ.replace('\n', '\\n'`

2022-10-05 13:45 UTC, HubM commented on src/views/pages/changerFournisseurPage/ChangerFournisseur.tsx
> +                  <h3 style={{ marginTop: 15, marginBottom: 3 }}>évaluation carbone</h3>
style inline obligatoire?

2022-10-05 13:48 UTC, HanaeY commented on src/views/components/AdminDashboard.tsx
> +              visibleForRoles={['admin', 'dgec-validateur']}
On peut extraire ce tableau `['admin', 'dgec-validateur']` dans une constante pour l'appliquer à chaque item du menu

2022-10-05 13:48 UTC, HanaeY commented on src/views/components/RoleBasedDashboard.tsx
>    if (['admin', 'dgec-validateur', 'dreal'].includes(role)) {
on ne peut pas retirer `'dreal'` du if ici ?

2022-10-05 14:09 UTC, HanaeY commented on src/views/components/AdminDashboard.tsx
Dans l'interface AdminDashboardProps, on peut utiliser le type CurrentPage présent dans la fichier PageLayout.tsx

2022-10-05 14:31 UTC, flodlc commented on src/views/components/AdminDashboard.tsx
> +              visibleForRoles={['admin', 'dgec-validateur']}
On a des menus qui ne sont pas toujours identiques pour les admin et les dgec-validateur.
Pour la page `Importer des courriers historiques` par exemple, seul les admin voient le menu

2022-10-05 14:32 UTC, flodlc commented on src/views/components/AdminDashboard.tsx
> +              visibleForRoles={['admin', 'dgec-validateur']}
Je trouve pas que ce soit plus clair, là on voit la liste des roles qui changera peut-être à l'avenir selon les menus

2022-10-05 14:35 UTC, flodlc commented on src/views/components/AdminDashboard.tsx
En fait ce sont deux types différents, j'ai réduit celui de PageLayout à ce qui est nécessaire.

2022-10-05 15:26 UTC, flodlc commented on src/views/pages/changerFournisseurPage/ChangerFournisseur.tsx
> +                  <h3 style={{ marginTop: 15, marginBottom: 3 }}>évaluation carbone</h3>
Dans ce cas la classe mt-4 de tailwind est écrasée par du style de main.min.css.
A rediscuter

2022-10-05 15:34 UTC, HanaeY commented on src/views/pages/AdemeStatistiquesPage.tsx
> +    <PageTemplate user={request.user}>
il manque le currentPage ici

2022-10-05 15:41 UTC, flodlc commented on src/views/pages/AdemeStatistiquesPage.tsx
> +    <PageTemplate user={request.user}>
On souhaiterais afficher quel menu en surbriullance ici ?

2022-10-05 15:42 UTC, flodlc commented on src/views/pages/AdemeStatistiquesPage.tsx
> +    <PageTemplate user={request.user}>
J'ai pas mis le currentPage pour n'activer aucun menu

2022-10-05 15:56 UTC, HanaeY commented
Le bleu n'est pas le bon pour le texte du lien actif dans le menu : 

proposition : 

  <li className="py-2 px-4 border-0 border-b lg:border-b-0 border-solid border-slate-200 lg:p-4">
    <a
      className={`no-underline pl-4 lg:pl-0 lg:pb-3  ${
        isCurrent &&
        'font-medium border-0 border-l-4 border-solid border-blue-france-sun-base lg:border-l-0 lg:border-b-4'
      }`}
      href={href}
      {...(isCurrent
        ? { 'aria-current': 'page', style: { color: '#000091' } }
        : { style: { color: 'black' } })}
    >
      {children}
    </a>
  </li>

2022-10-05 16:15 UTC, HanaeY approved these changes

2022-10-06 10:22 UTC, HanaeY requested changes

2022-10-06 10:22 UTC, HanaeY commented on src/views/components/Header.tsx
> -          ? 'text-blue-france-sun-base font-medium border-0 border-l-4 border-solid border-blue-france-sun-base lg:border-l-0 lg:border-b-4'
J'ai revérifié le dsfr suite aux retours de Julie, et peut être que notre border du bas est un peu épaisse, si 2 c'est trop petit, on peut mettre une valeur en px 
https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/navigation-principale#

2022-10-06 10:22 UTC, HanaeY commented on src/views/components/Header.tsx
>      <a
il faudrait ajouter une couleur #f6f6f6 de background au survol (voir ici : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/navigation-principale#)

2022-10-06 14:57 UTC, HanaeY approved these changes

2022-10-06 16:21 UTC, HubM approved these changes
👍🏼

2022-10-07 06:50 UTC, merged