179 Users should see the requests for their respective scopes
MTES-MCT/potentiel pull request #66
Opened 2021-01-22 17:16 UTC by paduc

2021-01-25 08:32 UTC, paduc commented on src/infra/sequelize/queries/getModificationRequestListForUser.ts
> +    return okAsync<any, InfraNotAvailableError>([])
Ce n'est pas une erreur qui est retournée ici mais un `okAsync` avec un array vide.
J'ai spécifié les types de mon `okAsync` pour que la méthode `_getDrealRegionsForUser` ait le bon type de retour.

2021-01-25 08:35 UTC, paduc commented on src/infra/sequelize/queries/getModificationRequestListForUser.ts
> +  ).map((items: any) => items.map((item) => item.dreal))
La raison pour laquelle j'ai tendance à utiliser `items` est que ce ne sont pas des instances de `dreal` mais plutôt des objets sequelize intermédiaires (issus de la table de liaison `UserDreal`).

2021-01-25 14:43 UTC, Zekdar approved these changes

2021-07-02 11:33 UTC, Zekdar requested changes

2021-07-02 12:54 UTC, Zekdar approved these changes

2021-07-02 13:31 UTC, merged