✨ (1157): ajout de GF par un admin
MTES-MCT/potentiel pull request #660
Opened 2022-10-06 12:59 UTC by flodlc

2022-10-12 09:35 UTC, HubM requested changes

2022-10-12 09:35 UTC, HubM commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +                        uploadedByRole === 'admin') && {
Proposition : `['porteur-projet', 'dreal', 'admin'].includes(uploadedByRole) && { uploadedByRole }`

2022-10-12 09:35 UTC, HubM commented on src/views/components/timeline/components/GFItem.tsx
> +  const canUpdateGF = role === 'porteur-projet' || role === 'dreal' || role === 'admin'
Proposition: `['porteur-projet', 'dreal', 'admin'].includes(role)`

Vu le nombre d'occurence tu pourrais en faire une fonction au début du fichier

2022-10-12 09:35 UTC, HubM commented on src/views/components/timeline/components/GFItem.tsx
> +  const isAdmin = role === 'admin'
proposition : `const peutAjouterEtTéléchargerGf = ["admin", "dreal"].includes(role)`

2022-10-12 12:13 UTC, JulienPavon requested changes

2022-10-12 12:13 UTC, JulienPavon commented on src/views/components/timeline/components/GFItem.tsx
> +          {(isDreal || isAdmin) && (
Est ce qu'on n'aurait pas plutôt une constante du genre `canUpload/peutCharger` ?

2022-10-12 14:21 UTC, HubM approved these changes
👍🏼

2022-10-13 08:40 UTC, JulienPavon approved these changes

2022-10-13 09:50 UTC, merged