✨ (1190) : Démarrer un import de gestionnaire de réseau
MTES-MCT/potentiel pull request #665
Opened 2022-10-11 16:19 UTC by JulienPavon

2022-10-12 12:42 UTC, HubM requested changes

2022-10-12 12:42 UTC, HubM commented on src/modules/imports/gestionnaireRéseau/démarrerImportGestionnaireRéseau.spec.ts
> +        const publishToEventStore = jest.fn(() => okAsync<null, InfraNotAvailableError>(null))
On peut en faire une const globale puisque cette ligne se répète sur les différents tests

2022-10-12 12:55 UTC, JulienPavon commented on src/modules/imports/gestionnaireRéseau/démarrerImportGestionnaireRéseau.spec.ts
> +        const publishToEventStore = jest.fn(() => okAsync<null, InfraNotAvailableError>(null))
J'en ai profité pour créer des constante comme jeu de tests histoire de ne pas se répéter

2022-10-12 12:56 UTC, HubM approved these changes
👍🏼

2022-10-13 11:53 UTC, HanaeY commented on src/modules/imports/gestionnaireRéseau/démarrerImportGestionnaireRéseau.ts
> +            new ImportGestionnaireRéseauDémarré({
Pourquoi cet événement ImportGestionnaireRéseauDémarré n'est pas émis en premier (avant MiseAJourDateMiseEnServiceDémarrée) ?

2022-10-13 11:55 UTC, HanaeY commented on src/modules/imports/gestionnaireRéseau/démarrerImportGestionnaireRéseau.ts
> +  gestionnaire: string
est-ce qu'on ne pourrait pas typer le gestionnaire ? Donc pour le moment on n'aurait que "enedis" comme option

2022-10-13 11:56 UTC, HanaeY commented on src/modules/imports/gestionnaireRéseau/events/ImportGestionnaireRéseauDémarré.ts
> +  gestionnaire: string
Même question ici sur le typage du gestionnaire

2022-10-13 11:58 UTC, HanaeY commented on src/modules/imports/gestionnaireRéseau/events/MiseAJourDateMiseEnServiceDémarrée.ts
> +  gestionnaire: string
idem sur le type de gestionnaire

2022-10-14 07:13 UTC, JulienPavon commented on src/modules/imports/gestionnaireRéseau/démarrerImportGestionnaireRéseau.ts
> +            new ImportGestionnaireRéseauDémarré({
Pour ne pas avoir d'import en état démarré si la publication de l'évènement `MiseAJourDateMiseEnServiceDémarrée` à échouée

2022-10-14 07:16 UTC, JulienPavon commented on src/modules/imports/gestionnaireRéseau/démarrerImportGestionnaireRéseau.ts
> +  gestionnaire: string
On peut oui par contre par la suite il faudra revenir à un type `string` pour pouvoir faire des imports pour n'importe quel gestionnaire de réseau.

2022-10-14 07:18 UTC, JulienPavon commented on src/modules/imports/gestionnaireRéseau/events/ImportGestionnaireRéseauDémarré.ts
> +  gestionnaire: string
Ici je laisserai une chaine de caractère car restreindre depuis la commande pourquoi pas mais dans l'évènement cela reste une données libre, non ?

2022-10-14 08:58 UTC, HanaeY approved these changes

2022-10-14 09:03 UTC, HubM approved these changes
👍🏼

2022-10-14 09:04 UTC, merged