1189 améliorer retour erreurs fichier import
MTES-MCT/potentiel pull request #666
Opened 2022-10-11 16:27 UTC by HubM

2022-10-12 13:30 UTC, JulienPavon commented on src/controllers/helpers/yupFormatCsvDataError.ts
> +  if (!error || !error.inner || !error.inner.length) {
Il faut penser à typer en TS les argument des fonctions pour ne pas s'embetter à faire ces vérifications

2022-10-12 13:33 UTC, JulienPavon commented on src/controllers/admin/importGestionnaireRéseau/postDémarrerImportGestionnaireRéseau.ts
> +    return errAsync(formattedErrors)
Ici il faut une erreur spécifique. J'ai any dans ce cas et donc difficile de savoir si on ne se trompe pas

2022-10-12 13:34 UTC, JulienPavon commented on src/controllers/helpers/yupFormatCsvDataError.ts
> +export const yupFormatCsvDataError = (
Je l'aurai plus appelé `mapYupValidationErrorToCsvValidationError` ou quelque chose comme ça

2022-10-12 13:37 UTC, JulienPavon commented on src/controllers/helpers/yupFormatCsvDataError.spec.ts
> +  describe(`Si la fonction est exécutée avec une erreur`, () => {
On pourrait avoir ce genre de formulation pour les scénarios:
```
Lorsqu'on map une ValidationError avec ...
Alors on devrait avoir une liste d'erreurs correspondant aux ...
```

2022-10-12 13:38 UTC, JulienPavon commented on src/controllers/helpers/yupFormatCsvDataError.spec.ts
> +  describe(`Si la fonction est exécutée avec une erreur`, () => {
Il faut éviter d'avoir trop describe imbriqué car cela rend difficile la lecture des tests.
Quelques fois la duplication permet de rendre le code plus lisible

2022-10-12 13:40 UTC, JulienPavon commented on src/controllers/helpers/yupFormatCsvDataError.ts
> +    acc.push(formattedErreur)
Il vaut mieux retourner une copie du tableau avec le nouvel élément plutôt que de modifier le précédent

2022-10-17 10:01 UTC, HanaeY commented on src/controllers/admin/importGestionnaireRéseau/postDémarrerImportGestionnaireRéseau.ts
> +  console.log('im here')
console.log à retirer

2022-10-17 10:28 UTC, HanaeY commented on src/views/components/UI/molecules/CsvValidationErrorBox.tsx
> +)
Ca serait bien d'utiliser le DSFR pour l'alerte, sur le même modèle de l'AlertBox et InfoBox, on aurait une ErrorBox et une SuccessBox pour afficher le feedback.

2022-10-17 10:30 UTC, HanaeY commented on src/views/pages/importGestionnaireReseauPage/ImportGestionnaireReseau.tsx
> +    return <SuccessErrorBox success={feedback.success} />
Même chose ici, ça serait bien de ne plus utiliser ces box legacy pour passer au DSFR. Après si tu veux boucler cette PR pour avancer sur la fonctionnalité d'import avec Julien, je peux faire une petite PR cette semaine en mode "dette UI", comme tu veux :)!

2022-10-17 12:06 UTC, HubM commented on src/views/components/UI/molecules/CsvValidationErrorBox.tsx
> +)
vu ensemble, on va traiter ce retour dans une autre PR : https://airtable.com/apphLwfLi4vad9EAq/tbl8Xmi9jiTVtLxVp/viwZ5cGuW9v5FJb7B/rectmyfS8Xn9CxHh5?blocks=hide

2022-10-17 12:42 UTC, JulienPavon requested changes

2022-10-17 12:42 UTC, JulienPavon commented on src/controllers/helpers/mapYupValidationErrorToCsvValidationError.spec.ts
> +            params: {
Je pense qu'il serait plus clair d'avoir ce cas dans un autre scénario avec une explication claire de ce que nous devrions avoir en résultat

2022-10-17 12:42 UTC, JulienPavon commented on src/views/pages/importGestionnaireReseauPage/ImportGestionnaireReseau.tsx
> +const afficherFeedback = (feedback) => {
Est ce qu'on ne ferai pas plutôt un component ici ? Et merci de type l'argument `feedback`

2022-10-17 12:55 UTC, JulienPavon commented on src/controllers/admin/importGestionnaireRéseau/postDémarrerImportGestionnaireRéseau.ts
> +    routes.IMPORT_GESTIONNAIRE_RESEAU,
Avoir une route spécifique au POST

2022-10-17 14:54 UTC, HanaeY submitted a review, later dismissed

2022-10-18 09:58 UTC, HanaeY approved these changes

2022-10-18 10:08 UTC, JulienPavon approved these changes

2022-10-18 11:14 UTC, merged