♻️ usage d'une seule ligne projectEvent pour les gf
MTES-MCT/potentiel pull request #669
Opened 2022-10-13 12:17 UTC by flodlc

2022-10-14 08:53 UTC, HanaeY commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +const getGarantiesFinancières = ({
J'ai supprimé le test d'intégration pour la partie GF car il ne correspondait plus du tout à ce qu'on récupère et ce qu'on veut retourner. Mais il faudra peut être couvrir cette fonction par un test.

2022-10-14 15:11 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/garantiesFinancières/onProjectGFRemoved.ts
> +      })
Dans quelle situation métier on pourrait arriver ici ?

2022-10-14 15:11 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/garantiesFinancières/onProjectGFRemoved.integration.ts
>  describe('onProjectGFRemoved', () => {
Test à mettre à jour : correction du scenario et ajout des autres cas possibles

2022-10-14 16:12 UTC, HanaeY commented
- Il faudrait ajouter un handler pour la projection ProjectEvent pour les événement ProjectGFInvalidated
- Le test d'intégration de onProjectStepStatusUpdated n'est plus bon

2022-10-17 11:59 UTC, flodlc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/garantiesFinancières/onProjectGFRemoved.ts
> +      })
Dans le cas où le porteur a upload/submit sans une GF avec un item de GF généré à la volée. Et dans ce cas le retrait de la GF devrait supprimer la ligne de la DB pour retrouner à l'état initial. Le porteur aurait donc de nouveau l'item de la frise généré à la volée.

2022-10-18 07:04 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/garantiesFinancières/onProjectGFInvalidated.ts
> +    await ProjectEvent.update(
L'événement ProjectGFInvalidated est émis une seule fois dans le code, dans l'agrégat Projet en cas de changement de producteur. L'effet métier attendu en cas de changement de producteur est de supprimer la GF car ne nouveau producteur doit en envoyer de nouvelles. 
Le problème est que cet événement n'est pas très bien nommé et peut prêter à confusion. 
Dans l'agrégat projet, dans la fonction _processEvents, lorsqu'il est chargé l'événement ProjectGFInvalidated a pour effet de retirer la GF (hasCurrentGF = false). 
Je pense qu'ici il faudrait passer l'item GF en dûe, puisqu'on aura forcément une due date (voir project.updateProducteur). 
Il y a peut être un comportement à revoir aussi dans la projection Project (je créé une carte).

2022-10-18 08:36 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/projectEvents/updates/garantiesFinancières/onProjectGFInvalidated.integration.ts
> +  it(`Etant donné un élément GF avec le statut 'uploaded' et aucunue date limite d'envoi dans ProjectEvent,
type : aucune

2022-10-18 12:26 UTC, JulienPavon requested changes

2022-10-18 12:26 UTC, JulienPavon commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +        ).concat(garantiesFinancières ? [garantiesFinancières] : []),
Je ne comprend pas pourquoi on utilise un concat ici. Est ce qu'on ne peut pas traiter le cas des GFs dans le switch plus haut comme les autres events ?

2022-10-18 12:52 UTC, flodlc commented on src/infra/sequelize/projectionsNext/projectEvents/updates/garantiesFinancières/onDateEchéanceGFAjoutée.ts
> +        payload: typeCheck<GarantiesFinancièreEventPayload>({
L'alternative serait de déclarer `payload` au dessus pour le typer, ce qui me semble plus lourd à appliquer.
Il y a eu pas mal de discussion sur github pour une nouvelle feature ts qui permettrait de valider un type en inline comme le `as` mais de manière strict et c'est inclus dans ts 4.9 avec la syntaxe `{...} satisfies MyType`

2022-10-18 13:08 UTC, flodlc commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +        ).concat(garantiesFinancières ? [garantiesFinancières] : []),
Dans certains cas un item de frise GF est généré à la volée sans ProjectEvent de type GF en base.
Donc on ne passerait pas dans le switch dans ce cas là, c'est pour ça qu'on le définit au dessus et on l'ajoute aux events ensuite. Tu pensais à le faire comment ?

2022-10-19 07:53 UTC, JulienPavon commented on src/infra/sequelize/projectionsNext/projectEvents/updates/garantiesFinancières/onDateEchéanceGFAjoutée.ts
> +        payload: typeCheck<GarantiesFinancièreEventPayload>({
ok. Ah oui vivement la 4.9

2022-10-19 08:02 UTC, JulienPavon commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +        ).concat(garantiesFinancières ? [garantiesFinancières] : []),
J'aurai plus vu la logique d'avoir ou non un élément dans la frise pour les GFs dans les handlers.
Par exemple vérifier que le projet est bien soumis aux GFs, ou bien si le projet n'est pas lauréat ne pas créer de ligne dans la projection.
Par contre il serait nécessaire d'écouter les évènements si le projet repasse en lauréat (suite à un recours) pour créer la ligne.
Je trouve que ça simplifirait la query qui commence à avoir trop de responsabilités.

Peut être qu'on pourrait faire ça dans une autre PR par contre

2022-10-19 08:04 UTC, JulienPavon submitted a review, later dismissed

2022-10-19 08:21 UTC, HanaeY submitted a review, later dismissed

2022-10-19 09:48 UTC, flodlc commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +        ).concat(garantiesFinancières ? [garantiesFinancières] : []),
C'est le cas, on supprime la ligne GF dans ProjectEvents dans certains cas.
Mais il y a le cas ou il n'y a pas de ligne et pourtant on souhaite quand même afficher les GF dans la frise (on créé l'élément à la volé), c'est pas terrible mais faudrait voir à quel moment on devrait créer la ligne en base dans ce cas.
A faire dans une autre PR en effet

2022-10-19 10:27 UTC, HanaeY approved these changes

2022-10-19 12:46 UTC, JulienPavon approved these changes

2022-10-19 12:47 UTC, merged