✅ (1210): ajout du use-case + empecher la mise à jour si la date est …
MTES-MCT/potentiel pull request #675
Opened 2022-10-18 14:53 UTC by HubM

…plus récente que celle existante dans le projet

2022-10-18 15:21 UTC, JulienPavon requested changes

2022-10-18 15:21 UTC, JulienPavon commented on src/modules/project/useCases/renseignerDateDeMiseEnService.spec.ts
> +  describe(`Impossible de renseigner la date de mise en service si le projet dispose d'une date de mise en service plus récente que celle à renseigner`, () => {
On doit pouvoir modifier la date que si la nouvelle date est plus ancienne que l'actuelle du projet et non l'inverse

2022-10-18 15:50 UTC, JulienPavon requested changes

2022-10-18 15:50 UTC, JulienPavon commented on src/modules/project/useCases/renseignerDateDeMiseEnService.spec.ts
> +        Lorsqu'on renseigne une nouvelle date de mise en service pour ce projet et que celle-ci est plus récente que celle existante
...plus récente que celle du projet

2022-10-18 15:50 UTC, JulienPavon commented on src/modules/project/useCases/renseignerDateDeMiseEnService.spec.ts
> +  describe(`Impossible de renseigner la date de mise en service si le projet dispose d'une date plus ancienne que celle à renseigner`, () => {
"Impossible de renseigner une date de mise en service plus récente que celle du projet"

2022-10-18 15:50 UTC, JulienPavon commented on src/modules/project/useCases/renseignerDateDeMiseEnService.spec.ts
> +        Alors la date de mise en service n'est pas remplacée et une erreur de type 'DateDeMiseEnServicePlusRécenteError' est retournée
Remplacer par : "Alors on devrait être averti qu'il n'est pas possible de renseigner une date plus récente que celle du projet"

2022-10-18 15:50 UTC, JulienPavon commented on src/modules/project/useCases/renseignerDateDeMiseEnService.spec.ts
> +        projectRepo,
Il faut spécifier la date de mise en service ici plutôt que d'utiliser celle par défaut qui est '2023-01-01' et donc plus récente que celle que l'on souhaite renseigner (2022-01-01).

2022-10-18 15:50 UTC, JulienPavon commented on src/modules/project/useCases/renseignerDateDeMiseEnService.ts
> +      projet.dateMiseEnService.getTime() >= commande.dateMiseEnService.getTime()
Avec des données correctes dans les tests tu verra que l'implémentation n'est pas correcte

2022-10-19 09:05 UTC, JulienPavon commented on src/modules/project/useCases/renseignerDateDeMiseEnService.spec.ts
> +    it(`Étant donné un projet
On peut omettre cette étape dans le scénario et avoir dans l'étape qui suit : '... pour un projet'

2022-10-19 14:08 UTC, HanaeY commented on src/infra/sequelize/projections/project/updates/onDateDeMiseEnServiceRenseignée.ts
> +
console.log à retirer

2022-10-19 14:22 UTC, HanaeY commented on src/modules/project/Project.ts
> +  dateDeMiseEnService: Date | undefined
Ligne 236 plus haut, c'est 'dateDeMiseEnService', il manque le 'de'

2022-10-19 14:39 UTC, JulienPavon requested changes

2022-10-19 14:39 UTC, JulienPavon commented on src/infra/sequelize/projections/project/updates/onDateDeMiseEnServiceRenseignée.ts
> +      logger.error(
Il serait bien aussi d'avoir une erreur avec plus de contexte en utilisant `ProjectionEnEchec` comme fait plus bas

2022-10-19 14:39 UTC, JulienPavon commented on src/modules/project/Project.spec.ts
> +      expect(projet.dateDeMiseEnService).toEqual(dateDeMiseEnService)
On souhaite avoir un objet `Date` ici et non une chaîne de caractère

2022-10-19 14:39 UTC, JulienPavon commented on src/modules/project/Project.ts
> +        props.dateDeMiseEnService = event.payload.dateDeMiseEnService
Ici `payload.dateDeMiseEnService` est un type `string` (malgré le `any` car le TS ici n'est pas correct) 
Il faut donc affecter une `Date` dans `props.dateDeMiseEnService`

2022-10-19 15:29 UTC, HanaeY submitted a review, later dismissed

2022-10-19 15:53 UTC, HanaeY approved these changes

2022-10-19 16:04 UTC, merged