✨ On masque les étapes du projet pour les ademe
MTES-MCT/potentiel pull request #677
Opened 2022-10-18 15:19 UTC by flodlc

2022-10-18 16:20 UTC, HubM approved these changes
👍🏼

2022-10-18 16:24 UTC, HubM requested changes

2022-10-18 16:24 UTC, HubM commented on src/controllers/project/getProjectPage.ts
> +          if (user.role === 'ademe') {
ptet utiliser le helper `userIs` ?

2022-10-18 16:27 UTC, HanaeY requested changes

2022-10-19 12:46 UTC, HubM approved these changes
👍🏼

2022-10-19 13:38 UTC, HanaeY approved these changes

2022-10-19 13:39 UTC, merged