✨ (1222): brancher le controller au usecase démarrerImportGestionnair…
MTES-MCT/potentiel pull request #679
Opened 2022-10-20 12:53 UTC by HubM

…eRéseau

2022-10-21 14:24 UTC, JulienPavon approved these changes

2022-10-24 14:41 UTC, flodlc requested changes

2022-10-24 14:41 UTC, flodlc commented on src/controllers/admin/importGestionnaireRéseau/postDémarrerImportGestionnaireRéseau.ts
> +  const form = request.session.forms && request.session.forms[formId]
```suggestion
  const form = request.session.forms?.[formId]
```

2022-10-24 15:02 UTC, flodlc submitted a review, later dismissed

2022-10-24 15:17 UTC, HanaeY commented on src/modules/imports/gestionnaireRéseau/eventHandlers/onTâcheMiseAJourDatesMiseEnServiceDémarrée.ts
> +      return mettreAJourDateMiseEnService({
On pourrait pas appeler cette commande "mettreAJourDatesMiseEnService" plutôt ? comme elle vise à modifier plusieurs projets

2022-10-24 15:57 UTC, flodlc approved these changes

2022-10-24 15:59 UTC, HanaeY approved these changes

2022-10-24 16:01 UTC, merged