💄 (1220) : Afficher la liste des tâches d'import
MTES-MCT/potentiel pull request #680
Opened 2022-10-20 13:15 UTC by JulienPavon

2022-10-21 09:34 UTC, HubM requested changes

2022-10-21 09:34 UTC, HubM commented on src/views/pages/importGestionnaireReseauPage/ImportGestionnaireReseau.tsx
> +        </ul>
```suggestion
{
  tâches.length === 0 
  ?
    (
      <div className="flex p-16 border border-dashed border-grey-625-base">
        <span className="mx-auto text-center">Aucune mise à jour n'a encore été démarrée</span>
      </div>
    ) : (
      <ul className="m-0 p-0 list-none">
        {tâches.map((tâche) => (
          <li key={tâche.id} className="m-0 mb-3 p-0">
            <Tile>
              <Tâche {...tâche} />
            </Tile>
          </li>
        ))}
        </ul>
    )
}
```

2022-10-24 07:54 UTC, HubM approved these changes
👍🏼

2022-10-24 09:34 UTC, HanaeY submitted a review, later dismissed

2022-10-24 13:31 UTC, HubM approved these changes
👍🏼

2022-10-24 13:53 UTC, merged