💄 application du dsfr pour la navigation des admins
MTES-MCT/potentiel pull request #689
Opened 2022-10-25 15:52 UTC by flodlc

2022-10-27 07:31 UTC, HanaeY commented on src/views/components/PageTemplate.tsx
> -    key="main-menu-1"
Pourquoi retirer les "key" ?

2022-10-31 14:25 UTC, JulienPavon commented on src/views/index.html.tsx
> +  return html`s
`s` à supprimer

2022-10-31 14:31 UTC, JulienPavon commented on src/views/components/Header.tsx
> -  const menuItems = React.Children.map(children, (child: React.ReactElement) => {
Le problème ici est que nous ne pouvons pas accepter n'importe quel composant à afficher dans la partie menu. Peut être vaut-il mieux avoir une propriété dans les props pour définir leséléments du menu et laisser le header gérer son affichage indépendamment

2022-11-01 09:16 UTC, JulienPavon requested changes

2022-11-01 09:16 UTC, JulienPavon commented on src/views/components/UI/molecules/DropdownMenu.tsx
> +            className={`ml-auto md:ml-2 mr-2 md:mr-0 transition transition-rotate`}
`transition-rotate` n'existe pas si ?

2022-11-01 09:16 UTC, JulienPavon commented on src/views/components/UI/molecules/DropdownMenu.tsx
> +            style={{ transform: visible ? 'rotate(180deg)' : '' }}
Plutôt que du style inline il faudrait créer une animation custom dans la config tailwind (cf. https://tailwindcss.com/docs/animation#customizing-your-theme)

2022-11-02 14:29 UTC, flodlc commented on src/views/components/UI/molecules/DropdownMenu.tsx
> +            style={{ transform: visible ? 'rotate(180deg)' : '' }}
Vu en visio
on utilise le inline pour l'instant

2022-11-02 14:31 UTC, flodlc commented on src/views/components/Header.tsx
> -  const menuItems = React.Children.map(children, (child: React.ReactElement) => {
Vu en visio
On garde comme ça pour l'instant. Comme pour les autres components c'est au développeur de veiller au bon usage du component.

2022-11-02 15:50 UTC, JulienPavon approved these changes

2022-11-03 08:58 UTC, HanaeY approved these changes

2022-11-03 08:59 UTC, merged