1140 Application du délai de 18 mois CDC 2022
MTES-MCT/potentiel pull request #697
Opened 2022-10-28 13:35 UTC by HanaeY

Application du délai  de 18 mois automatique pour les projets qui ont une date de mise en service et respectent les règles pour ce délai (date de mise en service comprise dans une fourchette selon le type d'AO et souscription au CDC 2022). 
L'application du délai est un effet de l'ajout des dates de mise en service lors de l'import du fichier gestionnaire réseau.

2022-10-31 13:51 UTC, JulienPavon requested changes

2022-10-31 13:51 UTC, JulienPavon commented on src/modules/project/eventHandlers/onDateMiseEnServiceRenseignée.ts
> +        const dateMin = appelOffre?.type === 'eolien' ? '2022-06-01' : '2022-09-01'
Il faudrait avoir ces données directement dans le cdc de l'appel d'offre ce qui éviterait d'avoir ces données en dur dans le code. Ça réduirait aussi le cas où l'on vérifie le type du cdc plus bas et les cas des tests

2022-10-31 13:51 UTC, JulienPavon commented on src/modules/project/eventHandlers/onDateMiseEnServiceRenseignée.ts
> +            new DélaiCDC2022Appliqué({
Est ce que cet évènement est vraiment nécessaire ? On pourrait imaginer avoir la raison de la maj de la date dans l'évènement précédent. 

```

interface ProjectCompletionDueDateSetPayload {
  projectId: string
  completionDueOn: number
  setBy?: string
  raison?: 'délaiCdc2022' | 'délaiCovid'
  
}

```

2022-11-02 16:03 UTC, JulienPavon requested changes

2022-11-02 16:03 UTC, JulienPavon commented on src/entities/cahierDesCharges.ts
> +    | { min: '2022-06-01'; max: '2024-09-30' } // éolien
Pourquoi ne pas mettre un type `Date` ici et laisser les appels d'offres libre de mettre leur données ?

2022-11-02 16:03 UTC, JulienPavon commented on src/entities/cahierDesCharges.ts
> +  datesLimitesMeS:
Renommer par `intervaleDateMiseEnService`

2022-11-02 16:45 UTC, JulienPavon submitted a review, later dismissed

2022-11-02 16:49 UTC, flodlc requested changes

2022-11-02 16:49 UTC, flodlc commented on src/modules/notification/eventHandlers/onProjectCompletionDueDateSet.ts
> +    )
Ici je crois pas qu'on ait besoin des Promise.all vu qu'on se sert pas des retours de promise.
```suggestion
regions.forEach(async (region) => {
        const dreals = await findUsersForDreal(region)
        dreals.forEach(({ email, fullName, id }) =>
            sendNotification({
              type: 'dreals-delai-cdc-2022-appliqué',
              context: { projetId: projectId, utilisateurId: id },
              variables: {
                nom_projet: projet.nomProjet,
                projet_url: routes.PROJECT_DETAILS(projectId),
              },
              message: {
                email,
                name: fullName,
                subject: `Potentiel - Nouveau délai appliqué pour le projet ${projet.nomProjet}`,
              },
            })
          )
      })
```

2022-11-02 16:49 UTC, flodlc commented on src/views/components/timeline/helpers/extractACItemProps.ts
> +
`find` pourrait être remplacé par `some` pour que `hasCovidDelay` soit un boolean

2022-11-03 08:17 UTC, HanaeY commented on src/modules/notification/eventHandlers/onProjectCompletionDueDateSet.ts
> +    )
Il me semble que jusqu'à maintenant on a utilisé un Promise.all pour l'envoi des mails dans tous nos handlers pour exécuter les envois en parallèle et non les uns après les autres. Mais on peut en discuter !

2022-11-03 08:29 UTC, flodlc commented on src/modules/notification/eventHandlers/onProjectCompletionDueDateSet.ts
> +    )
Ok, j'approve et ce sera peut-être l'objet d'un clean lors d'une PR dédiée

2022-11-03 08:30 UTC, flodlc submitted a review, later dismissed

2022-11-03 09:20 UTC, HubM requested changes

2022-11-03 09:20 UTC, HubM commented on src/modules/project/eventHandlers/onDateMiseEnServiceRenseignée.spec.ts
> +  describe(`Projets non pouvant pas bénéficier du délai de 18 mois`, () => {
```suggestion
  describe(`Projets ne pouvant pas bénéficier du délai de 18 mois`, () => {
```

2022-11-03 09:42 UTC, flodlc approved these changes

2022-11-03 09:42 UTC, HubM approved these changes

2022-11-03 09:44 UTC, merged