🔥  839 supprimer package dsfr de potentiel
MTES-MCT/potentiel pull request #709
Opened 2022-11-03 15:32 UTC by HubM

2022-11-03 16:27 UTC, flodlc approved these changes

2022-11-03 16:28 UTC, flodlc commented
Est-ce que tu as fait un npm i ? Car le package lock n'est pas modifié

2022-11-03 16:38 UTC, flodlc approved these changes

2022-11-03 16:38 UTC, HanaeY commented on src/views/components/Footer.tsx
> +          <div className="mt-4 flex flex-wrap items-center border-0 border-t border-solid border-gray-400">
La bordure actuelle est un peu plus claire que ce gris là

2022-11-03 16:39 UTC, HanaeY commented on src/views/components/Footer.tsx
> +            <ul className="p-0 m-0 list-none w-full flex flex-wrap items-center px-0 pt-2 pb-4">
Même chose ici pour la couleur des traits qui séparent les items entre eux

2022-11-03 16:43 UTC, HanaeY commented on src/views/index.html.tsx
> -        <link href="/css/dsfr.css" rel="stylesheet" />
La font Marianne n'est plus appliqué sur les pages (on a du arial j'ai l'impression)

2022-11-03 17:13 UTC, HubM commented on src/views/index.html.tsx
> -        <link href="/css/dsfr.css" rel="stylesheet" />
oui tu as raison j'ai pas fais gaffe

2022-11-04 10:07 UTC, HanaeY submitted a review, later dismissed

2022-11-04 10:25 UTC, JulienPavon requested changes

2022-11-04 10:25 UTC, JulienPavon commented on src/views/components/Footer.tsx
> +        <div className="w-full px-4 mx-auto dsfr-breakpoint-992:px-6 lg:max-w-[78rem]">
Je ne pense pas qu'il faille introduire un nouveau breakpoint ici. On peut réutiliser ce qui a été fait dans le header :
````
<div className="flex flex-col xl:mx-auto xl:max-w-7xl">
````

2022-11-04 10:31 UTC, HubM commented on src/views/components/Footer.tsx
> +        <div className="w-full px-4 mx-auto dsfr-breakpoint-992:px-6 lg:max-w-[78rem]">
Hum dans tt les cas j'ai besoin d'appliquer des règles spécifiques à partir de 992px pour le reste du footer (ce breakpoint custom étant utilisé 3 fois).
Du coup j'avoue ne pas comprendre vraiment l'intérêt de ne pas l'utiliser ici

2022-11-04 10:37 UTC, JulienPavon commented on src/views/components/Footer.tsx
> +        <div className="w-full px-4 mx-auto dsfr-breakpoint-992:px-6 lg:max-w-[78rem]">
Tailwind a déjà plusieurs breakpoint `sm`, `md` ... Histoire de garder les choses simples pour le header on avait utilisé ceux-ci sans en introduire de nouveau.

2022-11-04 10:39 UTC, JulienPavon commented on src/views/components/Footer.tsx
> +        <div className="w-full px-4 mx-auto dsfr-breakpoint-992:px-6 lg:max-w-[78rem]">
Si on souhaite avoir les valeurs exactes du dsfr pour les breakpoint il faudrait surharger celles de tailwind plutôt que d'en avoir de nouvelles. Le but étant de gérer les styles simplement (small, medium, large etc...) Ici en arrivant sur le composant je ne comprend pas à quel écran la valeur 992 correspond. Mobile, Tablette...

2022-11-04 10:56 UTC, HanaeY submitted a review, later dismissed

2022-11-04 13:02 UTC, JulienPavon approved these changes

2022-11-04 13:10 UTC, HanaeY approved these changes

2022-11-04 13:14 UTC, merged