♻️ (1172): Renommage d'un evenement
MTES-MCT/potentiel pull request #724
Opened 2022-11-08 16:57 UTC by JulienPavon

2022-11-09 15:12 UTC, HanaeY requested changes

2022-11-09 15:12 UTC, HanaeY commented on src/infra/sequelize/projections/project/updates/onDonnéesDeRaccordementRenseignées.ts
>  export const onDateMiseEnServiceRenseignée: OnDateMiseEnServiceRenseignée =
On ne devrait pas renommer cet handler onDonnéesDeRaccordementRenseignées pour qu'il corresponde à son événement ?

2022-11-09 15:38 UTC, JulienPavon commented on src/modules/imports/donnéesRaccordement/mettreAJourDonnéesDeRaccordement/mettreAJourDonnéesDeRaccordement.ts
> +    dateFileAttente?: Date
Il me semblait que la données n'était pas forcément renseignée. Je me renseigne auprès de Julie

2022-11-09 16:07 UTC, JulienPavon commented on src/modules/imports/donnéesRaccordement/mettreAJourDonnéesDeRaccordement/mettreAJourDonnéesDeRaccordement.ts
> +    dateFileAttente?: Date
J'ai eu la réponse et la données est bien facultative

2022-11-09 16:57 UTC, JulienPavon commented on src/controllers/admin/importDonnéesRaccordement/postDémarrerImportDonnéesRaccordement.ts
> +      'Entr�e FA': yup
On peut oui par contre ça necessitera une opération manuelle avant l'import

2022-11-10 08:49 UTC, HanaeY commented on src/modules/project/eventHandlers/onDonnéesDeRaccordementRenseignées.ts
> +type onDonnéesDeRaccordementRenseignées = (
type OnDonnéesDeRaccordementRenseignées

2022-11-10 08:49 UTC, HanaeY commented on src/modules/project/eventHandlers/onDonnéesDeRaccordementRenseignées.ts
>  type MakeOnDateMiseEnServiceRenseignée = (deps: {
MakeOnDonnéesDeRaccordementRenseignées

2022-11-10 08:50 UTC, HanaeY commented on src/modules/project/eventHandlers/onDonnéesDeRaccordementRenseignées.ts
>  export const makeOnDateMiseEnServiceRenseignée: MakeOnDateMiseEnServiceRenseignée =
makeOnDonnéesDeRaccordementRenseignées

2022-11-10 08:50 UTC, HanaeY commented on src/modules/project/eventHandlers/onDonnéesDeRaccordementRenseignées.spec.ts
> +import { makeOnDateMiseEnServiceRenseignée } from './onDonnéesDeRaccordementRenseignées'
makeOnDonnéesDeRaccordementRenseignées

2022-11-10 08:53 UTC, HanaeY commented on src/config/eventHandlers/project.eventHandlers.ts
>    getProjectAppelOffre,
onDonnéesDeRaccordementRenseignéesHandler

2022-11-10 08:54 UTC, HanaeY commented on src/infra/sequelize/projections/project/updates/onDonnéesDeRaccordementRenseignées.ts
>            'Erreur dans la projection onDateMiseEnServiceRenseingée : impossible de récupérer le projet de la db',
onDonnéesDeRaccordementRenseignées

2022-11-10 14:31 UTC, merged