1233 ajout manuel délai cdc 2022
MTES-MCT/potentiel pull request #726
Opened 2022-11-09 14:11 UTC by HanaeY

2022-11-09 15:30 UTC, JulienPavon requested changes

2022-11-09 15:30 UTC, JulienPavon commented on src/controllers/project/postSignalerDemandeDelai.ts
> +  raison: yup.string().optional(),
Si une seule valeur est possible aujourd'hui pourquoi avoir un type string et non un booléen ?

2022-11-09 15:30 UTC, JulienPavon commented on src/modules/project/useCases/signalerDemandeDelai.spec.ts
> +      describe(`Lorsque l'utilisateur n'est pas 'admin' ou 'dgec-validateur'`, () => {
Est ce que ce cas est seulement lié à appliquer un délai en rapport avec le cdc 2022 ? J'ai l'impression que peu importe la raison seul un admin ou dgec-validateur peut signaler un délai non ?

2022-11-09 15:30 UTC, JulienPavon commented on src/controllers/project/postSignalerDemandeDelai.ts
> +          ...(raison === 'délaiCdc2022' && { raison: 'délaiCdc2022' }),
La raison devrait être dans le cas `status === 'acceptée'`

2022-11-09 15:30 UTC, JulienPavon commented on src/modules/project/useCases/signalerDemandeDelai.ts
> +            if (status === 'acceptée' && args.raison === 'délaiCdc2022') {
Est ce qu'on ne devrait pas appliquer un délai de 18 mois dans ce cas ? Je ne vois pas où cela se passe ?

2022-11-09 15:30 UTC, JulienPavon commented on src/modules/project/useCases/signalerDemandeDelai.ts
> +      raison?: 'délaiCdc2022'
Est ce que nous ne devrions pas plutôt avoir soit un `newCompletionDueOn` soit `appliquerDélaiCdc` ?

2022-11-09 15:34 UTC, HanaeY commented on src/modules/project/useCases/signalerDemandeDelai.spec.ts
> +      describe(`Lorsque l'utilisateur n'est pas 'admin' ou 'dgec-validateur'`, () => {
Les Dreals peuvent aussi déclarer une demande de délai faite hors Potentiel.

2022-11-09 15:37 UTC, HanaeY commented on src/modules/project/useCases/signalerDemandeDelai.ts
> +            if (status === 'acceptée' && args.raison === 'délaiCdc2022') {
C'est l'admin qui saisit la nouvelle date d'achèvement qui applique le délai de 18 mois à la main. On avait validé ça en conception métier avec Julie, mais on peut en rediscuter avec elle pour voir si elle voudrait au final que le délai de 18 mois soit calculé automatiquement.

2022-11-09 16:01 UTC, HanaeY commented on src/modules/project/useCases/signalerDemandeDelai.ts
> +      raison?: 'délaiCdc2022'
Même si la raison est l'application du délai du CDC 2022, on devrait quand même avoir une date d'achèvement car dans le formulaire, la date calculée restera éditable.

2022-11-10 13:23 UTC, JulienPavon requested changes

2022-11-10 13:23 UTC, JulienPavon commented on src/views/pages/signalerDemandeDelaiPage/SignalerDemandeDelai.tsx
> +                    onClick={() => setappliquerCDC2022Délai(!appliquerCDC2022Délai)}
Utiliser `onChange` plutôt que `onClick`

2022-11-10 13:24 UTC, JulienPavon commented on src/modules/project/Project.ts
> +          délaiCdc2022?: true
:+1:

2022-11-10 16:57 UTC, JulienPavon approved these changes

2022-11-14 08:51 UTC, HubM commented on src/views/helpers/appliquerDélaiEnMois.ts
> +  )
On aurait ptet pu faire des tests sur ce helper

2022-11-14 10:39 UTC, HubM approved these changes
👍🏼

2022-11-14 10:47 UTC, merged