🚧 (1113): création du model + migration
MTES-MCT/potentiel pull request #733
Opened 2022-11-15 13:54 UTC by HubM

2022-11-16 16:54 UTC, flodlc commented on src/infra/sequelize/migrations/20221115144500-ajout-table-connexionsParRoleEtParJour.ts
> +      },
Pourquoi ne pas utiliser le type Postgres `date` plutôt qu'un string ?

2022-11-17 09:57 UTC, flodlc submitted a review, later dismissed

2022-11-17 16:20 UTC, flodlc submitted a review, later dismissed

2022-11-18 13:07 UTC, JulienPavon requested changes

2022-11-18 13:07 UTC, JulienPavon commented on src/infra/keycloak/mettreAJourConnexionsParRoleEtParJour.integration.ts
> +describe(`helper mettreAJourConnexionsParRoleEtParJour`, () => {
Ici plutôt que de mettre `helper` autant mettre la phrase `Mettre à jour le nombre de connexion par rôle et par jour` directement non ?

2022-11-18 13:07 UTC, JulienPavon commented on src/infra/keycloak/mettreAJourConnexionsParRoleEtParJour.integration.ts
> +  describe(`Lorsqu'il n'y a pas d'entrée dans la table ConnexionsParRoleEtParJour pour le rôle à la date du jour`, () => {
Ne pas confondre la mise en place d'un contexte `Étant donné que` et l'action `Lorsque/Quand`

Étant donné qu'aucune connexion n'a été faite le JJ/MM/AAAA pour le rôle ...
Lorsqu'un utilisateur avec le rôle ... se connecte le JJ/MM/AAAA
Alors le compteur de connexion  devrait être de 1 pour le jour du JJ/MM/AAAA

2022-11-18 13:59 UTC, JulienPavon commented on src/infra/keycloak/mettreAJourConnexionsParRoleEtParJour.integration.ts
> +  describe(`Étant donné qu'aucune connexion n'a été faite le 01/01/2022 pour le rôle admin
Le `describe` ici n'a pas de réél intérêt. On peut mettre tout le scénario directement dans le `it`

2022-11-18 15:01 UTC, HanaeY approved these changes

2022-11-18 15:44 UTC, JulienPavon approved these changes

2022-11-18 15:48 UTC, merged