1268 ne pas signaler nouveau abandon si abandon existant en attente
MTES-MCT/potentiel pull request #737
Opened 2022-11-16 14:33 UTC by flodlc

2022-11-16 15:30 UTC, HanaeY requested changes

2022-11-16 15:30 UTC, HanaeY commented on src/controllers/project/postSignalerDemandeAbandon.ts
> +          if (error instanceof DemandeDeMêmeTypeDéjàOuverteError) {
![image](https://user-images.githubusercontent.com/72154904/202223114-82424f7a-c9b7-4054-9c20-9fe98f94de84.png)

2022-11-16 15:32 UTC, flodlc commented on src/controllers/project/postSignalerDemandeAbandon.ts
> +          if (error instanceof DemandeDeMêmeTypeDéjàOuverteError) {
Je regarde

2022-11-16 16:09 UTC, flodlc commented on src/controllers/project/postSignalerDemandeAbandon.ts
> +          if (error instanceof DemandeDeMêmeTypeDéjàOuverteError) {
On avait en fait la redirection vers la page de recours.
Et la page de demande de recours avait un probleme pour accéder au user. C'est corrigé.

2022-11-16 16:53 UTC, HanaeY approved these changes

2022-11-17 09:27 UTC, HubM requested changes

2022-11-17 09:27 UTC, HubM commented on src/controllers/project/postSignalerDemandeAbandon.ts
> +import { DemandeDeMêmeTypeDéjàOuverteError } from '../../modules/project/errors/DemandeDeMêmeTypeDéjàOuverteError'
```suggestion
import { DemandeDeMêmeTypeDéjàOuverteError } from '@modules/project/errors/DemandeDeMêmeTypeDéjàOuverteError'
```

2022-11-17 09:30 UTC, HanaeY approved these changes

2022-11-17 09:37 UTC, merged