🚧 (1216): création de la table + model + méthode pour mettre à jour l…
MTES-MCT/potentiel pull request #741
Opened 2022-11-17 15:44 UTC by HubM

…es connexions par projet et par role par jour

2022-11-17 16:32 UTC, flodlc requested changes

2022-11-17 16:32 UTC, flodlc commented on src/infra/sequelize/tableModels/connexionsParProjetEtParRoleParJour.model.ts
> +    ],
On pourrait ajouter une contrainte d'unicité sur role et date

2022-11-17 17:11 UTC, HanaeY commented on src/infra/keycloak/mettreAJourConnexionsParProjetEtParRoleParJour.ts
> +export const mettreAJourConnexionsParProjetEtParRoleParJour = async ({
Je m'interroge sur l'emplacement de cette fonction dans le projet, comme elle n'a pas de bien avec keycloak, on pourrait la déplacer plus près de là où elle est utlisée ?

2022-11-18 15:06 UTC, HanaeY approved these changes

2022-11-22 15:41 UTC, closed without merging