:star2:  Add pipeline to download projects as csv
MTES-MCT/potentiel pull request #75
Opened 2021-01-28 16:02 UTC by Zekdar

2021-02-05 09:41 UTC, paduc requested changes

2021-02-05 09:41 UTC, paduc commented on src/controllers/project/downloadProjectListCsv.ts
> +      { name: 'prixReference', hiddenFor: ['dreal'] },
Une alternative possible: maintenir pour chaque role, un tableau de champs autorisés. Et un tableau qui contient les champs autorisés pour tous pour aller plus vite.
Par exemple:
```
const commonFields = ['numeroCRE', 'appelOffreId', ... ]
const adminFields = ['prixReference', ... ]
```

Qu'en penses-tu ?

2021-02-05 09:41 UTC, paduc commented on src/controllers/project/downloadProjectListCsv.ts
> +    return response.type('text/csv').sendFile(csvFilePath)
On ne supprimerait pas le fichier après l'avoir retourné ?

2021-02-05 09:41 UTC, paduc commented on src/controllers/project/downloadProjectListCsv.ts
> +const writeFileAsync = promisify(writeFile)
J'ai découvert qu'il y a des versions déjà promisifiées des méthodes `fs`.

`import { writeFile } from 'fs/promises'`

2021-02-05 09:41 UTC, paduc commented on package.json
> +    "mocha": "^8.1.3",
Ca sert où ?

2021-02-05 09:41 UTC, paduc commented on package.json
> +    "csv-generate": "^3.3.0",
Où est-ce que ça sert ?

2021-02-05 09:41 UTC, paduc commented on src/controllers/project/index.ts
> +export * from './downloadProjectListCsv'
J'ai pris la convention de préfixer les controlleurs avec leur verbe http.
Renommer `getProjectListCsv`.

2021-02-05 09:41 UTC, paduc commented on src/routes.ts
> +  static DOWNLOAD_PROJECTS_CSV = '/downloadProjectsCsv'
Je le renommerais pour avoir un meilleur nom de fichier téléchargé:
`static DOWNLOAD_PROJECTS_CSV = '/export-projets.csv'`

2021-02-05 09:41 UTC, paduc commented on src/views/pages/listProjects.tsx
> +                href={Object.entries(request.query).reduce(
Il y a une lib qui s'appelle `querystring` qui permet de faire ça. Tu trouveras un exemple de son usage dans `routes.ts`.

Ce que tu cherches est `querystring.stringify()`

2021-02-05 10:02 UTC, Zekdar commented on package.json
> +    "mocha": "^8.1.3",
Le changement est dû à un tri des dépendances  `package.json`. Cette lib était déjà là avant, elle a juste changé de place. Si on l'utilise pas je peux l'enlever.

2021-02-05 10:03 UTC, Zekdar commented on package.json
> +    "csv-generate": "^3.3.0",
C'est un résidu de POC. Je l'enlève.

2021-02-05 10:58 UTC, paduc commented on package.json
> +    "mocha": "^8.1.3",
Ok, tu peux laisser alors.

2021-02-05 23:37 UTC, Zekdar commented on package.json
> +    "watch": "./node_modules/ts-node-dev/bin/ts-node-dev --poll src/index.ts"
Car depuis node 14, `ts-node-dev` ne fonctionne plus sous linux. Ca crash une erreur `ERR_FEATURE_UNAVAILABLE_ON_PLATFORM`

2021-02-05 23:41 UTC, Zekdar commented on src/controllers/project/downloadProjectListCsv.ts
> +      { name: 'prixReference', hiddenFor: ['dreal'] },
Je me suis posé la question, il est plus naturel et plus sécurisé de le faire avec `visibility` plutôt que `hiddenFor`. J'ai finalement opté pour la 2° possibilité car c'était plus rapide à coder vu le nombre de champs. Finalement, j'ai fait un script pour inverser les rôles.

Voilà le script que j'ai écris : 
```js
const newRoles = orderedFields.map((el) => {
  if (!el.hiddenFor) return { ...el, visibility: ["*"] };

  const visibility = [admin, dgec, porteurProjet, dreal, edfoa].reduce((acc, curr) => {
    return el.hiddenFor.includes(curr) ? acc : [...acc, curr];
  }, []);

  return { name: el.name, visibility };
});
```

2021-02-07 06:51 UTC, paduc commented on package.json
> +    "watch": "./node_modules/ts-node-dev/bin/ts-node-dev --poll src/index.ts"
Ok, dans ce cas, comme c’est spécifique au cas Linux et que ça prends des ressources CPU supplémentaires, je préconise de ne pas le rajouter ici et de le rajouter de ton coté quand tu le lances.
`npm run watch — —poll` fera le même effet.

2021-02-07 06:53 UTC, paduc commented on src/controllers/project/downloadProjectListCsv.ts
> +      { name: 'prixReference', hiddenFor: ['dreal'] },
Ok très bien. On aura l’occasion de sortir cette partie de ce contrôleur par la suite parce que ça peut resservir à tous les autres endroits où on retourne des données projet.

2021-02-07 06:57 UTC, paduc requested changes

2021-02-07 06:57 UTC, paduc commented on src/routes.ts
> +  static GET_PROJECT_LIST_CSV = '/getProjectListCsv'
J’avais suggéré  `static DOWNLOAD_PROJECTS_CSV = '/export-projets.csv'`

2021-02-07 06:57 UTC, paduc commented on tsconfig.json
> +    "moduleResolution": "Node",
Ca résout un problème la majuscule ? Dans la doc officielle, je vois `node` en minuscule.

2021-02-08 11:18 UTC, Zekdar commented on src/controllers/project/downloadProjectListCsv.ts
> +    return response.type('text/csv').sendFile(csvFilePath)
Tu ferais comment ? Car si je supprime le fichier à la suite de cette ligne, le fichier aura déjà été supprimé avant que le client ne le télélécharge.

2021-02-08 11:18 UTC, Zekdar commented on package.json
> +    "watch": "./node_modules/ts-node-dev/bin/ts-node-dev --poll src/index.ts"
Ok

2021-02-08 16:02 UTC, Zekdar commented on tsconfig.json
> +    "moduleResolution": "Node",
C'est l'intellisence de vscode qui m'a suggéré `Node`, mais à priori les deux on l'air valide. Je revert pour éviter un changement inutile.

2021-02-08 17:23 UTC, paduc commented on src/controllers/project/downloadProjectListCsv.ts
> +    return response.type('text/csv').sendFile(csvFilePath)
Il est possible de mettre un listener sur la requête, qui s’exécutera lorsque la requête sera terminée (normalement après que le fichier ait fini d’être téléchargé). Je m’en sers dans le middleware `upload`.
```
request.on(‘finish’, ...)
```

2021-02-15 10:43 UTC, paduc requested changes

2021-02-15 10:43 UTC, paduc commented on src/dataAccess/inMemory/appelsOffres/commonDataFields.ts
> +    field: 'garantiesFinancieresFile',
J'en ai discuté avec Julie. On peut retirer cette colonne.

2021-02-15 10:43 UTC, paduc commented on src/dataAccess/inMemory/appelsOffres/commonDataFields.ts
> +    field: 'garantiesFinancieresDate',
En base, c'est un timestamp. Il faudrait le transformer en date lisible dans le csv.

2021-02-15 10:43 UTC, paduc commented on src/dataAccess/inMemory/appelsOffres/commonDataFields.ts
> +    field: 'garantiesFinancieresSubmittedOn',
Idem, timestamp à transformer en date.

2021-02-15 10:43 UTC, paduc commented on src/routes.ts
> +  static DOWNLOAD_PROJECTS_CSV = '/export-projects.csv'
Restons en français 

```suggestion
  static DOWNLOAD_PROJECTS_CSV = '/export-projets.csv'
```

2021-02-15 10:48 UTC, Zekdar commented on src/dataAccess/inMemory/appelsOffres/commonDataFields.ts
> +    field: 'garantiesFinancieresDate',
C'est déjà fait L.492 de `getProjectListCsv.ts`

2021-02-15 10:48 UTC, Zekdar commented on src/dataAccess/inMemory/appelsOffres/commonDataFields.ts
> +    field: 'garantiesFinancieresSubmittedOn',
Idem

2021-02-15 10:50 UTC, paduc commented on src/dataAccess/inMemory/appelsOffres/commonDataFields.ts
> +    field: 'garantiesFinancieresDate',
Ok top !

2021-02-15 11:00 UTC, paduc approved these changes

2021-02-15 11:08 UTC, merged