✨ (1291): afficher les taux des GF envoyées
MTES-MCT/potentiel pull request #751
Opened 2022-11-22 12:43 UTC by HubM

<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/751"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-11-22 16:20 UTC, HanaeY commented on src/infra/sequelize/migrations/20221121173511-mise-a-jour-isSoumisGf-projet.ts
> +                  [Op.gte]: 1586901600000, // 15/04/2020,
Ici je mettrais pas de limite de notification car on pourrait avoir besoin dans un autre contexte de savoir si les projets notifiés hors Potentiel sont soumis à GF. Et puis les données vont être fausses car on va laisser le valeur défaut s'appliquer (false) pour ces projets notifiés hors potentiel alors que ça peut être true. On pourra mettre la date de notification minimum dans la requête metabase plutôt.

2022-11-22 16:22 UTC, HanaeY commented on src/infra/sequelize/migrations/20221121164000-ajout-colonne-isSoumisGF-project.ts
> +    await queryInterface.addColumn('projects', 'isSoumisGF', {
Pas besoin du "is" je pense, on peut pas appeler la colonne "soumisAuxGarantiesFinancière" (ou "soumisAuxGF") ?

2022-11-22 16:34 UTC, HanaeY commented
Il faut ajouter isSoumisGF: false, au fake project (__tests__ / fixtures / project.ts

2022-11-23 14:00 UTC, HanaeY requested changes

2022-11-23 14:14 UTC, HubM commented on src/infra/sequelize/migrations/20221121173511-mise-a-jour-soumisAuxGF-projet.ts
> +            [Op.and]: [
Plus à rien du coup tu as raison

2022-11-23 14:17 UTC, closed without merging