🗃️ (1216): Mise en place statistique d'utilisation
MTES-MCT/potentiel pull request #753
Opened 2022-11-22 14:34 UTC by HubM

2022-11-22 15:08 UTC, JulienPavon requested changes

2022-11-22 15:08 UTC, JulienPavon commented on src/controllers/project/getProjectPage.ts
> +              date: new Date(),
Ne pas fournir la date ici et laisser la table la gérer automatiquement.

2022-11-22 15:08 UTC, JulienPavon commented on src/controllers/project/getProjectPage.ts
> +                appelOffreId: project.appelOffreId,
J'aurai fait une proprité `projet` avec ces infos (sauf role)

2022-11-22 15:08 UTC, JulienPavon commented on src/controllers/project/getProjectPage.ts
> +                role: request.user.role,
Peut être ajouter un proprité `utilisateur` ici pour plus de clareté ?

2022-11-22 17:20 UTC, HanaeY commented on src/controllers/helpers/miseAJourStatistiquesUtilisation.ts
> +type MiseAJourStatistiquesUtilisationProps = { type: string; données: Données }
MiseAJourStatistiquesUtilisationArgs ?

2022-11-23 08:34 UTC, JulienPavon approved these changes

2022-11-23 10:04 UTC, HanaeY approved these changes

2022-11-23 10:04 UTC, merged