1312 nouvelle projection gf
MTES-MCT/potentiel pull request #762
Opened 2022-11-25 14:17 UTC by HanaeY

2022-11-29 14:55 UTC, HubM requested changes

2022-11-29 14:55 UTC, HubM commented on src/infra/sequelize/projectionsNext/garantiesFinancières/updates/onProjectGFDueDateCancelled.ts
> +          ...(validéPar && { validéPar: validéPar }),
J'ai une deuxième remarque, vu qu'ici tu détruis puis recréée une nouvelle entrée dans la table, est-ce que tu peux pas directement faire 

```suggestion
...entréeExistante
```

2022-11-29 15:54 UTC, flodlc commented on src/infra/sequelize/migrations/20221125170000-create-table-GF.ts
> +      },
validéPar et validéLe, si on parle des garantiesFinancières est-ce qu'on devrait pas accorder donc `ées` ?

2022-11-29 16:02 UTC, HanaeY commented on docs/RECIPES.md
> +    //timestamps: true,
oui c'est pour montrer que la variable existe

2022-11-29 16:02 UTC, HanaeY commented on src/infra/sequelize/migrations/20221125170000-create-table-GF.ts
> +      },
oui tu as raison !

2022-11-29 16:04 UTC, flodlc commented on src/infra/sequelize/migrations/20221125170000-create-table-GF.ts
> +      },
Ça s'applique aux autres attributs de la table

2022-11-29 16:20 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/garantiesFinancières/updates/onProjectGFDueDateCancelled.ts
> +          ...(validéPar && { validéPar: validéPar }),
Si je destructure l'entrée existante je vais récupérer la donnée que je ne veux pas avoir (dateLimiteDEnvoi)

2022-11-29 16:22 UTC, HanaeY commented on src/infra/sequelize/migrations/20221125170000-create-table-GF.ts
> +      },
oui j'ai accordé partout du coup

2022-11-30 11:03 UTC, HubM approved these changes
👍🏼

2022-11-30 11:49 UTC, flodlc approved these changes

2022-11-30 12:55 UTC, merged