🗃️ (1319): Migrer l'évènement ProjectCertificateDownloaded vers une nouvelle statistique d'utilisation CertificatTéléchargé
MTES-MCT/potentiel pull request #766
Opened 2022-11-28 17:05 UTC by HubM

2022-11-29 15:46 UTC, HanaeY commented on src/infra/sequelize/migrations/20221128171700-migrer-ProjectCertificateDownloaded-vers-statistiquesUtilisation.ts
> +                utilisateur: { role: 'porteur-projet' },
Ce ne sont pas toujours des téléchargements par un porteur de projet. Tu peux retrouver le rôle de l'utilisateur qui a réalisé l'action grâce au downloadedBy de l'événement ProjectCertificateDownloaded.

2022-11-29 15:52 UTC, HanaeY commented
Est-ce qu'on ne profiterait pas de cette PR pour mettre en place le nouveau système de complétion de la table statistiquesUtilisation, soit appeler `miseAJourStatistiquesUtilisation` aux téléchargements d'attestations ? 
Sinon si on laisse le système actuel avec un ProjectCertificateDownloaded émis à chaque téléchargement, tu vas devoir refaire cette même migration plus tard.

2022-11-29 15:54 UTC, JulienPavon approved these changes

2022-11-29 15:54 UTC, JulienPavon commented on src/infra/sequelize/migrations/20221128171700-migrer-ProjectCertificateDownloaded-vers-statistiquesUtilisation.ts
> +      for (const entrée of évènementsÀMigrer) {
pourquoi `entrée` et pas `évènement` ?

2022-11-29 15:56 UTC, HubM commented on src/infra/sequelize/migrations/20221128171700-migrer-ProjectCertificateDownloaded-vers-statistiquesUtilisation.ts
> +                utilisateur: { role: 'porteur-projet' },
![Capture d’écran 2022-11-29 à 16 55 47](https://user-images.githubusercontent.com/13203242/204578525-53b38572-ebd8-44c2-bb4b-fc8498d0b7d6.png)

L'évènement est déclenché uniquement quand il s'agit d'un PP, c'est pour ça que j'ai mis en dur

2022-11-29 15:57 UTC, JulienPavon commented on src/infra/sequelize/migrations/20221128171700-migrer-ProjectCertificateDownloaded-vers-statistiquesUtilisation.ts
> +                utilisateur: { role: 'porteur-projet' },
Dans le code cet évènement n'est emis que pour les porteurs cf. https://github.com/MTES-MCT/potentiel/blob/master/src/controllers/candidateNotification/getProjectCertificateFile.ts#L28

2022-11-30 09:55 UTC, JulienPavon requested changes

2022-11-30 09:55 UTC, JulienPavon commented on src/controllers/candidateNotification/getProjectCertificateFile.ts
> +                  ...(projet.appelOffreId && { appelOffreId: projet.appelOffreId }),
Pourquoi faire si compliqué pour le passage des infos du projet ?
On peut directement avoir :
```
projet: {
  appelOffreId: projet.appelOffreId,
  periodeId: projet.periodeId,
  familleId: projet.familleId,
  numeroCRE: projet.
},

```

2022-11-30 11:02 UTC, HubM commented on src/controllers/candidateNotification/getProjectCertificateFile.ts
> +                  ...(projet.appelOffreId && { appelOffreId: projet.appelOffreId }),
car des fois on a des familleId qui peuvent etre vide. du coup j'ai pensé que ca serait cool d'avoir conditonnellement les infos, je sais pas ?

2022-11-30 13:13 UTC, JulienPavon commented on src/controllers/candidateNotification/getProjectCertificateFile.ts
> +                  ...(projet.appelOffreId && { appelOffreId: projet.appelOffreId }),
On ne peut pas identifier un projet sans appelOffreId, periodeId, numeroCRE à minima (familleId est optionnel)

2022-11-30 13:17 UTC, JulienPavon commented on src/controllers/candidateNotification/getProjectCertificateFile.ts
> +                  ...(projet.appelOffreId && { appelOffreId: projet.appelOffreId }),
Dans ce cas cette projections n'a pas de typescript donc il faut vérifier la définition de la table. On peut remarquer que ces colonnes n'accepte pas de valeur `null`

2022-11-30 13:17 UTC, JulienPavon approved these changes

2022-11-30 13:19 UTC, HubM commented on src/controllers/candidateNotification/getProjectCertificateFile.ts
> +                  ...(projet.appelOffreId && { appelOffreId: projet.appelOffreId }),
Yes c'est ce que j'ai vu quand je suis repassé sur ton commentaire :)

2022-11-30 13:22 UTC, HanaeY approved these changes

2022-11-30 13:24 UTC, merged