[GF] ajout des handlers de validation/invalidation pour la projection GarantiesFinancières
MTES-MCT/potentiel pull request #772
Opened 2022-11-30 15:52 UTC by flodlc

2022-11-30 16:25 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/garantiesFinancières/updates/onGarantiesFinancièresInvalidées.integration.ts
> +describe(`handler onGarantiesFinancièresValidées pour la projection garantiesFinancières`, () => {
typo 'onGarantiesFinancièresInvalidées'

2022-11-30 16:25 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/garantiesFinancières/updates/onGarantiesFinancièresInvalidées.integration.ts
> +          invalidéesPar: new Date().toISOString(),
invalidéesPar : new UniqueEntityID().toISOString()

2022-11-30 16:25 UTC, HanaeY commented on src/infra/sequelize/projectionsNext/garantiesFinancières/updates/onGarantiesFinancièresValidées.integration.ts
> +  it(`Etant donné un projet existant dans la projection garantiesFinancières avec le statut,
Etant donné une GF avec le statut 'à traiter'

2022-11-30 16:27 UTC, HanaeY commented
+ rebuild de garantiesFinancières

2022-11-30 16:36 UTC, HanaeY submitted a review, later dismissed

2022-12-01 09:02 UTC, HubM requested changes

2022-12-01 09:20 UTC, flodlc commented on src/infra/sequelize/projectionsNext/garantiesFinancières/garantiesFinancières.model.ts
> +  validéesLe: Date | null
En fait avec undefined le type est faux.
Lorsqu'on fait récupère des données, avec findOne Par exemple, on aura `null` et jamais undefined.
Dans certaines projection on a utilisé `undefined` et ça cause pas trop de problème car `undefined` et `null` ont des comportements similaires lorsqu'on les mets dans des `if`. Mais en fait on a null en retour de DB pour les columns.
 
Lorsqu'on update de la donnée, alors on utilise `null` pour passer la valeur `null` en db. Ce que `undefined` ne permet pas.

2022-12-01 09:58 UTC, HubM approved these changes
👍🏼

2022-12-01 09:58 UTC, HanaeY approved these changes

2022-12-01 10:00 UTC, merged