♻️ 1347 simplification ft import données raccordement
MTES-MCT/potentiel pull request #800
Opened 2022-12-08 15:59 UTC by HubM

2022-12-09 09:33 UTC, HanaeY requested changes

2022-12-09 09:33 UTC, HanaeY commented on src/infra/sequelize/migrations/20221207143000-modifier-column-project-dateMiseEnService.ts
> +    await queryInterface.removeColumn('projects', 'dateMiseEnService')
Ici avant de retirer la colonne il faudra s'assurer qu'elle est encore bien vide (à voir avec Julie quand elle a prévu d'importer les données mais maintenant il vaudrait mieux lui demander d'attendre que cette PR soit mergée).

2022-12-09 09:33 UTC, HanaeY commented on src/modules/imports/donnéesRaccordement/events/TâcheMiseAJourDonnéesDeRaccordementDémarrée.ts
> +  données: ({ identifiantGestionnaireRéseau: string } & (
Ici tu peux utiliser le type DonnéesRaccordement

2022-12-09 09:33 UTC, HanaeY commented on src/modules/project/useCases/renseignerDonnéesDeRaccordement.ts
> +        // @ts-ignore
Je m'interroge sur l'utilisation de ce ts-ignore ici, il y a aussi la solution de passer directement la commande en retirant juste le numéro de gestionnaire, ou alors même pour simplifier on pourrait laisser le numéro de gestionnaire dans l'événement DonnéesDeRaccordementRenseignées, à discuter !

2022-12-09 09:33 UTC, JulienPavon requested changes

2022-12-09 09:33 UTC, JulienPavon commented on src/infra/sequelize/projections/project/project.model.ts
> -        type: DataTypes.STRING,
Ne pourrait-on pas plutôt avoir une PR dédiée pour cette partie projection ? Le but du refacto est surtout de simplifier l'utilisation des payload des évènements et là la PR fait beaucoup de choses

2022-12-09 09:41 UTC, HubM commented on src/infra/sequelize/migrations/20221207143000-modifier-column-project-dateMiseEnService.ts
> +    await queryInterface.removeColumn('projects', 'dateMiseEnService')
Actuellement il n'y en a pas, c'est pour ça que je me suis permis de directement faire le changement

2022-12-09 10:20 UTC, JulienPavon commented on src/infra/sequelize/migrations/20221207143000-modifier-column-project-dateMiseEnService.ts
> +    await queryInterface.removeColumn('projects', 'dateMiseEnService')
Et donc pourquoi ne pas changer tout simplement la colonne ?

2022-12-09 10:24 UTC, JulienPavon commented on src/modules/project/useCases/renseignerDonnéesDeRaccordement.ts
> +        // @ts-ignore
D'accord oui en tout cas @ts-ignore devrait être interdit car c'est une source d'erreur

2022-12-09 10:29 UTC, HubM commented on src/infra/sequelize/projections/project/project.model.ts
> -        type: DataTypes.STRING,
En effet on aurait pu mais du coup vu que j'ai déjà fais tout le traitement c'est pour ça que j'ai défini la ft comme une simplification

2022-12-09 10:29 UTC, HubM commented on src/infra/sequelize/queries/project/getProjectDataForSignalerDemandeDelaiPage.integration.ts
> +beforeEach(async () => {
Yes tu as raison

2022-12-09 10:35 UTC, HubM commented on src/infra/sequelize/migrations/20221207143000-modifier-column-project-dateMiseEnService.ts
> +    await queryInterface.removeColumn('projects', 'dateMiseEnService')
Tu préconiserais d'utiliser plutôt le `changeColumn` ? 
Quand j'avais essayé j'avais pas réussi à le faire fonctionner j'avais des erreurs 🤔

2022-12-09 10:38 UTC, HubM commented on src/modules/project/useCases/renseignerDonnéesDeRaccordement.ts
> +        payload: {
J'ai rajouté le @ts-ignore (ce qui est pas fou je l'accorde) car avant on avait ce code :

```
  if ('dateMiseEnService' in commande && 'dateFileAttente' in commande) {
      return publishToEventStore(
        new DonnéesDeRaccordementRenseignées({
          payload: {
            projetId: commande.projetId,
            dateMiseEnService: commande.dateMiseEnService.toISOString(),
            dateFileAttente: commande.dateFileAttente.toISOString(),
          },
        })
      )
    }
    if ('dateMiseEnService' in commande && !('dateFileAttente' in commande)) {
      return publishToEventStore(
        new DonnéesDeRaccordementRenseignées({
          payload: {
            projetId: commande.projetId,
            dateMiseEnService: commande.dateMiseEnService.toISOString(),
          },
        })
      )
    }
    if (!('dateMiseEnService' in commande) && 'dateFileAttente' in commande) {
      return publishToEventStore(
        new DonnéesDeRaccordementRenseignées({
          payload: {
            projetId: commande.projetId,
            dateFileAttente: commande.dateFileAttente.toISOString(),
          },
        })
      )
    }
```

je voulais éviter d'avoir les 3 if consécutifs... Si je laisse mon implémentation actuel sans le `@ts-ignore`, TS relève des erreurs car il considère que certaines dates ne peuvent être `undefined`. Je sais pas comment gérer ce cas en TS, dispo pour en parler si jamais.

2022-12-09 12:55 UTC, JulienPavon commented on src/infra/sequelize/migrations/20221207143000-modifier-column-project-dateMiseEnService.ts
> +    await queryInterface.removeColumn('projects', 'dateMiseEnService')
Oui c'est ça `changeColumn`. Si des erreurs il faudrait essayer de comprendre pourquoi

2022-12-09 15:16 UTC, HanaeY approved these changes
:+1:

2022-12-12 13:45 UTC, JulienPavon approved these changes

2022-12-12 13:47 UTC, merged