🗃️ (Migrations): Ajout de ProjectGFDueDateCancelled pour corriger des projets
MTES-MCT/potentiel pull request #805
Opened 2022-12-09 11:15 UTC by HanaeY

Suite à un refacto dans le code (qui a été corrigé depuis), des événements ProjectGFDueDate set ont été émis pour des projets non soumis à GF après un changement de producteur. 
Dans une requête on récupère les id des projets non soumis à GF mais qui sont associés à un événement ProjectGFDueDateSet dans le store. 
Pour chaque id de ces projets, on émet un nouvel événement ProjectGFDueDateCancelled.

2022-12-09 13:56 UTC, JulienPavon commented on src/infra/sequelize/migrations/20221209113100-correction-projets-ajout-ProjectGFRemoved.ts.ts
> +      if (!projetsACorriger.length) {
Est ce qu'il ne vaudrait pas mieux avoir `if (projetsACorriger.length === 0)` ?

2022-12-09 13:56 UTC, JulienPavon commented on src/infra/sequelize/migrations/20221209113100-correction-projets-ajout-ProjectGFRemoved.ts.ts
> +          await EventStore.create(
Ici on pourrait le faire en une seule instruction avec un `bulkCreate` et un map

2022-12-09 14:58 UTC, HubM requested changes

2022-12-09 14:58 UTC, HubM commented on src/modules/project/events/EtapeGFSupprimée.ts
> +// Suppression des GF quelque soient leur statut pour un projet non soumis à GF
```suggestion
// Suppression des GF quelque soit leur statut pour un projet non soumis à GF
```

2022-12-09 14:58 UTC, HubM commented on src/modules/project/events/EtapeGFSupprimée.ts
> +export interface EtapeGFSuppriméePayload {
pourquoi en faire une interface ici ?

2022-12-09 15:08 UTC, HanaeY commented on src/modules/project/events/EtapeGFSupprimée.ts
> +export interface EtapeGFSuppriméePayload {
Pas de raison, j'était juste partie d'un événement existant

2022-12-09 15:30 UTC, HubM submitted a review, later dismissed
👍🏼

2022-12-12 13:49 UTC, JulienPavon commented on src/modules/project/events/EtapeGFSupprimée.ts
> +export type EtapeGFSuppriméePayload = {
Ne pas exporter ce type qui est seulement utilisé ici.

2022-12-12 14:49 UTC, JulienPavon approved these changes

2022-12-12 14:56 UTC, HubM approved these changes
👍🏼

2022-12-12 14:58 UTC, merged