🔥 (1345): supprimer 'delai' des params disponible pour modificationRequest
MTES-MCT/potentiel pull request #809
Opened 2022-12-09 15:54 UTC by HubM

2022-12-12 14:08 UTC, HanaeY requested changes

2022-12-12 14:08 UTC, HanaeY commented on src/controllers/modificationRequest/postReplyToModificationRequest.ts
> -      case 'delai':
tu peux retirer le  `delayInMonths` ligne 49 et ce bout de code aussi ligne 104`if (type === 'delai' && !isStrictlyPositiveNumber(delayInMonths)) {
      return response.redirect(
        addQueryParams(routes.DEMANDE_PAGE_DETAILS(modificationRequestId), {
          error:
            "La réponse n'a pas pu être envoyée: le délai accordé doit être un nombre supérieur à 0.",
        })
      )
    }`

2022-12-12 14:08 UTC, HanaeY commented on src/modules/modificationRequest/ModificationRequest.ts
>    | { type: 'recours'; newNotificationDate: Date }
On ne peut pas supprimer le type delai ligne 65 aussi N

2022-12-13 09:02 UTC, HanaeY commented on src/controllers/project/postChoisirCahierDesCharges.ts
> +export type TypeDeModificationCDC = ModificationRequestType | 'delai'
Proposition de nommage : `TypeDeModification`(avec le CDC derrière on s'attend à avoir un type de CDC)

2022-12-13 09:04 UTC, HanaeY submitted a review, later dismissed
:+1:

2022-12-13 15:43 UTC, JulienPavon commented on src/views/components/UI/organisms/choisirCahierDesCharges/ChoisirCahierDesChargesFormulaire.tsx
> +import { TypeDeModification } from '../../../../../controllers/project/postChoisirCahierDesCharges'
On ne devrait pas avoir d'import depuis un controlleur dans un composant visuel.

2022-12-14 09:08 UTC, HanaeY commented on src/views/components/UI/organisms/choisirCahierDesCharges/ChoisirCahierDesChargesFormulaire.tsx
> +    | 'actionnaire'
Je me demande si ça ne serait pas mieux de stocker ce type ailleurs pour pouvoir l'utiliser à plusieurs endroits (notamment le contrôleur et ce composant, je ne sais pas s'il y a d'autres endroits..)

2022-12-14 10:43 UTC, HubM commented on src/views/components/UI/organisms/choisirCahierDesCharges/ChoisirCahierDesChargesFormulaire.tsx
> +    | 'actionnaire'
Justement je l'ai dupliqué ici car @JulienPavon m'a fait un retour comme quoi il ne fallait pas importer un type provenant d'un controller

2022-12-14 12:37 UTC, HanaeY commented on src/views/components/UI/organisms/choisirCahierDesCharges/ChoisirCahierDesChargesFormulaire.tsx
> +    | 'actionnaire'
Et on ne peut pas stocker le type ailleurs que dans le contrôleur ? c'est juste un peu dommage de dupliquer notamment si un jour on change le type dans le contrôleur, il faut aussi penser à le changer dans le composant.

2022-12-14 12:40 UTC, HubM commented on src/views/components/UI/organisms/choisirCahierDesCharges/ChoisirCahierDesChargesFormulaire.tsx
> +    | 'actionnaire'
Je suis bien d'accord, discutons en pour nous mettre d'accord

2022-12-14 13:48 UTC, HanaeY approved these changes

2022-12-14 14:04 UTC, JulienPavon approved these changes

2022-12-14 14:11 UTC, merged