✨ (1328): Pouvoir inviter un utilisateur CRE
MTES-MCT/potentiel pull request #810
Opened 2022-12-09 16:26 UTC by JulienPavon

2022-12-15 13:22 UTC, HubM commented on src/controllers/userAccount/getSignupPage.ts
> +          ? { utilisateurInvité: true, email: query.email.toString() }
Pourquoi avoir besoin de faire un `toString()` ici ?

2022-12-15 13:37 UTC, HubM requested changes

2022-12-15 13:37 UTC, HubM commented on src/infra/sequelize/migrations/20221209153846-modification-User-fullname-colonne.ts
> +}
Y a un oubli de modification ici ? les changements sont les même entre up et down c'est normal?

2022-12-15 13:37 UTC, HubM commented on src/modules/utilisateur/créerProfil/créerProfilUtilisateur.spec.ts
> +    it(`Étant donné un utilisateur invité en tant que 'CRE'
Pourquoi on teste spécifiquement CRE et pas les autres profils (hors PP) ? On pourrait faire un `for` ici

2022-12-15 13:37 UTC, HubM commented on src/modules/utilisateur/créerProfil/créerProfilUtilisateur.spec.ts
On test pas le scénario du profil déjà existant ?

2022-12-15 13:54 UTC, HanaeY commented on src/controllers/userAccount/getSignupPage.ts
> +          ? { utilisateurInvité: true, email: query.email.toString() }
query.email n'est pas de type string

2022-12-15 14:01 UTC, HanaeY commented on src/modules/utilisateur/créerProfil/créerProfilUtilisateur.spec.ts
> +    it(`Étant donné un utilisateur invité en tant que 'CRE'
Le scénario de ce test a été écrit quand on avait une validation du rôle dans l'implémentation : on comparait un rôle passé dans la commande au rôle de l'agrégat. Mais j'ai retiré cette validation car le contrôleur ne passe pas de rôle. Donc je mets à jour le scenario pour que ça soit plus clair. On va réintroduire une notion de rôle pour le cas porteur dans une autre PR.

2022-12-15 14:07 UTC, HanaeY commented on src/modules/utilisateur/créerProfil/créerProfilUtilisateur.spec.ts
si c'est le premier test (ligne 7)

2022-12-16 08:19 UTC, HubM submitted a review, later dismissed
👍🏼

2022-12-16 12:11 UTC, flodlc approved these changes

2022-12-16 12:11 UTC, flodlc commented on src/infra/sequelize/projectionsNext/users/updates/onRôleUtilisateurModifié.ts
> +          nomProjection: 'Users.RôleUtilisateurModifié',
Dans d'autres cas il me semble qu'en nom de projection on mettrait Users. A définir pour être cohérent.
Idem pour les autres cas de cette PR. Non bloquant.

2022-12-16 12:11 UTC, flodlc commented on src/config/useCases.config.ts
>  const publishToEventStore = eventStore.publish.bind(eventStore)
Je suis curieux de savoir si c'est vraiment indispensable de faire un bind manuel sachant que la fonction `publish` est définit avec une arrow function dans l'eventStore donc devrait être bindée à son contexte il me semble

2022-12-16 14:12 UTC, HanaeY approved these changes

2022-12-16 14:13 UTC, JulienPavon commented on src/config/useCases.config.ts
>  const publishToEventStore = eventStore.publish.bind(eventStore)
Effectivement à mon avis comme ce n'est pas une classe mais juste un regroupement de fonction je pense qu'on peut se passer du bind. Il faudrait prévoir une tâche de refactoring pour tester et nettoyer ça

2022-12-16 14:16 UTC, JulienPavon commented on src/infra/sequelize/projectionsNext/users/updates/onRôleUtilisateurModifié.ts
> +          nomProjection: 'Users.RôleUtilisateurModifié',
Effectivement et c'est plus logique. Comme c'est le cas dans d'autres projections je vais faire ce changement dans une autre PR. Merci !

2022-12-16 14:17 UTC, merged