♻️ (1357): utilisation de dateMiseEnService au format Date
MTES-MCT/potentiel pull request #816
Opened 2022-12-13 14:09 UTC by HubM

2022-12-13 15:54 UTC, JulienPavon requested changes

2022-12-13 15:54 UTC, JulienPavon commented on src/infra/sequelize/migrations/20221213094500-migration-dateMiseEnService-format-date.ts
> +          console.error(e)
S'il y a une erreur on ne devrait pas rollback et annuler la modifications ? Le problème c'est qu'en supprimant directement la colonne on perdra les infos. Peut être vaudrait-il mieux ne supprimer la colonne qu'une fois le traitement totalement terminé

2022-12-15 13:36 UTC, HanaeY approved these changes

2022-12-15 14:11 UTC, flodlc approved these changes

2022-12-16 10:22 UTC, HanaeY submitted a review, later dismissed

2022-12-16 10:24 UTC, JulienPavon submitted a review, later dismissed

2022-12-16 10:32 UTC, JulienPavon approved these changes

2022-12-16 10:38 UTC, merged