🚧 (1370): adpater le nom du fichier aux règles de nommage interne
MTES-MCT/potentiel pull request #823
Opened 2022-12-15 10:43 UTC by HubM

2022-12-16 08:56 UTC, flodlc requested changes

2022-12-16 08:56 UTC, flodlc commented on src/controllers/modificationRequest/getModeleReponse.ts
> +  const nomDeFichier = `${new Date().getFullYear()}-XXX - ${initials} - ${type} ${appelOffreId.toUpperCase()} ${periodeId.toUpperCase()} - ${données.nomCandidat.toUpperCase()} - ${données.nomProjet.t
Je crois qu'il y a un espace en trop à la fin du nom du fichier

2022-12-16 12:52 UTC, flodlc approved these changes

2022-12-19 09:40 UTC, HanaeY requested changes

2022-12-19 09:40 UTC, HanaeY commented on src/controllers/modificationRequest/getModeleReponse.ts
> +  const nomDeFichier = `${new Date().getFullYear()}-XXX - ${initials} - ${type} ${appelOffreId.toUpperCase()} ${periodeId.toUpperCase()} - ${données.nomCandidat.toUpperCase()} - ${données.nomProjet.t
Il me semble qu'il faut un `T` devant le numéro de période

2022-12-19 09:40 UTC, HanaeY commented on src/controllers/modificationRequest/getModeleReponse.ts
> +  const initials = user.fullName
Initiales à passer en majuscules peut être ?

2022-12-19 10:27 UTC, HubM commented on src/controllers/modificationRequest/getModeleReponse.ts
> +  const initials = user.fullName
Bah c'était comme le modèle que m'avait donné Julie :/

2022-12-19 13:52 UTC, HanaeY approved these changes

2022-12-19 13:54 UTC, merged