🛂 (1423): Mise à jour des éléments visible dans la frise par la CRE
MTES-MCT/potentiel pull request #862
Opened 2022-12-30 09:21 UTC by HubM

2022-12-30 13:23 UTC, JulienPavon requested changes

2022-12-30 13:23 UTC, JulienPavon commented on src/infra/sequelize/queries/frise/getGarantiesFinancièresDTO.ts
> +    !userIs(['porteur-projet', 'admin', 'dgec-validateur', 'dreal', 'caisse-des-dépôts', 'cre'])(
Pourquoi interdire l'accès aux infos des GFs pour le role CRE ?

2022-12-30 13:23 UTC, JulienPavon commented on src/infra/sequelize/queries/frise/getGarantiesFinancièresDTO.integration.ts
> +          'cre',
La CRE doit avoir accès aux données des GFs

2022-12-30 13:40 UTC, JulienPavon requested changes
Je pense qu'il manque l'accès CRE pour les demandes 'DemandeAbandon' et probablement les autres

2022-12-30 13:48 UTC, JulienPavon requested changes

2022-12-30 13:48 UTC, JulienPavon commented on src/infra/sequelize/queries/frise/getProjectEvents.ts
> +                  if (
Pourquoi avoir ajouté ce block d'instruction alors qu'il est identique au suivant `case` ?

2022-12-30 16:53 UTC, JulienPavon submitted a review, later dismissed

2023-01-02 13:16 UTC, HanaeY commented
Dans getProjectEvents, il me semble qu'il faut aussi retourner les événements pour le type 'LegacyModificationFileAttached', sauf si vous avez vu avec Julie que la CRE n'a pas accès aux courriers de réponse des demandes legacy ?

2023-01-03 08:07 UTC, JulienPavon approved these changes

2023-01-03 08:54 UTC, merged