47 PP can submit PTF
MTES-MCT/potentiel pull request #87
Opened 2021-02-05 17:01 UTC by paduc

2021-02-21 20:52 UTC, Zekdar requested changes

2021-02-21 20:52 UTC, Zekdar commented on src/controllers/steps/getRemoveStep.ts
> +    if (!projectId || !['ptf'].includes(type)) {
Si on veut rejeter la requête dans le cas où `type` est différent de  `ptf`, il vaudrait mieux écrire `type !== 'ptf'`

2021-02-21 20:52 UTC, Zekdar commented on src/controllers/steps/postSubmitStep.ts
> +    if (!projectId || !['ptf'].includes(type)) {
Même remarque pour `ptf`

2021-02-21 20:52 UTC, Zekdar commented on src/controllers/steps/postSubmitStep.ts
> +    if (type === 'ptf' && !ptfDate) {
Ici `type` est forcément égal à `ptf` grâce à la ligne 21. A enlever.

2021-02-21 20:52 UTC, Zekdar commented on src/controllers/steps/postSubmitStep.ts
> +    }
A exporter dans une fonction privée `convertDate()`

2021-02-21 20:52 UTC, Zekdar commented on src/controllers/steps/postSubmitStep.ts
> +            "Votre dépôt n'a pas pu être transmis. Merci de joindre l'attestation en pièce-jointe.",
Pour éviter la répétition `joindre / pièce-jointe` => `Merci d'attacher l'attestation en pièce-jointe.`

2021-02-21 20:52 UTC, Zekdar commented on src/controllers/steps/postSubmitStep.ts
> +            error: "Votre demande n'a pas pu être prise en compte: " + e.message,
Utiliser l'interpollation de string pour garder une code base homogène

2021-02-21 20:52 UTC, Zekdar commented on src/infra/sequelize/queries/getProjectDataForProjectPage.ts
> +        result.ptf = { submittedOn, file: file && file.get(), ptfDate: stepDate }
`file?.get()`

2021-02-21 20:52 UTC, Zekdar commented on src/modules/project/events/ProjectPTFSubmitted.ts
> +    // convert to date (in case it is a string)
Pourrait-on forcer le type en Date pour éviter d'avoir une string à convertir ?

2021-02-22 09:15 UTC, paduc commented on src/controllers/steps/getRemoveStep.ts
> +    if (!projectId || !['ptf'].includes(type)) {
C'est un controlleur générique pour toutes les étapes du projet. Pour l'instant, il n'y a que ptf de possible mais on va rajouter les autres à court terme. D'où l'usage d'un array et `includes`.

2021-02-22 09:16 UTC, paduc commented on src/controllers/steps/postSubmitStep.ts
> +    if (type === 'ptf' && !ptfDate) {
Bientôt, ce ne sera pas le cas (quand on rajoutera les autres types). Je préfère le laisser pour éviter des régressions.

2021-02-22 09:19 UTC, paduc commented on src/modules/project/events/ProjectPTFSubmitted.ts
> +    // convert to date (in case it is a string)
Le payload peut provenir d'un json qui est en base. C'est pourquoi lors de la deserialization, les dates ne sont pas pas forcément en `Date`.

2021-02-22 09:50 UTC, Zekdar commented on src/controllers/steps/getRemoveStep.ts
> +    if (!projectId || !['ptf'].includes(type)) {
Ok

2021-02-22 09:52 UTC, Zekdar approved these changes

2021-02-22 09:58 UTC, merged