Dont use project repo
MTES-MCT/potentiel pull request #873
Opened 2023-01-04 17:02 UTC by JulienPavon

2023-01-06 13:54 UTC, HubM requested changes

2023-01-06 13:54 UTC, HubM commented on src/infra/sequelize/projections/project/project.model.ts
> +      // freezeTableName: true,
commentaire à supprimer ?

2023-01-09 13:18 UTC, HanaeY commented on src/infra/sequelize/projections/project/project.model.ts
> +  actionnariat: string
Actionnariat est optionnel il me semble. A moins que la valeur dans ce cas soit une chaîne vide ?

2023-01-09 13:21 UTC, HanaeY commented on src/infra/sequelize/projections/project/project.model.ts
> +  actionnariat: string
Aussi on pourrait typer les valeurs possibles : financement collectif ou gouvernance partagée

2023-01-09 13:53 UTC, JulienPavon commented on src/infra/sequelize/projections/project/project.model.ts
> +  actionnariat: string
Il me semble que c'est une chaine vide

2023-01-09 14:14 UTC, HanaeY approved these changes

2023-01-09 14:19 UTC, merged