:sparkles: 1486 - Accorder annulation abandon
MTES-MCT/potentiel pull request #893
Opened 2023-01-19 16:45 UTC by HanaeY

2023-01-20 09:52 UTC, JulienPavon requested changes

2023-01-20 09:52 UTC, JulienPavon commented on src/config/eventHandlers/project.eventHandlers.ts
> +
Spécifié 'Project' comme nom de consommateur pour éviter de relire tous les msg redis lors de l'ajout d'un prochain évènement de la projection Project

2023-01-20 09:52 UTC, JulienPavon commented on src/infra/sequelize/projections/project/updates/onAbandonProjetAnnulé.ts
> +  Object.assign(projectInstance, {
On pourrait peut être plutôt passer par un `.update` directement non ?

2023-01-20 13:04 UTC, JulienPavon submitted a review, later dismissed

2023-01-20 13:42 UTC, HubM requested changes

2023-01-20 13:42 UTC, HubM commented on src/modules/demandeModification/demandeAnnulationAbandon/accorder/StatutDemandeIncompatibleAvecAccordAnnulationAbandonError.ts
> +}
Y a peut-être moyen d'harmoniser cette erreur avec celle du rejet de la demande? On pourrait soit : 
- trouver un wording commun, et passer le fait d'accepter ou de refuser via un params
- soit simplement que l'erreur du rejet ressemble à celle que tu as décrite ici

2023-01-20 16:36 UTC, HanaeY commented on src/modules/demandeModification/demandeAnnulationAbandon/accorder/StatutDemandeIncompatibleAvecAccordAnnulationAbandonError.ts
> +}
J'ai mis la même phrase aux deux erreurs, en précisant le statut actuel de la demande

2023-01-20 16:48 UTC, HubM approved these changes
:+1:

2023-01-23 11:06 UTC, JulienPavon approved these changes

2023-01-23 11:07 UTC, merged