🎨 Amélioration typage modèle de réponse annulation abandon
MTES-MCT/potentiel pull request #898
Opened 2023-01-23 15:30 UTC by HubM

2023-01-23 17:11 UTC, JulienPavon requested changes

2023-01-23 17:11 UTC, JulienPavon commented on src/controllers/modificationRequest/getModeleReponse.ts
>    if (type === 'abandon' && status === 'demande confirmée') {
Il faudrait avoir ce cas dans le usecase 'abandon'

2023-01-24 13:14 UTC, HubM commented on src/controllers/modificationRequest/getModeleReponse.ts
>    if (type === 'abandon' && status === 'demande confirmée') {
Actuellement tout se passe dans ce controller `getModeleReponse.ts`, on va aller récupérer le type de demande et le status et retourner le bon docx rempli. Je vois pas trop où je pourrais me mettre le use-case `demandeAbandon`, tu avais une idée spécifique en tête ?

2023-01-24 15:46 UTC, JulienPavon commented on src/controllers/modificationRequest/getModeleReponse.ts
>    if (type === 'abandon' && status === 'demande confirmée') {
Ah non désolé je voulais dire le case du switch plus bas

2023-01-24 16:37 UTC, HubM commented on src/controllers/modificationRequest/getModeleReponse.ts
>    if (type === 'abandon' && status === 'demande confirmée') {
Ah ok je comprends mieux du coup

2023-01-25 08:17 UTC, JulienPavon approved these changes

2023-01-25 08:30 UTC, merged