✨  Ajout d'un composant barre de recherche conforme DSFR
MTES-MCT/potentiel pull request #906
Opened 2023-01-30 16:18 UTC by HubM

2023-02-06 13:39 UTC, JulienPavon requested changes

2023-02-06 13:39 UTC, JulienPavon commented on src/views/components/UI/atoms/InputSearch.tsx
> +export const InputSearch: FC<InputSearchProps> = ({
Ce composant ne serait-il pas plus une molécule ? Et en tant que molécule peut être vaudrait-il mieux la nommer nenrançais ?

2023-02-06 13:39 UTC, JulienPavon commented on src/views/components/UI/atoms/InputSearch.tsx
> +      <input
Est ce qu'on ne devrait pas utiliser l'atome `Input` ici ?

2023-02-06 13:39 UTC, JulienPavon commented on src/views/components/UI/atoms/InputSearch.tsx
> +      <button
Idem pourquoi ne pas utiliser l'atome `Button` ?

2023-02-06 13:39 UTC, JulienPavon commented on src/views/components/UI/atoms/icons.ts
> +export { FiSearch as SearchIcon } from '@react-icons/all-files/fi/FiSearch'
La bibliothèque d'icones utilisée par le DSFR est la Remix et non la Feather

2023-02-06 13:39 UTC, JulienPavon commented on src/views/pages/garantiesFinancieresPage/GarantiesFinancieres.tsx
> +            <div className="mt-5 form__group">
On devrait pouvoir se passer de la classe `form__group`

2023-02-06 13:39 UTC, JulienPavon commented on src/views/pages/garantiesFinancieresPage/GarantiesFinancieres.tsx
> +                className="pr-10"
Ce `padding` est il vraiment nécessaire ?

2023-02-06 13:39 UTC, JulienPavon commented on src/views/pages/AdminNotificationCandidatsPage.tsx
> +              <InputSearch name="recherche" className="pr-10" defaultValue={recherche || ''} />
Il faudrait un `placeholder` ici pour savoir sur quoi se fait la recherche

2023-02-06 13:39 UTC, JulienPavon commented on src/views/pages/ListeProjetsPage.tsx
> +              {/* <input
Commentaire à supprimer

2023-02-06 15:37 UTC, HubM commented on src/views/pages/AdminNotificationCandidatsPage.tsx
> +              <InputSearch name="recherche" className="pr-10" defaultValue={recherche || ''} />
Par défaut le composant retourne "Rechercher"

2023-02-06 15:50 UTC, JulienPavon commented on src/views/pages/AdminNotificationCandidatsPage.tsx
> +              <InputSearch name="recherche" className="pr-10" defaultValue={recherche || ''} />
Ok mais dans quoi allons nous rechercher ? nom de projet, appel d'offre ...

2023-02-06 16:19 UTC, JulienPavon commented on src/views/components/UI/molecules/BarreDeRecherche.tsx
> +  name?: string
Je mettrai cette props comme obligatoire

2023-02-06 16:25 UTC, HubM commented on src/views/components/UI/molecules/BarreDeRecherche.tsx
> +  name?: string
Tu parles de laquelle ? placeholder + name ?

2023-02-06 16:41 UTC, HubM commented on src/views/pages/AdminNotificationCandidatsPage.tsx
> +              <InputSearch name="recherche" className="pr-10" defaultValue={recherche || ''} />
J'ai regardé et on va chercher un projet dont la recherche match en se basant sur la liste de colonnes suivante : 
```ts
  const defaultSearchedProjectsColumns = [
    'nomCandidat',
    'nomProjet',
    'nomRepresentantLegal',
    'email',
    'adresseProjet',
    'codePostalProjet',
    'communeProjet',
    'departementProjet',
    'regionProjet',
    'numeroCRE',
    'details.Nom et prénom du signataire du formulaire',
    'details.Nom et prénom du contact',
    'potentielIdentifier',
  ]
 ```
 
 Ça fait beaucoup pour un seul placeholder 🤔

2023-02-06 16:42 UTC, HubM commented on src/views/pages/AdminNotificationCandidatsPage.tsx
> +              <InputSearch name="recherche" className="pr-10" defaultValue={recherche || ''} />
C'est pour ça que j'avais laissé la valeur par défaut, à savoir "Rechercher"

2023-02-06 16:47 UTC, JulienPavon commented on src/views/pages/AdminNotificationCandidatsPage.tsx
> +              <InputSearch name="recherche" className="pr-10" defaultValue={recherche || ''} />
Oui tu as raison laissons comme ça et d'ailleurs j'ai du mal à voir l'intérêt de filtrer cette page

2023-02-07 09:16 UTC, JulienPavon requested changes

2023-02-07 09:16 UTC, JulienPavon commented on src/views/components/forms/Label.tsx
> +export const Label = ({ required, children, ...props }: LabelProps) => (
Est ce qu'on en profiterai pas pour déplacer ça dans les atomes ?

2023-02-07 09:16 UTC, JulienPavon commented on src/views/components/inputs/Input.tsx
> +export const Input = ({ className = '', error, onChange, ...props }: InputProps) => {
Est ce qu'on en profiterai pas pour déplacer ça dans les atomes ?

2023-02-07 12:29 UTC, JulienPavon requested changes

2023-02-07 12:29 UTC, JulienPavon commented on src/views/components/UI/atoms/Input.tsx
>  export const Input = ({ className = '', error = '', onChange, ...props }: InputProps) => {
Ajouter une story

2023-02-07 12:29 UTC, JulienPavon commented on src/views/components/UI/atoms/Label.tsx
> +export const Label = ({ required, children, ...props }: LabelProps) => (
Ajouter une story

2023-02-07 13:52 UTC, JulienPavon approved these changes

2023-02-07 14:07 UTC, merged