👔 1486 (Effets AnnulationAbandonAccordé): Nouvelles GF dues
MTES-MCT/potentiel pull request #909
Opened 2023-02-01 10:55 UTC by HanaeY

2023-02-02 10:44 UTC, JulienPavon requested changes

2023-02-02 10:44 UTC, JulienPavon commented on src/modules/project/eventHandlers/onAnnulationAbandonAccordée.ts
>  export const makeOnAnnulationAbandonAccordée =
Je ne vois aucun tests pour cette partie alors qu'il s'agit bien de règles métier et pas seulement de projection de données

2023-02-02 10:59 UTC, HanaeY commented on src/modules/project/eventHandlers/onAnnulationAbandonAccordée.ts
>  export const makeOnAnnulationAbandonAccordée =
Comme l'implémentation est simple je me suis dit que ce n'était pas forcément nécessaire, mais si c'est pour couvrir le risque de régression aussi je peux effectivement ajouter un test !

2023-02-02 12:50 UTC, JulienPavon commented on src/modules/project/eventHandlers/onAnnulationAbandonAccordée.ts
>  export const makeOnAnnulationAbandonAccordée =
Oui en fait c'est comme pour le cas des query sur les projections. Même si ça reste simple il vaut mieux avoir un test et d'ailleurs si l'implémentation est simple le test devrait l'être aussi et ça nous permet de faire des refactorings en ayant toujours le besoin de couvert

2023-02-06 10:46 UTC, JulienPavon requested changes

2023-02-06 10:46 UTC, JulienPavon commented on src/modules/project/eventHandlers/onAnnulationAbandonAccordée.spec.ts
> +    it(`Etant donné un événement AnnulationAbandonAccordée émis pour un projet soumis à GF,
Ici il faudrait revoir la formulation de la 1ère partie du scénario :
```
Étant donné un projet soumis aux GFs
Lorsqu'un évènement 'AnnulationAbandonAccordée' est emis pour celui-ci
Alors....
```

Quand on formule le besoin sous forme de scénario l'étape `Étant donné que...` mets en place un contexte. Ici un projet soumis aux GFs. Cette étape n'est pas obligatoire pour tous les scénario car certaines fois un contexte n'est pas nécessaire.
Par contre il faut toujours avoir l'étape qui déclenche la commande métier et pour ça on utilise le mot clé `Lorsque/Quand`. Ici ça correspond à l'émission d'un évènement.

2023-02-06 10:46 UTC, JulienPavon commented on src/modules/project/eventHandlers/onAnnulationAbandonAccordée.spec.ts
> +  const projectRepo = fakeTransactionalRepo(
Cette partie n'est elle pas spécifique au scénatio ci-dessous uniquement ? Si oui il vaudrait mieux tous déplacer dans le `it` correspondant.

2023-02-06 12:08 UTC, HanaeY commented on src/modules/project/eventHandlers/onAnnulationAbandonAccordée.spec.ts
> +  const projectRepo = fakeTransactionalRepo(
Non on passe le même projectRepo aux deux scenarios, ce qui change c'est l'appel d'offres

2023-02-06 13:04 UTC, JulienPavon commented on src/modules/project/eventHandlers/onAnnulationAbandonAccordée.spec.ts
> +        lorsqu'un événement AnnulationAbandonAccordée émis pour ce projet,
"EST émis"

2023-02-06 13:51 UTC, merged