:lipstick:  1536 - liens téléchargement explicites
MTES-MCT/potentiel pull request #910
Opened 2023-02-01 16:05 UTC by HanaeY

Utilisation partout où nécessaire des composants DownloadLink, SecondaryLinkButton ...

2023-02-02 14:21 UTC, HubM requested changes

2023-02-02 14:21 UTC, HubM commented on src/views/pages/demanderAbandonPage/DemanderAbandon.tsx
>                </div>
Je pense qu'on devrait inverser l'ordre des boutons, et mettre l'annulation à droite, et l'envoi à droite (plus logique et habituel pour les utilisateurs)

2023-02-02 14:21 UTC, HubM commented on src/views/pages/modificationRequestPage/components/DemandeDetails.tsx
> +          </SecondaryLinkButton>
C'est bizzare d'avoir un bouton là, ça devrait plutôt être un DownloadLink, comme les autres. Il faut également que l'icone soit situé après l'intitulé

2023-02-02 16:48 UTC, HanaeY commented on src/views/pages/demanderAbandonPage/DemanderAbandon.tsx
>                </div>
Je ne suis pas sûre de comprendre ton idée. Le bouton "Annuler" est déjà à droite (comme sur les autres formulaires de modification d'ailleurs).

2023-02-03 08:34 UTC, HubM approved these changes
👍🏼

2023-02-03 08:37 UTC, merged