✨ (1455):  Afficher le numéro de gestionnaire de réseau dans la page du détail d'un projet
MTES-MCT/potentiel pull request #919
Opened 2023-02-07 14:29 UTC by JulienPavon

2023-02-08 14:30 UTC, HanaeY requested changes

2023-02-08 14:30 UTC, HanaeY commented on src/infra/sequelize/queries/project/consulter/getProjectDataForProjectPage.ts
> +  ): ResultAsync<{ project: any; appelOffre: ProjectAppelOffre }, EntityNotFoundError> => {
ça ne fonctionne pas avec le type `Project` ?

2023-02-08 14:30 UTC, HanaeY commented on src/views/pages/projectDetailsPage/sections/GestionnaireDeRéseau.tsx
> +    <div className="mb-[10px]">Identifiant: {numeroGestionnaire}</div>
il manque un espace avant les `:` : `Identifiant : `

2023-02-08 15:02 UTC, JulienPavon commented on src/infra/sequelize/queries/project/consulter/getProjectDataForProjectPage.ts
> +  ): ResultAsync<{ project: any; appelOffre: ProjectAppelOffre }, EntityNotFoundError> => {
Non à cause de propriétés qui ne sont pas déclarée dans le type du model sequelize. J'avais essayé sans succès au début mais je peut réessayer

2023-02-08 15:40 UTC, JulienPavon commented on src/infra/sequelize/queries/project/consulter/getProjectDataForProjectPage.ts
> +    if (!project || (!project.notifiedOn && userIsNot(['admin', 'dgec-validateur', 'cre'])(user))) {
J'ai gardé la logique qu'il y avait déjà et on peut se poser la question effectivement. Est ce qu'il faut indiquer que l'accès au projet n'est pas autorisé et dire implicitement que le projet existe ou bien tout simplement dire qu'il n'existe pas du tout pour l'utilisateur. Ça dépend du degré de confidentialité de l'accès aux projets non notifiés pour les rôles ne devant pas y accéder

2023-02-08 15:56 UTC, JulienPavon commented on src/infra/sequelize/queries/project/consulter/getProjectDataForProjectPage.gestionnaire-de-réseau.integration.ts
> +      for (const role of ['ademe', 'caisse-des-dépôts']) {
Aujourd'hui le besoin est de ne pas inclure les données pour ces 2 rôles. Devons nous pour autant y inclure aussi les futurs rôles ? Je pense qu'il vaudrait mieux au plus vite séparer les requêtes par rôles et ce sera bcp plus simple.

2023-02-08 16:56 UTC, HanaeY commented on src/infra/sequelize/queries/project/consulter/getProjectDataForProjectPage.ts
> +            prixReference,
les rôles qui ont accès au prix : admin, dgec-validateur, porteur-projet, dreal, acheteur-obligé, cre. L'ademe et la caisse des dépôts n'ont pas accès à cette donnée. Mais en réalité on n'affiche le prix que pour les rôles DGEC dans le formulaire modif projet, donc on pourrait peut être se limiter à ces deux rôles ?

2023-02-08 17:00 UTC, JulienPavon commented on src/infra/sequelize/queries/project/consulter/getProjectDataForProjectPage.ts
> +            prixReference,
En vrai aujourd'hui le prix n'est visible que dans la partie édition. Je veux bien faire la modification mais il va y avoir beaucoup de données dans ce genre tant que nous n'aurons pas séparé la partie modification de la partie consultation

2023-02-10 09:47 UTC, HanaeY approved these changes

2023-02-10 09:48 UTC, merged