:recycle: 1478 - récupérer données pour candidats notification page
MTES-MCT/potentiel pull request #924
Opened 2023-02-10 16:56 UTC by HanaeY

refacto de la query qui n'a plus besoin d'utiliser des dépendances venant du oldProjectRepo

2023-02-13 13:48 UTC, HubM commented on src/infra/sequelize/queries/project/lister/getDonnéesPourPageNotificationCandidats.integration.ts
> +    describe(`Affichage de la page sans filtres sur un AO et période spécifiques`, () => {
Je pense qu'on peut virer les describe dans ces scénarios. Les `it()` ont une description suffisante à bien faire comprendre le contexte du scénario

2023-02-13 13:54 UTC, HubM requested changes
quelques commentaires

2023-02-14 11:28 UTC, HubM submitted a review, later dismissed
👍🏼

2023-02-14 13:17 UTC, JulienPavon requested changes

2023-02-14 13:17 UTC, JulienPavon commented on src/infra/sequelize/queries/project/lister/getDonnéesPourPageNotificationCandidats.ts
> +      return null
Est ce qu'on ne devrait pas retourner une liste vide plutôt que null ?

2023-02-14 13:17 UTC, JulienPavon commented on src/infra/sequelize/queries/project/lister/getDonnéesPourPageNotificationCandidats.ts
> +    const listeAOs = projetsNonNotifiés.reduce(
J'aurai bien mis les logiques pour récupérer les filtres dans différentes fonctions (privées) pour amélioré la lisibilité

2023-02-14 15:35 UTC, merged