:sparkles: (1173): Renseigner son gestionnaire réseau et son identifiant
MTES-MCT/potentiel pull request #978
Opened 2023-02-28 10:22 UTC by HanaeY

- choix d'un gestionnaire dans un menu déroulant
- aide à la saisie selon le gestionnaire choisi

2023-03-02 15:44 UTC, HubM requested changes

2023-03-02 15:44 UTC, HubM commented on src/infra/sequelize/projectionsNext/raccordements/updates/onNumeroGestionnaireSubmitted.integration.ts
> +      Alors des deux données devraient être enregistrée`, async () => {
```suggestion
      Alors ces deux données devraient être enregistrée`, async () => {
```

2023-03-02 15:44 UTC, HubM commented on src/infra/sequelize/projectionsNext/raccordements/updates/onNumeroGestionnaireSubmitted.integration.ts
> +          codeEICGestionnaireRéseau: undefined,
On a vraiment besoin de renseigner `codeEICGestionnaireRéseau: undefined` ici ? Sachant que vu qu'il est pas obligatoire il ne sera pas maj

2023-03-02 15:44 UTC, HubM commented on src/infra/sequelize/queries/project/résuméProjetQueryHandler.integration.ts
> +    // Arrange
commentaire à supprimer

2023-03-02 15:44 UTC, HubM commented on src/infra/sequelize/queries/project/résuméProjetQueryHandler.integration.ts
> +    // Act
commentaire à supprimer

2023-03-02 15:44 UTC, HubM commented on src/infra/sequelize/queries/project/résuméProjetQueryHandler.integration.ts
> +    // Assert
commentaire à supprimer

2023-03-02 15:44 UTC, HubM commented on src/infra/sequelize/queries/project/résuméProjetQueryHandler.integration.ts
> +    // Arrange
commentaire à supprimer

2023-03-02 15:44 UTC, HubM commented on src/infra/sequelize/queries/project/résuméProjetQueryHandler.integration.ts
> +    // Act
commentaire à supprimer

2023-03-02 15:44 UTC, HubM commented on src/infra/sequelize/queries/project/résuméProjetQueryHandler.integration.ts
> +    // Assert
commentaire à supprimer

2023-03-02 15:44 UTC, HubM commented on src/modules/project/useCases/renseignerIdentifiantGestionnaireRéseau.factory.spec.ts
> +
on devrait pas tester que l'erreur retournée est bien de type `CodeEICNonTrouvéError` ?

2023-03-02 15:44 UTC, HubM commented on src/modules/project/useCases/renseignerIdentifiantGestionnaireRéseau.factory.ts
> +      : okAsync(null);
Je suis pas mega fan des double ternaires, je trouve que ça entrave la lisibilité du code. Je te propose l'implémentation suivante : 

```suggestion
  }) => {
    if (projet.identifiantGestionnaireRéseau !== identifiantGestionnaireRéseau) {
      return publish(
          new NumeroGestionnaireSubmitted({
            payload: {
              projectId: projetId,
              submittedBy: utilisateur.id,
              numeroGestionnaire: identifiantGestionnaireRéseau,
              ...(codeEICGestionnaireRéseau && { codeEICGestionnaireRéseau }),
            },
          }),
        )
    }

    if (codeEICGestionnaireRéseau) {
      return publish(
          new GestionnaireRéseauRenseigné({
            payload: {
              projectId: projetId,
              submittedBy: utilisateur.id,
              codeEIC: codeEICGestionnaireRéseau,
            },
          }),
        )
    }

    return okAsync(null)
  }
```

2023-03-02 15:44 UTC, HubM commented on src/views/pages/modifierIdentifiantGestionnaireReseauPage/ModifierIdentifiantGestionnaireReseau.tsx
> +            </div>
je sais pas si la <div> apporte grand chose, ptet qu'on peut directement passer par une balise vide

```suggestion
            <>
              <Label htmlFor="codeEICGestionnaireRéseau">Gestionnaire de réseau</Label>
              <Select
                id="codeEICGestionnaireRéseau"
                name="codeEICGestionnaireRéseau"
                onChange={(e) => handleGestionnaireSéléctionné(e)}
                defaultValue={projet.gestionnaireRéseau?.codeEIC || ''}
              >
                {!projet.gestionnaireRéseau?.codeEIC && <option selected disabled hidden></option>}
                {listeGestionnairesRéseau.map(({ codeEIC, raisonSociale }) => (
                  <option value={codeEIC} key={codeEIC}>
                    {raisonSociale} (code EIC : {codeEIC})
                  </option>
                ))}
              </Select>
            </>
```

2023-03-02 15:45 UTC, HubM requested changes
Je t'ai fais quelques commentaires + suggestions de changes

2023-03-02 15:54 UTC, HubM requested changes

2023-03-02 15:54 UTC, HubM commented on src/views/pages/modifierIdentifiantGestionnaireReseauPage/ModifierIdentifiantGestionnaireReseau.tsx
> +  const [légende, setLégende] = useState('');
En testant je me suis rendu compte d'un petit problème : 
1. Je renseigne un gestionnaire de réseau pour un projet
2. Je retourne sur la page pour modifier les informations de mon gestionnaire de réseau. Dans l'input de séléction de mon gestionnaire, la valeur par défaut est bien mise à jour. Par contre je n'ai pas accès à la légende et au format. 

Je pense qu'on devrait faire en sort que le useState prenne soit la valeur du format / légende si il y a un gestionnaire déjà séléctionné, ou une chaine de caractère vide

2023-03-02 16:01 UTC, HanaeY commented on src/modules/project/useCases/renseignerIdentifiantGestionnaireRéseau.factory.spec.ts
> +
oui bien vu !

2023-03-02 16:11 UTC, HanaeY commented on src/views/pages/modifierIdentifiantGestionnaireReseauPage/ModifierIdentifiantGestionnaireReseau.tsx
> +            </div>
Jusqu'à maintenant les label+input sont dans des div et ce pour les disposer les uns par rapport aux autres dans une flex box, donc je vais laisser comme ça pour garder une cohérence. Qu'est-ce que ça apporterait de retirer le div ?

2023-03-02 16:21 UTC, HubM commented on src/views/pages/modifierIdentifiantGestionnaireReseauPage/ModifierIdentifiantGestionnaireReseau.tsx
> +            </div>
En vérité ça ne changerait rien, div n'a aucune valeur sémantique. Mais oui gardons une cohérence :)

2023-03-03 09:32 UTC, HubM approved these changes
👍🏼

2023-03-03 09:56 UTC, merged