385 regenerate all certificates for a given periode
MTES-MCT/potentiel pull request #98
Opened 2021-02-18 14:34 UTC by paduc

2021-02-21 20:33 UTC, Zekdar requested changes

2021-02-21 20:33 UTC, Zekdar commented on src/controllers/admin/postRegenerateCertificates.ts
> +    const { user } = request
Tu peux le faire en une ligne : 

```js
const { user, body : { appelOffreAndPeriode, reason, notificationDate } } = request
```

2021-02-21 20:33 UTC, Zekdar commented on src/controllers/admin/postRegenerateCertificates.ts
> +      moment(notificationDate, FORMAT_DATE).format(FORMAT_DATE) !== notificationDate
Exporter dans une variable qui pourrait être nommée `isNotificationDateWrongFormat`

2021-02-21 20:33 UTC, Zekdar commented on src/modules/project/events/CertificatesForPeriodeRegenerated.ts
> +    return JSON.stringify(key, Object.keys(key).sort()) // This make the stringify stable (key order)
Typo : il manque un `s` à `make`

2021-02-21 20:33 UTC, Zekdar commented on src/modules/project/useCases/regenerateCertificatesForPeriode.ts
> +  if (!user || !['admin', 'dgec'].includes(user.role)) {
Pourquoi inclure `dgec` alors que le rôle n'existe pas en base ?

2021-02-22 09:31 UTC, paduc commented on src/modules/project/useCases/regenerateCertificatesForPeriode.ts
> +  if (!user || !['admin', 'dgec'].includes(user.role)) {
Pour l'instant, on a mis les utilisateurs `dgec` et `admin` sur le même plan mais c'est prévu de changer.

2021-02-22 09:49 UTC, Zekdar commented on src/modules/project/useCases/regenerateCertificatesForPeriode.ts
> +  if (!user || !['admin', 'dgec'].includes(user.role)) {
D'accord. Quand on rajoutera le rôle, il faudra également le rajouter dans l'export des projets en csv.

2021-02-22 09:50 UTC, Zekdar approved these changes

2021-03-19 13:57 UTC, merged