Export notifications csv
MTES-MCT/potentiel pull request #99
Opened 2021-02-19 03:12 UTC by Zekdar

2021-02-19 10:12 UTC, paduc requested changes
Il y a deux commits issus de l'autre PR qu'il faut retirer également.

2021-02-19 10:12 UTC, paduc commented on src/routes.ts
> +  static ADMIN_DOWNLOAD_PROJECTS_CANDIDATS_CSV = '/export-projets-candidats.csv'
`ADMIN_DOWNLOAD_CANDIDATES_CSV`

2021-02-19 10:12 UTC, paduc commented on src/controllers/project/getProjectsCandidatsCsv.ts
> +const getProjectsNotifiesCsv = asyncHandler(async (request, response) => {
Garder une cohérence entre le nom du fichier et de l'export ( `getProjectsCandidatsCsv.ts` vs `getProjectsNotifiesCsv` ).
Si j'ai bien compris, ça peut servir pour les candidats notifiés ou pas notifiés, donc j'irais pour `getCandidatesCsv(.ts)`.

2021-02-19 12:22 UTC, Zekdar commented on src/helpers/csv.ts
> +  fn?: Function
`fn` sert dans le cas où on veut donner une valeur calculée dans un champ du csv.
Pour l'instant je l'utilise comme ça : 

```js
{
  name: 'Investissement ou financement participatif ?',
  fn: (row) => row.isInvestissementParticipatif || row.isFinancementParticipatif,
  visibility: ['admin', 'dreal', 'edfoa'],
},
```

2021-02-19 13:55 UTC, paduc commented on src/helpers/csv.ts
> +  fn?: Function
Dans ce cas, tu peux mettre `value: (project: Project) => any` pour etre plus explicite.

2021-02-19 15:46 UTC, paduc commented on src/helpers/csv.ts
> +}
```suggestion
export function formatField(field: {
  label: string
  value: (project: Project) => any
} | { dataField: string } | { label: string, detailField: string }): { label: string; value: string | ((project: Project) => any) } {
  if('value' in field) return { label, value }
  
  if('detailField' in field) return { label, value: `details.${name}` }
  
  return  { label: dataFieldsFlattened.get(dataField), value: dataField }
}
```

2021-02-23 08:38 UTC, paduc requested changes

2021-02-23 08:38 UTC, paduc commented on src/views/pages/adminNotifyCandidates.tsx
> +                <a
il faut rajouter `download` pour indiquer que c'est un fichier téléchargeable.

2021-02-23 08:38 UTC, paduc commented on src/views/pages/listProjects.tsx
> +                    <a
idem il faut rajouter `download` pour indiquer que c'est un fichier téléchargeable.

2021-02-25 23:36 UTC, Zekdar commented on src/views/pages/adminNotifyCandidates.tsx
> +                <a
Je ne connaissais pas cet attribut. Je le mets !

2021-02-26 08:39 UTC, paduc approved these changes

2021-02-26 09:11 UTC, merged